using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002C9 RID: 713
	public class AcceptCallToWarAgreementDecision : KingdomDecision
	{
		// Token: 0x0600264A RID: 9802 RVA: 0x0009F221 File Offset: 0x0009D421
		internal static void AutoGeneratedStaticCollectObjectsAcceptCallToWarAgreementDecision(object o, List<object> collectedObjects)
		{
			((AcceptCallToWarAgreementDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600264B RID: 9803 RVA: 0x0009F22F File Offset: 0x0009D42F
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.CallingKingdom);
			collectedObjects.Add(this.KingdomToCallToWarAgainst);
		}

		// Token: 0x0600264C RID: 9804 RVA: 0x0009F250 File Offset: 0x0009D450
		internal static object AutoGeneratedGetMemberValueCallingKingdom(object o)
		{
			return ((AcceptCallToWarAgreementDecision)o).CallingKingdom;
		}

		// Token: 0x0600264D RID: 9805 RVA: 0x0009F25D File Offset: 0x0009D45D
		internal static object AutoGeneratedGetMemberValueKingdomToCallToWarAgainst(object o)
		{
			return ((AcceptCallToWarAgreementDecision)o).KingdomToCallToWarAgainst;
		}

		// Token: 0x0600264E RID: 9806 RVA: 0x0009F26A File Offset: 0x0009D46A
		internal static object AutoGeneratedGetMemberValueCallToWarCost(object o)
		{
			return ((AcceptCallToWarAgreementDecision)o).CallToWarCost;
		}

		// Token: 0x1700096A RID: 2410
		// (get) Token: 0x0600264F RID: 9807 RVA: 0x0009F27C File Offset: 0x0009D47C
		public IAllianceCampaignBehavior AllianceCampaignBehavior
		{
			get
			{
				if (this._allianceCampaignBehavior == null)
				{
					this._allianceCampaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
				}
				return this._allianceCampaignBehavior;
			}
		}

		// Token: 0x06002650 RID: 9808 RVA: 0x0009F29C File Offset: 0x0009D49C
		public AcceptCallToWarAgreementDecision(Clan proposerClan, Kingdom callingKingdom, Kingdom kingdomToCallToWarAgainst) : base(proposerClan)
		{
			this.CallingKingdom = callingKingdom;
			this.KingdomToCallToWarAgainst = kingdomToCallToWarAgainst;
			this.CallToWarCost = Campaign.Current.Models.AllianceModel.GetCallToWarCost(callingKingdom, proposerClan.Kingdom, kingdomToCallToWarAgainst);
		}

		// Token: 0x06002651 RID: 9809 RVA: 0x0009F2D5 File Offset: 0x0009D4D5
		public override bool IsAllowed()
		{
			return this.CallingKingdom.IsAllyWith(base.Kingdom) && !base.Kingdom.IsAtWarWith(this.KingdomToCallToWarAgainst) && this.CallingKingdom.IsAtWarWith(this.KingdomToCallToWarAgainst);
		}

		// Token: 0x06002652 RID: 9810 RVA: 0x0009F310 File Offset: 0x0009D510
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.AllianceModel.GetInfluenceCostOfCallingToWar(base.ProposerClan);
		}

		// Token: 0x06002653 RID: 9811 RVA: 0x0009F32C File Offset: 0x0009D52C
		public override TextObject GetGeneralTitle()
		{
			TextObject textObject = new TextObject("{=syGyjjKE}Answer the call of the {CALLING_KINGDOM}, and declare war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}.", null);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.InformalName);
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.InformalName);
			return textObject;
		}

		// Token: 0x06002654 RID: 9812 RVA: 0x0009F368 File Offset: 0x0009D568
		public override TextObject GetSupportTitle()
		{
			TextObject textObject = new TextObject("{=eiGl6XBr}Vote on whether to answer the {CALLING_KINGDOM} call to war against the {KINGDOM_TO_CALL_TO_WAR_AGAINST} for {CALL_TO_WAR_PAYMENT}{GOLD_ICON}.", null);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.InformalName);
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.InformalName);
			textObject.SetTextVariable("CALL_TO_WAR_PAYMENT", this.CallToWarCost);
			textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
			return textObject;
		}

		// Token: 0x06002655 RID: 9813 RVA: 0x0009F3D4 File Offset: 0x0009D5D4
		public override TextObject GetChooseTitle()
		{
			TextObject textObject = new TextObject("{=Cf0amFBD}Accepting the {CALLING_KINGDOM} Call to War Against the {KINGDOM_TO_CALL_TO_WAR_AGAINST} for {CALL_TO_WAR_PAYMENT}{GOLD_ICON}", null);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.InformalName);
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.InformalName);
			textObject.SetTextVariable("CALL_TO_WAR_PAYMENT", this.CallToWarCost);
			textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
			return textObject;
		}

		// Token: 0x06002656 RID: 9814 RVA: 0x0009F440 File Offset: 0x0009D640
		public override TextObject GetSupportDescription()
		{
			TextObject textObject = new TextObject("{=m69pvful}{KINGDOM_LEADER} will decide if your realm will answer the call of the {CALLING_KINGDOM} and declare war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST} for {CALL_TO_WAR_PAYMENT}{GOLD_ICON}. You can pick your stance regarding this decision.", null);
			textObject.SetTextVariable("KINGDOM_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.InformalName);
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.InformalName);
			textObject.SetTextVariable("CALL_TO_WAR_PAYMENT", this.CallToWarCost);
			textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
			return textObject;
		}

		// Token: 0x06002657 RID: 9815 RVA: 0x0009F4C8 File Offset: 0x0009D6C8
		public override TextObject GetChooseDescription()
		{
			TextObject textObject = new TextObject("{=oAw74q3r}As {RULER_NAME_AND_TITLE}, you must decide if your realm will answer the call of the {CALLING_KINGDOM} and declare war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST} for {CALL_TO_WAR_PAYMENT}{GOLD_ICON}.", null);
			textObject.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, false);
			textObject.SetTextVariable("RULER_NAME_AND_TITLE", GameTexts.FindText("str_faction_ruler_name_with_title", base.Kingdom.Culture.StringId));
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.InformalName);
			textObject.SetTextVariable("CALL_TO_WAR_PAYMENT", this.CallToWarCost);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.Name);
			textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
			return textObject;
		}

		// Token: 0x06002658 RID: 9816 RVA: 0x0009F573 File Offset: 0x0009D773
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome(true, base.Kingdom, this.CallingKingdom, this.KingdomToCallToWarAgainst);
			yield return new AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome(false, base.Kingdom, this.CallingKingdom, this.KingdomToCallToWarAgainst);
			yield break;
		}

		// Token: 0x06002659 RID: 9817 RVA: 0x0009F583 File Offset: 0x0009D783
		public override Clan DetermineChooser()
		{
			return base.Kingdom.RulingClan;
		}

		// Token: 0x0600265A RID: 9818 RVA: 0x0009F590 File Offset: 0x0009D790
		protected override bool ShouldBeCancelledInternal()
		{
			TextObject textObject;
			return !this.CanMakeDecision(out textObject);
		}

		// Token: 0x0600265B RID: 9819 RVA: 0x0009F5A8 File Offset: 0x0009D7A8
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome)decisionOutcome).ShouldAcceptCallToWar)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x0600265C RID: 9820 RVA: 0x0009F614 File Offset: 0x0009D814
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			if (((AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome)chosenOutcome).ShouldAcceptCallToWar)
			{
				this.AllianceCampaignBehavior.StartCallToWarAgreement(this.CallingKingdom, base.Kingdom, this.KingdomToCallToWarAgainst, this.CallToWarCost, false);
			}
		}

		// Token: 0x0600265D RID: 9821 RVA: 0x0009F647 File Offset: 0x0009D847
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x0600265E RID: 9822 RVA: 0x0009F649 File Offset: 0x0009D849
		public override TextObject GetSecondaryEffects()
		{
			return new TextObject("{=!}All supporters gains some relation with each other.", null);
		}

		// Token: 0x0600265F RID: 9823 RVA: 0x0009F658 File Offset: 0x0009D858
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if (((AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome)chosenOutcome).ShouldAcceptCallToWar)
			{
				if (base.IsSingleClanDecision())
				{
					textObject = new TextObject("{=vf2pb7Ts}{RULER.NAME} has answered the call of the {CALLING_KINGDOM} name and declared war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject = new TextObject("{=ZZ1oLfEq}{RULER.NAME} has answered the call of the {CALLING_KINGDOM} name and declared war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject = new TextObject("{=Lalj0T1i}{RULER.NAME} has answered the call of the {CALLING_KINGDOM} name and declared war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST} despite opposition from {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else
				{
					textObject = new TextObject("{=uiY3ds0Z}{RULER.NAME} has answered the call of the {CALLING_KINGDOM} name and declared war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST} with the support of half of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
			}
			else if (base.IsSingleClanDecision())
			{
				textObject = new TextObject("{=Bk3Wqy5j}{RULER.NAME} has decided not to answer the call of the {CALLING_KINGDOM} name and will not war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Majority)
			{
				textObject = new TextObject("{=fcuUcjYV}{RULER.NAME} has decided not to answer the call of the {CALLING_KINGDOM} name and will not war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}. The decision had the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Minority)
			{
				textObject = new TextObject("{=K5w135N9}{RULER.NAME} has decided not to answer the call of the {CALLING_KINGDOM} name and will not war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}. The decision was taken against the advice of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else
			{
				textObject = new TextObject("{=Ouj6eSWC}{RULER.NAME} has decided not to answer the call of the {CALLING_KINGDOM} name and will not war on the {KINGDOM_TO_CALL_TO_WAR_AGAINST}. The decision had the support of half of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			StringHelpers.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, textObject, false);
			textObject.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.Name);
			textObject.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.Name);
			return textObject;
		}

		// Token: 0x06002660 RID: 9824 RVA: 0x0009F74C File Offset: 0x0009D94C
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome)t).ShouldAcceptCallToWar);
		}

		// Token: 0x06002661 RID: 9825 RVA: 0x0009F773 File Offset: 0x0009D973
		public float CalculateSupport(Clan clan)
		{
			return this.DetermineSupport(clan, new AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome(true, base.Kingdom, this.CallingKingdom, this.KingdomToCallToWarAgainst));
		}

		// Token: 0x06002662 RID: 9826 RVA: 0x0009F794 File Offset: 0x0009D994
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome acceptCallToWarAgreementDecisionOutcome = (AcceptCallToWarAgreementDecision.AcceptCallToWarAgreementDecisionOutcome)possibleOutcome;
			TextObject textObject;
			float scoreOfJoiningWar = Campaign.Current.Models.AllianceModel.GetScoreOfJoiningWar(this.CallingKingdom, base.Kingdom, this.KingdomToCallToWarAgainst, clan, out textObject);
			if (acceptCallToWarAgreementDecisionOutcome.ShouldAcceptCallToWar)
			{
				float num = scoreOfJoiningWar;
				float num2 = (float)clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 2.5f + (float)clan.Leader.GetTraitLevel(DefaultTraits.Calculating) * 2.5f;
				return num + num2;
			}
			float num3 = -scoreOfJoiningWar;
			float num4 = -((float)clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 2.5f) - (float)clan.Leader.GetTraitLevel(DefaultTraits.Calculating) * 2.5f;
			return num3 + num4;
		}

		// Token: 0x06002663 RID: 9827 RVA: 0x0009F844 File Offset: 0x0009DA44
		public override bool CanMakeDecision(out TextObject reason)
		{
			if (this.CallingKingdom.IsEliminated || base.Kingdom.IsEliminated || this.KingdomToCallToWarAgainst.IsEliminated)
			{
				reason = new TextObject("{=a5EAl1aW}That realm has been eliminated.", null);
				return false;
			}
			if (this.KingdomToCallToWarAgainst.IsAtWarWith(base.Kingdom))
			{
				reason = new TextObject("{=lseJ70y0}Your realm is at war with the {KINGDOM_NAME}.", null);
				reason.SetTextVariable("KINGDOM_NAME", this.KingdomToCallToWarAgainst.Name);
				return false;
			}
			if (!this.KingdomToCallToWarAgainst.IsAtWarWith(this.CallingKingdom))
			{
				reason = new TextObject("{=eUWYqwE6}The {CALLING_KINGDOM} is not at war with {KINGDOM_TO_CALL_TO_WAR_AGAINST} anymore.", null);
				reason.SetTextVariable("CALLING_KINGDOM", this.CallingKingdom.Name);
				reason.SetTextVariable("KINGDOM_TO_CALL_TO_WAR_AGAINST", this.KingdomToCallToWarAgainst.Name);
				return false;
			}
			if (!base.Kingdom.IsAllyWith(this.CallingKingdom))
			{
				reason = new TextObject("{=hz30Xfqh}Your realm is not ally with {KINGDOM_NAME} anymore.", null);
				reason.SetTextVariable("KINGDOM_NAME", this.CallingKingdom.Name);
				return false;
			}
			reason = TextObject.GetEmpty();
			return true;
		}

		// Token: 0x04000B29 RID: 2857
		[SaveableField(101)]
		public readonly Kingdom CallingKingdom;

		// Token: 0x04000B2A RID: 2858
		[SaveableField(102)]
		public readonly Kingdom KingdomToCallToWarAgainst;

		// Token: 0x04000B2B RID: 2859
		[SaveableField(103)]
		public readonly int CallToWarCost;

		// Token: 0x04000B2C RID: 2860
		private IAllianceCampaignBehavior _allianceCampaignBehavior;

		// Token: 0x02000660 RID: 1632
		public class AcceptCallToWarAgreementDecisionOutcome : DecisionOutcome
		{
			// Token: 0x060050D4 RID: 20692 RVA: 0x00183630 File Offset: 0x00181830
			public AcceptCallToWarAgreementDecisionOutcome(bool shouldAcceptCallToWar, Kingdom kingdom, Kingdom callingKingdom, Kingdom kingdomToCallToWarAgainst)
			{
				this.ShouldAcceptCallToWar = shouldAcceptCallToWar;
				this.Kingdom = kingdom;
				this.CallingKingdom = callingKingdom;
				this.KingdomToCallToWarAgainst = kingdomToCallToWarAgainst;
			}

			// Token: 0x060050D5 RID: 20693 RVA: 0x00183655 File Offset: 0x00181855
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldAcceptCallToWar ? 1 : 0);
				return textObject;
			}

			// Token: 0x060050D6 RID: 20694 RVA: 0x0018367C File Offset: 0x0018187C
			public override TextObject GetDecisionDescription()
			{
				if (base.SponsorClan != null && this.Kingdom != null && this.CallingKingdom != null && this.KingdomToCallToWarAgainst != null && base.SponsorClan != Clan.PlayerClan)
				{
					TextObject empty = TextObject.GetEmpty();
					if (this.ShouldAcceptCallToWar)
					{
						Campaign.Current.Models.AllianceModel.GetScoreOfJoiningWar(this.Kingdom, this.CallingKingdom, this.KingdomToCallToWarAgainst, base.SponsorClan, out empty);
					}
					if (!empty.IsEmpty())
					{
						return empty;
					}
				}
				if (this.ShouldAcceptCallToWar)
				{
					TextObject textObject = new TextObject("{=h9bWTLgK}It is time to join our allies, the {KINGDOM_NAME}, in their war.", null);
					textObject.SetTextVariable("KINGDOM_NAME", this.CallingKingdom.Name);
					return textObject;
				}
				TextObject textObject2 = new TextObject("{=q9DnHVcZ}It is not in our interests to join the {KINGDOM_NAME} in their war.", null);
				textObject2.SetTextVariable("KINGDOM_NAME", this.CallingKingdom.Name);
				return textObject2;
			}

			// Token: 0x060050D7 RID: 20695 RVA: 0x0018374A File Offset: 0x0018194A
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x060050D8 RID: 20696 RVA: 0x0018374D File Offset: 0x0018194D
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x04001999 RID: 6553
			[SaveableField(100)]
			public readonly bool ShouldAcceptCallToWar;

			// Token: 0x0400199A RID: 6554
			[SaveableField(101)]
			public readonly Kingdom Kingdom;

			// Token: 0x0400199B RID: 6555
			[SaveableField(102)]
			public readonly Kingdom CallingKingdom;

			// Token: 0x0400199C RID: 6556
			[SaveableField(103)]
			public readonly Kingdom KingdomToCallToWarAgainst;
		}
	}
}
