using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000309 RID: 777
	public class CaravanPartyComponent : PartyComponent
	{
		// Token: 0x06002DA0 RID: 11680 RVA: 0x000BFE1D File Offset: 0x000BE01D
		internal static void AutoGeneratedStaticCollectObjectsCaravanPartyComponent(object o, List<object> collectedObjects)
		{
			((CaravanPartyComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002DA1 RID: 11681 RVA: 0x000BFE2B File Offset: 0x000BE02B
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._leader);
			collectedObjects.Add(this.Settlement);
			collectedObjects.Add(this.Owner);
		}

		// Token: 0x06002DA2 RID: 11682 RVA: 0x000BFE58 File Offset: 0x000BE058
		internal static object AutoGeneratedGetMemberValueSettlement(object o)
		{
			return ((CaravanPartyComponent)o).Settlement;
		}

		// Token: 0x06002DA3 RID: 11683 RVA: 0x000BFE65 File Offset: 0x000BE065
		internal static object AutoGeneratedGetMemberValueOwner(object o)
		{
			return ((CaravanPartyComponent)o).Owner;
		}

		// Token: 0x06002DA4 RID: 11684 RVA: 0x000BFE72 File Offset: 0x000BE072
		internal static object AutoGeneratedGetMemberValue_isElite(object o)
		{
			return ((CaravanPartyComponent)o)._isElite;
		}

		// Token: 0x06002DA5 RID: 11685 RVA: 0x000BFE84 File Offset: 0x000BE084
		internal static object AutoGeneratedGetMemberValue_leader(object o)
		{
			return ((CaravanPartyComponent)o)._leader;
		}

		// Token: 0x17000B38 RID: 2872
		// (get) Token: 0x06002DA6 RID: 11686 RVA: 0x000BFE91 File Offset: 0x000BE091
		// (set) Token: 0x06002DA7 RID: 11687 RVA: 0x000BFE99 File Offset: 0x000BE099
		[SaveableProperty(1)]
		public Settlement Settlement { get; private set; }

		// Token: 0x17000B39 RID: 2873
		// (get) Token: 0x06002DA8 RID: 11688 RVA: 0x000BFEA2 File Offset: 0x000BE0A2
		// (set) Token: 0x06002DA9 RID: 11689 RVA: 0x000BFEAA File Offset: 0x000BE0AA
		[SaveableProperty(2)]
		public Hero Owner { get; private set; }

		// Token: 0x17000B3A RID: 2874
		// (get) Token: 0x06002DAA RID: 11690 RVA: 0x000BFEB3 File Offset: 0x000BE0B3
		public override Hero PartyOwner
		{
			get
			{
				return this.Owner;
			}
		}

		// Token: 0x17000B3B RID: 2875
		// (get) Token: 0x06002DAB RID: 11691 RVA: 0x000BFEBB File Offset: 0x000BE0BB
		public bool IsElite
		{
			get
			{
				return this._isElite;
			}
		}

		// Token: 0x06002DAC RID: 11692 RVA: 0x000BFEC4 File Offset: 0x000BE0C4
		public override Banner GetDefaultComponentBanner()
		{
			if (this.Leader != null)
			{
				return this.Leader.ClanBanner;
			}
			if (this.Owner == Hero.MainHero)
			{
				return this.Owner.MapFaction.Banner;
			}
			return this.Owner.HomeSettlement.OwnerClan.MapFaction.Banner;
		}

		// Token: 0x17000B3C RID: 2876
		// (get) Token: 0x06002DAD RID: 11693 RVA: 0x000BFF1D File Offset: 0x000BE11D
		public override TextObject Name
		{
			get
			{
				if (this._cachedName == null)
				{
					if (base.MobileParty == null)
					{
						return GameTexts.FindText("str_caravan_party_name", null);
					}
					this.CacheName();
				}
				return this._cachedName;
			}
		}

		// Token: 0x17000B3D RID: 2877
		// (get) Token: 0x06002DAE RID: 11694 RVA: 0x000BFF4F File Offset: 0x000BE14F
		public override bool CanHaveNavalNavigationCapability
		{
			get
			{
				return !base.MobileParty.HasLandNavigationCapability;
			}
		}

		// Token: 0x17000B3E RID: 2878
		// (get) Token: 0x06002DAF RID: 11695 RVA: 0x000BFF5F File Offset: 0x000BE15F
		public override bool CanHaveLandNavigationCapability
		{
			get
			{
				return base.MobileParty.HasLandNavigationCapability;
			}
		}

		// Token: 0x17000B3F RID: 2879
		// (get) Token: 0x06002DB0 RID: 11696 RVA: 0x000BFF6C File Offset: 0x000BE16C
		public override Settlement HomeSettlement
		{
			get
			{
				return this.Settlement;
			}
		}

		// Token: 0x17000B40 RID: 2880
		// (get) Token: 0x06002DB1 RID: 11697 RVA: 0x000BFF74 File Offset: 0x000BE174
		public override Hero Leader
		{
			get
			{
				return this._leader;
			}
		}

		// Token: 0x06002DB2 RID: 11698 RVA: 0x000BFF7C File Offset: 0x000BE17C
		protected CaravanPartyComponent(Settlement settlement, Hero owner, Hero partyLeader, bool isElite, CaravanPartyComponent.InitializationArgs args)
		{
			this.Settlement = settlement;
			this.Owner = owner;
			this._leader = partyLeader;
			this._isElite = isElite;
			this._initializationArgs = args;
		}

		// Token: 0x06002DB3 RID: 11699 RVA: 0x000BFFAC File Offset: 0x000BE1AC
		protected override void OnMobilePartySetOnCreation()
		{
			base.MobileParty.Aggressiveness = 0f;
			base.MobileParty.ActualClan = this.Owner.Clan;
			base.MobileParty.Party.SetVisualAsDirty();
			if (this._initializationArgs != null)
			{
				this._initializationArgs.InitializeCaravanOnCreation(base.MobileParty, this.Settlement);
				this._initializationArgs = null;
			}
		}

		// Token: 0x06002DB4 RID: 11700 RVA: 0x000C0015 File Offset: 0x000BE215
		protected override void OnInitialize()
		{
			this.Owner.OwnedCaravans.Add(this);
		}

		// Token: 0x06002DB5 RID: 11701 RVA: 0x000C0028 File Offset: 0x000BE228
		protected override void OnFinalize()
		{
			this.Owner.OwnedCaravans.Remove(this);
		}

		// Token: 0x06002DB6 RID: 11702 RVA: 0x000C003C File Offset: 0x000BE23C
		public static void ConvertPartyToCaravanParty(MobileParty mobileParty, Hero caravanOwner, Settlement spawnSettlement, bool isInitialSpawn = false, Hero caravanLeader = null, ItemRoster caravanItems = null, bool isElite = false)
		{
			mobileParty.SetPartyComponent(new CaravanPartyComponent(spawnSettlement, caravanOwner, caravanLeader, isElite, null), true);
			if (mobileParty.LeaderHero != null)
			{
				CampaignEventDispatcher.Instance.OnHeroGetsBusy(mobileParty.LeaderHero, HeroGetsBusyReasons.BecomeCaravanLeader);
			}
		}

		// Token: 0x06002DB7 RID: 11703 RVA: 0x000C006A File Offset: 0x000BE26A
		protected override void OnChangePartyLeader(Hero newLeader)
		{
			this._leader = newLeader;
		}

		// Token: 0x06002DB8 RID: 11704 RVA: 0x000C0073 File Offset: 0x000BE273
		public override void ClearCachedName()
		{
			this._cachedName = null;
		}

		// Token: 0x06002DB9 RID: 11705 RVA: 0x000C007C File Offset: 0x000BE27C
		private void CacheName()
		{
			if (base.MobileParty.HasNavalNavigationCapability)
			{
				this._cachedName = GameTexts.FindText(this.IsElite ? "str_armed_convoy_party_name" : "str_convoy_party_name", null);
			}
			else
			{
				this._cachedName = GameTexts.FindText(this.IsElite ? "str_armed_caravan_party_name" : "str_caravan_party_name", null);
			}
			TextObject cachedName = this._cachedName;
			string tag = "OWNER";
			Hero leaderHero = base.MobileParty.LeaderHero;
			cachedName.SetCharacterProperties(tag, ((leaderHero != null) ? leaderHero.CharacterObject : null) ?? this.Owner.CharacterObject, false);
		}

		// Token: 0x06002DBA RID: 11706 RVA: 0x000C0110 File Offset: 0x000BE310
		public static MobileParty CreateCaravanParty(Hero caravanOwner, Settlement spawnSettlement, PartyTemplateObject templateObject, bool isInitialSpawn = false, Hero caravanLeader = null, ItemRoster caravanItems = null, bool isElite = false)
		{
			bool flag = templateObject.ShipHulls.Any<ShipTemplateStack>();
			CaravanPartyComponent.InitializationArgs args = new CaravanPartyComponent.InitializationArgs(templateObject, caravanLeader, caravanItems);
			MobileParty mobileParty = MobileParty.CreateParty("caravan_template_" + spawnSettlement.Culture.StringId.ToLower() + "_1", new CaravanPartyComponent(spawnSettlement, caravanOwner, caravanLeader, isElite, args));
			mobileParty.InitializePartyTrade(Campaign.Current.Models.CaravanModel.GetInitialTradeGold(caravanOwner, flag, isElite));
			if (spawnSettlement.Party.MapEvent == null && spawnSettlement.SiegeEvent == null)
			{
				mobileParty.SetMoveGoToSettlement(spawnSettlement, flag ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default, flag);
				mobileParty.RecalculateShortTermBehavior();
				EnterSettlementAction.ApplyForParty(mobileParty, spawnSettlement);
			}
			else
			{
				mobileParty.SetMoveModeHold();
			}
			if (mobileParty.LeaderHero != null)
			{
				CampaignEventDispatcher.Instance.OnHeroGetsBusy(mobileParty.LeaderHero, HeroGetsBusyReasons.BecomeCaravanLeader);
			}
			return mobileParty;
		}

		// Token: 0x06002DBB RID: 11707 RVA: 0x000C01D8 File Offset: 0x000BE3D8
		public override void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
		{
			IFaction mapFaction = party.MapFaction;
			string text;
			if (mapFaction == null)
			{
				text = null;
			}
			else
			{
				CultureObject culture = mapFaction.Culture;
				text = ((culture != null) ? culture.StringId : null);
			}
			string a = text ?? string.Empty;
			if (a == "aserai" || a == "khuzait")
			{
				mountStringId = "camel";
				if (party.Index % 2 == 0)
				{
					harnessStringId = "camel_saddle_a";
					return;
				}
				harnessStringId = "camel_saddle_b";
				return;
			}
			else
			{
				mountStringId = "mule";
				int num = party.Index % 3;
				if (num == 0)
				{
					harnessStringId = "mule_load_a";
					return;
				}
				if (num != 1)
				{
					harnessStringId = "mule_load_c";
					return;
				}
				harnessStringId = "mule_load_b";
				return;
			}
		}

		// Token: 0x06002DBC RID: 11708 RVA: 0x000C027C File Offset: 0x000BE47C
		public static void TransferCaravanOwnership(MobileParty caravan, Hero newOwner, Settlement homeSettlement)
		{
			int partyTradeGold = caravan.PartyTradeGold;
			CaravanPartyComponent.ConvertPartyToCaravanParty(caravan, newOwner, homeSettlement, false, caravan.LeaderHero, null, caravan.CaravanPartyComponent.IsElite);
			caravan.PartyTradeGold = partyTradeGold;
		}

		// Token: 0x06002DBD RID: 11709 RVA: 0x000C02B2 File Offset: 0x000BE4B2
		public void ChangeHomeSettlement(Settlement newHomeSettlement)
		{
			this.Settlement = newHomeSettlement;
		}

		// Token: 0x04000D57 RID: 3415
		private CaravanPartyComponent.InitializationArgs _initializationArgs;

		// Token: 0x04000D5A RID: 3418
		[CachedData]
		private TextObject _cachedName;

		// Token: 0x04000D5B RID: 3419
		[SaveableField(4)]
		private bool _isElite;

		// Token: 0x04000D5C RID: 3420
		[SaveableField(3)]
		private Hero _leader;

		// Token: 0x020006C6 RID: 1734
		protected class InitializationArgs
		{
			// Token: 0x060053B3 RID: 21427 RVA: 0x0018DAA3 File Offset: 0x0018BCA3
			public InitializationArgs(PartyTemplateObject partyTemplateObject, Hero caravanLeader = null, ItemRoster caravanItems = null)
			{
				this.CaravanLeader = caravanLeader;
				this.CaravanItems = caravanItems;
				this.PartyTemplateObject = partyTemplateObject;
			}

			// Token: 0x060053B4 RID: 21428 RVA: 0x0018DAC0 File Offset: 0x0018BCC0
			public void InitializeCaravanOnCreation(MobileParty mobileParty, Settlement settlement)
			{
				bool flag = this.PartyTemplateObject.ShipHulls != null && this.PartyTemplateObject.ShipHulls.Count > 0;
				CampaignVec2 position = flag ? settlement.PortPosition : settlement.GatePosition;
				if (flag)
				{
					mobileParty.SetLandNavigationAccess(false);
				}
				mobileParty.InitializeMobilePartyAtPosition(this.PartyTemplateObject, position);
				if (this.CaravanLeader != null)
				{
					Hero caravanLeader = this.CaravanLeader;
					if (caravanLeader != null)
					{
						MobileParty partyBelongedTo = caravanLeader.PartyBelongedTo;
						if (partyBelongedTo != null)
						{
							TroopRoster memberRoster = partyBelongedTo.MemberRoster;
							if (memberRoster != null)
							{
								memberRoster.AddToCounts(this.CaravanLeader.CharacterObject, -1, false, 0, 0, true, -1);
							}
						}
					}
					mobileParty.MemberRoster.AddToCounts(this.CaravanLeader.CharacterObject, 1, true, 0, 0, true, -1);
				}
				else
				{
					mobileParty.MemberRoster.AddToCounts(mobileParty.Party.Owner.Culture.CaravanMaster, 1, true, 0, 0, true, -1);
				}
				if (this.CaravanItems != null)
				{
					mobileParty.ItemRoster.Add(this.CaravanItems);
					return;
				}
				float num = 10000f;
				ItemObject itemObject = null;
				foreach (ItemObject itemObject2 in Items.All)
				{
					if (itemObject2.ItemCategory == DefaultItemCategories.PackAnimal && !itemObject2.NotMerchandise && (float)itemObject2.Value < num)
					{
						itemObject = itemObject2;
						num = (float)itemObject2.Value;
					}
				}
				if (itemObject != null)
				{
					mobileParty.ItemRoster.Add(new ItemRosterElement(itemObject, (int)((float)mobileParty.MemberRoster.TotalManCount * 0.5f), null));
				}
			}

			// Token: 0x04001B30 RID: 6960
			public readonly Hero CaravanLeader;

			// Token: 0x04001B31 RID: 6961
			public readonly ItemRoster CaravanItems;

			// Token: 0x04001B32 RID: 6962
			public readonly PartyTemplateObject PartyTemplateObject;
		}
	}
}
