using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x02000062 RID: 98
	public sealed class Clan : MBObjectBase, IFaction
	{
		// Token: 0x06000AC0 RID: 2752 RVA: 0x0003F6CD File Offset: 0x0003D8CD
		internal static void AutoGeneratedStaticCollectObjectsClan(object o, List<object> collectedObjects)
		{
			((Clan)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000AC1 RID: 2753 RVA: 0x0003F6DC File Offset: 0x0003D8DC
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._defaultPartyTemplate);
			collectedObjects.Add(this._minorFactionCharacterTemplates);
			collectedObjects.Add(this._kingdom);
			collectedObjects.Add(this._basicTroop);
			collectedObjects.Add(this._leader);
			collectedObjects.Add(this._banner);
			collectedObjects.Add(this._home);
			collectedObjects.Add(this.Name);
			collectedObjects.Add(this.InformalName);
			collectedObjects.Add(this.Culture);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.LastFactionChangeTime, collectedObjects);
			collectedObjects.Add(this.EncyclopediaText);
			collectedObjects.Add(this.InitialHomeSettlement);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.ShouldStayInKingdomUntil, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.NotAttackableByPlayerUntilTime, collectedObjects);
		}

		// Token: 0x06000AC2 RID: 2754 RVA: 0x0003F7B3 File Offset: 0x0003D9B3
		internal static object AutoGeneratedGetMemberValueName(object o)
		{
			return ((Clan)o).Name;
		}

		// Token: 0x06000AC3 RID: 2755 RVA: 0x0003F7C0 File Offset: 0x0003D9C0
		internal static object AutoGeneratedGetMemberValueInformalName(object o)
		{
			return ((Clan)o).InformalName;
		}

		// Token: 0x06000AC4 RID: 2756 RVA: 0x0003F7CD File Offset: 0x0003D9CD
		internal static object AutoGeneratedGetMemberValueCulture(object o)
		{
			return ((Clan)o).Culture;
		}

		// Token: 0x06000AC5 RID: 2757 RVA: 0x0003F7DA File Offset: 0x0003D9DA
		internal static object AutoGeneratedGetMemberValueLastFactionChangeTime(object o)
		{
			return ((Clan)o).LastFactionChangeTime;
		}

		// Token: 0x06000AC6 RID: 2758 RVA: 0x0003F7EC File Offset: 0x0003D9EC
		internal static object AutoGeneratedGetMemberValueAutoRecruitmentExpenses(object o)
		{
			return ((Clan)o).AutoRecruitmentExpenses;
		}

		// Token: 0x06000AC7 RID: 2759 RVA: 0x0003F7FE File Offset: 0x0003D9FE
		internal static object AutoGeneratedGetMemberValueEncyclopediaText(object o)
		{
			return ((Clan)o).EncyclopediaText;
		}

		// Token: 0x06000AC8 RID: 2760 RVA: 0x0003F80B File Offset: 0x0003DA0B
		internal static object AutoGeneratedGetMemberValueIsNoble(object o)
		{
			return ((Clan)o).IsNoble;
		}

		// Token: 0x06000AC9 RID: 2761 RVA: 0x0003F81D File Offset: 0x0003DA1D
		internal static object AutoGeneratedGetMemberValueMercenaryAwardMultiplier(object o)
		{
			return ((Clan)o).MercenaryAwardMultiplier;
		}

		// Token: 0x06000ACA RID: 2762 RVA: 0x0003F82F File Offset: 0x0003DA2F
		internal static object AutoGeneratedGetMemberValueInitialHomeSettlement(object o)
		{
			return ((Clan)o).InitialHomeSettlement;
		}

		// Token: 0x06000ACB RID: 2763 RVA: 0x0003F83C File Offset: 0x0003DA3C
		internal static object AutoGeneratedGetMemberValueIsRebelClan(object o)
		{
			return ((Clan)o).IsRebelClan;
		}

		// Token: 0x06000ACC RID: 2764 RVA: 0x0003F84E File Offset: 0x0003DA4E
		internal static object AutoGeneratedGetMemberValueIsMinorFaction(object o)
		{
			return ((Clan)o).IsMinorFaction;
		}

		// Token: 0x06000ACD RID: 2765 RVA: 0x0003F860 File Offset: 0x0003DA60
		internal static object AutoGeneratedGetMemberValueIsOutlaw(object o)
		{
			return ((Clan)o).IsOutlaw;
		}

		// Token: 0x06000ACE RID: 2766 RVA: 0x0003F872 File Offset: 0x0003DA72
		internal static object AutoGeneratedGetMemberValueIsNomad(object o)
		{
			return ((Clan)o).IsNomad;
		}

		// Token: 0x06000ACF RID: 2767 RVA: 0x0003F884 File Offset: 0x0003DA84
		internal static object AutoGeneratedGetMemberValueIsMafia(object o)
		{
			return ((Clan)o).IsMafia;
		}

		// Token: 0x06000AD0 RID: 2768 RVA: 0x0003F896 File Offset: 0x0003DA96
		internal static object AutoGeneratedGetMemberValueIsClanTypeMercenary(object o)
		{
			return ((Clan)o).IsClanTypeMercenary;
		}

		// Token: 0x06000AD1 RID: 2769 RVA: 0x0003F8A8 File Offset: 0x0003DAA8
		internal static object AutoGeneratedGetMemberValueIsSect(object o)
		{
			return ((Clan)o).IsSect;
		}

		// Token: 0x06000AD2 RID: 2770 RVA: 0x0003F8BA File Offset: 0x0003DABA
		internal static object AutoGeneratedGetMemberValueIsUnderMercenaryService(object o)
		{
			return ((Clan)o).IsUnderMercenaryService;
		}

		// Token: 0x06000AD3 RID: 2771 RVA: 0x0003F8CC File Offset: 0x0003DACC
		internal static object AutoGeneratedGetMemberValueShouldStayInKingdomUntil(object o)
		{
			return ((Clan)o).ShouldStayInKingdomUntil;
		}

		// Token: 0x06000AD4 RID: 2772 RVA: 0x0003F8DE File Offset: 0x0003DADE
		internal static object AutoGeneratedGetMemberValueColor(object o)
		{
			return ((Clan)o).Color;
		}

		// Token: 0x06000AD5 RID: 2773 RVA: 0x0003F8F0 File Offset: 0x0003DAF0
		internal static object AutoGeneratedGetMemberValueColor2(object o)
		{
			return ((Clan)o).Color2;
		}

		// Token: 0x06000AD6 RID: 2774 RVA: 0x0003F902 File Offset: 0x0003DB02
		internal static object AutoGeneratedGetMemberValueBannerBackgroundColorPrimary(object o)
		{
			return ((Clan)o).BannerBackgroundColorPrimary;
		}

		// Token: 0x06000AD7 RID: 2775 RVA: 0x0003F914 File Offset: 0x0003DB14
		internal static object AutoGeneratedGetMemberValueBannerBackgroundColorSecondary(object o)
		{
			return ((Clan)o).BannerBackgroundColorSecondary;
		}

		// Token: 0x06000AD8 RID: 2776 RVA: 0x0003F926 File Offset: 0x0003DB26
		internal static object AutoGeneratedGetMemberValueBannerIconColor(object o)
		{
			return ((Clan)o).BannerIconColor;
		}

		// Token: 0x06000AD9 RID: 2777 RVA: 0x0003F938 File Offset: 0x0003DB38
		internal static object AutoGeneratedGetMemberValueIsBanditFaction(object o)
		{
			return ((Clan)o).IsBanditFaction;
		}

		// Token: 0x06000ADA RID: 2778 RVA: 0x0003F94A File Offset: 0x0003DB4A
		internal static object AutoGeneratedGetMemberValueRenown(object o)
		{
			return ((Clan)o).Renown;
		}

		// Token: 0x06000ADB RID: 2779 RVA: 0x0003F95C File Offset: 0x0003DB5C
		internal static object AutoGeneratedGetMemberValueMainHeroCrimeRating(object o)
		{
			return ((Clan)o).MainHeroCrimeRating;
		}

		// Token: 0x06000ADC RID: 2780 RVA: 0x0003F96E File Offset: 0x0003DB6E
		internal static object AutoGeneratedGetMemberValueNotAttackableByPlayerUntilTime(object o)
		{
			return ((Clan)o).NotAttackableByPlayerUntilTime;
		}

		// Token: 0x06000ADD RID: 2781 RVA: 0x0003F980 File Offset: 0x0003DB80
		internal static object AutoGeneratedGetMemberValue_defaultPartyTemplate(object o)
		{
			return ((Clan)o)._defaultPartyTemplate;
		}

		// Token: 0x06000ADE RID: 2782 RVA: 0x0003F98D File Offset: 0x0003DB8D
		internal static object AutoGeneratedGetMemberValue_isEliminated(object o)
		{
			return ((Clan)o)._isEliminated;
		}

		// Token: 0x06000ADF RID: 2783 RVA: 0x0003F99F File Offset: 0x0003DB9F
		internal static object AutoGeneratedGetMemberValue_minorFactionCharacterTemplates(object o)
		{
			return ((Clan)o)._minorFactionCharacterTemplates;
		}

		// Token: 0x06000AE0 RID: 2784 RVA: 0x0003F9AC File Offset: 0x0003DBAC
		internal static object AutoGeneratedGetMemberValue_kingdom(object o)
		{
			return ((Clan)o)._kingdom;
		}

		// Token: 0x06000AE1 RID: 2785 RVA: 0x0003F9B9 File Offset: 0x0003DBB9
		internal static object AutoGeneratedGetMemberValue_influence(object o)
		{
			return ((Clan)o)._influence;
		}

		// Token: 0x06000AE2 RID: 2786 RVA: 0x0003F9CB File Offset: 0x0003DBCB
		internal static object AutoGeneratedGetMemberValue_basicTroop(object o)
		{
			return ((Clan)o)._basicTroop;
		}

		// Token: 0x06000AE3 RID: 2787 RVA: 0x0003F9D8 File Offset: 0x0003DBD8
		internal static object AutoGeneratedGetMemberValue_leader(object o)
		{
			return ((Clan)o)._leader;
		}

		// Token: 0x06000AE4 RID: 2788 RVA: 0x0003F9E5 File Offset: 0x0003DBE5
		internal static object AutoGeneratedGetMemberValue_banner(object o)
		{
			return ((Clan)o)._banner;
		}

		// Token: 0x06000AE5 RID: 2789 RVA: 0x0003F9F2 File Offset: 0x0003DBF2
		internal static object AutoGeneratedGetMemberValue_tier(object o)
		{
			return ((Clan)o)._tier;
		}

		// Token: 0x06000AE6 RID: 2790 RVA: 0x0003FA04 File Offset: 0x0003DC04
		internal static object AutoGeneratedGetMemberValue_aggressiveness(object o)
		{
			return ((Clan)o)._aggressiveness;
		}

		// Token: 0x06000AE7 RID: 2791 RVA: 0x0003FA16 File Offset: 0x0003DC16
		internal static object AutoGeneratedGetMemberValue_tributeWallet(object o)
		{
			return ((Clan)o)._tributeWallet;
		}

		// Token: 0x06000AE8 RID: 2792 RVA: 0x0003FA28 File Offset: 0x0003DC28
		internal static object AutoGeneratedGetMemberValue_home(object o)
		{
			return ((Clan)o)._home;
		}

		// Token: 0x06000AE9 RID: 2793 RVA: 0x0003FA35 File Offset: 0x0003DC35
		internal static object AutoGeneratedGetMemberValue_clanDebtToKingdom(object o)
		{
			return ((Clan)o)._clanDebtToKingdom;
		}

		// Token: 0x1700021B RID: 539
		// (get) Token: 0x06000AEA RID: 2794 RVA: 0x0003FA47 File Offset: 0x0003DC47
		// (set) Token: 0x06000AEB RID: 2795 RVA: 0x0003FA4F File Offset: 0x0003DC4F
		[SaveableProperty(51)]
		public TextObject Name { get; private set; }

		// Token: 0x1700021C RID: 540
		// (get) Token: 0x06000AEC RID: 2796 RVA: 0x0003FA58 File Offset: 0x0003DC58
		// (set) Token: 0x06000AED RID: 2797 RVA: 0x0003FA60 File Offset: 0x0003DC60
		[SaveableProperty(52)]
		public TextObject InformalName { get; private set; }

		// Token: 0x1700021D RID: 541
		// (get) Token: 0x06000AEE RID: 2798 RVA: 0x0003FA69 File Offset: 0x0003DC69
		// (set) Token: 0x06000AEF RID: 2799 RVA: 0x0003FA71 File Offset: 0x0003DC71
		[SaveableProperty(53)]
		public CultureObject Culture { get; set; }

		// Token: 0x1700021E RID: 542
		// (get) Token: 0x06000AF0 RID: 2800 RVA: 0x0003FA7A File Offset: 0x0003DC7A
		// (set) Token: 0x06000AF1 RID: 2801 RVA: 0x0003FA82 File Offset: 0x0003DC82
		[SaveableProperty(55)]
		public CampaignTime LastFactionChangeTime { get; set; }

		// Token: 0x1700021F RID: 543
		// (get) Token: 0x06000AF2 RID: 2802 RVA: 0x0003FA8B File Offset: 0x0003DC8B
		public PartyTemplateObject DefaultPartyTemplate
		{
			get
			{
				if (this._defaultPartyTemplate != null)
				{
					return this._defaultPartyTemplate;
				}
				return this.Culture.DefaultPartyTemplate;
			}
		}

		// Token: 0x17000220 RID: 544
		// (get) Token: 0x06000AF3 RID: 2803 RVA: 0x0003FAA7 File Offset: 0x0003DCA7
		public bool HasNavalNavigationCapability
		{
			get
			{
				return this.DefaultPartyTemplate.ShipHulls.Count > 0;
			}
		}

		// Token: 0x17000221 RID: 545
		// (get) Token: 0x06000AF4 RID: 2804 RVA: 0x0003FABC File Offset: 0x0003DCBC
		// (set) Token: 0x06000AF5 RID: 2805 RVA: 0x0003FAC4 File Offset: 0x0003DCC4
		[SaveableProperty(58)]
		public int AutoRecruitmentExpenses { get; set; }

		// Token: 0x17000222 RID: 546
		// (get) Token: 0x06000AF6 RID: 2806 RVA: 0x0003FACD File Offset: 0x0003DCCD
		// (set) Token: 0x06000AF7 RID: 2807 RVA: 0x0003FAD5 File Offset: 0x0003DCD5
		[SaveableProperty(56)]
		public TextObject EncyclopediaText { get; private set; }

		// Token: 0x17000223 RID: 547
		// (get) Token: 0x06000AF8 RID: 2808 RVA: 0x0003FADE File Offset: 0x0003DCDE
		// (set) Token: 0x06000AF9 RID: 2809 RVA: 0x0003FAE6 File Offset: 0x0003DCE6
		[SaveableProperty(140)]
		public bool IsNoble { get; set; }

		// Token: 0x17000224 RID: 548
		// (get) Token: 0x06000AFA RID: 2810 RVA: 0x0003FAEF File Offset: 0x0003DCEF
		public bool IsEliminated
		{
			get
			{
				return this._isEliminated;
			}
		}

		// Token: 0x17000225 RID: 549
		// (get) Token: 0x06000AFB RID: 2811 RVA: 0x0003FAF7 File Offset: 0x0003DCF7
		public IList<CharacterObject> MinorFactionCharacterTemplates
		{
			get
			{
				return this._minorFactionCharacterTemplates;
			}
		}

		// Token: 0x17000226 RID: 550
		// (get) Token: 0x06000AFC RID: 2812 RVA: 0x0003FAFF File Offset: 0x0003DCFF
		public string EncyclopediaLink
		{
			get
			{
				return Campaign.Current.EncyclopediaManager.GetIdentifier(typeof(Clan)) + "-" + base.StringId;
			}
		}

		// Token: 0x17000227 RID: 551
		// (get) Token: 0x06000AFD RID: 2813 RVA: 0x0003FB2A File Offset: 0x0003DD2A
		public TextObject EncyclopediaLinkWithName
		{
			get
			{
				return HyperlinkTexts.GetClanHyperlinkText(this.EncyclopediaLink, this.Name);
			}
		}

		// Token: 0x17000228 RID: 552
		// (get) Token: 0x06000AFE RID: 2814 RVA: 0x0003FB3D File Offset: 0x0003DD3D
		// (set) Token: 0x06000AFF RID: 2815 RVA: 0x0003FB45 File Offset: 0x0003DD45
		public Kingdom Kingdom
		{
			get
			{
				return this._kingdom;
			}
			set
			{
				if (this._kingdom != value)
				{
					this.SetKingdomInternal(value);
				}
			}
		}

		// Token: 0x17000229 RID: 553
		// (get) Token: 0x06000B00 RID: 2816 RVA: 0x0003FB57 File Offset: 0x0003DD57
		public IEnumerable<CharacterObject> DungeonPrisonersOfClan
		{
			get
			{
				foreach (Town town in this.Fiefs)
				{
					foreach (CharacterObject characterObject in town.Settlement.Party.PrisonerHeroes)
					{
						yield return characterObject;
					}
					IEnumerator<CharacterObject> enumerator2 = null;
				}
				List<Town>.Enumerator enumerator = default(List<Town>.Enumerator);
				yield break;
				yield break;
			}
		}

		// Token: 0x1700022A RID: 554
		// (get) Token: 0x06000B01 RID: 2817 RVA: 0x0003FB67 File Offset: 0x0003DD67
		public MBReadOnlyList<Town> Fiefs
		{
			get
			{
				return this._fiefsCache;
			}
		}

		// Token: 0x1700022B RID: 555
		// (get) Token: 0x06000B02 RID: 2818 RVA: 0x0003FB6F File Offset: 0x0003DD6F
		public MBReadOnlyList<Village> Villages
		{
			get
			{
				return this._villagesCache;
			}
		}

		// Token: 0x1700022C RID: 556
		// (get) Token: 0x06000B03 RID: 2819 RVA: 0x0003FB77 File Offset: 0x0003DD77
		public MBReadOnlyList<Settlement> Settlements
		{
			get
			{
				return this._settlementsCache;
			}
		}

		// Token: 0x1700022D RID: 557
		// (get) Token: 0x06000B04 RID: 2820 RVA: 0x0003FB7F File Offset: 0x0003DD7F
		public MBReadOnlyList<Hero> SupporterNotables
		{
			get
			{
				return this._supporterNotablesCache;
			}
		}

		// Token: 0x1700022E RID: 558
		// (get) Token: 0x06000B05 RID: 2821 RVA: 0x0003FB87 File Offset: 0x0003DD87
		public MBReadOnlyList<Hero> AliveLords
		{
			get
			{
				return this._aliveLordsCache;
			}
		}

		// Token: 0x1700022F RID: 559
		// (get) Token: 0x06000B06 RID: 2822 RVA: 0x0003FB8F File Offset: 0x0003DD8F
		public MBReadOnlyList<Hero> DeadLords
		{
			get
			{
				return this._deadLordsCache;
			}
		}

		// Token: 0x17000230 RID: 560
		// (get) Token: 0x06000B07 RID: 2823 RVA: 0x0003FB97 File Offset: 0x0003DD97
		public MBReadOnlyList<Hero> Heroes
		{
			get
			{
				return this._heroesCache;
			}
		}

		// Token: 0x17000231 RID: 561
		// (get) Token: 0x06000B08 RID: 2824 RVA: 0x0003FB9F File Offset: 0x0003DD9F
		public MBReadOnlyList<Hero> Companions
		{
			get
			{
				return this._companionsCache;
			}
		}

		// Token: 0x17000232 RID: 562
		// (get) Token: 0x06000B09 RID: 2825 RVA: 0x0003FBA7 File Offset: 0x0003DDA7
		public MBReadOnlyList<WarPartyComponent> WarPartyComponents
		{
			get
			{
				return this._warPartyComponentsCache;
			}
		}

		// Token: 0x17000233 RID: 563
		// (get) Token: 0x06000B0A RID: 2826 RVA: 0x0003FBAF File Offset: 0x0003DDAF
		// (set) Token: 0x06000B0B RID: 2827 RVA: 0x0003FBB7 File Offset: 0x0003DDB7
		public float Influence
		{
			get
			{
				return this._influence;
			}
			set
			{
				if (value < this._influence && this.Leader != null)
				{
					SkillLevelingManager.OnInfluenceSpent(this.Leader, value - this._influence);
				}
				this._influence = value;
			}
		}

		// Token: 0x17000234 RID: 564
		// (get) Token: 0x06000B0C RID: 2828 RVA: 0x0003FBE4 File Offset: 0x0003DDE4
		public ExplainedNumber InfluenceChangeExplained
		{
			get
			{
				return Campaign.Current.Models.ClanPoliticsModel.CalculateInfluenceChange(this, true);
			}
		}

		// Token: 0x17000235 RID: 565
		// (get) Token: 0x06000B0D RID: 2829 RVA: 0x0003FBFC File Offset: 0x0003DDFC
		// (set) Token: 0x06000B0E RID: 2830 RVA: 0x0003FC04 File Offset: 0x0003DE04
		[CachedData]
		public float CurrentTotalStrength { get; private set; }

		// Token: 0x17000236 RID: 566
		// (get) Token: 0x06000B0F RID: 2831 RVA: 0x0003FC0D File Offset: 0x0003DE0D
		// (set) Token: 0x06000B10 RID: 2832 RVA: 0x0003FC15 File Offset: 0x0003DE15
		[SaveableProperty(65)]
		public int MercenaryAwardMultiplier { get; set; }

		// Token: 0x17000237 RID: 567
		// (get) Token: 0x06000B11 RID: 2833 RVA: 0x0003FC1E File Offset: 0x0003DE1E
		public bool IsMapFaction
		{
			get
			{
				return this._kingdom == null;
			}
		}

		// Token: 0x17000238 RID: 568
		// (get) Token: 0x06000B12 RID: 2834 RVA: 0x0003FC29 File Offset: 0x0003DE29
		// (set) Token: 0x06000B13 RID: 2835 RVA: 0x0003FC31 File Offset: 0x0003DE31
		[SaveableProperty(114)]
		public Settlement InitialHomeSettlement { get; private set; }

		// Token: 0x17000239 RID: 569
		// (get) Token: 0x06000B14 RID: 2836 RVA: 0x0003FC3A File Offset: 0x0003DE3A
		// (set) Token: 0x06000B15 RID: 2837 RVA: 0x0003FC42 File Offset: 0x0003DE42
		[SaveableProperty(68)]
		public bool IsRebelClan { get; set; }

		// Token: 0x1700023A RID: 570
		// (get) Token: 0x06000B16 RID: 2838 RVA: 0x0003FC4B File Offset: 0x0003DE4B
		// (set) Token: 0x06000B17 RID: 2839 RVA: 0x0003FC53 File Offset: 0x0003DE53
		[SaveableProperty(69)]
		public bool IsMinorFaction { get; private set; }

		// Token: 0x1700023B RID: 571
		// (get) Token: 0x06000B18 RID: 2840 RVA: 0x0003FC5C File Offset: 0x0003DE5C
		// (set) Token: 0x06000B19 RID: 2841 RVA: 0x0003FC64 File Offset: 0x0003DE64
		[SaveableProperty(70)]
		public bool IsOutlaw { get; private set; }

		// Token: 0x1700023C RID: 572
		// (get) Token: 0x06000B1A RID: 2842 RVA: 0x0003FC6D File Offset: 0x0003DE6D
		// (set) Token: 0x06000B1B RID: 2843 RVA: 0x0003FC75 File Offset: 0x0003DE75
		[SaveableProperty(71)]
		public bool IsNomad { get; private set; }

		// Token: 0x1700023D RID: 573
		// (get) Token: 0x06000B1C RID: 2844 RVA: 0x0003FC7E File Offset: 0x0003DE7E
		// (set) Token: 0x06000B1D RID: 2845 RVA: 0x0003FC86 File Offset: 0x0003DE86
		[SaveableProperty(72)]
		public bool IsMafia { get; private set; }

		// Token: 0x1700023E RID: 574
		// (get) Token: 0x06000B1E RID: 2846 RVA: 0x0003FC8F File Offset: 0x0003DE8F
		// (set) Token: 0x06000B1F RID: 2847 RVA: 0x0003FC97 File Offset: 0x0003DE97
		[SaveableProperty(73)]
		public bool IsClanTypeMercenary { get; private set; }

		// Token: 0x1700023F RID: 575
		// (get) Token: 0x06000B20 RID: 2848 RVA: 0x0003FCA0 File Offset: 0x0003DEA0
		// (set) Token: 0x06000B21 RID: 2849 RVA: 0x0003FCA8 File Offset: 0x0003DEA8
		[SaveableProperty(74)]
		public bool IsSect { get; private set; }

		// Token: 0x17000240 RID: 576
		// (get) Token: 0x06000B22 RID: 2850 RVA: 0x0003FCB1 File Offset: 0x0003DEB1
		// (set) Token: 0x06000B23 RID: 2851 RVA: 0x0003FCB9 File Offset: 0x0003DEB9
		[SaveableProperty(75)]
		public bool IsUnderMercenaryService { get; private set; }

		// Token: 0x17000241 RID: 577
		// (get) Token: 0x06000B24 RID: 2852 RVA: 0x0003FCC2 File Offset: 0x0003DEC2
		// (set) Token: 0x06000B25 RID: 2853 RVA: 0x0003FCCA File Offset: 0x0003DECA
		[SaveableProperty(188)]
		public CampaignTime ShouldStayInKingdomUntil { get; set; }

		// Token: 0x17000242 RID: 578
		// (get) Token: 0x06000B26 RID: 2854 RVA: 0x0003FCD3 File Offset: 0x0003DED3
		// (set) Token: 0x06000B27 RID: 2855 RVA: 0x0003FCDB File Offset: 0x0003DEDB
		[SaveableProperty(76)]
		public uint Color { get; set; }

		// Token: 0x17000243 RID: 579
		// (get) Token: 0x06000B28 RID: 2856 RVA: 0x0003FCE4 File Offset: 0x0003DEE4
		// (set) Token: 0x06000B29 RID: 2857 RVA: 0x0003FCEC File Offset: 0x0003DEEC
		[SaveableProperty(77)]
		public uint Color2 { get; set; }

		// Token: 0x17000244 RID: 580
		// (get) Token: 0x06000B2A RID: 2858 RVA: 0x0003FCF5 File Offset: 0x0003DEF5
		// (set) Token: 0x06000B2B RID: 2859 RVA: 0x0003FCFD File Offset: 0x0003DEFD
		[SaveableProperty(111)]
		private uint BannerBackgroundColorPrimary { get; set; }

		// Token: 0x17000245 RID: 581
		// (get) Token: 0x06000B2C RID: 2860 RVA: 0x0003FD06 File Offset: 0x0003DF06
		// (set) Token: 0x06000B2D RID: 2861 RVA: 0x0003FD0E File Offset: 0x0003DF0E
		[SaveableProperty(112)]
		private uint BannerBackgroundColorSecondary { get; set; }

		// Token: 0x17000246 RID: 582
		// (get) Token: 0x06000B2E RID: 2862 RVA: 0x0003FD17 File Offset: 0x0003DF17
		// (set) Token: 0x06000B2F RID: 2863 RVA: 0x0003FD1F File Offset: 0x0003DF1F
		[SaveableProperty(113)]
		private uint BannerIconColor { get; set; }

		// Token: 0x17000247 RID: 583
		// (get) Token: 0x06000B30 RID: 2864 RVA: 0x0003FD28 File Offset: 0x0003DF28
		public Settlement FactionMidSettlement
		{
			get
			{
				return this._midSettlement;
			}
		}

		// Token: 0x17000248 RID: 584
		// (get) Token: 0x06000B31 RID: 2865 RVA: 0x0003FD30 File Offset: 0x0003DF30
		// (set) Token: 0x06000B32 RID: 2866 RVA: 0x0003FD47 File Offset: 0x0003DF47
		public CharacterObject BasicTroop
		{
			get
			{
				return this._basicTroop ?? this.Culture.BasicTroop;
			}
			set
			{
				this._basicTroop = value;
			}
		}

		// Token: 0x17000249 RID: 585
		// (get) Token: 0x06000B33 RID: 2867 RVA: 0x0003FD50 File Offset: 0x0003DF50
		public static Clan PlayerClan
		{
			get
			{
				return Campaign.Current.PlayerDefaultFaction;
			}
		}

		// Token: 0x1700024A RID: 586
		// (get) Token: 0x06000B34 RID: 2868 RVA: 0x0003FD5C File Offset: 0x0003DF5C
		public Hero Leader
		{
			get
			{
				return this._leader;
			}
		}

		// Token: 0x1700024B RID: 587
		// (get) Token: 0x06000B35 RID: 2869 RVA: 0x0003FD64 File Offset: 0x0003DF64
		public int Gold
		{
			get
			{
				Hero leader = this.Leader;
				if (leader == null)
				{
					return 0;
				}
				return leader.Gold;
			}
		}

		// Token: 0x1700024C RID: 588
		// (get) Token: 0x06000B36 RID: 2870 RVA: 0x0003FD77 File Offset: 0x0003DF77
		// (set) Token: 0x06000B37 RID: 2871 RVA: 0x0003FDA1 File Offset: 0x0003DFA1
		public Banner Banner
		{
			get
			{
				if (this.Kingdom == null || this.Kingdom.RulingClan != this)
				{
					return this._banner;
				}
				return this.Kingdom.Banner;
			}
			set
			{
				this._banner = value;
			}
		}

		// Token: 0x1700024D RID: 589
		// (get) Token: 0x06000B38 RID: 2872 RVA: 0x0003FDAA File Offset: 0x0003DFAA
		public Banner ClanOriginalBanner
		{
			get
			{
				return this._banner;
			}
		}

		// Token: 0x1700024E RID: 590
		// (get) Token: 0x06000B39 RID: 2873 RVA: 0x0003FDB2 File Offset: 0x0003DFB2
		// (set) Token: 0x06000B3A RID: 2874 RVA: 0x0003FDBA File Offset: 0x0003DFBA
		[SaveableProperty(85)]
		public bool IsBanditFaction { get; private set; }

		// Token: 0x1700024F RID: 591
		// (get) Token: 0x06000B3B RID: 2875 RVA: 0x0003FDC3 File Offset: 0x0003DFC3
		bool IFaction.IsKingdomFaction
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000250 RID: 592
		// (get) Token: 0x06000B3C RID: 2876 RVA: 0x0003FDC6 File Offset: 0x0003DFC6
		public bool IsClan
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000251 RID: 593
		// (get) Token: 0x06000B3D RID: 2877 RVA: 0x0003FDC9 File Offset: 0x0003DFC9
		// (set) Token: 0x06000B3E RID: 2878 RVA: 0x0003FDD1 File Offset: 0x0003DFD1
		[SaveableProperty(88)]
		public float Renown { get; set; }

		// Token: 0x17000252 RID: 594
		// (get) Token: 0x06000B3F RID: 2879 RVA: 0x0003FDDA File Offset: 0x0003DFDA
		// (set) Token: 0x06000B40 RID: 2880 RVA: 0x0003FDE2 File Offset: 0x0003DFE2
		[SaveableProperty(89)]
		public float MainHeroCrimeRating { get; set; }

		// Token: 0x17000253 RID: 595
		// (get) Token: 0x06000B41 RID: 2881 RVA: 0x0003FDEC File Offset: 0x0003DFEC
		public float DailyCrimeRatingChange
		{
			get
			{
				return Campaign.Current.Models.CrimeModel.GetDailyCrimeRatingChange(this, false).ResultNumber;
			}
		}

		// Token: 0x17000254 RID: 596
		// (get) Token: 0x06000B42 RID: 2882 RVA: 0x0003FE17 File Offset: 0x0003E017
		public ExplainedNumber DailyCrimeRatingChangeExplained
		{
			get
			{
				return Campaign.Current.Models.CrimeModel.GetDailyCrimeRatingChange(this, true);
			}
		}

		// Token: 0x17000255 RID: 597
		// (get) Token: 0x06000B43 RID: 2883 RVA: 0x0003FE2F File Offset: 0x0003E02F
		// (set) Token: 0x06000B44 RID: 2884 RVA: 0x0003FE38 File Offset: 0x0003E038
		public int Tier
		{
			get
			{
				return this._tier;
			}
			private set
			{
				int minClanTier = Campaign.Current.Models.ClanTierModel.MinClanTier;
				int maxClanTier = Campaign.Current.Models.ClanTierModel.MaxClanTier;
				if (value > maxClanTier)
				{
					value = maxClanTier;
				}
				else if (value < minClanTier)
				{
					value = minClanTier;
				}
				this._tier = value;
			}
		}

		// Token: 0x17000256 RID: 598
		// (get) Token: 0x06000B45 RID: 2885 RVA: 0x0003FE86 File Offset: 0x0003E086
		public IFaction MapFaction
		{
			get
			{
				if (this.Kingdom != null)
				{
					return this.Kingdom;
				}
				return this;
			}
		}

		// Token: 0x17000257 RID: 599
		// (get) Token: 0x06000B46 RID: 2886 RVA: 0x0003FE98 File Offset: 0x0003E098
		// (set) Token: 0x06000B47 RID: 2887 RVA: 0x0003FEA0 File Offset: 0x0003E0A0
		[SaveableProperty(100)]
		public CampaignTime NotAttackableByPlayerUntilTime { get; set; }

		// Token: 0x17000258 RID: 600
		// (get) Token: 0x06000B48 RID: 2888 RVA: 0x0003FEA9 File Offset: 0x0003E0A9
		// (set) Token: 0x06000B49 RID: 2889 RVA: 0x0003FEB1 File Offset: 0x0003E0B1
		public float Aggressiveness
		{
			get
			{
				return this._aggressiveness;
			}
			internal set
			{
				this._aggressiveness = MathF.Clamp(value, 0f, 100f);
			}
		}

		// Token: 0x06000B4A RID: 2890 RVA: 0x0003FECC File Offset: 0x0003E0CC
		public void UpdateFactionsAtWarWith()
		{
			this._factionsAtWarWith.Clear();
			foreach (Kingdom kingdom in Kingdom.All)
			{
				if (!kingdom.IsEliminated && this.IsAtWarWith(kingdom))
				{
					this._factionsAtWarWith.Add(kingdom);
				}
			}
			foreach (Clan clan in Clan.All)
			{
				if (!clan.IsEliminated && this.IsAtWarWith(clan))
				{
					this._factionsAtWarWith.Add(clan);
				}
			}
		}

		// Token: 0x17000259 RID: 601
		// (get) Token: 0x06000B4B RID: 2891 RVA: 0x0003FF98 File Offset: 0x0003E198
		// (set) Token: 0x06000B4C RID: 2892 RVA: 0x0003FFA0 File Offset: 0x0003E1A0
		public int TributeWallet
		{
			get
			{
				return this._tributeWallet;
			}
			set
			{
				this._tributeWallet = value;
			}
		}

		// Token: 0x1700025A RID: 602
		// (get) Token: 0x06000B4D RID: 2893 RVA: 0x0003FFA9 File Offset: 0x0003E1A9
		// (set) Token: 0x06000B4E RID: 2894 RVA: 0x0003FFB1 File Offset: 0x0003E1B1
		public Settlement HomeSettlement
		{
			get
			{
				return this._home;
			}
			private set
			{
				this._home = value;
			}
		}

		// Token: 0x1700025B RID: 603
		// (get) Token: 0x06000B4F RID: 2895 RVA: 0x0003FFBC File Offset: 0x0003E1BC
		// (set) Token: 0x06000B50 RID: 2896 RVA: 0x0003FFC4 File Offset: 0x0003E1C4
		public int DebtToKingdom
		{
			get
			{
				return this._clanDebtToKingdom;
			}
			set
			{
				this._clanDebtToKingdom = value;
			}
		}

		// Token: 0x06000B51 RID: 2897 RVA: 0x0003FFD0 File Offset: 0x0003E1D0
		public void UpdateCurrentStrength()
		{
			this.CurrentTotalStrength = 0f;
			foreach (WarPartyComponent warPartyComponent in this._warPartyComponentsCache)
			{
				this.CurrentTotalStrength += warPartyComponent.MobileParty.Party.EstimatedStrength;
			}
			foreach (Town town in this.Fiefs)
			{
				if (town.GarrisonParty != null)
				{
					this.CurrentTotalStrength += town.GarrisonParty.Party.EstimatedStrength;
				}
			}
		}

		// Token: 0x1700025C RID: 604
		// (get) Token: 0x06000B52 RID: 2898 RVA: 0x000400A4 File Offset: 0x0003E2A4
		public MBReadOnlyList<IFaction> FactionsAtWarWith
		{
			get
			{
				return this._factionsAtWarWith;
			}
		}

		// Token: 0x1700025D RID: 605
		// (get) Token: 0x06000B53 RID: 2899 RVA: 0x000400AC File Offset: 0x0003E2AC
		public int RenownRequirementForNextTier
		{
			get
			{
				return Campaign.Current.Models.ClanTierModel.GetRequiredRenownForTier(this.Tier + 1);
			}
		}

		// Token: 0x1700025E RID: 606
		// (get) Token: 0x06000B54 RID: 2900 RVA: 0x000400CA File Offset: 0x0003E2CA
		public int CompanionLimit
		{
			get
			{
				return Campaign.Current.Models.ClanTierModel.GetCompanionLimit(this);
			}
		}

		// Token: 0x1700025F RID: 607
		// (get) Token: 0x06000B55 RID: 2901 RVA: 0x000400E1 File Offset: 0x0003E2E1
		public float DistanceToClosestNonAllyFortification
		{
			get
			{
				if (this._distanceToClosestNonAllyFortificationCacheDirty)
				{
					this._distanceToClosestNonAllyFortificationCache = FactionHelper.GetDistanceToClosestNonAllyFortificationOfFaction(this);
					this._distanceToClosestNonAllyFortificationCacheDirty = false;
				}
				return this._distanceToClosestNonAllyFortificationCache;
			}
		}

		// Token: 0x17000260 RID: 608
		// (get) Token: 0x06000B56 RID: 2902 RVA: 0x00040104 File Offset: 0x0003E304
		public int CommanderLimit
		{
			get
			{
				return Campaign.Current.Models.ClanTierModel.GetPartyLimitForTier(this, this.Tier);
			}
		}

		// Token: 0x06000B57 RID: 2903 RVA: 0x00040121 File Offset: 0x0003E321
		public bool IsAtWarWith(IFaction other)
		{
			return FactionManager.IsAtWarAgainstFaction(this, other);
		}

		// Token: 0x06000B58 RID: 2904 RVA: 0x0004012C File Offset: 0x0003E32C
		private void InitMembers()
		{
			this._companionsCache = new MBList<Hero>();
			this._factionsAtWarWith = new MBList<IFaction>();
			this._warPartyComponentsCache = new MBList<WarPartyComponent>();
			this._supporterNotablesCache = new MBList<Hero>();
			this._aliveLordsCache = new MBList<Hero>();
			this._deadLordsCache = new MBList<Hero>();
			this._heroesCache = new MBList<Hero>();
			this._villagesCache = new MBList<Village>();
			this._fiefsCache = new MBList<Town>();
			this._settlementsCache = new MBList<Settlement>();
		}

		// Token: 0x06000B59 RID: 2905 RVA: 0x000401A7 File Offset: 0x0003E3A7
		public Clan()
		{
			this.InitMembers();
			this._isEliminated = false;
			this.NotAttackableByPlayerUntilTime = CampaignTime.Zero;
		}

		// Token: 0x06000B5A RID: 2906 RVA: 0x000401D0 File Offset: 0x0003E3D0
		public static Clan CreateClan(string stringID)
		{
			stringID = Campaign.Current.CampaignObjectManager.FindNextUniqueStringId<Clan>(stringID);
			Clan clan = new Clan();
			clan.StringId = stringID;
			Campaign.Current.CampaignObjectManager.AddClan(clan);
			return clan;
		}

		// Token: 0x06000B5B RID: 2907 RVA: 0x00040210 File Offset: 0x0003E410
		protected override void PreAfterLoad()
		{
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.0", 0) && this.IsBanditFaction && this.IsEliminated)
			{
				this._isEliminated = false;
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.2", 0) && base.StringId == "neutral")
			{
				foreach (Hero hero in Campaign.Current.AliveHeroes)
				{
					if (hero.Clan == this)
					{
						hero.ResetClanForOldSave();
						if (this._aliveLordsCache.Contains(hero))
						{
							this._aliveLordsCache.Remove(hero);
						}
						if (this._heroesCache.Contains(hero))
						{
							this._heroesCache.Remove(hero);
						}
					}
				}
				foreach (Hero hero2 in Campaign.Current.DeadOrDisabledHeroes)
				{
					if (hero2.Clan == this)
					{
						hero2.ResetClanForOldSave();
						if (this._aliveLordsCache.Contains(hero2))
						{
							this._aliveLordsCache.Remove(hero2);
						}
						if (this._heroesCache.Contains(hero2))
						{
							this._heroesCache.Remove(hero2);
						}
					}
				}
				for (int i = this.Heroes.Count - 1; i >= 0; i--)
				{
					Hero hero3 = this.Heroes[i];
					hero3.ResetClanForOldSave();
					if (this._aliveLordsCache.Contains(hero3))
					{
						this._aliveLordsCache.Remove(hero3);
					}
					if (this._heroesCache.Contains(hero3))
					{
						this._heroesCache.Remove(hero3);
					}
				}
				DestroyClanAction.Apply(this);
				Campaign.Current.CampaignObjectManager.RemoveClan(this);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("e1.8.0.0", 0))
			{
				Hero leader = this.Leader;
				this.IsNoble = (leader != null && leader.IsNobleForOldSaves);
			}
			Kingdom kingdom = this._kingdom;
			if (kingdom != null)
			{
				kingdom.AddClanInternal(this);
			}
			this.UpdateBannerColorsAccordingToKingdom();
		}

		// Token: 0x06000B5C RID: 2908 RVA: 0x00040464 File Offset: 0x0003E664
		protected override void AfterLoad()
		{
			this.UpdateCurrentStrength();
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("e1.8.0.0", 0) && this.Kingdom != null)
			{
				FactionHelper.AdjustFactionStancesForClanJoiningKingdom(this, this.Kingdom);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.1.3", 0) && this.Kingdom == null && this.IsUnderMercenaryService)
			{
				EndMercenaryServiceAction.EndByLeavingKingdom(this);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.0", 0) && this.IsEliminated && this.Leader != null && this.Leader.IsAlive)
			{
				DestroyClanAction.Apply(this);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.0", 0))
			{
				Settlement settlement = this.HomeSettlement;
				if (settlement == null)
				{
					IEnumerable<Settlement> enumerable = from x in Campaign.Current.Settlements
					where x.Culture == this.Culture
					select x;
					settlement = ((enumerable != null) ? enumerable.GetRandomElementInefficiently<Settlement>() : null);
				}
				if (settlement == null)
				{
					settlement = Campaign.Current.Settlements.First<Settlement>();
				}
				this.SetInitialHomeSettlement(settlement);
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000B5D RID: 2909 RVA: 0x00040590 File Offset: 0x0003E790
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this.SetLeader(objectManager.ReadObjectReferenceFromXml("owner", typeof(Hero), node) as Hero);
			this.Kingdom = (Kingdom)objectManager.ReadObjectReferenceFromXml("super_faction", typeof(Kingdom), node);
			this.Tier = ((node.Attributes["tier"] == null) ? 1 : Convert.ToInt32(node.Attributes["tier"].Value));
			this.Renown = (float)Campaign.Current.Models.ClanTierModel.CalculateInitialRenown(this);
			if (node.Attributes["initial_home_settlement"] != null)
			{
				Settlement initialHomeSettlement = (Settlement)objectManager.ReadObjectReferenceFromXml("initial_home_settlement", typeof(Settlement), node);
				this.SetInitialHomeSettlement(initialHomeSettlement);
			}
			this.ChangeClanName(new TextObject(node.Attributes["name"].Value, null), (node.Attributes["short_name"] != null) ? new TextObject(node.Attributes["short_name"].Value, null) : new TextObject(node.Attributes["name"].Value, null));
			this.Culture = (CultureObject)objectManager.ReadObjectReferenceFromXml("culture", typeof(CultureObject), node);
			this.Banner = null;
			XmlNode xmlNode = node.Attributes["is_noble"];
			if (xmlNode != null)
			{
				this.IsNoble = Convert.ToBoolean(xmlNode.InnerText);
			}
			this.Color = ((node.Attributes["color"] == null) ? 4291609515U : Convert.ToUInt32(node.Attributes["color"].Value, 16));
			this.Color2 = ((node.Attributes["color2"] == null) ? 4291609515U : Convert.ToUInt32(node.Attributes["color2"].Value, 16));
			this.IsBanditFaction = (node.Attributes["is_bandit"] != null && Convert.ToBoolean(node.Attributes["is_bandit"].Value));
			this.IsMinorFaction = (node.Attributes["is_minor_faction"] != null && Convert.ToBoolean(node.Attributes["is_minor_faction"].Value));
			this.IsOutlaw = (node.Attributes["is_outlaw"] != null && Convert.ToBoolean(node.Attributes["is_outlaw"].Value));
			this.IsSect = (node.Attributes["is_sect"] != null && Convert.ToBoolean(node.Attributes["is_sect"].Value));
			this.IsMafia = (node.Attributes["is_mafia"] != null && Convert.ToBoolean(node.Attributes["is_mafia"].Value));
			this.IsClanTypeMercenary = (node.Attributes["is_clan_type_mercenary"] != null && Convert.ToBoolean(node.Attributes["is_clan_type_mercenary"].Value));
			this.IsNomad = (node.Attributes["is_nomad"] != null && Convert.ToBoolean(node.Attributes["is_nomad"].Value));
			this._defaultPartyTemplate = (PartyTemplateObject)objectManager.ReadObjectReferenceFromXml("default_party_template", typeof(PartyTemplateObject), node);
			this.EncyclopediaText = ((node.Attributes["text"] != null) ? new TextObject(node.Attributes["text"].Value, null) : TextObject.GetEmpty());
			if (node.Attributes["banner_key"] != null)
			{
				this._banner = new Banner();
				this._banner.Deserialize(node.Attributes["banner_key"].Value);
			}
			else
			{
				this._banner = Banner.CreateRandomClanBanner(base.StringId.GetDeterministicHashCode());
			}
			this.BannerBackgroundColorPrimary = this._banner.GetPrimaryColor();
			this.BannerBackgroundColorSecondary = this._banner.GetSecondaryColor();
			this.BannerIconColor = this._banner.GetFirstIconColor();
			this.UpdateBannerColorsAccordingToKingdom();
			this._minorFactionCharacterTemplates = new MBList<CharacterObject>();
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode2 = (XmlNode)obj;
				if (xmlNode2.Name == "minor_faction_character_templates")
				{
					using (IEnumerator enumerator2 = xmlNode2.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj2 = enumerator2.Current;
							XmlNode node2 = (XmlNode)obj2;
							CharacterObject item = objectManager.ReadObjectReferenceFromXml("id", typeof(CharacterObject), node2) as CharacterObject;
							this._minorFactionCharacterTemplates.Add(item);
						}
						continue;
					}
				}
				if (xmlNode2.Name == "relationship")
				{
					IFaction faction;
					if (xmlNode2.Attributes["clan"] != null)
					{
						faction = (Clan)objectManager.ReadObjectReferenceFromXml("clan", typeof(Clan), xmlNode2);
					}
					else
					{
						faction = (Kingdom)objectManager.ReadObjectReferenceFromXml("kingdom", typeof(Kingdom), xmlNode2);
					}
					if (Convert.ToInt32(xmlNode2.Attributes["value"].InnerText) < 0)
					{
						FactionManager.DeclareWar(this, faction);
					}
					else
					{
						FactionManager.SetNeutral(this, faction);
					}
				}
			}
		}

		// Token: 0x06000B5E RID: 2910 RVA: 0x00040B80 File Offset: 0x0003ED80
		protected override void OnBeforeLoad()
		{
		}

		// Token: 0x06000B5F RID: 2911 RVA: 0x00040B82 File Offset: 0x0003ED82
		[LoadInitializationCallback]
		private void OnLoad(MetaData metaData)
		{
			this.InitMembers();
		}

		// Token: 0x06000B60 RID: 2912 RVA: 0x00040B8A File Offset: 0x0003ED8A
		public int GetRelationWithClan(Clan other)
		{
			if (this.Leader != null && other.Leader != null)
			{
				return this.Leader.GetRelation(other.Leader);
			}
			return 0;
		}

		// Token: 0x06000B61 RID: 2913 RVA: 0x00040BAF File Offset: 0x0003EDAF
		public void SetLeader(Hero leader)
		{
			this._leader = leader;
			if (leader != null)
			{
				leader.Clan = this;
			}
		}

		// Token: 0x06000B62 RID: 2914 RVA: 0x00040BC2 File Offset: 0x0003EDC2
		public void SetInitialHomeSettlement(Settlement initialHomeSettlement)
		{
			this.InitialHomeSettlement = initialHomeSettlement;
			this.ConsiderAndUpdateHomeSettlement();
		}

		// Token: 0x06000B63 RID: 2915 RVA: 0x00040BD4 File Offset: 0x0003EDD4
		public void ConsiderAndUpdateHomeSettlement()
		{
			Settlement settlement = Campaign.Current.Models.SettlementValueModel.FindMostSuitableHomeSettlement(this);
			if (settlement != this.HomeSettlement)
			{
				this.HomeSettlement = settlement;
				foreach (Hero hero in this.Heroes)
				{
					hero.UpdateHomeSettlement();
				}
			}
		}

		// Token: 0x06000B64 RID: 2916 RVA: 0x00040C4C File Offset: 0x0003EE4C
		public override TextObject GetName()
		{
			return this.Name;
		}

		// Token: 0x06000B65 RID: 2917 RVA: 0x00040C54 File Offset: 0x0003EE54
		public void ChangeClanName(TextObject name, TextObject informalName)
		{
			this.Name = name;
			this.InformalName = informalName;
		}

		// Token: 0x06000B66 RID: 2918 RVA: 0x00040C64 File Offset: 0x0003EE64
		public override string ToString()
		{
			return string.Concat(new object[]
			{
				"(",
				base.Id,
				") ",
				this.Name
			});
		}

		// Token: 0x06000B67 RID: 2919 RVA: 0x00040C98 File Offset: 0x0003EE98
		public StanceLink GetStanceWith(IFaction other)
		{
			return FactionManager.Instance.GetStanceLinkInternal(this, other);
		}

		// Token: 0x06000B68 RID: 2920 RVA: 0x00040CA6 File Offset: 0x0003EEA6
		private void SetKingdomInternal(Kingdom value)
		{
			if (this.Kingdom != null)
			{
				this.LeaveKingdomInternal();
			}
			this._kingdom = value;
			if (this.Kingdom != null)
			{
				this.EnterKingdomInternal();
			}
			this.UpdateBannerColorsAccordingToKingdom();
			this.LastFactionChangeTime = CampaignTime.Now;
		}

		// Token: 0x06000B69 RID: 2921 RVA: 0x00040CDC File Offset: 0x0003EEDC
		private void EnterKingdomInternal()
		{
			this._kingdom.AddClanInternal(this);
			foreach (Hero hero in this.Heroes)
			{
				this._kingdom.OnHeroAdded(hero);
			}
			foreach (Town fortification in this.Fiefs)
			{
				this._kingdom.OnFortificationAdded(fortification);
			}
			foreach (WarPartyComponent warPartyComponent in this.WarPartyComponents)
			{
				this._kingdom.OnWarPartyAdded(warPartyComponent);
			}
		}

		// Token: 0x06000B6A RID: 2922 RVA: 0x00040DD4 File Offset: 0x0003EFD4
		private void LeaveKingdomInternal()
		{
			ChangeClanInfluenceAction.Apply(this, -this.Influence);
			this._kingdom.RemoveClanInternal(this);
			foreach (Hero hero in this.Heroes)
			{
				this._kingdom.OnHeroRemoved(hero);
			}
			foreach (Town fortification in this.Fiefs)
			{
				this._kingdom.OnFortificationRemoved(fortification);
			}
			List<WarPartyComponent> list = this.WarPartyComponents.ToListQ<WarPartyComponent>();
			for (int i = list.Count<WarPartyComponent>() - 1; i >= 0; i--)
			{
				if (list[i].MobileParty.Army != null)
				{
					list[i].MobileParty.Army = null;
				}
				this._kingdom.OnWarPartyRemoved(list[i]);
			}
		}

		// Token: 0x06000B6B RID: 2923 RVA: 0x00040EEC File Offset: 0x0003F0EC
		public void ClanLeaveKingdom(bool giveBackFiefs = false)
		{
			ChangeClanInfluenceAction.Apply(this, -this.Influence);
			if (this.Kingdom != null)
			{
				foreach (Settlement settlement in Campaign.Current.Settlements)
				{
					if (settlement.IsTown && settlement.OwnerClan == this)
					{
						SettlementHelper.TakeEnemyVillagersOutsideSettlements(settlement);
					}
				}
			}
			this.LastFactionChangeTime = CampaignTime.Now;
			this.Kingdom = null;
		}

		// Token: 0x06000B6C RID: 2924 RVA: 0x00040F7C File Offset: 0x0003F17C
		public float CalculateTotalSettlementBaseValue()
		{
			float num = 0f;
			foreach (Town town in this.Fiefs)
			{
				num += Campaign.Current.Models.SettlementValueModel.CalculateSettlementBaseValue(town.Owner.Settlement);
			}
			return num;
		}

		// Token: 0x06000B6D RID: 2925 RVA: 0x00040FF4 File Offset: 0x0003F1F4
		public void StartMercenaryService()
		{
			this.IsUnderMercenaryService = true;
		}

		// Token: 0x06000B6E RID: 2926 RVA: 0x00041000 File Offset: 0x0003F200
		public void ResetPlayerHomeAndFactionMidSettlement()
		{
			this._home = null;
			this._midSettlement = null;
			this.InitialHomeSettlement = null;
			Settlement initialHomeSettlement = Campaign.Current.Models.SettlementValueModel.FindMostSuitableHomeSettlement(this);
			this.SetInitialHomeSettlement(initialHomeSettlement);
			this.CalculateMidSettlement();
		}

		// Token: 0x06000B6F RID: 2927 RVA: 0x00041048 File Offset: 0x0003F248
		private int DistanceOfTwoValues(int x, int y)
		{
			int num = (x < 50) ? x : (100 - x);
			int num2 = (y < 50) ? y : (100 - y);
			return MathF.Min(num + num2, x - y);
		}

		// Token: 0x06000B70 RID: 2928 RVA: 0x00041078 File Offset: 0x0003F278
		public static Clan FindFirst(Predicate<Clan> predicate)
		{
			return Clan.All.FirstOrDefault((Clan x) => predicate(x));
		}

		// Token: 0x06000B71 RID: 2929 RVA: 0x000410A8 File Offset: 0x0003F2A8
		public void EndMercenaryService(bool isByLeavingKingdom)
		{
			this.IsUnderMercenaryService = false;
		}

		// Token: 0x06000B72 RID: 2930 RVA: 0x000410B4 File Offset: 0x0003F2B4
		public static IEnumerable<Clan> FindAll(Predicate<Clan> predicate)
		{
			return from x in Clan.All
			where predicate(x)
			select x;
		}

		// Token: 0x17000261 RID: 609
		// (get) Token: 0x06000B73 RID: 2931 RVA: 0x000410E4 File Offset: 0x0003F2E4
		public static MBReadOnlyList<Clan> All
		{
			get
			{
				return Campaign.Current.Clans;
			}
		}

		// Token: 0x17000262 RID: 610
		// (get) Token: 0x06000B74 RID: 2932 RVA: 0x000410F0 File Offset: 0x0003F2F0
		public static IEnumerable<Clan> NonBanditFactions
		{
			get
			{
				foreach (Clan clan in Campaign.Current.Clans)
				{
					if (!clan.IsBanditFaction)
					{
						yield return clan;
					}
				}
				List<Clan>.Enumerator enumerator = default(List<Clan>.Enumerator);
				yield break;
				yield break;
			}
		}

		// Token: 0x06000B75 RID: 2933 RVA: 0x000410FC File Offset: 0x0003F2FC
		public float CalculateTotalSettlementValueForFaction(Kingdom kingdom)
		{
			float num = 0f;
			foreach (Town town in this.Fiefs)
			{
				num += Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForFaction(town.Owner.Settlement, kingdom);
			}
			return num;
		}

		// Token: 0x17000263 RID: 611
		// (get) Token: 0x06000B76 RID: 2934 RVA: 0x00041174 File Offset: 0x0003F374
		public static IEnumerable<Clan> BanditFactions
		{
			get
			{
				foreach (Clan clan in Campaign.Current.Clans)
				{
					if (clan.IsBanditFaction)
					{
						yield return clan;
					}
				}
				List<Clan>.Enumerator enumerator = default(List<Clan>.Enumerator);
				yield break;
				yield break;
			}
		}

		// Token: 0x06000B77 RID: 2935 RVA: 0x00041180 File Offset: 0x0003F380
		internal void OnFortificationAdded(Town settlement)
		{
			this._fiefsCache.Add(settlement);
			this._settlementsCache.Add(settlement.Settlement);
			foreach (Village village in settlement.Settlement.BoundVillages)
			{
				this.OnBoundVillageAddedInternal(village);
			}
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
			if (this._kingdom != null)
			{
				this._kingdom.OnFortificationAdded(settlement);
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000B78 RID: 2936 RVA: 0x00041218 File Offset: 0x0003F418
		internal void OnFortificationRemoved(Town settlement)
		{
			this._fiefsCache.Remove(settlement);
			this._settlementsCache.Remove(settlement.Settlement);
			foreach (Village village in settlement.Settlement.BoundVillages)
			{
				this._villagesCache.Remove(village);
				this._settlementsCache.Remove(village.Settlement);
			}
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
			if (this._kingdom != null)
			{
				this._kingdom.OnFortificationRemoved(settlement);
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000B79 RID: 2937 RVA: 0x000412C8 File Offset: 0x0003F4C8
		internal void OnBoundVillageAdded(Village village)
		{
			this.OnBoundVillageAddedInternal(village);
			if (this._kingdom != null)
			{
				this._kingdom.OnBoundVillageAdded(village);
			}
		}

		// Token: 0x06000B7A RID: 2938 RVA: 0x000412E5 File Offset: 0x0003F4E5
		private void OnBoundVillageAddedInternal(Village village)
		{
			this._villagesCache.Add(village);
			this._settlementsCache.Add(village.Settlement);
		}

		// Token: 0x06000B7B RID: 2939 RVA: 0x00041304 File Offset: 0x0003F504
		internal void OnLordAdded(Hero lord)
		{
			if (lord.IsDead)
			{
				this._deadLordsCache.Add(lord);
			}
			else
			{
				this._aliveLordsCache.Add(lord);
			}
			this.OnHeroAdded(lord);
		}

		// Token: 0x06000B7C RID: 2940 RVA: 0x0004132F File Offset: 0x0003F52F
		public void OnHeroChangedState(Hero hero, Hero.CharacterStates oldState)
		{
			if (hero.IsDead && oldState != Hero.CharacterStates.Dead)
			{
				this._aliveLordsCache.Remove(hero);
				this._deadLordsCache.Add(hero);
				if (this._kingdom != null)
				{
					this._kingdom.OnHeroChangedState(hero, oldState);
				}
			}
		}

		// Token: 0x06000B7D RID: 2941 RVA: 0x0004136B File Offset: 0x0003F56B
		internal void OnLordRemoved(Hero lord)
		{
			if (lord.IsDead)
			{
				this._deadLordsCache.Remove(lord);
			}
			else
			{
				this._aliveLordsCache.Remove(lord);
			}
			this.OnHeroRemoved(lord);
		}

		// Token: 0x06000B7E RID: 2942 RVA: 0x00041398 File Offset: 0x0003F598
		internal void OnCompanionAdded(Hero companion)
		{
			this._companionsCache.Add(companion);
			this.OnHeroAdded(companion);
		}

		// Token: 0x06000B7F RID: 2943 RVA: 0x000413AD File Offset: 0x0003F5AD
		internal void OnCompanionRemoved(Hero companion)
		{
			this._companionsCache.Remove(companion);
			this.OnHeroRemoved(companion);
		}

		// Token: 0x06000B80 RID: 2944 RVA: 0x000413C3 File Offset: 0x0003F5C3
		private void OnHeroAdded(Hero hero)
		{
			this._heroesCache.Add(hero);
			if (this._kingdom != null)
			{
				this._kingdom.OnHeroAdded(hero);
			}
		}

		// Token: 0x06000B81 RID: 2945 RVA: 0x000413E5 File Offset: 0x0003F5E5
		private void OnHeroRemoved(Hero hero)
		{
			this._heroesCache.Remove(hero);
			if (this._kingdom != null)
			{
				this._kingdom.OnHeroRemoved(hero);
			}
		}

		// Token: 0x06000B82 RID: 2946 RVA: 0x00041408 File Offset: 0x0003F608
		internal void OnWarPartyAdded(WarPartyComponent warPartyComponent)
		{
			this._warPartyComponentsCache.Add(warPartyComponent);
			if (this._kingdom != null)
			{
				this._kingdom.OnWarPartyAdded(warPartyComponent);
			}
		}

		// Token: 0x06000B83 RID: 2947 RVA: 0x0004142A File Offset: 0x0003F62A
		internal void OnWarPartyRemoved(WarPartyComponent warPartyComponent)
		{
			this._warPartyComponentsCache.Remove(warPartyComponent);
			if (this._kingdom != null)
			{
				this._kingdom.OnWarPartyRemoved(warPartyComponent);
			}
		}

		// Token: 0x06000B84 RID: 2948 RVA: 0x0004144D File Offset: 0x0003F64D
		internal void OnSupporterNotableAdded(Hero hero)
		{
			this._supporterNotablesCache.Add(hero);
		}

		// Token: 0x06000B85 RID: 2949 RVA: 0x0004145B File Offset: 0x0003F65B
		internal void OnSupporterNotableRemoved(Hero hero)
		{
			this._supporterNotablesCache.Remove(hero);
		}

		// Token: 0x06000B86 RID: 2950 RVA: 0x0004146C File Offset: 0x0003F66C
		public void AddRenown(float value, bool shouldNotify = true)
		{
			if (value > 0f)
			{
				this.Renown += value;
				int num = Campaign.Current.Models.ClanTierModel.CalculateTier(this);
				if (num > this.Tier)
				{
					this.Tier = num;
					CampaignEventDispatcher.Instance.OnClanTierChanged(this, shouldNotify);
				}
			}
		}

		// Token: 0x06000B87 RID: 2951 RVA: 0x000414C1 File Offset: 0x0003F6C1
		public void ResetClanRenown()
		{
			this.Renown = 0f;
			this.Tier = Campaign.Current.Models.ClanTierModel.CalculateTier(this);
			CampaignEventDispatcher.Instance.OnClanTierChanged(this, false);
		}

		// Token: 0x06000B88 RID: 2952 RVA: 0x000414F8 File Offset: 0x0003F6F8
		public void OnSupportedByClan(Clan supporterClan)
		{
			DiplomacyModel diplomacyModel = Campaign.Current.Models.DiplomacyModel;
			int influenceCostOfSupportingClan = diplomacyModel.GetInfluenceCostOfSupportingClan();
			if (supporterClan.Influence >= (float)influenceCostOfSupportingClan)
			{
				int influenceValueOfSupportingClan = diplomacyModel.GetInfluenceValueOfSupportingClan();
				int relationValueOfSupportingClan = diplomacyModel.GetRelationValueOfSupportingClan();
				ChangeClanInfluenceAction.Apply(supporterClan, (float)(-(float)influenceCostOfSupportingClan));
				ChangeClanInfluenceAction.Apply(this, (float)influenceValueOfSupportingClan);
				ChangeRelationAction.ApplyRelationChangeBetweenHeroes(supporterClan.Leader, this.Leader, relationValueOfSupportingClan, true);
			}
		}

		// Token: 0x06000B89 RID: 2953 RVA: 0x00041558 File Offset: 0x0003F758
		public static Clan CreateSettlementRebelClan(Settlement settlement, Hero owner, int iconMeshId = -1)
		{
			TextObject textObject = new TextObject("{=2LIV2cy7}{SETTLEMENT}{.o} rebels", null);
			textObject.SetTextVariable("SETTLEMENT", settlement.Name);
			Clan clan = Clan.CreateClan(settlement.StringId + "_rebel_clan");
			clan.ChangeClanName(textObject, textObject);
			clan.Culture = settlement.Culture;
			clan.Banner = Banner.CreateOneColoredBannerWithOneIcon(settlement.MapFaction.Banner.GetFirstIconColor(), settlement.MapFaction.Banner.GetPrimaryColor(), iconMeshId);
			clan.SetInitialHomeSettlement(settlement);
			clan.SetLeader(owner);
			clan.Color = settlement.MapFaction.Color2;
			clan.Color2 = settlement.MapFaction.Color;
			clan.Tier = Campaign.Current.Models.ClanTierModel.RebelClanStartingTier;
			clan.BannerBackgroundColorPrimary = settlement.MapFaction.Banner.GetFirstIconColor();
			clan.BannerBackgroundColorSecondary = settlement.MapFaction.Banner.GetFirstIconColor();
			clan.BannerIconColor = settlement.MapFaction.Banner.GetPrimaryColor();
			clan._distanceToClosestNonAllyFortificationCacheDirty = true;
			clan.HomeSettlement = settlement;
			clan.IsRebelClan = true;
			clan.CalculateMidSettlement();
			CampaignEventDispatcher.Instance.OnClanCreated(clan, false);
			return clan;
		}

		// Token: 0x06000B8A RID: 2954 RVA: 0x0004168D File Offset: 0x0003F88D
		public void CalculateMidSettlement()
		{
			if (Campaign.Current.MapSceneWrapper != null)
			{
				this._midSettlement = FactionHelper.GetMidSettlementOfFaction(this);
			}
		}

		// Token: 0x06000B8B RID: 2955 RVA: 0x000416A8 File Offset: 0x0003F8A8
		public static Clan CreateCompanionToLordClan(Hero hero, Settlement settlement, TextObject clanName, int newClanIconId)
		{
			Clan clan = Clan.CreateClan(Hero.MainHero.MapFaction.StringId + "_companion_clan");
			clan.ChangeClanName(clanName, clanName);
			clan.Culture = settlement.Culture;
			clan.Banner = Banner.CreateOneColoredBannerWithOneIcon(settlement.MapFaction.Banner.GetFirstIconColor(), settlement.MapFaction.Banner.GetPrimaryColor(), newClanIconId);
			clan.Kingdom = Hero.MainHero.Clan.Kingdom;
			clan.Tier = Campaign.Current.Models.ClanTierModel.CompanionToLordClanStartingTier;
			clan.SetInitialHomeSettlement(settlement);
			hero.Clan = clan;
			clan.SetLeader(hero);
			clan.IsNoble = true;
			ChangeOwnerOfSettlementAction.ApplyByGift(settlement, hero);
			CampaignEventDispatcher.Instance.OnClanCreated(clan, true);
			return clan;
		}

		// Token: 0x06000B8C RID: 2956 RVA: 0x00041774 File Offset: 0x0003F974
		public Dictionary<Hero, int> GetHeirApparents()
		{
			Dictionary<Hero, int> dictionary = new Dictionary<Hero, int>();
			int heroComesOfAge = Campaign.Current.Models.AgeModel.HeroComesOfAge;
			Hero leader = this.Leader;
			foreach (Hero hero in this.Heroes)
			{
				if (hero != this.Leader && hero.IsAlive && hero.DeathMark == KillCharacterAction.KillCharacterActionDetail.None && !hero.IsNotSpawned && !hero.IsDisabled && !hero.IsWanderer && !hero.IsNotable && hero.Age >= (float)heroComesOfAge)
				{
					int value = Campaign.Current.Models.HeirSelectionCalculationModel.CalculateHeirSelectionPoint(hero, this.Leader, ref leader);
					dictionary.Add(hero, value);
				}
			}
			if (leader != this.Leader)
			{
				Dictionary<Hero, int> dictionary2 = dictionary;
				Hero key = leader;
				dictionary2[key] += Campaign.Current.Models.HeirSelectionCalculationModel.HighestSkillPoint;
			}
			return dictionary;
		}

		// Token: 0x06000B8D RID: 2957 RVA: 0x00041894 File Offset: 0x0003FA94
		private void UpdateBannerColorsAccordingToKingdom()
		{
			if (this.Kingdom != null)
			{
				Banner banner = this.Banner;
				if (banner != null)
				{
					banner.ChangePrimaryColor(this.Kingdom.PrimaryBannerColor);
				}
				Banner banner2 = this.Banner;
				if (banner2 != null)
				{
					banner2.ChangeIconColors(this.Kingdom.SecondaryBannerColor);
				}
				if (this.Kingdom.RulingClan == this)
				{
					Banner banner3 = this._banner;
					if (banner3 != null)
					{
						banner3.ChangePrimaryColor(this.Kingdom.PrimaryBannerColor);
					}
					Banner banner4 = this._banner;
					if (banner4 != null)
					{
						banner4.ChangeIconColors(this.Kingdom.SecondaryBannerColor);
					}
				}
			}
			else if (this.BannerBackgroundColorPrimary != 0U || this.BannerBackgroundColorSecondary != 0U || this.BannerIconColor != 0U)
			{
				Banner banner5 = this.Banner;
				if (banner5 != null)
				{
					banner5.ChangeBackgroundColor(this.BannerBackgroundColorPrimary, this.BannerBackgroundColorSecondary);
				}
				Banner banner6 = this.Banner;
				if (banner6 != null)
				{
					banner6.ChangeIconColors(this.BannerIconColor);
				}
			}
			else if (this.IsMinorFaction)
			{
				Banner banner7 = this.Banner;
				if (banner7 != null)
				{
					banner7.ChangePrimaryColor(this.Color);
				}
				Banner banner8 = this.Banner;
				if (banner8 != null)
				{
					banner8.ChangeIconColors((this.Color != this.Color2) ? this.Color2 : uint.MaxValue);
				}
			}
			foreach (WarPartyComponent warPartyComponent in this.WarPartyComponents)
			{
				warPartyComponent.Party.SetVisualAsDirty();
			}
		}

		// Token: 0x06000B8E RID: 2958 RVA: 0x00041A14 File Offset: 0x0003FC14
		public void UpdateBannerColor(uint backgroundColor, uint iconColor)
		{
			this.BannerBackgroundColorPrimary = backgroundColor;
			this.BannerBackgroundColorSecondary = backgroundColor;
			this.BannerIconColor = iconColor;
		}

		// Token: 0x06000B8F RID: 2959 RVA: 0x00041A2B File Offset: 0x0003FC2B
		internal void DeactivateClan()
		{
			this._isEliminated = true;
		}

		// Token: 0x06000B90 RID: 2960 RVA: 0x00041A34 File Offset: 0x0003FC34
		string IFaction.get_StringId()
		{
			return base.StringId;
		}

		// Token: 0x06000B91 RID: 2961 RVA: 0x00041A3C File Offset: 0x0003FC3C
		MBGUID IFaction.get_Id()
		{
			return base.Id;
		}

		// Token: 0x040002F6 RID: 758
		[SaveableField(54)]
		private PartyTemplateObject _defaultPartyTemplate;

		// Token: 0x040002FB RID: 763
		[SaveableField(97)]
		private bool _isEliminated;

		// Token: 0x040002FC RID: 764
		[SaveableField(99)]
		private MBList<CharacterObject> _minorFactionCharacterTemplates;

		// Token: 0x040002FD RID: 765
		[CachedData]
		private MBList<Hero> _supporterNotablesCache;

		// Token: 0x040002FE RID: 766
		[SaveableField(57)]
		private Kingdom _kingdom;

		// Token: 0x040002FF RID: 767
		[CachedData]
		private MBList<Town> _fiefsCache;

		// Token: 0x04000300 RID: 768
		[CachedData]
		private MBList<Village> _villagesCache;

		// Token: 0x04000301 RID: 769
		[CachedData]
		private MBList<Settlement> _settlementsCache;

		// Token: 0x04000302 RID: 770
		[CachedData]
		private MBList<Hero> _aliveLordsCache;

		// Token: 0x04000303 RID: 771
		[CachedData]
		private MBList<Hero> _deadLordsCache;

		// Token: 0x04000304 RID: 772
		[CachedData]
		private MBList<Hero> _heroesCache;

		// Token: 0x04000305 RID: 773
		[CachedData]
		private MBList<Hero> _companionsCache;

		// Token: 0x04000306 RID: 774
		[CachedData]
		private MBList<WarPartyComponent> _warPartyComponentsCache;

		// Token: 0x04000307 RID: 775
		[SaveableField(62)]
		private float _influence;

		// Token: 0x04000319 RID: 793
		[CachedData]
		private Settlement _midSettlement;

		// Token: 0x0400031A RID: 794
		[SaveableField(82)]
		private CharacterObject _basicTroop;

		// Token: 0x0400031B RID: 795
		[SaveableField(83)]
		private Hero _leader;

		// Token: 0x0400031C RID: 796
		[SaveableField(84)]
		private Banner _banner;

		// Token: 0x04000320 RID: 800
		[SaveableField(91)]
		private int _tier;

		// Token: 0x04000322 RID: 802
		[SaveableField(120)]
		private float _aggressiveness;

		// Token: 0x04000323 RID: 803
		[SaveableField(130)]
		private int _tributeWallet;

		// Token: 0x04000324 RID: 804
		[SaveableField(95)]
		private Settlement _home;

		// Token: 0x04000325 RID: 805
		[SaveableField(110)]
		private int _clanDebtToKingdom;

		// Token: 0x04000326 RID: 806
		private MBList<IFaction> _factionsAtWarWith;

		// Token: 0x04000327 RID: 807
		[CachedData]
		private float _distanceToClosestNonAllyFortificationCache;

		// Token: 0x04000328 RID: 808
		[CachedData]
		internal bool _distanceToClosestNonAllyFortificationCacheDirty = true;
	}
}
