using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.BarterSystem.Barterables;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002C3 RID: 707
	public class DeclareWarDecision : KingdomDecision
	{
		// Token: 0x060025B2 RID: 9650 RVA: 0x0009CCF3 File Offset: 0x0009AEF3
		internal static void AutoGeneratedStaticCollectObjectsDeclareWarDecision(object o, List<object> collectedObjects)
		{
			((DeclareWarDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060025B3 RID: 9651 RVA: 0x0009CD01 File Offset: 0x0009AF01
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.FactionToDeclareWarOn);
		}

		// Token: 0x060025B4 RID: 9652 RVA: 0x0009CD16 File Offset: 0x0009AF16
		internal static object AutoGeneratedGetMemberValueFactionToDeclareWarOn(object o)
		{
			return ((DeclareWarDecision)o).FactionToDeclareWarOn;
		}

		// Token: 0x060025B5 RID: 9653 RVA: 0x0009CD23 File Offset: 0x0009AF23
		public DeclareWarDecision(Clan proposerClan, IFaction factionToDeclareWarOn) : base(proposerClan)
		{
			this.FactionToDeclareWarOn = factionToDeclareWarOn;
		}

		// Token: 0x060025B6 RID: 9654 RVA: 0x0009CD34 File Offset: 0x0009AF34
		public override bool IsAllowed()
		{
			TextObject textObject;
			return !this.FactionToDeclareWarOn.IsKingdomFaction || Campaign.Current.Models.KingdomDecisionPermissionModel.IsWarDecisionAllowedBetweenKingdoms(base.Kingdom, this.FactionToDeclareWarOn as Kingdom, out textObject);
		}

		// Token: 0x060025B7 RID: 9655 RVA: 0x0009CD77 File Offset: 0x0009AF77
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.DiplomacyModel.GetInfluenceCostOfProposingWar(base.ProposerClan);
		}

		// Token: 0x060025B8 RID: 9656 RVA: 0x0009CD93 File Offset: 0x0009AF93
		public override TextObject GetGeneralTitle()
		{
			TextObject textObject = new TextObject("{=rtfoywJl}Declare war on the {KINGDOM_NAME}", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025B9 RID: 9657 RVA: 0x0009CDB7 File Offset: 0x0009AFB7
		public override TextObject GetSupportTitle()
		{
			TextObject textObject = new TextObject("{=xM97H0oR}Vote for declaring war on the {KINGDOM_NAME}.", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025BA RID: 9658 RVA: 0x0009CDDB File Offset: 0x0009AFDB
		public override TextObject GetChooseTitle()
		{
			TextObject textObject = new TextObject("{=aQAI99d4}Declaring War on the {KINGDOM_NAME}", null);
			textObject.SetTextVariable("KINGDOM_NAME", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025BB RID: 9659 RVA: 0x0009CDFF File Offset: 0x0009AFFF
		public override TextObject GetSupportDescription()
		{
			TextObject textObject = new TextObject("{=KSrNutEO}{FACTION_LEADER} will decide if war will be declared on the {KINGDOM_NAME}. You can pick your stance regarding this decision.", null);
			textObject.SetTextVariable("FACTION_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("KINGDOM_NAME", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025BC RID: 9660 RVA: 0x0009CE40 File Offset: 0x0009B040
		public override TextObject GetChooseDescription()
		{
			TextObject textObject = new TextObject("{=4JSzHkpt}As {?IS_FEMALE}queen{?}king{\\?}, you must decide if war will be declared on the {KINGDOM_NAME}", null);
			textObject.SetTextVariable("IS_FEMALE", this.DetermineChooser().Leader.IsFemale ? 1 : 0);
			textObject.SetTextVariable("KINGDOM_NAME", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025BD RID: 9661 RVA: 0x0009CE91 File Offset: 0x0009B091
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new DeclareWarDecision.DeclareWarDecisionOutcome(true, base.Kingdom, this.FactionToDeclareWarOn);
			yield return new DeclareWarDecision.DeclareWarDecisionOutcome(false, base.Kingdom, this.FactionToDeclareWarOn);
			yield break;
		}

		// Token: 0x060025BE RID: 9662 RVA: 0x0009CEA1 File Offset: 0x0009B0A1
		public override Clan DetermineChooser()
		{
			return base.Kingdom.RulingClan;
		}

		// Token: 0x060025BF RID: 9663 RVA: 0x0009CEAE File Offset: 0x0009B0AE
		protected override bool ShouldBeCancelledInternal()
		{
			return this.FactionToDeclareWarOn.IsEliminated || base.Kingdom.IsAtWarWith(this.FactionToDeclareWarOn);
		}

		// Token: 0x060025C0 RID: 9664 RVA: 0x0009CED0 File Offset: 0x0009B0D0
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((DeclareWarDecision.DeclareWarDecisionOutcome)decisionOutcome).ShouldWarBeDeclared)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x060025C1 RID: 9665 RVA: 0x0009CF3C File Offset: 0x0009B13C
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			if (((DeclareWarDecision.DeclareWarDecisionOutcome)chosenOutcome).ShouldWarBeDeclared)
			{
				DeclareWarAction.ApplyByKingdomDecision(base.Kingdom, this.FactionToDeclareWarOn);
			}
		}

		// Token: 0x060025C2 RID: 9666 RVA: 0x0009CF5C File Offset: 0x0009B15C
		public override TextObject GetSecondaryEffects()
		{
			return new TextObject("{=!}All supporters gains some relation with each other.", null);
		}

		// Token: 0x060025C3 RID: 9667 RVA: 0x0009CF69 File Offset: 0x0009B169
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x060025C4 RID: 9668 RVA: 0x0009CF6C File Offset: 0x0009B16C
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if (((DeclareWarDecision.DeclareWarDecisionOutcome)chosenOutcome).ShouldWarBeDeclared)
			{
				if (base.IsSingleClanDecision())
				{
					textObject = new TextObject("{=Shk9QCDg}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} has declared war on the {KINGDOM}.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject = new TextObject("{=cRpsjvOM}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} has declared war on the {KINGDOM} with the support of {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject = new TextObject("{=DphlPaF9}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} has declared war on the {KINGDOM} despite opposition from {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else
				{
					textObject = new TextObject("{=RH8mgLEk}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} has declared war on the {KINGDOM} with support from half of {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council.", null);
				}
			}
			else if (base.IsSingleClanDecision())
			{
				textObject = new TextObject("{=9WDK03GW}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} chose not to go to war with the {KINGDOM}.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Majority)
			{
				textObject = new TextObject("{=8RBZaQKk}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} chose not to go to war with the {KINGDOM} with the support of {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Minority)
			{
				textObject = new TextObject("{=XaZyU3Cn}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} chose not to go to war with the {KINGDOM} despite the wishes of {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else
			{
				textObject = new TextObject("{=5L0wDGhR}{AGGRESSOR_RULER.NAME} of the {AGGRESSOR_KINGDOM} chose not to go to war with the {KINGDOM}, with {?AGGRESSOR_RULER.GENDER}her{?}his{\\?} council evenly split.", null);
			}
			StringHelpers.SetCharacterProperties("AGGRESSOR_RULER", base.Kingdom.Leader.CharacterObject, textObject, false);
			textObject.SetTextVariable("AGGRESSOR_KINGDOM", base.Kingdom.EncyclopediaLinkWithName);
			textObject.SetTextVariable("KINGDOM", this.FactionToDeclareWarOn.InformalName);
			return textObject;
		}

		// Token: 0x060025C5 RID: 9669 RVA: 0x0009D060 File Offset: 0x0009B260
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((DeclareWarDecision.DeclareWarDecisionOutcome)t).ShouldWarBeDeclared);
		}

		// Token: 0x060025C6 RID: 9670 RVA: 0x0009D087 File Offset: 0x0009B287
		public float CalculateSupport(Clan clan)
		{
			return this.DetermineSupport(clan, new DeclareWarDecision.DeclareWarDecisionOutcome(true, base.Kingdom, this.FactionToDeclareWarOn));
		}

		// Token: 0x060025C7 RID: 9671 RVA: 0x0009D0A4 File Offset: 0x0009B2A4
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			Hero leader = clan.Leader;
			DeclareWarDecision.DeclareWarDecisionOutcome declareWarDecisionOutcome = (DeclareWarDecision.DeclareWarDecisionOutcome)possibleOutcome;
			float num = (float)new DeclareWarBarterable(base.Kingdom, this.FactionToDeclareWarOn).GetValueForFaction(clan) * Campaign.Current.Models.DiplomacyModel.DenarsToInfluence();
			if (declareWarDecisionOutcome.ShouldWarBeDeclared)
			{
				float num2 = num;
				int num3 = clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 20 - clan.Leader.GetTraitLevel(DefaultTraits.Mercy) * 10;
				return num2 + (float)num3;
			}
			float num4 = -num;
			int num5 = -clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 20 + clan.Leader.GetTraitLevel(DefaultTraits.Mercy) * 10;
			return num4 + (float)num5;
		}

		// Token: 0x04000B1A RID: 2842
		[SaveableField(101)]
		public readonly IFaction FactionToDeclareWarOn;

		// Token: 0x0200064C RID: 1612
		public class DeclareWarDecisionOutcome : DecisionOutcome
		{
			// Token: 0x06005058 RID: 20568 RVA: 0x001826B8 File Offset: 0x001808B8
			internal static void AutoGeneratedStaticCollectObjectsDeclareWarDecisionOutcome(object o, List<object> collectedObjects)
			{
				((DeclareWarDecision.DeclareWarDecisionOutcome)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005059 RID: 20569 RVA: 0x001826C6 File Offset: 0x001808C6
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this.Kingdom);
				collectedObjects.Add(this.FactionToDeclareWarOn);
			}

			// Token: 0x0600505A RID: 20570 RVA: 0x001826E7 File Offset: 0x001808E7
			internal static object AutoGeneratedGetMemberValueShouldWarBeDeclared(object o)
			{
				return ((DeclareWarDecision.DeclareWarDecisionOutcome)o).ShouldWarBeDeclared;
			}

			// Token: 0x0600505B RID: 20571 RVA: 0x001826F9 File Offset: 0x001808F9
			internal static object AutoGeneratedGetMemberValueKingdom(object o)
			{
				return ((DeclareWarDecision.DeclareWarDecisionOutcome)o).Kingdom;
			}

			// Token: 0x0600505C RID: 20572 RVA: 0x00182706 File Offset: 0x00180906
			internal static object AutoGeneratedGetMemberValueFactionToDeclareWarOn(object o)
			{
				return ((DeclareWarDecision.DeclareWarDecisionOutcome)o).FactionToDeclareWarOn;
			}

			// Token: 0x0600505D RID: 20573 RVA: 0x00182713 File Offset: 0x00180913
			public DeclareWarDecisionOutcome(bool shouldWarBeDeclared, Kingdom kingdom, IFaction factionToDeclareWarOn)
			{
				this.ShouldWarBeDeclared = shouldWarBeDeclared;
				this.Kingdom = kingdom;
				this.FactionToDeclareWarOn = factionToDeclareWarOn;
			}

			// Token: 0x0600505E RID: 20574 RVA: 0x00182730 File Offset: 0x00180930
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldWarBeDeclared ? 1 : 0);
				return textObject;
			}

			// Token: 0x0600505F RID: 20575 RVA: 0x00182758 File Offset: 0x00180958
			public override TextObject GetDecisionDescription()
			{
				if (base.SponsorClan != null && this.Kingdom != null && this.FactionToDeclareWarOn != null && base.SponsorClan != Clan.PlayerClan)
				{
					TextObject empty = TextObject.GetEmpty();
					if (this.ShouldWarBeDeclared)
					{
						Campaign.Current.Models.DiplomacyModel.GetScoreOfDeclaringWar(this.Kingdom, this.FactionToDeclareWarOn, base.SponsorClan, out empty, true);
					}
					if (!empty.IsEmpty())
					{
						return empty;
					}
				}
				if (this.ShouldWarBeDeclared)
				{
					return new TextObject("{=w9olmhv0}It is time to declare war", null);
				}
				return new TextObject("{=epnk9qIt}We oppose a declaration of war", null);
			}

			// Token: 0x06005060 RID: 20576 RVA: 0x001827EB File Offset: 0x001809EB
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x06005061 RID: 20577 RVA: 0x001827EE File Offset: 0x001809EE
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x0400195E RID: 6494
			[SaveableField(100)]
			public readonly bool ShouldWarBeDeclared;

			// Token: 0x0400195F RID: 6495
			[SaveableField(110)]
			public readonly Kingdom Kingdom;

			// Token: 0x04001960 RID: 6496
			[SaveableField(120)]
			public readonly IFaction FactionToDeclareWarOn;
		}
	}
}
