using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002BD RID: 701
	public class ExpelClanFromKingdomDecision : KingdomDecision
	{
		// Token: 0x0600250A RID: 9482 RVA: 0x0009A8B8 File Offset: 0x00098AB8
		internal static void AutoGeneratedStaticCollectObjectsExpelClanFromKingdomDecision(object o, List<object> collectedObjects)
		{
			((ExpelClanFromKingdomDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600250B RID: 9483 RVA: 0x0009A8C6 File Offset: 0x00098AC6
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.ClanToExpel);
			collectedObjects.Add(this.OldKingdom);
		}

		// Token: 0x0600250C RID: 9484 RVA: 0x0009A8E7 File Offset: 0x00098AE7
		internal static object AutoGeneratedGetMemberValueClanToExpel(object o)
		{
			return ((ExpelClanFromKingdomDecision)o).ClanToExpel;
		}

		// Token: 0x0600250D RID: 9485 RVA: 0x0009A8F4 File Offset: 0x00098AF4
		internal static object AutoGeneratedGetMemberValueOldKingdom(object o)
		{
			return ((ExpelClanFromKingdomDecision)o).OldKingdom;
		}

		// Token: 0x0600250E RID: 9486 RVA: 0x0009A901 File Offset: 0x00098B01
		public ExpelClanFromKingdomDecision(Clan proposerClan, Clan clan) : base(proposerClan)
		{
			this.ClanToExpel = clan;
			this.OldKingdom = clan.Kingdom;
		}

		// Token: 0x0600250F RID: 9487 RVA: 0x0009A91D File Offset: 0x00098B1D
		public override bool IsAllowed()
		{
			return Campaign.Current.Models.KingdomDecisionPermissionModel.IsExpulsionDecisionAllowed(this.ClanToExpel);
		}

		// Token: 0x06002510 RID: 9488 RVA: 0x0009A939 File Offset: 0x00098B39
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.DiplomacyModel.GetInfluenceCostOfExpellingClan(base.ProposerClan);
		}

		// Token: 0x06002511 RID: 9489 RVA: 0x0009A955 File Offset: 0x00098B55
		public override TextObject GetGeneralTitle()
		{
			TextObject textObject = new TextObject("{=pF92DagG}Expel {CLAN_NAME} from {KINGDOM_NAME}", null);
			textObject.SetTextVariable("CLAN_NAME", this.ClanToExpel.Name);
			textObject.SetTextVariable("KINGDOM_NAME", this.OldKingdom.Name);
			return textObject;
		}

		// Token: 0x06002512 RID: 9490 RVA: 0x0009A990 File Offset: 0x00098B90
		public override TextObject GetSupportTitle()
		{
			TextObject textObject = new TextObject("{=ZwpWX8Zx}Vote for expelling {CLAN_NAME} from the kingdom", null);
			textObject.SetTextVariable("CLAN_NAME", this.ClanToExpel.Name);
			return textObject;
		}

		// Token: 0x06002513 RID: 9491 RVA: 0x0009A9B4 File Offset: 0x00098BB4
		public override TextObject GetChooseTitle()
		{
			TextObject textObject = new TextObject("{=pF92DagG}Expel {CLAN_NAME} from {KINGDOM_NAME}", null);
			textObject.SetTextVariable("CLAN_NAME", this.ClanToExpel.Name);
			textObject.SetTextVariable("KINGDOM_NAME", this.OldKingdom.Name);
			return textObject;
		}

		// Token: 0x06002514 RID: 9492 RVA: 0x0009A9F0 File Offset: 0x00098BF0
		public override TextObject GetSupportDescription()
		{
			TextObject textObject = new TextObject("{=eTr0XHas}{FACTION_LEADER} will decide if {CLAN_NAME} will be expelled from {KINGDOM_NAME}. You can pick your stance regarding this decision.", null);
			textObject.SetTextVariable("FACTION_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("CLAN_NAME", this.ClanToExpel.Name);
			textObject.SetTextVariable("KINGDOM_NAME", this.OldKingdom.Name);
			return textObject;
		}

		// Token: 0x06002515 RID: 9493 RVA: 0x0009AA54 File Offset: 0x00098C54
		public override TextObject GetChooseDescription()
		{
			TextObject textObject = new TextObject("{=J8brFxIW}As {?IS_FEMALE}queen{?}king{\\?} you must decide if {CLAN_NAME} will be expelled from kingdom.", null);
			textObject.SetTextVariable("IS_FEMALE", this.DetermineChooser().Leader.IsFemale ? 1 : 0);
			textObject.SetTextVariable("CLAN_NAME", this.ClanToExpel.Name);
			return textObject;
		}

		// Token: 0x06002516 RID: 9494 RVA: 0x0009AAA5 File Offset: 0x00098CA5
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome(true);
			yield return new ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome(false);
			yield break;
		}

		// Token: 0x06002517 RID: 9495 RVA: 0x0009AAAE File Offset: 0x00098CAE
		public override Clan DetermineChooser()
		{
			return this.OldKingdom.RulingClan;
		}

		// Token: 0x06002518 RID: 9496 RVA: 0x0009AABB File Offset: 0x00098CBB
		protected override bool ShouldBeCancelledInternal()
		{
			return !base.Kingdom.Clans.Contains(this.ClanToExpel);
		}

		// Token: 0x06002519 RID: 9497 RVA: 0x0009AAD8 File Offset: 0x00098CD8
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			bool shouldBeExpelled = ((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)possibleOutcome).ShouldBeExpelled;
			float num = 3.5f;
			float num2 = (float)FactionManager.GetRelationBetweenClans(this.ClanToExpel, clan) * num;
			float num3 = 0f;
			float num4 = 0f;
			float num5 = 0f;
			float num6 = 10000f;
			foreach (Settlement settlement in this.ClanToExpel.Settlements)
			{
				num3 += settlement.GetSettlementValueForFaction(this.OldKingdom) * 0.005f;
			}
			if (clan.Leader.GetTraitLevel(DefaultTraits.Calculating) > 0)
			{
				num5 = this.ClanToExpel.Influence * 0.05f + this.ClanToExpel.Renown * 0.02f;
			}
			if (clan.Leader.GetTraitLevel(DefaultTraits.Commander) > 0)
			{
				foreach (WarPartyComponent warPartyComponent in this.ClanToExpel.WarPartyComponents)
				{
					num4 += (float)warPartyComponent.MobileParty.MemberRoster.TotalManCount * 0.01f;
				}
			}
			float num7 = num6 + num2 + num3 + num4 + num5;
			float result;
			if (shouldBeExpelled)
			{
				result = -num7;
			}
			else
			{
				result = num7;
			}
			return result;
		}

		// Token: 0x0600251A RID: 9498 RVA: 0x0009AC54 File Offset: 0x00098E54
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)decisionOutcome).ShouldBeExpelled)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x0600251B RID: 9499 RVA: 0x0009ACC0 File Offset: 0x00098EC0
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			if (((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)chosenOutcome).ShouldBeExpelled)
			{
				int relationCostOfExpellingClanFromKingdom = Campaign.Current.Models.DiplomacyModel.GetRelationCostOfExpellingClanFromKingdom();
				foreach (Supporter supporter in chosenOutcome.SupporterList)
				{
					if (((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)chosenOutcome).ShouldBeExpelled && this.ClanToExpel.Leader != supporter.Clan.Leader)
					{
						ChangeRelationAction.ApplyRelationChangeBetweenHeroes(this.ClanToExpel.Leader, supporter.Clan.Leader, relationCostOfExpellingClanFromKingdom, true);
					}
				}
				ChangeKingdomAction.ApplyByLeaveKingdom(this.ClanToExpel, true);
			}
		}

		// Token: 0x0600251C RID: 9500 RVA: 0x0009AD80 File Offset: 0x00098F80
		public override TextObject GetSecondaryEffects()
		{
			return new TextObject("{=fJY9uosa}All supporters gain some relations with each other and lose a large amount of relations with the expelled clan.", null);
		}

		// Token: 0x0600251D RID: 9501 RVA: 0x0009AD8D File Offset: 0x00098F8D
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x0600251E RID: 9502 RVA: 0x0009AD90 File Offset: 0x00098F90
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if (((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)chosenOutcome).ShouldBeExpelled)
			{
				if (base.IsSingleClanDecision())
				{
					textObject = new TextObject("{=h5eTEYON}{RULER.NAME} has expelled the {CLAN} clan from the {KINGDOM}.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject = new TextObject("{=rd229FYG}{RULER.NAME} has expelled the {CLAN} clan from the {KINGDOM} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject = new TextObject("{=G3qGLAeQ}{RULER.NAME} has expelled the {CLAN} clan from the {KINGDOM} against the wishes of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else
				{
					textObject = new TextObject("{=m6OVl6Dg}{RULER.NAME} has expelled the {CLAN} clan from the {KINGDOM}, with {?RULER.GENDER}her{?}his{\\?} council evenly split on the matter.", null);
				}
			}
			else if (base.IsSingleClanDecision())
			{
				textObject = new TextObject("{=mvkKP6OE}{RULER.NAME} chose not to expel the {CLAN} clan from the {KINGDOM}.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Majority)
			{
				textObject = new TextObject("{=yBL3TzXw}{RULER.NAME} chose not to expel the {CLAN} clan from the {KINGDOM} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Minority)
			{
				textObject = new TextObject("{=940TwBPs}{RULER.NAME} chose not to expel the {CLAN} clan from the {KINGDOM} over the objections of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else
			{
				textObject = new TextObject("{=Oe1NdVLe}{RULER.NAME} chose not to expel the {CLAN} clan from the {KINGDOM} with {?RULER.GENDER}her{?}his{\\?} council evenly split on the matter.", null);
			}
			textObject.SetTextVariable("CLAN", this.ClanToExpel.Name);
			textObject.SetTextVariable("KINGDOM", this.OldKingdom.Name);
			StringHelpers.SetCharacterProperties("RULER", this.OldKingdom.Leader.CharacterObject, textObject, false);
			return textObject;
		}

		// Token: 0x0600251F RID: 9503 RVA: 0x0009AE84 File Offset: 0x00099084
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)t).ShouldBeExpelled);
		}

		// Token: 0x04000B04 RID: 2820
		private const float ClanFiefModifier = 0.005f;

		// Token: 0x04000B05 RID: 2821
		[SaveableField(100)]
		public readonly Clan ClanToExpel;

		// Token: 0x04000B06 RID: 2822
		[SaveableField(102)]
		public readonly Kingdom OldKingdom;

		// Token: 0x0200063C RID: 1596
		public class ExpelClanDecisionOutcome : DecisionOutcome
		{
			// Token: 0x06005002 RID: 20482 RVA: 0x00181F64 File Offset: 0x00180164
			internal static void AutoGeneratedStaticCollectObjectsExpelClanDecisionOutcome(object o, List<object> collectedObjects)
			{
				((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005003 RID: 20483 RVA: 0x00181F72 File Offset: 0x00180172
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005004 RID: 20484 RVA: 0x00181F7B File Offset: 0x0018017B
			internal static object AutoGeneratedGetMemberValueShouldBeExpelled(object o)
			{
				return ((ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome)o).ShouldBeExpelled;
			}

			// Token: 0x06005005 RID: 20485 RVA: 0x00181F8D File Offset: 0x0018018D
			public ExpelClanDecisionOutcome(bool shouldBeExpelled)
			{
				this.ShouldBeExpelled = shouldBeExpelled;
			}

			// Token: 0x06005006 RID: 20486 RVA: 0x00181F9C File Offset: 0x0018019C
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldBeExpelled ? 1 : 0);
				return textObject;
			}

			// Token: 0x06005007 RID: 20487 RVA: 0x00181FC1 File Offset: 0x001801C1
			public override TextObject GetDecisionDescription()
			{
				if (this.ShouldBeExpelled)
				{
					return new TextObject("{=s8z5Ugvm}The clan should be expelled", null);
				}
				return new TextObject("{=b2InhEeP}We oppose expelling the clan", null);
			}

			// Token: 0x06005008 RID: 20488 RVA: 0x00181FE2 File Offset: 0x001801E2
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x06005009 RID: 20489 RVA: 0x00181FE5 File Offset: 0x001801E5
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x04001935 RID: 6453
			[SaveableField(100)]
			public readonly bool ShouldBeExpelled;
		}
	}
}
