using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000301 RID: 769
	public class GarrisonPartyComponent : PartyComponent
	{
		// Token: 0x06002CAA RID: 11434 RVA: 0x000BB416 File Offset: 0x000B9616
		internal static void AutoGeneratedStaticCollectObjectsGarrisonPartyComponent(object o, List<object> collectedObjects)
		{
			((GarrisonPartyComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002CAB RID: 11435 RVA: 0x000BB424 File Offset: 0x000B9624
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Settlement);
		}

		// Token: 0x06002CAC RID: 11436 RVA: 0x000BB439 File Offset: 0x000B9639
		internal static object AutoGeneratedGetMemberValueSettlement(object o)
		{
			return ((GarrisonPartyComponent)o).Settlement;
		}

		// Token: 0x06002CAD RID: 11437 RVA: 0x000BB448 File Offset: 0x000B9648
		public static MobileParty CreateGarrisonParty(string stringId, Settlement settlement)
		{
			GarrisonPartyComponent.InitializationArgs args = new GarrisonPartyComponent.InitializationArgs();
			return MobileParty.CreateParty(stringId, new GarrisonPartyComponent(settlement, args));
		}

		// Token: 0x06002CAE RID: 11438 RVA: 0x000BB468 File Offset: 0x000B9668
		public static void ConvertPartyToGarrisonParty(MobileParty mobileParty, Settlement settlement)
		{
			mobileParty.SetPartyComponent(new GarrisonPartyComponent(settlement, null), true);
		}

		// Token: 0x17000B03 RID: 2819
		// (get) Token: 0x06002CAF RID: 11439 RVA: 0x000BB478 File Offset: 0x000B9678
		public override Hero PartyOwner
		{
			get
			{
				return this.Settlement.OwnerClan.Leader;
			}
		}

		// Token: 0x06002CB0 RID: 11440 RVA: 0x000BB48A File Offset: 0x000B968A
		public override Banner GetDefaultComponentBanner()
		{
			return this.Settlement.Banner;
		}

		// Token: 0x17000B04 RID: 2820
		// (get) Token: 0x06002CB1 RID: 11441 RVA: 0x000BB498 File Offset: 0x000B9698
		public override TextObject Name
		{
			get
			{
				if (this._cachedName == null)
				{
					this._cachedName = GameTexts.FindText("str_garrison_party_name", null);
					this._cachedName.SetTextVariable("MAJOR_PARTY_LEADER", this.Settlement.Name);
				}
				return this._cachedName;
			}
		}

		// Token: 0x17000B05 RID: 2821
		// (get) Token: 0x06002CB2 RID: 11442 RVA: 0x000BB4E6 File Offset: 0x000B96E6
		public override Settlement HomeSettlement
		{
			get
			{
				return this.Settlement;
			}
		}

		// Token: 0x17000B06 RID: 2822
		// (get) Token: 0x06002CB3 RID: 11443 RVA: 0x000BB4EE File Offset: 0x000B96EE
		public override int WagePaymentLimit
		{
			get
			{
				return this.Settlement.GarrisonWagePaymentLimit;
			}
		}

		// Token: 0x06002CB4 RID: 11444 RVA: 0x000BB4FB File Offset: 0x000B96FB
		public override void SetWagePaymentLimit(int newLimit)
		{
			this.Settlement.SetGarrisonWagePaymentLimit(newLimit);
		}

		// Token: 0x17000B07 RID: 2823
		// (get) Token: 0x06002CB5 RID: 11445 RVA: 0x000BB509 File Offset: 0x000B9709
		public override bool CanHaveNavalNavigationCapability
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000B08 RID: 2824
		// (get) Token: 0x06002CB6 RID: 11446 RVA: 0x000BB50C File Offset: 0x000B970C
		// (set) Token: 0x06002CB7 RID: 11447 RVA: 0x000BB514 File Offset: 0x000B9714
		[SaveableProperty(1)]
		public Settlement Settlement { get; private set; }

		// Token: 0x06002CB8 RID: 11448 RVA: 0x000BB51D File Offset: 0x000B971D
		protected GarrisonPartyComponent(Settlement settlement, GarrisonPartyComponent.InitializationArgs args)
		{
			this.Settlement = settlement;
			this._initializationArgs = args;
		}

		// Token: 0x06002CB9 RID: 11449 RVA: 0x000BB534 File Offset: 0x000B9734
		protected override void OnMobilePartySetOnCreation()
		{
			base.MobileParty.Party.SetVisualAsDirty();
			base.MobileParty.InitializePartyTrade(Campaign.Current.Models.ClanFinanceModel.PartyGoldLowerThreshold);
			base.MobileParty.Ai.DisableAi();
			base.MobileParty.Aggressiveness = 0f;
			base.MobileParty.DesiredAiNavigationType = MobileParty.NavigationType.None;
			if (this._initializationArgs != null)
			{
				this._initializationArgs.InitializeGarrisonPartyProperties(base.MobileParty, this.Settlement);
				this._initializationArgs = null;
			}
		}

		// Token: 0x06002CBA RID: 11450 RVA: 0x000BB5C2 File Offset: 0x000B97C2
		protected override void OnInitialize()
		{
			this.Settlement.Town.GarrisonPartyComponent = this;
		}

		// Token: 0x06002CBB RID: 11451 RVA: 0x000BB5D5 File Offset: 0x000B97D5
		protected override void OnFinalize()
		{
			this.Settlement.Town.GarrisonPartyComponent = null;
		}

		// Token: 0x06002CBC RID: 11452 RVA: 0x000BB5E8 File Offset: 0x000B97E8
		public override void ClearCachedName()
		{
			this._cachedName = null;
		}

		// Token: 0x04000CF5 RID: 3317
		private GarrisonPartyComponent.InitializationArgs _initializationArgs;

		// Token: 0x04000CF6 RID: 3318
		[CachedData]
		private TextObject _cachedName;

		// Token: 0x020006A9 RID: 1705
		protected class InitializationArgs
		{
			// Token: 0x06005249 RID: 21065 RVA: 0x001857AB File Offset: 0x001839AB
			public void InitializeGarrisonPartyProperties(MobileParty mobileParty, Settlement settlement)
			{
				mobileParty.CurrentSettlement = settlement;
				mobileParty.InitializeMobilePartyAtPosition(settlement.GatePosition);
			}
		}
	}
}
