using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core
{
	// Token: 0x02000033 RID: 51
	public sealed class ItemObject : MBObjectBase
	{
		// Token: 0x06000387 RID: 903 RVA: 0x0000DC6C File Offset: 0x0000BE6C
		internal static void AutoGeneratedStaticCollectObjectsItemObject(object o, List<object> collectedObjects)
		{
			((ItemObject)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000388 RID: 904 RVA: 0x0000DC7A File Offset: 0x0000BE7A
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x17000115 RID: 277
		// (get) Token: 0x06000389 RID: 905 RVA: 0x0000DC83 File Offset: 0x0000BE83
		// (set) Token: 0x0600038A RID: 906 RVA: 0x0000DC8B File Offset: 0x0000BE8B
		public ItemComponent ItemComponent { get; private set; }

		// Token: 0x17000116 RID: 278
		// (get) Token: 0x0600038B RID: 907 RVA: 0x0000DC94 File Offset: 0x0000BE94
		// (set) Token: 0x0600038C RID: 908 RVA: 0x0000DC9C File Offset: 0x0000BE9C
		public string MultiMeshName { get; private set; }

		// Token: 0x17000117 RID: 279
		// (get) Token: 0x0600038D RID: 909 RVA: 0x0000DCA5 File Offset: 0x0000BEA5
		// (set) Token: 0x0600038E RID: 910 RVA: 0x0000DCAD File Offset: 0x0000BEAD
		public string HolsterMeshName { get; private set; }

		// Token: 0x17000118 RID: 280
		// (get) Token: 0x0600038F RID: 911 RVA: 0x0000DCB6 File Offset: 0x0000BEB6
		// (set) Token: 0x06000390 RID: 912 RVA: 0x0000DCBE File Offset: 0x0000BEBE
		public string HolsterWithWeaponMeshName { get; private set; }

		// Token: 0x17000119 RID: 281
		// (get) Token: 0x06000391 RID: 913 RVA: 0x0000DCC7 File Offset: 0x0000BEC7
		// (set) Token: 0x06000392 RID: 914 RVA: 0x0000DCCF File Offset: 0x0000BECF
		public string[] ItemHolsters { get; private set; }

		// Token: 0x1700011A RID: 282
		// (get) Token: 0x06000393 RID: 915 RVA: 0x0000DCD8 File Offset: 0x0000BED8
		// (set) Token: 0x06000394 RID: 916 RVA: 0x0000DCE0 File Offset: 0x0000BEE0
		public Vec3 HolsterPositionShift { get; private set; }

		// Token: 0x1700011B RID: 283
		// (get) Token: 0x06000395 RID: 917 RVA: 0x0000DCE9 File Offset: 0x0000BEE9
		// (set) Token: 0x06000396 RID: 918 RVA: 0x0000DCF1 File Offset: 0x0000BEF1
		public bool HasLowerHolsterPriority { get; private set; }

		// Token: 0x1700011C RID: 284
		// (get) Token: 0x06000397 RID: 919 RVA: 0x0000DCFA File Offset: 0x0000BEFA
		// (set) Token: 0x06000398 RID: 920 RVA: 0x0000DD02 File Offset: 0x0000BF02
		public string FlyingMeshName { get; private set; }

		// Token: 0x1700011D RID: 285
		// (get) Token: 0x06000399 RID: 921 RVA: 0x0000DD0B File Offset: 0x0000BF0B
		// (set) Token: 0x0600039A RID: 922 RVA: 0x0000DD13 File Offset: 0x0000BF13
		public string BodyName { get; private set; }

		// Token: 0x1700011E RID: 286
		// (get) Token: 0x0600039B RID: 923 RVA: 0x0000DD1C File Offset: 0x0000BF1C
		// (set) Token: 0x0600039C RID: 924 RVA: 0x0000DD24 File Offset: 0x0000BF24
		public string SkeletonName { get; private set; }

		// Token: 0x1700011F RID: 287
		// (get) Token: 0x0600039D RID: 925 RVA: 0x0000DD2D File Offset: 0x0000BF2D
		// (set) Token: 0x0600039E RID: 926 RVA: 0x0000DD35 File Offset: 0x0000BF35
		public string StaticAnimationName { get; private set; }

		// Token: 0x17000120 RID: 288
		// (get) Token: 0x0600039F RID: 927 RVA: 0x0000DD3E File Offset: 0x0000BF3E
		// (set) Token: 0x060003A0 RID: 928 RVA: 0x0000DD46 File Offset: 0x0000BF46
		public string HolsterBodyName { get; private set; }

		// Token: 0x17000121 RID: 289
		// (get) Token: 0x060003A1 RID: 929 RVA: 0x0000DD4F File Offset: 0x0000BF4F
		// (set) Token: 0x060003A2 RID: 930 RVA: 0x0000DD57 File Offset: 0x0000BF57
		public string CollisionBodyName { get; private set; }

		// Token: 0x17000122 RID: 290
		// (get) Token: 0x060003A3 RID: 931 RVA: 0x0000DD60 File Offset: 0x0000BF60
		// (set) Token: 0x060003A4 RID: 932 RVA: 0x0000DD68 File Offset: 0x0000BF68
		public bool RecalculateBody { get; private set; }

		// Token: 0x17000123 RID: 291
		// (get) Token: 0x060003A5 RID: 933 RVA: 0x0000DD71 File Offset: 0x0000BF71
		// (set) Token: 0x060003A6 RID: 934 RVA: 0x0000DD79 File Offset: 0x0000BF79
		public string PrefabName { get; private set; }

		// Token: 0x17000124 RID: 292
		// (get) Token: 0x060003A7 RID: 935 RVA: 0x0000DD82 File Offset: 0x0000BF82
		// (set) Token: 0x060003A8 RID: 936 RVA: 0x0000DD8A File Offset: 0x0000BF8A
		public TextObject Name { get; private set; }

		// Token: 0x17000125 RID: 293
		// (get) Token: 0x060003A9 RID: 937 RVA: 0x0000DD93 File Offset: 0x0000BF93
		// (set) Token: 0x060003AA RID: 938 RVA: 0x0000DD9B File Offset: 0x0000BF9B
		public ItemFlags ItemFlags { get; private set; }

		// Token: 0x17000126 RID: 294
		// (get) Token: 0x060003AB RID: 939 RVA: 0x0000DDA4 File Offset: 0x0000BFA4
		// (set) Token: 0x060003AC RID: 940 RVA: 0x0000DDAC File Offset: 0x0000BFAC
		public ItemCategory ItemCategory { get; private set; }

		// Token: 0x17000127 RID: 295
		// (get) Token: 0x060003AD RID: 941 RVA: 0x0000DDB5 File Offset: 0x0000BFB5
		// (set) Token: 0x060003AE RID: 942 RVA: 0x0000DDBD File Offset: 0x0000BFBD
		public int Value { get; private set; }

		// Token: 0x17000128 RID: 296
		// (get) Token: 0x060003AF RID: 943 RVA: 0x0000DDC6 File Offset: 0x0000BFC6
		// (set) Token: 0x060003B0 RID: 944 RVA: 0x0000DDCE File Offset: 0x0000BFCE
		public float Effectiveness { get; private set; }

		// Token: 0x17000129 RID: 297
		// (get) Token: 0x060003B1 RID: 945 RVA: 0x0000DDD7 File Offset: 0x0000BFD7
		// (set) Token: 0x060003B2 RID: 946 RVA: 0x0000DDDF File Offset: 0x0000BFDF
		public float Weight { get; private set; }

		// Token: 0x1700012A RID: 298
		// (get) Token: 0x060003B3 RID: 947 RVA: 0x0000DDE8 File Offset: 0x0000BFE8
		// (set) Token: 0x060003B4 RID: 948 RVA: 0x0000DDF0 File Offset: 0x0000BFF0
		public int Difficulty { get; private set; }

		// Token: 0x1700012B RID: 299
		// (get) Token: 0x060003B5 RID: 949 RVA: 0x0000DDF9 File Offset: 0x0000BFF9
		// (set) Token: 0x060003B6 RID: 950 RVA: 0x0000DE01 File Offset: 0x0000C001
		public float Appearance { get; private set; }

		// Token: 0x1700012C RID: 300
		// (get) Token: 0x060003B7 RID: 951 RVA: 0x0000DE0A File Offset: 0x0000C00A
		// (set) Token: 0x060003B8 RID: 952 RVA: 0x0000DE12 File Offset: 0x0000C012
		public bool IsUsingTableau { get; private set; }

		// Token: 0x1700012D RID: 301
		// (get) Token: 0x060003B9 RID: 953 RVA: 0x0000DE1B File Offset: 0x0000C01B
		public bool IsUsingTeamColor
		{
			get
			{
				return this.ItemFlags.HasAnyFlag(ItemFlags.UseTeamColor);
			}
		}

		// Token: 0x1700012E RID: 302
		// (get) Token: 0x060003BA RID: 954 RVA: 0x0000DE2D File Offset: 0x0000C02D
		public bool DoesNotHideChest
		{
			get
			{
				return this.ItemFlags.HasAnyFlag(ItemFlags.DoesNotHideChest);
			}
		}

		// Token: 0x1700012F RID: 303
		// (get) Token: 0x060003BB RID: 955 RVA: 0x0000DE3F File Offset: 0x0000C03F
		public bool IsCivilian
		{
			get
			{
				return this.ItemFlags.HasAnyFlag(ItemFlags.Civilian);
			}
		}

		// Token: 0x17000130 RID: 304
		// (get) Token: 0x060003BC RID: 956 RVA: 0x0000DE51 File Offset: 0x0000C051
		public bool IsStealthItem
		{
			get
			{
				return this.ItemFlags.HasAnyFlag(ItemFlags.Stealth);
			}
		}

		// Token: 0x17000131 RID: 305
		// (get) Token: 0x060003BD RID: 957 RVA: 0x0000DE63 File Offset: 0x0000C063
		public bool UsingFacegenScaling
		{
			get
			{
				return this.Type == ItemObject.ItemTypeEnum.HeadArmor && this.ArmorComponent.MeshesMask.HasAnyFlag(SkinMask.HeadVisible);
			}
		}

		// Token: 0x17000132 RID: 306
		// (get) Token: 0x060003BE RID: 958 RVA: 0x0000DE82 File Offset: 0x0000C082
		// (set) Token: 0x060003BF RID: 959 RVA: 0x0000DE8A File Offset: 0x0000C08A
		public string ArmBandMeshName { get; private set; }

		// Token: 0x17000133 RID: 307
		// (get) Token: 0x060003C0 RID: 960 RVA: 0x0000DE93 File Offset: 0x0000C093
		// (set) Token: 0x060003C1 RID: 961 RVA: 0x0000DE9B File Offset: 0x0000C09B
		public bool IsFood { get; private set; }

		// Token: 0x17000134 RID: 308
		// (get) Token: 0x060003C2 RID: 962 RVA: 0x0000DEA4 File Offset: 0x0000C0A4
		// (set) Token: 0x060003C3 RID: 963 RVA: 0x0000DEAC File Offset: 0x0000C0AC
		public float ScaleFactor { get; private set; }

		// Token: 0x17000135 RID: 309
		// (get) Token: 0x060003C4 RID: 964 RVA: 0x0000DEB5 File Offset: 0x0000C0B5
		// (set) Token: 0x060003C5 RID: 965 RVA: 0x0000DEBD File Offset: 0x0000C0BD
		public BasicCultureObject Culture { get; private set; }

		// Token: 0x17000136 RID: 310
		// (get) Token: 0x060003C6 RID: 966 RVA: 0x0000DEC6 File Offset: 0x0000C0C6
		// (set) Token: 0x060003C7 RID: 967 RVA: 0x0000DECE File Offset: 0x0000C0CE
		public bool MultiplayerItem { get; private set; }

		// Token: 0x17000137 RID: 311
		// (get) Token: 0x060003C8 RID: 968 RVA: 0x0000DED7 File Offset: 0x0000C0D7
		// (set) Token: 0x060003C9 RID: 969 RVA: 0x0000DEDF File Offset: 0x0000C0DF
		public bool NotMerchandise { get; private set; }

		// Token: 0x17000138 RID: 312
		// (get) Token: 0x060003CA RID: 970 RVA: 0x0000DEE8 File Offset: 0x0000C0E8
		// (set) Token: 0x060003CB RID: 971 RVA: 0x0000DEF0 File Offset: 0x0000C0F0
		public bool IsCraftedByPlayer { get; private set; }

		// Token: 0x17000139 RID: 313
		// (get) Token: 0x060003CC RID: 972 RVA: 0x0000DEF9 File Offset: 0x0000C0F9
		// (set) Token: 0x060003CD RID: 973 RVA: 0x0000DF01 File Offset: 0x0000C101
		public int LodAtlasIndex { get; private set; }

		// Token: 0x1700013A RID: 314
		// (get) Token: 0x060003CE RID: 974 RVA: 0x0000DF0A File Offset: 0x0000C10A
		// (set) Token: 0x060003CF RID: 975 RVA: 0x0000DF12 File Offset: 0x0000C112
		private float TierfOverride { get; set; }

		// Token: 0x1700013B RID: 315
		// (get) Token: 0x060003D0 RID: 976 RVA: 0x0000DF1B File Offset: 0x0000C11B
		public bool IsTransferable
		{
			get
			{
				return Game.Current.BasicModels.ItemValueModel.GetIsTransferable(this);
			}
		}

		// Token: 0x1700013C RID: 316
		// (get) Token: 0x060003D1 RID: 977 RVA: 0x0000DF32 File Offset: 0x0000C132
		public float Tierf
		{
			get
			{
				if (this.TierfOverride >= 1f)
				{
					return this.TierfOverride - 1f;
				}
				return Game.Current.BasicModels.ItemValueModel.CalculateTier(this);
			}
		}

		// Token: 0x1700013D RID: 317
		// (get) Token: 0x060003D2 RID: 978 RVA: 0x0000DF63 File Offset: 0x0000C163
		public bool IsCraftedWeapon
		{
			get
			{
				return this.WeaponDesign != null;
			}
		}

		// Token: 0x1700013E RID: 318
		// (get) Token: 0x060003D3 RID: 979 RVA: 0x0000DF71 File Offset: 0x0000C171
		public ItemObject.ItemTiers Tier
		{
			get
			{
				if (this.ItemComponent == null)
				{
					return ItemObject.ItemTiers.Tier1;
				}
				return (ItemObject.ItemTiers)(MBMath.ClampInt(MathF.Round(this.Tierf), 0, 6) - 1);
			}
		}

		// Token: 0x1700013F RID: 319
		// (get) Token: 0x060003D4 RID: 980 RVA: 0x0000DF91 File Offset: 0x0000C191
		// (set) Token: 0x060003D5 RID: 981 RVA: 0x0000DF99 File Offset: 0x0000C199
		public WeaponDesign WeaponDesign { get; private set; }

		// Token: 0x17000140 RID: 320
		// (get) Token: 0x060003D6 RID: 982 RVA: 0x0000DFA2 File Offset: 0x0000C1A2
		public WeaponComponentData PrimaryWeapon
		{
			get
			{
				WeaponComponent weaponComponent = this.WeaponComponent;
				if (weaponComponent == null)
				{
					return null;
				}
				return weaponComponent.PrimaryWeapon;
			}
		}

		// Token: 0x17000141 RID: 321
		// (get) Token: 0x060003D7 RID: 983 RVA: 0x0000DFB5 File Offset: 0x0000C1B5
		public WeaponComponent WeaponComponent
		{
			get
			{
				return this.ItemComponent as WeaponComponent;
			}
		}

		// Token: 0x17000142 RID: 322
		// (get) Token: 0x060003D8 RID: 984 RVA: 0x0000DFC2 File Offset: 0x0000C1C2
		public bool HasWeaponComponent
		{
			get
			{
				return this.WeaponComponent != null;
			}
		}

		// Token: 0x17000143 RID: 323
		// (get) Token: 0x060003D9 RID: 985 RVA: 0x0000DFCD File Offset: 0x0000C1CD
		public HorseComponent HorseComponent
		{
			get
			{
				return this.ItemComponent as HorseComponent;
			}
		}

		// Token: 0x17000144 RID: 324
		// (get) Token: 0x060003DA RID: 986 RVA: 0x0000DFDA File Offset: 0x0000C1DA
		public bool HasHorseComponent
		{
			get
			{
				return this.HorseComponent != null;
			}
		}

		// Token: 0x17000145 RID: 325
		// (get) Token: 0x060003DB RID: 987 RVA: 0x0000DFE5 File Offset: 0x0000C1E5
		public ArmorComponent ArmorComponent
		{
			get
			{
				return this.ItemComponent as ArmorComponent;
			}
		}

		// Token: 0x17000146 RID: 326
		// (get) Token: 0x060003DC RID: 988 RVA: 0x0000DFF2 File Offset: 0x0000C1F2
		public bool HasArmorComponent
		{
			get
			{
				return this.ArmorComponent != null;
			}
		}

		// Token: 0x17000147 RID: 327
		// (get) Token: 0x060003DD RID: 989 RVA: 0x0000DFFD File Offset: 0x0000C1FD
		public BannerComponent BannerComponent
		{
			get
			{
				return this.ItemComponent as BannerComponent;
			}
		}

		// Token: 0x17000148 RID: 328
		// (get) Token: 0x060003DE RID: 990 RVA: 0x0000E00A File Offset: 0x0000C20A
		public bool HasBannerComponent
		{
			get
			{
				return this.BannerComponent != null;
			}
		}

		// Token: 0x17000149 RID: 329
		// (get) Token: 0x060003DF RID: 991 RVA: 0x0000E015 File Offset: 0x0000C215
		public SaddleComponent SaddleComponent
		{
			get
			{
				return this.ItemComponent as SaddleComponent;
			}
		}

		// Token: 0x1700014A RID: 330
		// (get) Token: 0x060003E0 RID: 992 RVA: 0x0000E022 File Offset: 0x0000C222
		public bool HasSaddleComponent
		{
			get
			{
				return this.SaddleComponent != null;
			}
		}

		// Token: 0x1700014B RID: 331
		// (get) Token: 0x060003E1 RID: 993 RVA: 0x0000E02D File Offset: 0x0000C22D
		public TradeItemComponent FoodComponent
		{
			get
			{
				return this.ItemComponent as TradeItemComponent;
			}
		}

		// Token: 0x1700014C RID: 332
		// (get) Token: 0x060003E2 RID: 994 RVA: 0x0000E03A File Offset: 0x0000C23A
		public bool HasFoodComponent
		{
			get
			{
				return this.FoodComponent != null;
			}
		}

		// Token: 0x060003E3 RID: 995 RVA: 0x0000E045 File Offset: 0x0000C245
		public ItemObject()
		{
		}

		// Token: 0x060003E4 RID: 996 RVA: 0x0000E04D File Offset: 0x0000C24D
		public ItemObject(string stringId) : base(stringId)
		{
		}

		// Token: 0x060003E5 RID: 997 RVA: 0x0000E058 File Offset: 0x0000C258
		public ItemObject(ItemObject itemToCopy) : base(itemToCopy)
		{
			this.ItemComponent = itemToCopy.ItemComponent;
			this.MultiMeshName = itemToCopy.MultiMeshName;
			this.HolsterMeshName = itemToCopy.HolsterMeshName;
			this.HolsterWithWeaponMeshName = itemToCopy.HolsterWithWeaponMeshName;
			this.ItemHolsters = itemToCopy.ItemHolsters;
			this.HolsterPositionShift = itemToCopy.HolsterPositionShift;
			this.FlyingMeshName = itemToCopy.FlyingMeshName;
			this.BodyName = itemToCopy.BodyName;
			this.SkeletonName = itemToCopy.SkeletonName;
			this.StaticAnimationName = itemToCopy.StaticAnimationName;
			this.HolsterBodyName = itemToCopy.HolsterBodyName;
			this.CollisionBodyName = itemToCopy.CollisionBodyName;
			this.RecalculateBody = itemToCopy.RecalculateBody;
			this.PrefabName = itemToCopy.PrefabName;
			this.Name = itemToCopy.Name;
			this.ItemFlags = itemToCopy.ItemFlags;
			this.Value = itemToCopy.Value;
			this.Weight = itemToCopy.Weight;
			this.Difficulty = itemToCopy.Difficulty;
			this.ArmBandMeshName = itemToCopy.ArmBandMeshName;
			this.IsFood = itemToCopy.IsFood;
			this.Type = itemToCopy.Type;
			this.ScaleFactor = itemToCopy.ScaleFactor;
		}

		// Token: 0x060003E6 RID: 998 RVA: 0x0000E180 File Offset: 0x0000C380
		internal void SetCraftedWeaponName(TextObject weaponName)
		{
			this.Name = weaponName;
			if (this.WeaponDesign != null)
			{
				this.WeaponDesign.SetWeaponName(this.Name);
			}
		}

		// Token: 0x060003E7 RID: 999 RVA: 0x0000E1A8 File Offset: 0x0000C3A8
		public static ItemObject InitializeTradeGood(ItemObject item, TextObject name, string meshName, ItemCategory category, int value, float weight, ItemObject.ItemTypeEnum itemType, bool isFood = false)
		{
			item.Initialize();
			item.Name = name;
			item.MultiMeshName = meshName;
			item.ItemCategory = category;
			item.Value = value;
			item.Weight = weight;
			item.ItemType = itemType;
			item.IsFood = isFood;
			item.ItemComponent = new TradeItemComponent();
			item.AfterInitialized();
			item.ItemFlags |= ItemFlags.Civilian;
			return item;
		}

		// Token: 0x060003E8 RID: 1000 RVA: 0x0000E214 File Offset: 0x0000C414
		public static void InitAsPlayerCraftedItem(ref ItemObject itemObject)
		{
			itemObject.IsCraftedByPlayer = true;
		}

		// Token: 0x060003E9 RID: 1001 RVA: 0x0000E220 File Offset: 0x0000C420
		internal static void InitCraftedItemObject(ref ItemObject itemObject, TextObject name, BasicCultureObject culture, ItemFlags itemProperties, float weight, float appearance, WeaponDesign craftedData, ItemObject.ItemTypeEnum itemType)
		{
			BladeData bladeData = craftedData.UsedPieces[0].CraftingPiece.BladeData;
			itemObject.Weight = weight;
			itemObject.Name = name;
			itemObject.MultiMeshName = "";
			itemObject.HolsterMeshName = "";
			itemObject.HolsterWithWeaponMeshName = "";
			itemObject.ItemHolsters = (string[])craftedData.Template.ItemHolsters.Clone();
			itemObject.HolsterPositionShift = craftedData.HolsterShiftAmount;
			itemObject.FlyingMeshName = "";
			itemObject.BodyName = ((bladeData != null) ? bladeData.BodyName : null);
			itemObject.HolsterBodyName = (((bladeData != null) ? bladeData.HolsterBodyName : null) ?? ((bladeData != null) ? bladeData.BodyName : null));
			itemObject.CollisionBodyName = "";
			itemObject.RecalculateBody = true;
			itemObject.Culture = culture;
			itemObject.Difficulty = 0;
			itemObject.ScaleFactor = 1f;
			itemObject.Type = itemType;
			itemObject.ItemFlags = itemProperties;
			itemObject.Appearance = appearance;
			itemObject.WeaponDesign = craftedData;
		}

		// Token: 0x060003EA RID: 1002 RVA: 0x0000E338 File Offset: 0x0000C538
		public override int GetHashCode()
		{
			return (int)base.Id.SubId;
		}

		// Token: 0x060003EB RID: 1003 RVA: 0x0000E353 File Offset: 0x0000C553
		public void SetItemFlagsForCosmetics(ItemFlags newFlags)
		{
			this.ItemFlags = newFlags;
		}

		// Token: 0x060003EC RID: 1004 RVA: 0x0000E35C File Offset: 0x0000C55C
		public void DetermineItemCategoryForItem()
		{
			if (Game.Current.BasicModels.ItemCategorySelector != null && this.ItemCategory == null)
			{
				this.ItemCategory = Game.Current.BasicModels.ItemCategorySelector.GetItemCategoryForItem(this);
			}
		}

		// Token: 0x060003ED RID: 1005 RVA: 0x0000E394 File Offset: 0x0000C594
		public static ItemObject GetCraftedItemObjectFromHashedCode(string hashedCode)
		{
			foreach (ItemObject itemObject in MBObjectManager.Instance.GetObjectTypeList<ItemObject>())
			{
				if (itemObject.IsCraftedWeapon && itemObject.WeaponDesign.HashedCode == hashedCode)
				{
					return itemObject;
				}
			}
			return null;
		}

		// Token: 0x1700014D RID: 333
		// (get) Token: 0x060003EE RID: 1006 RVA: 0x0000E408 File Offset: 0x0000C608
		public MBReadOnlyList<WeaponComponentData> Weapons
		{
			get
			{
				WeaponComponent weaponComponent = this.WeaponComponent;
				if (weaponComponent == null)
				{
					return null;
				}
				return weaponComponent.Weapons;
			}
		}

		// Token: 0x060003EF RID: 1007 RVA: 0x0000E41B File Offset: 0x0000C61B
		public void AddWeapon(WeaponComponentData weapon, ItemModifierGroup itemModifierGroup)
		{
			if (this.WeaponComponent == null)
			{
				this.ItemComponent = new WeaponComponent(this);
			}
			this.WeaponComponent.AddWeapon(weapon, itemModifierGroup);
		}

		// Token: 0x060003F0 RID: 1008 RVA: 0x0000E440 File Offset: 0x0000C640
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			if (node.Name == "CraftedItem")
			{
				XmlNode xmlNode = node.Attributes["multiplayer_item"];
				if (xmlNode != null && !string.IsNullOrEmpty(xmlNode.InnerText))
				{
					this.MultiplayerItem = (xmlNode.InnerText == "true");
				}
				XmlNode xmlNode2 = node.Attributes["is_merchandise"];
				if (xmlNode2 != null && !string.IsNullOrEmpty(xmlNode2.InnerText))
				{
					this.NotMerchandise = (xmlNode2.InnerText != "true");
				}
				TextObject craftedWeaponName = new TextObject(node.Attributes["name"].InnerText, null);
				string innerText = node.Attributes["crafting_template"].InnerText;
				bool flag = node.Attributes["has_modifier"] == null || node.Attributes["has_modifier"].InnerText != "false";
				XmlAttribute xmlAttribute = node.Attributes["modifier_group"];
				string text = (xmlAttribute != null) ? xmlAttribute.Value : null;
				ItemModifierGroup itemModifierGroup = null;
				if (flag)
				{
					if (text == null)
					{
						itemModifierGroup = CraftingTemplate.GetTemplateFromId(innerText).ItemModifierGroup;
					}
					else
					{
						itemModifierGroup = Game.Current.ObjectManager.GetObject<ItemModifierGroup>(text);
					}
				}
				WeaponDesignElement[] array = new WeaponDesignElement[4];
				XmlNode xmlNode3 = null;
				for (int i = 0; i < node.ChildNodes.Count; i++)
				{
					if (node.ChildNodes[i].Name == "Pieces")
					{
						xmlNode3 = node.ChildNodes[i];
						break;
					}
				}
				foreach (object obj in xmlNode3.ChildNodes)
				{
					XmlNode xmlNode4 = (XmlNode)obj;
					if (xmlNode4.Name == "Piece")
					{
						XmlNode xmlNode5 = xmlNode4.Attributes["id"];
						XmlAttribute xmlAttribute2 = xmlNode4.Attributes["Type"];
						XmlAttribute xmlAttribute3 = xmlNode4.Attributes["scale_factor"];
						string innerText2 = xmlNode5.InnerText;
						CraftingPiece.PieceTypes pieceTypes = (CraftingPiece.PieceTypes)Enum.Parse(typeof(CraftingPiece.PieceTypes), xmlAttribute2.InnerText);
						CraftingPiece @object = MBObjectManager.Instance.GetObject<CraftingPiece>(innerText2);
						array[(int)pieceTypes] = WeaponDesignElement.CreateUsablePiece(@object, 100);
						if (xmlAttribute3 != null)
						{
							array[(int)pieceTypes].SetScale(int.Parse(xmlAttribute3.Value));
						}
					}
				}
				ItemObject itemObject = Crafting.CreatePreCraftedWeaponOnDeserialize(this, array, innerText, craftedWeaponName, itemModifierGroup);
				if (itemObject.WeaponComponent == null)
				{
					Debug.FailedAssert("Crafted item: " + itemObject.StringId + " can not be initialized, item replaced with Trash item.", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "Deserialize", 446);
					MBObjectManager.Instance.UnregisterObject(this);
					return;
				}
				this.Effectiveness = this.CalculateEffectiveness();
				if (node.Attributes["value"] != null)
				{
					this.Value = int.Parse(node.Attributes["value"].Value);
				}
				else
				{
					this.DetermineValue();
				}
				if (node.Attributes["culture"] != null)
				{
					this.Culture = (BasicCultureObject)objectManager.ReadObjectReferenceFromXml("culture", typeof(BasicCultureObject), node);
				}
			}
			else
			{
				this.Name = new TextObject(node.Attributes["name"].InnerText, null);
				XmlNode xmlNode6 = node.Attributes["multiplayer_item"];
				if (xmlNode6 != null && !string.IsNullOrEmpty(xmlNode6.InnerText))
				{
					this.MultiplayerItem = (xmlNode6.InnerText == "true");
				}
				XmlNode xmlNode7 = node.Attributes["is_merchandise"];
				if (xmlNode7 != null && !string.IsNullOrEmpty(xmlNode7.InnerText))
				{
					this.NotMerchandise = (xmlNode7.InnerText != "true");
				}
				XmlNode xmlNode8 = node.Attributes["mesh"];
				if (xmlNode8 != null && !string.IsNullOrEmpty(xmlNode8.InnerText))
				{
					this.MultiMeshName = xmlNode8.InnerText;
				}
				this.HolsterMeshName = ((node.Attributes["holster_mesh"] != null) ? node.Attributes["holster_mesh"].Value : null);
				this.HolsterWithWeaponMeshName = ((node.Attributes["holster_mesh_with_weapon"] != null) ? node.Attributes["holster_mesh_with_weapon"].Value : null);
				this.FlyingMeshName = ((node.Attributes["flying_mesh"] != null) ? node.Attributes["flying_mesh"].Value : null);
				this.HasLowerHolsterPriority = false;
				if (node.Attributes["item_holsters"] != null)
				{
					this.ItemHolsters = node.Attributes["item_holsters"].Value.Split(new char[]
					{
						':'
					});
					if (node.Attributes["has_lower_holster_priority"] != null)
					{
						this.HasLowerHolsterPriority = bool.Parse(node.Attributes["has_lower_holster_priority"].Value);
					}
				}
				else
				{
					this.ItemHolsters = new string[4];
				}
				this.HolsterPositionShift = ((node.Attributes["holster_position_shift"] != null) ? Vec3.Parse(node.Attributes["holster_position_shift"].Value) : Vec3.Zero);
				this.BodyName = ((node.Attributes["body_name"] != null) ? node.Attributes["body_name"].Value : null);
				this.SkeletonName = ((node.Attributes["skeleton_name"] != null) ? node.Attributes["skeleton_name"].Value : null);
				this.StaticAnimationName = ((node.Attributes["static_animation_name"] != null) ? node.Attributes["static_animation_name"].Value : null);
				this.HolsterBodyName = ((node.Attributes["holster_body_name"] != null) ? node.Attributes["holster_body_name"].Value : null);
				this.CollisionBodyName = ((node.Attributes["shield_body_name"] != null) ? node.Attributes["shield_body_name"].Value : null);
				this.RecalculateBody = (node.Attributes["recalculate_body"] != null && bool.Parse(node.Attributes["recalculate_body"].Value));
				XmlNode xmlNode9 = node.Attributes["prefab"];
				if (xmlNode9 != null && !string.IsNullOrEmpty(xmlNode9.InnerText))
				{
					this.PrefabName = xmlNode9.InnerText;
				}
				else
				{
					this.PrefabName = "";
				}
				this.Culture = (BasicCultureObject)objectManager.ReadObjectReferenceFromXml("culture", typeof(BasicCultureObject), node);
				string text2 = (node.Attributes["item_category"] != null) ? node.Attributes["item_category"].Value : null;
				if (!string.IsNullOrEmpty(text2))
				{
					this.ItemCategory = Game.Current.ObjectManager.GetObject<ItemCategory>(text2);
				}
				this.Weight = ((node.Attributes["weight"] != null) ? float.Parse(node.Attributes["weight"].Value) : 1f);
				this.LodAtlasIndex = ((node.Attributes["lod_atlas_index"] != null) ? int.Parse(node.Attributes["lod_atlas_index"].Value) : -1);
				XmlAttribute xmlAttribute4 = node.Attributes["difficulty"];
				if (xmlAttribute4 != null)
				{
					this.Difficulty = int.Parse(xmlAttribute4.Value);
				}
				XmlAttribute xmlAttribute5 = node.Attributes["appearance"];
				this.Appearance = ((xmlAttribute5 != null) ? float.Parse(xmlAttribute5.Value) : 0.5f);
				XmlAttribute xmlAttribute6 = node.Attributes["IsFood"];
				if (xmlAttribute6 != null)
				{
					this.IsFood = Convert.ToBoolean(xmlAttribute6.InnerText);
				}
				this.IsUsingTableau = (node.Attributes["using_tableau"] != null && Convert.ToBoolean(node.Attributes["using_tableau"].InnerText));
				XmlNode xmlNode10 = node.Attributes["using_arm_band"];
				if (xmlNode10 != null)
				{
					this.ArmBandMeshName = Convert.ToString(xmlNode10.InnerText);
				}
				this.ScaleFactor = ((node.Attributes["scale_factor"] != null) ? float.Parse(node.Attributes["scale_factor"].Value) : 1f);
				this.ItemFlags = (ItemFlags)0U;
				foreach (object obj2 in node.ChildNodes)
				{
					XmlNode xmlNode11 = (XmlNode)obj2;
					if (xmlNode11.Name == "ItemComponent")
					{
						using (IEnumerator enumerator2 = xmlNode11.ChildNodes.GetEnumerator())
						{
							while (enumerator2.MoveNext())
							{
								object obj3 = enumerator2.Current;
								XmlNode xmlNode12 = (XmlNode)obj3;
								if (xmlNode12.NodeType != XmlNodeType.Comment)
								{
									string name = xmlNode12.Name;
									ItemComponent itemComponent;
									if (!(name == "Armor"))
									{
										if (!(name == "Weapon"))
										{
											if (!(name == "Horse"))
											{
												if (!(name == "Trade"))
												{
													if (!(name == "Food"))
													{
														if (!(name == "Banner"))
														{
															throw new Exception("Wrong ItemComponent type.");
														}
														itemComponent = new BannerComponent(this);
													}
													else
													{
														Debug.FailedAssert("FoodComponent tag has been converted to TradeComponent. Use Trade xml node type", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "Deserialize", 685);
														itemComponent = null;
													}
												}
												else
												{
													itemComponent = new TradeItemComponent();
												}
											}
											else
											{
												itemComponent = new HorseComponent();
											}
										}
										else
										{
											itemComponent = (this.ItemComponent ?? new WeaponComponent(this));
										}
									}
									else
									{
										itemComponent = new ArmorComponent(this);
									}
									if (itemComponent != null)
									{
										itemComponent.Deserialize(objectManager, xmlNode12);
										this.ItemComponent = itemComponent;
									}
								}
							}
							continue;
						}
					}
					if (xmlNode11.Name == "Flags")
					{
						foreach (object obj4 in Enum.GetValues(typeof(ItemFlags)))
						{
							ItemFlags itemFlags = (ItemFlags)obj4;
							XmlAttribute xmlAttribute7 = xmlNode11.Attributes[itemFlags.ToString()];
							if (xmlAttribute7 != null && xmlAttribute7.Value.ToLowerInvariant() != "false")
							{
								this.ItemFlags |= itemFlags;
							}
						}
					}
				}
				XmlAttribute xmlAttribute8 = node.Attributes["Type"];
				if (xmlAttribute8 != null)
				{
					this.Type = (ItemObject.ItemTypeEnum)Enum.Parse(typeof(ItemObject.ItemTypeEnum), xmlAttribute8.Value, true);
					if (this.WeaponComponent != null)
					{
						ItemObject.ItemTypeEnum itemType = this.WeaponComponent.GetItemType();
						if (this.Type != itemType)
						{
							Debug.Print(string.Concat(new object[]
							{
								"ItemType for \"",
								base.StringId,
								"\" has been overridden by WeaponClass from \"",
								this.Type,
								"\" to \"",
								itemType,
								"\""
							}), 0, Debug.DebugColor.Red, 64UL);
						}
						this.Type = itemType;
					}
				}
				if (this.Type == ItemObject.ItemTypeEnum.Banner && !(this.ItemComponent is BannerComponent) && !(base.StringId == "campaign_banner_small"))
				{
					Debug.FailedAssert("Banner item with name: " + this.Name + " is not properly set. It must either be a campaign banner or it must have a banner component.", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "Deserialize", 747);
					Debug.Print("Banner item with name: " + this.Name + " is not properly set. It must either be a campaign banner or it must have a banner component.", 0, Debug.DebugColor.Yellow, 17592186044416UL);
				}
				XmlAttribute xmlAttribute9 = node.Attributes["AmmoOffset"];
				if (xmlAttribute9 != null)
				{
					string[] array2 = xmlAttribute9.Value.Split(new char[]
					{
						','
					});
					this.WeaponComponent.PrimaryWeapon.SetAmmoOffset(new Vec3(0f, 0f, 0f, -1f));
					if (array2.Length == 3)
					{
						try
						{
							Vec3 ammoOffset = new Vec3(float.Parse(array2[0], CultureInfo.InvariantCulture), float.Parse(array2[1], CultureInfo.InvariantCulture), float.Parse(array2[2], CultureInfo.InvariantCulture), -1f);
							this.WeaponComponent.PrimaryWeapon.SetAmmoOffset(ammoOffset);
							goto IL_CF1;
						}
						catch (Exception)
						{
							Debug.FailedAssert("[DEBUG]Throw Base Offset is not valid", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "Deserialize", 774);
							goto IL_CF1;
						}
					}
					Debug.FailedAssert("[DEBUG]Throw Base Offset is not valid", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "Deserialize", 779);
				}
				IL_CF1:
				if (node.Attributes["tier_override"] != null)
				{
					float num = float.Parse(node.Attributes["tier_override"].Value);
					this.TierfOverride = num + 1f;
				}
				this.Effectiveness = this.CalculateEffectiveness();
				if (node.Attributes["value"] != null)
				{
					this.Value = int.Parse(node.Attributes["value"].Value);
				}
				else
				{
					this.DetermineValue();
				}
				if (this.PrimaryWeapon != null)
				{
					if (this.PrimaryWeapon.IsMeleeWeapon || this.PrimaryWeapon.IsRangedWeapon)
					{
						if (string.IsNullOrEmpty(this.BodyName))
						{
						}
					}
					else if (this.PrimaryWeapon.IsConsumable)
					{
						string.IsNullOrEmpty(this.HolsterBodyName);
						if (string.IsNullOrEmpty(this.BodyName))
						{
						}
					}
					else if (this.PrimaryWeapon.IsShield)
					{
						if (!string.IsNullOrEmpty(this.BodyName))
						{
							bool recalculateBody = this.RecalculateBody;
						}
						string.IsNullOrEmpty(this.CollisionBodyName);
					}
				}
			}
			this.DetermineItemCategoryForItem();
			Game.Current.ItemObjectDeserialized(this);
		}

		// Token: 0x1700014E RID: 334
		// (get) Token: 0x060003F1 RID: 1009 RVA: 0x0000F2D4 File Offset: 0x0000D4D4
		// (set) Token: 0x060003F2 RID: 1010 RVA: 0x0000F2DC File Offset: 0x0000D4DC
		public ItemObject.ItemTypeEnum ItemType
		{
			get
			{
				return this.Type;
			}
			private set
			{
				this.Type = value;
			}
		}

		// Token: 0x1700014F RID: 335
		// (get) Token: 0x060003F3 RID: 1011 RVA: 0x0000F2E5 File Offset: 0x0000D4E5
		public bool IsMountable
		{
			get
			{
				return this.HasHorseComponent && this.HorseComponent.IsRideable;
			}
		}

		// Token: 0x17000150 RID: 336
		// (get) Token: 0x060003F4 RID: 1012 RVA: 0x0000F2FC File Offset: 0x0000D4FC
		public bool IsTradeGood
		{
			get
			{
				return this.ItemType == ItemObject.ItemTypeEnum.Goods;
			}
		}

		// Token: 0x17000151 RID: 337
		// (get) Token: 0x060003F5 RID: 1013 RVA: 0x0000F308 File Offset: 0x0000D508
		public bool IsBannerItem
		{
			get
			{
				return this.ItemType == ItemObject.ItemTypeEnum.Banner;
			}
		}

		// Token: 0x17000152 RID: 338
		// (get) Token: 0x060003F6 RID: 1014 RVA: 0x0000F314 File Offset: 0x0000D514
		public bool IsAnimal
		{
			get
			{
				return this.HasHorseComponent && !this.HorseComponent.IsRideable;
			}
		}

		// Token: 0x060003F7 RID: 1015 RVA: 0x0000F32E File Offset: 0x0000D52E
		public override string ToString()
		{
			return base.StringId;
		}

		// Token: 0x17000153 RID: 339
		// (get) Token: 0x060003F8 RID: 1016 RVA: 0x0000F338 File Offset: 0x0000D538
		public SkillObject RelevantSkill
		{
			get
			{
				SkillObject result = null;
				if (this.PrimaryWeapon != null)
				{
					result = this.PrimaryWeapon.RelevantSkill;
				}
				else if (this.HasHorseComponent)
				{
					result = DefaultSkills.Riding;
				}
				return result;
			}
		}

		// Token: 0x060003F9 RID: 1017 RVA: 0x0000F36C File Offset: 0x0000D56C
		public static ItemObject GetItemFromWeaponKind(int weaponKind)
		{
			if (weaponKind < 0)
			{
				return null;
			}
			return MBObjectManager.Instance.GetObject(new MBGUID((uint)weaponKind)) as ItemObject;
		}

		// Token: 0x060003FA RID: 1018 RVA: 0x0000F38C File Offset: 0x0000D58C
		[Conditional("_RGL_KEEP_ASSERTS")]
		private void MakeSureProperFlagsSetForOneAndTwoHandedWeapons()
		{
			if (this.PrimaryWeapon != null)
			{
				if ((this.Type == ItemObject.ItemTypeEnum.Bow || this.Type == ItemObject.ItemTypeEnum.Crossbow || this.Type == ItemObject.ItemTypeEnum.TwoHandedWeapon) && !this.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.NotUsableWithOneHand))
				{
					Debug.FailedAssert(this.Name + ": Two Handed Item does not have NotUsableWithOneHand flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "MakeSureProperFlagsSetForOneAndTwoHandedWeapons", 957);
					this.PrimaryWeapon.WeaponFlags |= WeaponFlags.NotUsableWithOneHand;
				}
				if ((this.Type == ItemObject.ItemTypeEnum.Bow || this.Type == ItemObject.ItemTypeEnum.Crossbow) && !this.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.TwoHandIdleOnMount))
				{
					Debug.FailedAssert(this.Name + ": Two Handed Item does not have TwoHandIdleOnMount flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "MakeSureProperFlagsSetForOneAndTwoHandedWeapons", 966);
					this.PrimaryWeapon.WeaponFlags |= WeaponFlags.TwoHandIdleOnMount;
				}
				if ((this.Type == ItemObject.ItemTypeEnum.OneHandedWeapon || this.Type == ItemObject.ItemTypeEnum.Shield) && this.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.NotUsableWithOneHand))
				{
					Debug.FailedAssert(this.Name + ": One Handed Item has TwoHanded flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", "MakeSureProperFlagsSetForOneAndTwoHandedWeapons", 975);
					this.PrimaryWeapon.WeaponFlags &= ~WeaponFlags.NotUsableWithOneHand;
				}
			}
		}

		// Token: 0x060003FB RID: 1019 RVA: 0x0000F4D7 File Offset: 0x0000D6D7
		[Conditional("DEBUG")]
		private void DebugMakeSurePhysicsMaterialCorrectlySet()
		{
		}

		// Token: 0x060003FC RID: 1020 RVA: 0x0000F4DC File Offset: 0x0000D6DC
		[Conditional("DEBUG")]
		private void MakeSureWeaponLengthAndMissileSpeedCorrect()
		{
			if (this.WeaponComponent != null)
			{
				foreach (WeaponComponentData weaponComponentData in this.WeaponComponent.Weapons)
				{
					int weaponLength = weaponComponentData.WeaponLength;
					if (this.Type == ItemObject.ItemTypeEnum.Arrows || this.Type == ItemObject.ItemTypeEnum.Bolts || this.Type == ItemObject.ItemTypeEnum.SlingStones || this.Type == ItemObject.ItemTypeEnum.Bullets || this.Type == ItemObject.ItemTypeEnum.Thrown)
					{
						int missileSpeed = weaponComponentData.MissileSpeed;
					}
				}
			}
		}

		// Token: 0x060003FD RID: 1021 RVA: 0x0000F578 File Offset: 0x0000D778
		public static ItemObject.ItemTypeEnum GetAmmoTypeForItemType(ItemObject.ItemTypeEnum itemType)
		{
			switch (itemType)
			{
			case ItemObject.ItemTypeEnum.Bow:
				return ItemObject.ItemTypeEnum.Arrows;
			case ItemObject.ItemTypeEnum.Crossbow:
				return ItemObject.ItemTypeEnum.Bolts;
			case ItemObject.ItemTypeEnum.Sling:
				return ItemObject.ItemTypeEnum.SlingStones;
			case ItemObject.ItemTypeEnum.Thrown:
				return ItemObject.ItemTypeEnum.Thrown;
			default:
				if (itemType != ItemObject.ItemTypeEnum.Pistol)
				{
					return ItemObject.ItemTypeEnum.Invalid;
				}
				return ItemObject.ItemTypeEnum.Bullets;
			}
		}

		// Token: 0x060003FE RID: 1022 RVA: 0x0000F5A8 File Offset: 0x0000D7A8
		public static float GetAirFrictionConstant(WeaponClass weaponClass, WeaponFlags weaponFlags)
		{
			switch (weaponClass)
			{
			case WeaponClass.Arrow:
				if (weaponFlags.HasAnyFlag(WeaponFlags.MultiplePenetration))
				{
					return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaBolt);
				}
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
			case WeaponClass.Bolt:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
			case WeaponClass.SlingStone:
			case WeaponClass.Cartridge:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBullet);
			case WeaponClass.Bow:
			case WeaponClass.Crossbow:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
			case WeaponClass.Sling:
			case WeaponClass.Stone:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionStone);
			case WeaponClass.Boulder:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBoulder);
			case WeaponClass.ThrowingAxe:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionAxe);
			case WeaponClass.ThrowingKnife:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionKnife);
			case WeaponClass.Javelin:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionJavelin);
			case WeaponClass.Pistol:
			case WeaponClass.Musket:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBullet);
			case WeaponClass.BallistaBoulder:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaBoulder);
			case WeaponClass.BallistaStone:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaStone);
			default:
				return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
			}
		}

		// Token: 0x060003FF RID: 1023 RVA: 0x0000F6C8 File Offset: 0x0000D8C8
		private float CalculateEffectiveness()
		{
			float result = 1f;
			ArmorComponent armorComponent = this.ArmorComponent;
			if (armorComponent != null)
			{
				if (this.Type == ItemObject.ItemTypeEnum.HorseHarness)
				{
					result = (float)armorComponent.BodyArmor * 1.67f;
				}
				else
				{
					result = ((float)armorComponent.HeadArmor * 34f + (float)armorComponent.BodyArmor * 42f + (float)armorComponent.LegArmor * 12f + (float)armorComponent.ArmArmor * 12f) * 0.03f;
				}
			}
			if (this.WeaponComponent != null)
			{
				WeaponComponentData primaryWeapon = this.WeaponComponent.PrimaryWeapon;
				float num = 1f;
				switch (primaryWeapon.WeaponClass)
				{
				case WeaponClass.Dagger:
					num = 0.4f;
					break;
				case WeaponClass.OneHandedSword:
					num = 0.55f;
					break;
				case WeaponClass.TwoHandedSword:
					num = 0.6f;
					break;
				case WeaponClass.OneHandedAxe:
					num = 0.5f;
					break;
				case WeaponClass.TwoHandedAxe:
					num = 0.55f;
					break;
				case WeaponClass.Mace:
					num = 0.5f;
					break;
				case WeaponClass.Pick:
					num = 0.4f;
					break;
				case WeaponClass.TwoHandedMace:
					num = 0.55f;
					break;
				case WeaponClass.OneHandedPolearm:
					num = 0.4f;
					break;
				case WeaponClass.TwoHandedPolearm:
					num = 0.4f;
					break;
				case WeaponClass.LowGripPolearm:
					num = 0.4f;
					break;
				case WeaponClass.Arrow:
					num = 3f;
					break;
				case WeaponClass.Bolt:
					num = 3f;
					break;
				case WeaponClass.SlingStone:
					num = 0.1f;
					break;
				case WeaponClass.Cartridge:
					num = 3f;
					break;
				case WeaponClass.Bow:
					num = 0.55f;
					break;
				case WeaponClass.Crossbow:
					num = 0.57f;
					break;
				case WeaponClass.Sling:
					num = 0.1f;
					break;
				case WeaponClass.Stone:
				case WeaponClass.BallistaStone:
					num = 0.1f;
					break;
				case WeaponClass.Boulder:
				case WeaponClass.BallistaBoulder:
					num = 0.1f;
					break;
				case WeaponClass.ThrowingAxe:
					num = 0.25f;
					break;
				case WeaponClass.ThrowingKnife:
					num = 0.2f;
					break;
				case WeaponClass.Javelin:
					num = 0.28f;
					break;
				case WeaponClass.Pistol:
					num = 1f;
					break;
				case WeaponClass.Musket:
					num = 1f;
					break;
				case WeaponClass.SmallShield:
					num = 0.4f;
					break;
				case WeaponClass.LargeShield:
					num = 0.5f;
					break;
				}
				if (primaryWeapon.IsRangedWeapon)
				{
					if (primaryWeapon.IsConsumable)
					{
						result = ((float)(primaryWeapon.MissileDamage * primaryWeapon.MissileSpeed) * 1.775f + (float)(primaryWeapon.Accuracy * (int)primaryWeapon.MaxDataValue) * 25f + (float)primaryWeapon.WeaponLength * 4f) * 0.006944f * (float)primaryWeapon.MaxDataValue * num;
					}
					else
					{
						result = ((float)(primaryWeapon.MissileSpeed * primaryWeapon.MissileDamage) * 1.75f + (float)(primaryWeapon.ThrustSpeed * primaryWeapon.Accuracy) * 0.3f) * 0.01f * (float)primaryWeapon.MaxDataValue * num;
					}
				}
				else if (primaryWeapon.IsMeleeWeapon)
				{
					float b = (float)(primaryWeapon.ThrustSpeed * primaryWeapon.ThrustDamage) * 0.01f;
					float a = (float)(primaryWeapon.SwingSpeed * primaryWeapon.SwingDamage) * 0.01f;
					float num2 = MathF.Max(a, b);
					float num3 = MathF.Min(a, b);
					result = ((num2 + num3 * num3 / num2) * 120f + (float)primaryWeapon.Handling * 15f + (float)primaryWeapon.WeaponLength * 20f + this.Weight * 5f) * 0.01f * num;
				}
				else if (primaryWeapon.IsConsumable)
				{
					result = ((float)primaryWeapon.MissileDamage * 550f + (float)primaryWeapon.MissileSpeed * 15f + (float)primaryWeapon.MaxDataValue * 60f) * 0.01f * num;
				}
				else if (primaryWeapon.IsShield)
				{
					result = ((float)primaryWeapon.BodyArmor * 60f + (float)primaryWeapon.ThrustSpeed * 10f + (float)primaryWeapon.MaxDataValue * 40f + (float)primaryWeapon.WeaponLength * 20f) * 0.01f * num;
				}
			}
			if (this.HorseComponent != null)
			{
				result = ((float)(this.HorseComponent.ChargeDamage * this.HorseComponent.Speed + this.HorseComponent.Maneuver * this.HorseComponent.Speed) + (float)this.HorseComponent.BodyLength * this.Weight * 0.025f) * (float)(this.HorseComponent.HitPoints + this.HorseComponent.HitPointBonus) * 0.0001f;
			}
			return result;
		}

		// Token: 0x06000400 RID: 1024 RVA: 0x0000FAFE File Offset: 0x0000DCFE
		internal void DetermineValue()
		{
			ItemValueModel itemValueModel = Game.Current.BasicModels.ItemValueModel;
			this.Value = ((itemValueModel != null) ? itemValueModel.CalculateValue(this) : 1);
		}

		// Token: 0x06000401 RID: 1025 RVA: 0x0000FB22 File Offset: 0x0000DD22
		public WeaponComponentData GetWeaponWithUsageIndex(int usageIndex)
		{
			return this.Weapons.ElementAt(usageIndex);
		}

		// Token: 0x040001FB RID: 507
		public const float DefaultAppearanceValue = 0.5f;

		// Token: 0x040001FC RID: 508
		public const int MaxHolsterSlotCount = 4;

		// Token: 0x040001FD RID: 509
		private const float TierfOverrideAdjustmentValue = 1f;

		// Token: 0x0400020F RID: 527
		public ItemObject.ItemTypeEnum Type;

		// Token: 0x02000104 RID: 260
		public enum ItemUsageSetFlags
		{
			// Token: 0x04000736 RID: 1846
			RequiresMount = 1,
			// Token: 0x04000737 RID: 1847
			RequiresNoMount,
			// Token: 0x04000738 RID: 1848
			RequiresShield = 4,
			// Token: 0x04000739 RID: 1849
			RequiresNoShield = 8,
			// Token: 0x0400073A RID: 1850
			PassiveUsage = 16
		}

		// Token: 0x02000105 RID: 261
		public enum ItemTypeEnum
		{
			// Token: 0x0400073C RID: 1852
			Invalid,
			// Token: 0x0400073D RID: 1853
			Horse,
			// Token: 0x0400073E RID: 1854
			OneHandedWeapon,
			// Token: 0x0400073F RID: 1855
			TwoHandedWeapon,
			// Token: 0x04000740 RID: 1856
			Polearm,
			// Token: 0x04000741 RID: 1857
			Arrows,
			// Token: 0x04000742 RID: 1858
			Bolts,
			// Token: 0x04000743 RID: 1859
			SlingStones,
			// Token: 0x04000744 RID: 1860
			Shield,
			// Token: 0x04000745 RID: 1861
			Bow,
			// Token: 0x04000746 RID: 1862
			Crossbow,
			// Token: 0x04000747 RID: 1863
			Sling,
			// Token: 0x04000748 RID: 1864
			Thrown,
			// Token: 0x04000749 RID: 1865
			Goods,
			// Token: 0x0400074A RID: 1866
			HeadArmor,
			// Token: 0x0400074B RID: 1867
			BodyArmor,
			// Token: 0x0400074C RID: 1868
			LegArmor,
			// Token: 0x0400074D RID: 1869
			HandArmor,
			// Token: 0x0400074E RID: 1870
			Pistol,
			// Token: 0x0400074F RID: 1871
			Musket,
			// Token: 0x04000750 RID: 1872
			Bullets,
			// Token: 0x04000751 RID: 1873
			Animal,
			// Token: 0x04000752 RID: 1874
			Book,
			// Token: 0x04000753 RID: 1875
			ChestArmor,
			// Token: 0x04000754 RID: 1876
			Cape,
			// Token: 0x04000755 RID: 1877
			HorseHarness,
			// Token: 0x04000756 RID: 1878
			Banner
		}

		// Token: 0x02000106 RID: 262
		public enum ItemTiers
		{
			// Token: 0x04000758 RID: 1880
			Tier1,
			// Token: 0x04000759 RID: 1881
			Tier2,
			// Token: 0x0400075A RID: 1882
			Tier3,
			// Token: 0x0400075B RID: 1883
			Tier4,
			// Token: 0x0400075C RID: 1884
			Tier5,
			// Token: 0x0400075D RID: 1885
			Tier6,
			// Token: 0x0400075E RID: 1886
			NumTiers
		}
	}
}
