using System;
using System.Collections;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Roster
{
	// Token: 0x020002DD RID: 733
	public class ItemRoster : IReadOnlyList<ItemRosterElement>, IEnumerable<ItemRosterElement>, IEnumerable, IReadOnlyCollection<ItemRosterElement>, ISerializableObject
	{
		// Token: 0x060027C6 RID: 10182 RVA: 0x000A54A8 File Offset: 0x000A36A8
		internal static void AutoGeneratedStaticCollectObjectsItemRoster(object o, List<object> collectedObjects)
		{
			((ItemRoster)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060027C7 RID: 10183 RVA: 0x000A54B6 File Offset: 0x000A36B6
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._data);
		}

		// Token: 0x060027C8 RID: 10184 RVA: 0x000A54C4 File Offset: 0x000A36C4
		internal static object AutoGeneratedGetMemberValue_data(object o)
		{
			return ((ItemRoster)o)._data;
		}

		// Token: 0x060027C9 RID: 10185 RVA: 0x000A54D1 File Offset: 0x000A36D1
		internal static object AutoGeneratedGetMemberValue_count(object o)
		{
			return ((ItemRoster)o)._count;
		}

		// Token: 0x170009BD RID: 2493
		public ItemRosterElement this[int index]
		{
			get
			{
				return this._data[index];
			}
		}

		// Token: 0x170009BE RID: 2494
		// (get) Token: 0x060027CB RID: 10187 RVA: 0x000A54F1 File Offset: 0x000A36F1
		public int Count
		{
			get
			{
				return this._count;
			}
		}

		// Token: 0x060027CC RID: 10188 RVA: 0x000A54F9 File Offset: 0x000A36F9
		public ItemRoster()
		{
			this._data = new ItemRosterElement[4];
			this._count = 0;
		}

		// Token: 0x060027CD RID: 10189 RVA: 0x000A5514 File Offset: 0x000A3714
		public ItemRoster(ItemRoster other)
		{
			this._data = new ItemRosterElement[other.Count];
			this._count = 0;
			this.Add(other);
			this.CalculateCachedStats();
		}

		// Token: 0x170009BF RID: 2495
		// (get) Token: 0x060027CE RID: 10190 RVA: 0x000A5541 File Offset: 0x000A3741
		// (set) Token: 0x060027CF RID: 10191 RVA: 0x000A5549 File Offset: 0x000A3749
		[CachedData]
		public int VersionNo { get; private set; }

		// Token: 0x060027D0 RID: 10192 RVA: 0x000A5554 File Offset: 0x000A3754
		private void EnsureLength(int length)
		{
			if (length > 0 && (this._data == null || length > this._data.Length))
			{
				int num = 4;
				if (this._data != null)
				{
					num = this._data.Length * 2;
				}
				ItemRosterElement[] array = new ItemRosterElement[num];
				for (int i = 0; i < this._count; i++)
				{
					array[i] = this._data[i];
				}
				this._data = array;
			}
		}

		// Token: 0x060027D1 RID: 10193 RVA: 0x000A55C0 File Offset: 0x000A37C0
		public int FindIndexOfItem(ItemObject item)
		{
			for (int i = 0; i < this._count; i++)
			{
				if (this._data[i].EquipmentElement.Item == item)
				{
					return i;
				}
			}
			return -1;
		}

		// Token: 0x060027D2 RID: 10194 RVA: 0x000A5600 File Offset: 0x000A3800
		public int FindIndex(Predicate<ItemObject> predicate)
		{
			for (int i = 0; i < this._count; i++)
			{
				if (predicate(this._data[i].EquipmentElement.Item))
				{
					return i;
				}
			}
			return -1;
		}

		// Token: 0x060027D3 RID: 10195 RVA: 0x000A5644 File Offset: 0x000A3844
		public int FindIndexFirstAfterXthElement(Predicate<ItemObject> predicate, int x)
		{
			for (int i = 0; i < x + this._count; i++)
			{
				if (predicate(this._data[i % this._count].EquipmentElement.Item))
				{
					return i;
				}
			}
			return -1;
		}

		// Token: 0x060027D4 RID: 10196 RVA: 0x000A5690 File Offset: 0x000A3890
		public int FindIndexOfElement(EquipmentElement rosterElement)
		{
			for (int i = 0; i < this._count; i++)
			{
				if (rosterElement.IsEqualTo(this._data[i].EquipmentElement))
				{
					return i;
				}
			}
			return -1;
		}

		// Token: 0x060027D5 RID: 10197 RVA: 0x000A56CC File Offset: 0x000A38CC
		private int AddNewElement(ItemRosterElement rosterElement, bool insertAtFront = false)
		{
			int num = this._count + 1;
			this.EnsureLength(num);
			int num2 = this._count;
			this.OnRosterUpdated(ref rosterElement, rosterElement.Amount);
			if (insertAtFront)
			{
				for (int i = this._count; i > 0; i--)
				{
					this._data[i] = this._data[i - 1];
				}
				num2 = 0;
			}
			this._data[num2] = rosterElement;
			this._count = num;
			this.UpdateVersion();
			return num2;
		}

		// Token: 0x060027D6 RID: 10198 RVA: 0x000A574A File Offset: 0x000A394A
		public int AddToCounts(ItemObject item, int number)
		{
			if (number == 0)
			{
				return -1;
			}
			return this.AddToCounts(new EquipmentElement(item, null, null, false), number);
		}

		// Token: 0x060027D7 RID: 10199 RVA: 0x000A5764 File Offset: 0x000A3964
		public int AddToCounts(EquipmentElement rosterElement, int number)
		{
			if (number == 0)
			{
				return -1;
			}
			int num = this.FindIndexOfElement(rosterElement);
			if (num < 0)
			{
				if (number < 0)
				{
					Debug.FailedAssert("Trying to delete an element from Item Roster that does not exist!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Roster\\ItemRoster.cs", "AddToCounts", 169);
					return -1;
				}
				num = this.AddNewElement(new ItemRosterElement(rosterElement, 0), false);
			}
			this.OnRosterUpdated(ref this._data[num], number);
			ItemRosterElement[] data = this._data;
			int num2 = num;
			data[num2].Amount = data[num2].Amount + number;
			if (this._data[num].Amount <= 0)
			{
				this._data[num] = this._data[this._count - 1];
				this._data[this._count - 1] = ItemRosterElement.Invalid;
				this._count--;
			}
			this.UpdateVersion();
			return num;
		}

		// Token: 0x060027D8 RID: 10200 RVA: 0x000A583C File Offset: 0x000A3A3C
		public ItemRosterElement GetElementCopyAtIndex(int index)
		{
			if (index < this._count && index >= 0)
			{
				return this._data[index];
			}
			Debug.FailedAssert("GetElementCopyAtIndex can't find the element in ItemRoster", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Roster\\ItemRoster.cs", "GetElementCopyAtIndex", 201);
			return ItemRosterElement.Invalid;
		}

		// Token: 0x060027D9 RID: 10201 RVA: 0x000A5878 File Offset: 0x000A3A78
		public ItemObject GetItemAtIndex(int index)
		{
			if (index < this._count && index >= 0)
			{
				return this._data[index].EquipmentElement.Item;
			}
			Debug.FailedAssert("Given index for GetItemAtIndex is not valid in ItemRoster", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Roster\\ItemRoster.cs", "GetItemAtIndex", 212);
			return null;
		}

		// Token: 0x060027DA RID: 10202 RVA: 0x000A58C6 File Offset: 0x000A3AC6
		public int GetElementNumber(int index)
		{
			if (index < this._count && index >= 0)
			{
				return this._data[index].Amount;
			}
			Debug.FailedAssert("Given index for GetElementNumber is not valid in ItemRoster", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Roster\\ItemRoster.cs", "GetElementNumber", 223);
			return 0;
		}

		// Token: 0x060027DB RID: 10203 RVA: 0x000A5904 File Offset: 0x000A3B04
		public int GetElementUnitCost(int index)
		{
			if (index < this._count && index >= 0)
			{
				return this._data[index].EquipmentElement.ItemValue;
			}
			Debug.FailedAssert("Given index for GetElementUnitCost is not valid in ItemRoster", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Roster\\ItemRoster.cs", "GetElementUnitCost", 234);
			return 0;
		}

		// Token: 0x060027DC RID: 10204 RVA: 0x000A5954 File Offset: 0x000A3B54
		public int GetItemNumber(ItemObject item)
		{
			int num = this.FindIndexOfItem(item);
			if (num >= 0)
			{
				return this._data[num].Amount;
			}
			return 0;
		}

		// Token: 0x060027DD RID: 10205 RVA: 0x000A5980 File Offset: 0x000A3B80
		public void Clear()
		{
			for (int i = 0; i < this._count; i++)
			{
				this._data[i].Clear();
				this._data[i] = ItemRosterElement.Invalid;
			}
			this._count = 0;
			this.CalculateCachedStats();
			ItemRoster.RosterUpdatedEventDelegate rosterUpdatedEvent = this._rosterUpdatedEvent;
			if (rosterUpdatedEvent != null)
			{
				rosterUpdatedEvent(default(ItemRosterElement), 0);
			}
			this.UpdateVersion();
		}

		// Token: 0x060027DE RID: 10206 RVA: 0x000A59F0 File Offset: 0x000A3BF0
		public static bool RostersAreIdentical(ItemRoster a, ItemRoster b)
		{
			if (a == b)
			{
				return true;
			}
			if (a == null || b == null)
			{
				return false;
			}
			if (a.Count != b.Count)
			{
				return false;
			}
			for (int i = 0; i < a.Count; i++)
			{
				ItemRosterElement elementCopyAtIndex = a.GetElementCopyAtIndex(i);
				int num = b.FindIndexOfItem(elementCopyAtIndex.EquipmentElement.Item);
				if (num == -1)
				{
					return false;
				}
				ItemRosterElement elementCopyAtIndex2 = b.GetElementCopyAtIndex(num);
				if (elementCopyAtIndex.EquipmentElement.Item != elementCopyAtIndex2.EquipmentElement.Item || elementCopyAtIndex.Amount != elementCopyAtIndex2.Amount || elementCopyAtIndex.EquipmentElement.ItemModifier != elementCopyAtIndex2.EquipmentElement.ItemModifier)
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x060027DF RID: 10207 RVA: 0x000A5AB6 File Offset: 0x000A3CB6
		public IEnumerator<ItemRosterElement> GetEnumerator()
		{
			int num;
			for (int i = 0; i < this.Count; i = num + 1)
			{
				yield return this._data[i];
				num = i;
			}
			yield break;
		}

		// Token: 0x060027E0 RID: 10208 RVA: 0x000A5AC8 File Offset: 0x000A3CC8
		public int SelectRandomIndex(Func<ItemRosterElement, float> weightFunction)
		{
			List<ValueTuple<int, float>> list = new List<ValueTuple<int, float>>();
			float num = 0f;
			for (int i = 0; i < this.Count; i++)
			{
				float num2 = weightFunction(this._data[i]);
				if (num2 > 1E-05f)
				{
					list.Add(new ValueTuple<int, float>(i, num2));
					num += num2;
				}
			}
			if (list.Count > 0)
			{
				float num3 = MBRandom.RandomFloat * num;
				float num4 = 0f;
				for (int j = 0; j < list.Count; j++)
				{
					num4 += list[j].Item2;
					if (num4 >= num3)
					{
						return list[j].Item1;
					}
				}
				return list[list.Count - 1].Item1;
			}
			return -1;
		}

		// Token: 0x060027E1 RID: 10209 RVA: 0x000A5B87 File Offset: 0x000A3D87
		IEnumerator IEnumerable.GetEnumerator()
		{
			return this.GetEnumerator();
		}

		// Token: 0x060027E2 RID: 10210 RVA: 0x000A5B90 File Offset: 0x000A3D90
		public IEnumerable<ItemRosterElement> RemoveIf(Func<ItemRosterElement, int> match)
		{
			List<ItemRosterElement> list = new List<ItemRosterElement>();
			for (int i = 0; i < this._count; i++)
			{
				int num = match(this._data[i]);
				if (num > 0)
				{
					if (num > this._data[i].Amount)
					{
						num = this._data[i].Amount;
					}
					list.Add(new ItemRosterElement(this._data[i].EquipmentElement.Item, num, this._data[i].EquipmentElement.ItemModifier));
					this.AddToCounts(this._data[i].EquipmentElement, -num);
				}
			}
			return list;
		}

		// Token: 0x060027E3 RID: 10211 RVA: 0x000A5C50 File Offset: 0x000A3E50
		public void Add(IEnumerable<ItemRosterElement> rosterElementList)
		{
			foreach (ItemRosterElement itemRosterElement in rosterElementList)
			{
				this.AddToCounts(itemRosterElement.EquipmentElement, itemRosterElement.Amount);
			}
		}

		// Token: 0x060027E4 RID: 10212 RVA: 0x000A5CA8 File Offset: 0x000A3EA8
		public void Add(ItemRosterElement itemRosterElement)
		{
			this.AddToCounts(itemRosterElement.EquipmentElement, itemRosterElement.Amount);
		}

		// Token: 0x060027E5 RID: 10213 RVA: 0x000A5CBF File Offset: 0x000A3EBF
		public void Remove(ItemRosterElement itemRosterElement)
		{
			this.AddToCounts(itemRosterElement.EquipmentElement, -itemRosterElement.Amount);
		}

		// Token: 0x060027E6 RID: 10214 RVA: 0x000A5CD8 File Offset: 0x000A3ED8
		void ISerializableObject.SerializeTo(IWriter writer)
		{
			writer.WriteInt(this.Count);
			if (this._data != null)
			{
				writer.WriteInt(this._data.Length);
				foreach (ItemRosterElement itemRosterElement in this._data)
				{
					writer.WriteSerializableObject(itemRosterElement);
				}
				return;
			}
			writer.WriteInt(0);
		}

		// Token: 0x060027E7 RID: 10215 RVA: 0x000A5D38 File Offset: 0x000A3F38
		void ISerializableObject.DeserializeFrom(IReader reader)
		{
			this._count = reader.ReadInt();
			int num = reader.ReadInt();
			this._data = new ItemRosterElement[num];
			for (int i = 0; i < num; i++)
			{
				this._data[i] = (ItemRosterElement)reader.ReadSerializableObject();
			}
			this.CalculateCachedStats();
		}

		// Token: 0x14000010 RID: 16
		// (add) Token: 0x060027E8 RID: 10216 RVA: 0x000A5D90 File Offset: 0x000A3F90
		// (remove) Token: 0x060027E9 RID: 10217 RVA: 0x000A5DC8 File Offset: 0x000A3FC8
		private event ItemRoster.RosterUpdatedEventDelegate _rosterUpdatedEvent;

		// Token: 0x14000011 RID: 17
		// (add) Token: 0x060027EA RID: 10218 RVA: 0x000A5DFD File Offset: 0x000A3FFD
		// (remove) Token: 0x060027EB RID: 10219 RVA: 0x000A5E06 File Offset: 0x000A4006
		public event ItemRoster.RosterUpdatedEventDelegate RosterUpdatedEvent
		{
			add
			{
				this._rosterUpdatedEvent += value;
			}
			remove
			{
				this._rosterUpdatedEvent -= value;
			}
		}

		// Token: 0x060027EC RID: 10220 RVA: 0x000A5E10 File Offset: 0x000A4010
		public void UpdateVersion()
		{
			int versionNo = this.VersionNo;
			this.VersionNo = versionNo + 1;
		}

		// Token: 0x060027ED RID: 10221 RVA: 0x000A5E30 File Offset: 0x000A4030
		private void OnRosterUpdated(ref ItemRosterElement itemRosterElement, int count)
		{
			ItemObject item = itemRosterElement.EquipmentElement.Item;
			this.TotalValue += item.Value * count;
			if (item.IsTradeGood)
			{
				this.TradeGoodsTotalValue += item.Value * count;
			}
			if (item.HasHorseComponent)
			{
				if (item.HorseComponent.IsPackAnimal && itemRosterElement.EquipmentElement.ItemModifier == null)
				{
					this.NumberOfPackAnimals += count;
				}
				else if (item.HorseComponent.IsMount && itemRosterElement.EquipmentElement.ItemModifier == null)
				{
					this.NumberOfMounts += count;
				}
				else if (item.HorseComponent.IsLiveStock)
				{
					this.NumberOfLivestockAnimals += count;
					this.TotalFood += count * item.HorseComponent.MeatCount;
				}
			}
			else if (item.IsFood)
			{
				this.TotalFood += count;
				if (itemRosterElement.Amount == 0 && count > 0)
				{
					int foodVariety = this.FoodVariety;
					this.FoodVariety = foodVariety + 1;
				}
				else if (itemRosterElement.Amount > 0 && itemRosterElement.Amount + count <= 0)
				{
					int foodVariety = this.FoodVariety;
					this.FoodVariety = foodVariety - 1;
				}
			}
			ItemRoster.RosterUpdatedEventDelegate rosterUpdatedEvent = this._rosterUpdatedEvent;
			if (rosterUpdatedEvent == null)
			{
				return;
			}
			rosterUpdatedEvent(itemRosterElement, count);
		}

		// Token: 0x060027EE RID: 10222 RVA: 0x000A5F92 File Offset: 0x000A4192
		[LoadInitializationCallback]
		public void OnLoadStarted(MetaData metaData)
		{
			ItemRoster.InstanceListForLoadGame.Add(this);
		}

		// Token: 0x060027EF RID: 10223 RVA: 0x000A5FA0 File Offset: 0x000A41A0
		public static void CalculateCachedStatsOnLoad()
		{
			foreach (ItemRoster itemRoster in ItemRoster.InstanceListForLoadGame)
			{
				ItemRoster.ReplaceInvalidItemsWithTrash(itemRoster);
				ItemRoster.RemoveZeroCountsFromRoster(itemRoster);
				itemRoster.CalculateCachedStats();
			}
			ItemRoster.InstanceListForLoadGame.Clear();
		}

		// Token: 0x060027F0 RID: 10224 RVA: 0x000A6008 File Offset: 0x000A4208
		private static void RemoveZeroCountsFromRoster(ItemRoster itemRoster)
		{
			int num = 0;
			int i = 0;
			if (itemRoster._count != 0 && itemRoster._count > itemRoster._data.Length)
			{
				itemRoster._count = itemRoster._data.Length;
			}
			while (i < itemRoster._count)
			{
				ItemRosterElement itemRosterElement = itemRoster._data[i];
				if (itemRosterElement.Amount > 0)
				{
					if (num != i)
					{
						itemRoster._data[num] = itemRosterElement;
					}
					num++;
				}
				i++;
			}
			for (int j = num; j < itemRoster._count; j++)
			{
				itemRoster._data[j].Clear();
				itemRoster._data[j] = ItemRosterElement.Invalid;
			}
			itemRoster._count = num;
		}

		// Token: 0x060027F1 RID: 10225 RVA: 0x000A60B4 File Offset: 0x000A42B4
		private static void ReplaceInvalidItemsWithTrash(ItemRoster itemRoster)
		{
			if (itemRoster._data != null)
			{
				for (int i = itemRoster._data.Length - 1; i >= 0; i--)
				{
					ItemObject item = itemRoster._data[i].EquipmentElement.Item;
					if (item != null && !item.IsReady)
					{
						ItemObject item2 = itemRoster._data[i].EquipmentElement.Item;
						itemRoster.AddToCounts(DefaultItems.Trash, itemRoster._data[i].Amount);
						itemRoster._data[i].Clear();
						if (MBObjectManager.Instance.GetObject(item2.Id) == item2)
						{
							MBObjectManager.Instance.UnregisterObject(item2);
						}
					}
					else
					{
						ItemModifier itemModifier = itemRoster._data[i].EquipmentElement.ItemModifier;
						if (itemModifier != null && !itemModifier.IsReady)
						{
							itemRoster.AddToCounts(itemRoster._data[i].EquipmentElement.Item, itemRoster._data[i].Amount);
							itemRoster._data[i].Clear();
						}
					}
				}
			}
		}

		// Token: 0x060027F2 RID: 10226 RVA: 0x000A61E8 File Offset: 0x000A43E8
		private void CalculateCachedStats()
		{
			this.NumberOfPackAnimals = 0;
			this.NumberOfMounts = 0;
			this.NumberOfLivestockAnimals = 0;
			this.TotalValue = 0;
			this.TradeGoodsTotalValue = 0;
			this.TotalFood = 0;
			this.FoodVariety = 0;
			for (int i = 0; i < this.Count; i++)
			{
				ItemObject item = this._data[i].EquipmentElement.Item;
				int amount = this._data[i].Amount;
				this.TotalValue += item.Value * amount;
				if (item.IsTradeGood)
				{
					this.TradeGoodsTotalValue += item.Value * amount;
				}
				if (item.HasHorseComponent)
				{
					if (item.HorseComponent.IsPackAnimal)
					{
						this.NumberOfPackAnimals += amount;
					}
					else if (item.HorseComponent.IsMount)
					{
						this.NumberOfMounts += amount;
					}
					else if (item.HorseComponent.IsLiveStock)
					{
						this.NumberOfLivestockAnimals += amount;
						this.TotalFood += amount * item.HorseComponent.MeatCount;
					}
				}
				else if (item.IsFood)
				{
					this.TotalFood += amount;
					int foodVariety = this.FoodVariety;
					this.FoodVariety = foodVariety + 1;
				}
			}
		}

		// Token: 0x170009C0 RID: 2496
		// (get) Token: 0x060027F3 RID: 10227 RVA: 0x000A633C File Offset: 0x000A453C
		// (set) Token: 0x060027F4 RID: 10228 RVA: 0x000A6344 File Offset: 0x000A4544
		[CachedData]
		public int TotalFood { get; internal set; }

		// Token: 0x170009C1 RID: 2497
		// (get) Token: 0x060027F5 RID: 10229 RVA: 0x000A634D File Offset: 0x000A454D
		// (set) Token: 0x060027F6 RID: 10230 RVA: 0x000A6355 File Offset: 0x000A4555
		[CachedData]
		public int FoodVariety { get; internal set; }

		// Token: 0x170009C2 RID: 2498
		// (get) Token: 0x060027F7 RID: 10231 RVA: 0x000A635E File Offset: 0x000A455E
		// (set) Token: 0x060027F8 RID: 10232 RVA: 0x000A6366 File Offset: 0x000A4566
		[CachedData]
		public int TotalValue { get; internal set; }

		// Token: 0x170009C3 RID: 2499
		// (get) Token: 0x060027F9 RID: 10233 RVA: 0x000A636F File Offset: 0x000A456F
		// (set) Token: 0x060027FA RID: 10234 RVA: 0x000A6377 File Offset: 0x000A4577
		[CachedData]
		public int TradeGoodsTotalValue { get; internal set; }

		// Token: 0x170009C4 RID: 2500
		// (get) Token: 0x060027FB RID: 10235 RVA: 0x000A6380 File Offset: 0x000A4580
		// (set) Token: 0x060027FC RID: 10236 RVA: 0x000A6388 File Offset: 0x000A4588
		[CachedData]
		public int NumberOfPackAnimals { get; private set; }

		// Token: 0x170009C5 RID: 2501
		// (get) Token: 0x060027FD RID: 10237 RVA: 0x000A6391 File Offset: 0x000A4591
		// (set) Token: 0x060027FE RID: 10238 RVA: 0x000A6399 File Offset: 0x000A4599
		[CachedData]
		public int NumberOfLivestockAnimals { get; private set; }

		// Token: 0x170009C6 RID: 2502
		// (get) Token: 0x060027FF RID: 10239 RVA: 0x000A63A2 File Offset: 0x000A45A2
		// (set) Token: 0x06002800 RID: 10240 RVA: 0x000A63AA File Offset: 0x000A45AA
		[CachedData]
		public int NumberOfMounts { get; private set; }

		// Token: 0x04000B7A RID: 2938
		[SaveableField(0)]
		private ItemRosterElement[] _data;

		// Token: 0x04000B7B RID: 2939
		[SaveableField(1)]
		private int _count;

		// Token: 0x04000B7C RID: 2940
		private static readonly List<ItemRoster> InstanceListForLoadGame = new List<ItemRoster>();

		// Token: 0x0200067A RID: 1658
		// (Invoke) Token: 0x06005191 RID: 20881
		public delegate void RosterUpdatedEventDelegate(ItemRosterElement item, int count);
	}
}
