using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x02000068 RID: 104
	public sealed class Kingdom : MBObjectBase, IFaction
	{
		// Token: 0x06000D9C RID: 3484 RVA: 0x000470D2 File Offset: 0x000452D2
		internal static void AutoGeneratedStaticCollectObjectsKingdom(object o, List<object> collectedObjects)
		{
			((Kingdom)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000D9D RID: 3485 RVA: 0x000470E0 File Offset: 0x000452E0
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._unresolvedDecisions);
			collectedObjects.Add(this._rulingClan);
			collectedObjects.Add(this._armies);
			collectedObjects.Add(this._activePolicies);
			collectedObjects.Add(this.Name);
			collectedObjects.Add(this.InformalName);
			collectedObjects.Add(this.EncyclopediaText);
			collectedObjects.Add(this.EncyclopediaTitle);
			collectedObjects.Add(this.EncyclopediaRulerTitle);
			collectedObjects.Add(this.Culture);
			collectedObjects.Add(this.InitialHomeSettlement);
			collectedObjects.Add(this.Banner);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.LastKingdomDecisionConclusionDate, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.LastMercenaryOfferTime, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.NotAttackableByPlayerUntilTime, collectedObjects);
		}

		// Token: 0x06000D9E RID: 3486 RVA: 0x000471B7 File Offset: 0x000453B7
		internal static object AutoGeneratedGetMemberValueName(object o)
		{
			return ((Kingdom)o).Name;
		}

		// Token: 0x06000D9F RID: 3487 RVA: 0x000471C4 File Offset: 0x000453C4
		internal static object AutoGeneratedGetMemberValueInformalName(object o)
		{
			return ((Kingdom)o).InformalName;
		}

		// Token: 0x06000DA0 RID: 3488 RVA: 0x000471D1 File Offset: 0x000453D1
		internal static object AutoGeneratedGetMemberValueEncyclopediaText(object o)
		{
			return ((Kingdom)o).EncyclopediaText;
		}

		// Token: 0x06000DA1 RID: 3489 RVA: 0x000471DE File Offset: 0x000453DE
		internal static object AutoGeneratedGetMemberValueEncyclopediaTitle(object o)
		{
			return ((Kingdom)o).EncyclopediaTitle;
		}

		// Token: 0x06000DA2 RID: 3490 RVA: 0x000471EB File Offset: 0x000453EB
		internal static object AutoGeneratedGetMemberValueEncyclopediaRulerTitle(object o)
		{
			return ((Kingdom)o).EncyclopediaRulerTitle;
		}

		// Token: 0x06000DA3 RID: 3491 RVA: 0x000471F8 File Offset: 0x000453F8
		internal static object AutoGeneratedGetMemberValueCulture(object o)
		{
			return ((Kingdom)o).Culture;
		}

		// Token: 0x06000DA4 RID: 3492 RVA: 0x00047205 File Offset: 0x00045405
		internal static object AutoGeneratedGetMemberValueInitialHomeSettlement(object o)
		{
			return ((Kingdom)o).InitialHomeSettlement;
		}

		// Token: 0x06000DA5 RID: 3493 RVA: 0x00047212 File Offset: 0x00045412
		internal static object AutoGeneratedGetMemberValueColor(object o)
		{
			return ((Kingdom)o).Color;
		}

		// Token: 0x06000DA6 RID: 3494 RVA: 0x00047224 File Offset: 0x00045424
		internal static object AutoGeneratedGetMemberValueColor2(object o)
		{
			return ((Kingdom)o).Color2;
		}

		// Token: 0x06000DA7 RID: 3495 RVA: 0x00047236 File Offset: 0x00045436
		internal static object AutoGeneratedGetMemberValuePrimaryBannerColor(object o)
		{
			return ((Kingdom)o).PrimaryBannerColor;
		}

		// Token: 0x06000DA8 RID: 3496 RVA: 0x00047248 File Offset: 0x00045448
		internal static object AutoGeneratedGetMemberValueSecondaryBannerColor(object o)
		{
			return ((Kingdom)o).SecondaryBannerColor;
		}

		// Token: 0x06000DA9 RID: 3497 RVA: 0x0004725A File Offset: 0x0004545A
		internal static object AutoGeneratedGetMemberValueMainHeroCrimeRating(object o)
		{
			return ((Kingdom)o).MainHeroCrimeRating;
		}

		// Token: 0x06000DAA RID: 3498 RVA: 0x0004726C File Offset: 0x0004546C
		internal static object AutoGeneratedGetMemberValueBanner(object o)
		{
			return ((Kingdom)o).Banner;
		}

		// Token: 0x06000DAB RID: 3499 RVA: 0x00047279 File Offset: 0x00045479
		internal static object AutoGeneratedGetMemberValueLastArmyCreationDay(object o)
		{
			return ((Kingdom)o).LastArmyCreationDay;
		}

		// Token: 0x06000DAC RID: 3500 RVA: 0x0004728B File Offset: 0x0004548B
		internal static object AutoGeneratedGetMemberValueLastKingdomDecisionConclusionDate(object o)
		{
			return ((Kingdom)o).LastKingdomDecisionConclusionDate;
		}

		// Token: 0x06000DAD RID: 3501 RVA: 0x0004729D File Offset: 0x0004549D
		internal static object AutoGeneratedGetMemberValueLastMercenaryOfferTime(object o)
		{
			return ((Kingdom)o).LastMercenaryOfferTime;
		}

		// Token: 0x06000DAE RID: 3502 RVA: 0x000472AF File Offset: 0x000454AF
		internal static object AutoGeneratedGetMemberValueNotAttackableByPlayerUntilTime(object o)
		{
			return ((Kingdom)o).NotAttackableByPlayerUntilTime;
		}

		// Token: 0x06000DAF RID: 3503 RVA: 0x000472C1 File Offset: 0x000454C1
		internal static object AutoGeneratedGetMemberValueMercenaryWallet(object o)
		{
			return ((Kingdom)o).MercenaryWallet;
		}

		// Token: 0x06000DB0 RID: 3504 RVA: 0x000472D3 File Offset: 0x000454D3
		internal static object AutoGeneratedGetMemberValuePoliticalStagnation(object o)
		{
			return ((Kingdom)o).PoliticalStagnation;
		}

		// Token: 0x06000DB1 RID: 3505 RVA: 0x000472E5 File Offset: 0x000454E5
		internal static object AutoGeneratedGetMemberValue_unresolvedDecisions(object o)
		{
			return ((Kingdom)o)._unresolvedDecisions;
		}

		// Token: 0x06000DB2 RID: 3506 RVA: 0x000472F2 File Offset: 0x000454F2
		internal static object AutoGeneratedGetMemberValue_rulingClan(object o)
		{
			return ((Kingdom)o)._rulingClan;
		}

		// Token: 0x06000DB3 RID: 3507 RVA: 0x000472FF File Offset: 0x000454FF
		internal static object AutoGeneratedGetMemberValue_armies(object o)
		{
			return ((Kingdom)o)._armies;
		}

		// Token: 0x06000DB4 RID: 3508 RVA: 0x0004730C File Offset: 0x0004550C
		internal static object AutoGeneratedGetMemberValue_activePolicies(object o)
		{
			return ((Kingdom)o)._activePolicies;
		}

		// Token: 0x06000DB5 RID: 3509 RVA: 0x00047319 File Offset: 0x00045519
		internal static object AutoGeneratedGetMemberValue_isEliminated(object o)
		{
			return ((Kingdom)o)._isEliminated;
		}

		// Token: 0x06000DB6 RID: 3510 RVA: 0x0004732B File Offset: 0x0004552B
		internal static object AutoGeneratedGetMemberValue_aggressiveness(object o)
		{
			return ((Kingdom)o)._aggressiveness;
		}

		// Token: 0x06000DB7 RID: 3511 RVA: 0x0004733D File Offset: 0x0004553D
		internal static object AutoGeneratedGetMemberValue_tributeWallet(object o)
		{
			return ((Kingdom)o)._tributeWallet;
		}

		// Token: 0x06000DB8 RID: 3512 RVA: 0x0004734F File Offset: 0x0004554F
		internal static object AutoGeneratedGetMemberValue_kingdomBudgetWallet(object o)
		{
			return ((Kingdom)o)._kingdomBudgetWallet;
		}

		// Token: 0x06000DB9 RID: 3513 RVA: 0x00047361 File Offset: 0x00045561
		internal static object AutoGeneratedGetMemberValue_callToWarWallet(object o)
		{
			return ((Kingdom)o)._callToWarWallet;
		}

		// Token: 0x17000334 RID: 820
		// (get) Token: 0x06000DBA RID: 3514 RVA: 0x00047373 File Offset: 0x00045573
		// (set) Token: 0x06000DBB RID: 3515 RVA: 0x0004737B File Offset: 0x0004557B
		[SaveableProperty(1)]
		public TextObject Name { get; private set; }

		// Token: 0x17000335 RID: 821
		// (get) Token: 0x06000DBC RID: 3516 RVA: 0x00047384 File Offset: 0x00045584
		// (set) Token: 0x06000DBD RID: 3517 RVA: 0x0004738C File Offset: 0x0004558C
		[SaveableProperty(2)]
		public TextObject InformalName { get; private set; }

		// Token: 0x17000336 RID: 822
		// (get) Token: 0x06000DBE RID: 3518 RVA: 0x00047395 File Offset: 0x00045595
		// (set) Token: 0x06000DBF RID: 3519 RVA: 0x0004739D File Offset: 0x0004559D
		[SaveableProperty(3)]
		public TextObject EncyclopediaText { get; private set; }

		// Token: 0x17000337 RID: 823
		// (get) Token: 0x06000DC0 RID: 3520 RVA: 0x000473A6 File Offset: 0x000455A6
		// (set) Token: 0x06000DC1 RID: 3521 RVA: 0x000473AE File Offset: 0x000455AE
		[SaveableProperty(4)]
		public TextObject EncyclopediaTitle { get; private set; }

		// Token: 0x17000338 RID: 824
		// (get) Token: 0x06000DC2 RID: 3522 RVA: 0x000473B7 File Offset: 0x000455B7
		// (set) Token: 0x06000DC3 RID: 3523 RVA: 0x000473BF File Offset: 0x000455BF
		[SaveableProperty(5)]
		public TextObject EncyclopediaRulerTitle { get; private set; }

		// Token: 0x17000339 RID: 825
		// (get) Token: 0x06000DC4 RID: 3524 RVA: 0x000473C8 File Offset: 0x000455C8
		public string EncyclopediaLink
		{
			get
			{
				return Campaign.Current.EncyclopediaManager.GetIdentifier(typeof(Kingdom)) + "-" + base.StringId;
			}
		}

		// Token: 0x1700033A RID: 826
		// (get) Token: 0x06000DC5 RID: 3525 RVA: 0x000473F3 File Offset: 0x000455F3
		public TextObject EncyclopediaLinkWithName
		{
			get
			{
				return HyperlinkTexts.GetKingdomHyperlinkText(this.EncyclopediaLink, this.InformalName);
			}
		}

		// Token: 0x1700033B RID: 827
		// (get) Token: 0x06000DC6 RID: 3526 RVA: 0x00047406 File Offset: 0x00045606
		public MBReadOnlyList<KingdomDecision> UnresolvedDecisions
		{
			get
			{
				return this._unresolvedDecisions;
			}
		}

		// Token: 0x1700033C RID: 828
		// (get) Token: 0x06000DC7 RID: 3527 RVA: 0x0004740E File Offset: 0x0004560E
		// (set) Token: 0x06000DC8 RID: 3528 RVA: 0x00047416 File Offset: 0x00045616
		[SaveableProperty(6)]
		public CultureObject Culture { get; private set; }

		// Token: 0x1700033D RID: 829
		// (get) Token: 0x06000DC9 RID: 3529 RVA: 0x0004741F File Offset: 0x0004561F
		// (set) Token: 0x06000DCA RID: 3530 RVA: 0x00047427 File Offset: 0x00045627
		[SaveableProperty(17)]
		public Settlement InitialHomeSettlement { get; private set; }

		// Token: 0x1700033E RID: 830
		// (get) Token: 0x06000DCB RID: 3531 RVA: 0x00047430 File Offset: 0x00045630
		public bool IsMapFaction
		{
			get
			{
				return true;
			}
		}

		// Token: 0x1700033F RID: 831
		// (get) Token: 0x06000DCC RID: 3532 RVA: 0x00047433 File Offset: 0x00045633
		public bool HasNavalNavigationCapability
		{
			get
			{
				return this.Culture.DefaultPartyTemplate.ShipHulls.Any<ShipTemplateStack>();
			}
		}

		// Token: 0x17000340 RID: 832
		// (get) Token: 0x06000DCD RID: 3533 RVA: 0x0004744A File Offset: 0x0004564A
		// (set) Token: 0x06000DCE RID: 3534 RVA: 0x00047452 File Offset: 0x00045652
		[SaveableProperty(9)]
		public uint Color { get; private set; }

		// Token: 0x17000341 RID: 833
		// (get) Token: 0x06000DCF RID: 3535 RVA: 0x0004745B File Offset: 0x0004565B
		// (set) Token: 0x06000DD0 RID: 3536 RVA: 0x00047463 File Offset: 0x00045663
		[SaveableProperty(10)]
		public uint Color2 { get; private set; }

		// Token: 0x17000342 RID: 834
		// (get) Token: 0x06000DD1 RID: 3537 RVA: 0x0004746C File Offset: 0x0004566C
		// (set) Token: 0x06000DD2 RID: 3538 RVA: 0x00047474 File Offset: 0x00045674
		[SaveableProperty(13)]
		public uint PrimaryBannerColor { get; private set; }

		// Token: 0x17000343 RID: 835
		// (get) Token: 0x06000DD3 RID: 3539 RVA: 0x0004747D File Offset: 0x0004567D
		// (set) Token: 0x06000DD4 RID: 3540 RVA: 0x00047485 File Offset: 0x00045685
		[SaveableProperty(14)]
		public uint SecondaryBannerColor { get; private set; }

		// Token: 0x17000344 RID: 836
		// (get) Token: 0x06000DD5 RID: 3541 RVA: 0x0004748E File Offset: 0x0004568E
		// (set) Token: 0x06000DD6 RID: 3542 RVA: 0x00047496 File Offset: 0x00045696
		[SaveableProperty(15)]
		public float MainHeroCrimeRating { get; set; }

		// Token: 0x17000345 RID: 837
		// (get) Token: 0x06000DD7 RID: 3543 RVA: 0x0004749F File Offset: 0x0004569F
		public MBReadOnlyList<IFaction> FactionsAtWarWith
		{
			get
			{
				return this._factionsAtWarWith;
			}
		}

		// Token: 0x17000346 RID: 838
		// (get) Token: 0x06000DD8 RID: 3544 RVA: 0x000474A7 File Offset: 0x000456A7
		public MBReadOnlyList<Kingdom> AlliedKingdoms
		{
			get
			{
				return this._alliedKingdoms;
			}
		}

		// Token: 0x17000347 RID: 839
		// (get) Token: 0x06000DD9 RID: 3545 RVA: 0x000474AF File Offset: 0x000456AF
		public MBReadOnlyList<Town> Fiefs
		{
			get
			{
				return this._fiefsCache;
			}
		}

		// Token: 0x17000348 RID: 840
		// (get) Token: 0x06000DDA RID: 3546 RVA: 0x000474B7 File Offset: 0x000456B7
		public MBReadOnlyList<Village> Villages
		{
			get
			{
				return this._villagesCache;
			}
		}

		// Token: 0x17000349 RID: 841
		// (get) Token: 0x06000DDB RID: 3547 RVA: 0x000474BF File Offset: 0x000456BF
		public MBReadOnlyList<Settlement> Settlements
		{
			get
			{
				return this._settlementsCache;
			}
		}

		// Token: 0x1700034A RID: 842
		// (get) Token: 0x06000DDC RID: 3548 RVA: 0x000474C7 File Offset: 0x000456C7
		public MBReadOnlyList<Hero> Heroes
		{
			get
			{
				return this._heroesCache;
			}
		}

		// Token: 0x1700034B RID: 843
		// (get) Token: 0x06000DDD RID: 3549 RVA: 0x000474CF File Offset: 0x000456CF
		public MBReadOnlyList<Hero> AliveLords
		{
			get
			{
				return this._aliveLordsCache;
			}
		}

		// Token: 0x1700034C RID: 844
		// (get) Token: 0x06000DDE RID: 3550 RVA: 0x000474D7 File Offset: 0x000456D7
		public MBReadOnlyList<Hero> DeadLords
		{
			get
			{
				return this._deadLordsCache;
			}
		}

		// Token: 0x1700034D RID: 845
		// (get) Token: 0x06000DDF RID: 3551 RVA: 0x000474DF File Offset: 0x000456DF
		public MBReadOnlyList<WarPartyComponent> WarPartyComponents
		{
			get
			{
				return this._warPartyComponentsCache;
			}
		}

		// Token: 0x1700034E RID: 846
		// (get) Token: 0x06000DE0 RID: 3552 RVA: 0x000474E8 File Offset: 0x000456E8
		public float DailyCrimeRatingChange
		{
			get
			{
				return Campaign.Current.Models.CrimeModel.GetDailyCrimeRatingChange(this, false).ResultNumber;
			}
		}

		// Token: 0x1700034F RID: 847
		// (get) Token: 0x06000DE1 RID: 3553 RVA: 0x00047513 File Offset: 0x00045713
		public ExplainedNumber DailyCrimeRatingChangeExplained
		{
			get
			{
				return Campaign.Current.Models.CrimeModel.GetDailyCrimeRatingChange(this, true);
			}
		}

		// Token: 0x17000350 RID: 848
		// (get) Token: 0x06000DE2 RID: 3554 RVA: 0x0004752B File Offset: 0x0004572B
		public CharacterObject BasicTroop
		{
			get
			{
				return this.Culture.BasicTroop;
			}
		}

		// Token: 0x17000351 RID: 849
		// (get) Token: 0x06000DE3 RID: 3555 RVA: 0x00047538 File Offset: 0x00045738
		public Hero Leader
		{
			get
			{
				Clan rulingClan = this._rulingClan;
				if (rulingClan == null)
				{
					return null;
				}
				return rulingClan.Leader;
			}
		}

		// Token: 0x17000352 RID: 850
		// (get) Token: 0x06000DE4 RID: 3556 RVA: 0x0004754B File Offset: 0x0004574B
		// (set) Token: 0x06000DE5 RID: 3557 RVA: 0x00047553 File Offset: 0x00045753
		[SaveableProperty(16)]
		public Banner Banner { get; set; }

		// Token: 0x17000353 RID: 851
		// (get) Token: 0x06000DE6 RID: 3558 RVA: 0x0004755C File Offset: 0x0004575C
		public bool IsBanditFaction
		{
			get
			{
				return this._rulingClan != null && this._rulingClan.IsBanditFaction;
			}
		}

		// Token: 0x17000354 RID: 852
		// (get) Token: 0x06000DE7 RID: 3559 RVA: 0x00047573 File Offset: 0x00045773
		public bool IsMinorFaction
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000355 RID: 853
		// (get) Token: 0x06000DE8 RID: 3560 RVA: 0x00047576 File Offset: 0x00045776
		bool IFaction.IsKingdomFaction
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000356 RID: 854
		// (get) Token: 0x06000DE9 RID: 3561 RVA: 0x00047579 File Offset: 0x00045779
		public bool IsRebelClan
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000357 RID: 855
		// (get) Token: 0x06000DEA RID: 3562 RVA: 0x0004757C File Offset: 0x0004577C
		public bool IsClan
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000358 RID: 856
		// (get) Token: 0x06000DEB RID: 3563 RVA: 0x0004757F File Offset: 0x0004577F
		public bool IsOutlaw
		{
			get
			{
				return this._rulingClan != null && this._rulingClan.IsOutlaw;
			}
		}

		// Token: 0x17000359 RID: 857
		// (get) Token: 0x06000DEC RID: 3564 RVA: 0x00047596 File Offset: 0x00045796
		public MBReadOnlyList<Clan> Clans
		{
			get
			{
				return this._clans;
			}
		}

		// Token: 0x1700035A RID: 858
		// (get) Token: 0x06000DED RID: 3565 RVA: 0x0004759E File Offset: 0x0004579E
		// (set) Token: 0x06000DEE RID: 3566 RVA: 0x000475A6 File Offset: 0x000457A6
		public Clan RulingClan
		{
			get
			{
				return this._rulingClan;
			}
			set
			{
				this._rulingClan = value;
			}
		}

		// Token: 0x1700035B RID: 859
		// (get) Token: 0x06000DEF RID: 3567 RVA: 0x000475AF File Offset: 0x000457AF
		// (set) Token: 0x06000DF0 RID: 3568 RVA: 0x000475B7 File Offset: 0x000457B7
		[SaveableProperty(19)]
		public int LastArmyCreationDay { get; private set; }

		// Token: 0x1700035C RID: 860
		// (get) Token: 0x06000DF1 RID: 3569 RVA: 0x000475C0 File Offset: 0x000457C0
		public MBReadOnlyList<Army> Armies
		{
			get
			{
				return this._armies;
			}
		}

		// Token: 0x06000DF2 RID: 3570 RVA: 0x000475C8 File Offset: 0x000457C8
		public override TextObject GetName()
		{
			return this.Name;
		}

		// Token: 0x06000DF3 RID: 3571 RVA: 0x000475D0 File Offset: 0x000457D0
		public override string ToString()
		{
			return this.Name.ToString();
		}

		// Token: 0x1700035D RID: 861
		// (get) Token: 0x06000DF4 RID: 3572 RVA: 0x000475E0 File Offset: 0x000457E0
		public float CurrentTotalStrength
		{
			get
			{
				float num = 0f;
				int count = this._clans.Count;
				for (int i = 0; i < count; i++)
				{
					num += this._clans[i].CurrentTotalStrength;
				}
				return num;
			}
		}

		// Token: 0x1700035E RID: 862
		// (get) Token: 0x06000DF5 RID: 3573 RVA: 0x00047620 File Offset: 0x00045820
		public Settlement FactionMidSettlement
		{
			get
			{
				return this._midSettlement;
			}
		}

		// Token: 0x1700035F RID: 863
		// (get) Token: 0x06000DF6 RID: 3574 RVA: 0x00047628 File Offset: 0x00045828
		public float DistanceToClosestNonAllyFortification
		{
			get
			{
				if (this._distanceToClosestNonAllyFortificationCacheDirty)
				{
					this._distanceToClosestNonAllyFortificationCache = FactionHelper.GetDistanceToClosestNonAllyFortificationOfFaction(this);
					this._distanceToClosestNonAllyFortificationCacheDirty = false;
				}
				return this._distanceToClosestNonAllyFortificationCache;
			}
		}

		// Token: 0x17000360 RID: 864
		// (get) Token: 0x06000DF7 RID: 3575 RVA: 0x0004764B File Offset: 0x0004584B
		public IList<PolicyObject> ActivePolicies
		{
			get
			{
				return this._activePolicies;
			}
		}

		// Token: 0x17000361 RID: 865
		// (get) Token: 0x06000DF8 RID: 3576 RVA: 0x00047653 File Offset: 0x00045853
		public static MBReadOnlyList<Kingdom> All
		{
			get
			{
				return Campaign.Current.Kingdoms;
			}
		}

		// Token: 0x17000362 RID: 866
		// (get) Token: 0x06000DF9 RID: 3577 RVA: 0x0004765F File Offset: 0x0004585F
		// (set) Token: 0x06000DFA RID: 3578 RVA: 0x00047667 File Offset: 0x00045867
		[SaveableProperty(28)]
		public CampaignTime LastKingdomDecisionConclusionDate { get; private set; }

		// Token: 0x17000363 RID: 867
		// (get) Token: 0x06000DFB RID: 3579 RVA: 0x00047670 File Offset: 0x00045870
		public bool IsEliminated
		{
			get
			{
				return this._isEliminated;
			}
		}

		// Token: 0x17000364 RID: 868
		// (get) Token: 0x06000DFC RID: 3580 RVA: 0x00047678 File Offset: 0x00045878
		// (set) Token: 0x06000DFD RID: 3581 RVA: 0x00047680 File Offset: 0x00045880
		[SaveableProperty(41)]
		public CampaignTime LastMercenaryOfferTime { get; set; }

		// Token: 0x17000365 RID: 869
		// (get) Token: 0x06000DFE RID: 3582 RVA: 0x00047689 File Offset: 0x00045889
		public IFaction MapFaction
		{
			get
			{
				return this;
			}
		}

		// Token: 0x17000366 RID: 870
		// (get) Token: 0x06000DFF RID: 3583 RVA: 0x0004768C File Offset: 0x0004588C
		// (set) Token: 0x06000E00 RID: 3584 RVA: 0x00047694 File Offset: 0x00045894
		[SaveableProperty(50)]
		public CampaignTime NotAttackableByPlayerUntilTime { get; set; }

		// Token: 0x17000367 RID: 871
		// (get) Token: 0x06000E01 RID: 3585 RVA: 0x0004769D File Offset: 0x0004589D
		// (set) Token: 0x06000E02 RID: 3586 RVA: 0x000476A5 File Offset: 0x000458A5
		public float Aggressiveness
		{
			get
			{
				return this._aggressiveness;
			}
			internal set
			{
				this._aggressiveness = MathF.Clamp(value, 0f, 100f);
			}
		}

		// Token: 0x17000368 RID: 872
		// (get) Token: 0x06000E03 RID: 3587 RVA: 0x000476BD File Offset: 0x000458BD
		public IEnumerable<MobileParty> AllParties
		{
			get
			{
				foreach (MobileParty mobileParty in Campaign.Current.MobileParties)
				{
					if (mobileParty.MapFaction == this)
					{
						yield return mobileParty;
					}
				}
				List<MobileParty>.Enumerator enumerator = default(List<MobileParty>.Enumerator);
				yield break;
				yield break;
			}
		}

		// Token: 0x17000369 RID: 873
		// (get) Token: 0x06000E04 RID: 3588 RVA: 0x000476CD File Offset: 0x000458CD
		// (set) Token: 0x06000E05 RID: 3589 RVA: 0x000476D5 File Offset: 0x000458D5
		[SaveableProperty(70)]
		public int MercenaryWallet { get; internal set; }

		// Token: 0x06000E06 RID: 3590 RVA: 0x000476E0 File Offset: 0x000458E0
		public void UpdateFactionsAtWarWith()
		{
			this._factionsAtWarWith.Clear();
			foreach (Kingdom kingdom in Kingdom.All)
			{
				if (!kingdom.IsEliminated && this.IsAtWarWith(kingdom))
				{
					this._factionsAtWarWith.Add(kingdom);
				}
			}
			foreach (Clan clan in Clan.All)
			{
				if (!clan.IsEliminated && this.IsAtWarWith(clan))
				{
					this._factionsAtWarWith.Add(clan);
				}
			}
			this.UpdateAlliedKingdoms();
		}

		// Token: 0x06000E07 RID: 3591 RVA: 0x000477B0 File Offset: 0x000459B0
		public void UpdateAlliedKingdoms()
		{
			this._alliedKingdoms.Clear();
			foreach (Kingdom kingdom in Kingdom.All)
			{
				if (!kingdom.IsEliminated && this.IsAllyWith(kingdom))
				{
					this._alliedKingdoms.Add(kingdom);
				}
			}
		}

		// Token: 0x1700036A RID: 874
		// (get) Token: 0x06000E08 RID: 3592 RVA: 0x00047824 File Offset: 0x00045A24
		// (set) Token: 0x06000E09 RID: 3593 RVA: 0x0004782C File Offset: 0x00045A2C
		public int TributeWallet
		{
			get
			{
				return this._tributeWallet;
			}
			set
			{
				this._tributeWallet = value;
			}
		}

		// Token: 0x1700036B RID: 875
		// (get) Token: 0x06000E0A RID: 3594 RVA: 0x00047835 File Offset: 0x00045A35
		// (set) Token: 0x06000E0B RID: 3595 RVA: 0x0004783D File Offset: 0x00045A3D
		public int KingdomBudgetWallet
		{
			get
			{
				return this._kingdomBudgetWallet;
			}
			set
			{
				this._kingdomBudgetWallet = value;
			}
		}

		// Token: 0x1700036C RID: 876
		// (get) Token: 0x06000E0C RID: 3596 RVA: 0x00047846 File Offset: 0x00045A46
		// (set) Token: 0x06000E0D RID: 3597 RVA: 0x0004784E File Offset: 0x00045A4E
		public int CallToWarWallet
		{
			get
			{
				return this._callToWarWallet;
			}
			set
			{
				this._callToWarWallet = value;
			}
		}

		// Token: 0x06000E0E RID: 3598 RVA: 0x00047858 File Offset: 0x00045A58
		public Kingdom()
		{
			this._activePolicies = new MBList<PolicyObject>();
			this._armies = new MBList<Army>();
			this.InitializeCachedLists();
			this.EncyclopediaText = TextObject.GetEmpty();
			this.EncyclopediaTitle = TextObject.GetEmpty();
			this.EncyclopediaRulerTitle = TextObject.GetEmpty();
			float randomFloat = MBRandom.RandomFloat;
			float randomFloat2 = MBRandom.RandomFloat;
			this.PoliticalStagnation = 10 + (int)(randomFloat * randomFloat2 * 100f);
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
			this._isEliminated = false;
			this.NotAttackableByPlayerUntilTime = CampaignTime.Zero;
			this.LastArmyCreationDay = (int)CampaignTime.Now.ToDays;
		}

		// Token: 0x06000E0F RID: 3599 RVA: 0x00047908 File Offset: 0x00045B08
		public static Kingdom CreateKingdom(string stringID)
		{
			stringID = Campaign.Current.CampaignObjectManager.FindNextUniqueStringId<Kingdom>(stringID);
			Kingdom kingdom = new Kingdom();
			kingdom.StringId = stringID;
			Campaign.Current.CampaignObjectManager.AddKingdom(kingdom);
			return kingdom;
		}

		// Token: 0x06000E10 RID: 3600 RVA: 0x00047948 File Offset: 0x00045B48
		public void InitializeKingdom(TextObject name, TextObject informalName, CultureObject culture, Banner banner, uint kingdomColor1, uint kingdomColor2, Settlement initialHomeSettlement, TextObject encyclopediaText, TextObject encyclopediaTitle, TextObject encyclopediaRulerTitle)
		{
			this.ChangeKingdomName(name, informalName);
			this.Culture = culture;
			this.Banner = banner;
			this.Color = kingdomColor1;
			this.Color2 = kingdomColor2;
			this.PrimaryBannerColor = this.Color;
			this.SecondaryBannerColor = this.Color2;
			this.PoliticalStagnation = 100;
			this.EncyclopediaText = encyclopediaText;
			this.EncyclopediaTitle = encyclopediaTitle;
			this.EncyclopediaRulerTitle = encyclopediaRulerTitle;
			this.InitialHomeSettlement = initialHomeSettlement;
			foreach (PolicyObject policy in this.Culture.DefaultPolicyList)
			{
				this.AddPolicy(policy);
			}
		}

		// Token: 0x06000E11 RID: 3601 RVA: 0x00047A08 File Offset: 0x00045C08
		private void InitializeCachedLists()
		{
			this._clans = new MBList<Clan>();
			this._factionsAtWarWith = new MBList<IFaction>();
			this._fiefsCache = new MBList<Town>();
			this._villagesCache = new MBList<Village>();
			this._settlementsCache = new MBList<Settlement>();
			this._heroesCache = new MBList<Hero>();
			this._aliveLordsCache = new MBList<Hero>();
			this._deadLordsCache = new MBList<Hero>();
			this._warPartyComponentsCache = new MBList<WarPartyComponent>();
			this._alliedKingdoms = new MBList<Kingdom>();
		}

		// Token: 0x06000E12 RID: 3602 RVA: 0x00047A83 File Offset: 0x00045C83
		public void ChangeKingdomName(TextObject name, TextObject informalName)
		{
			this.Name = name;
			this.InformalName = informalName;
		}

		// Token: 0x06000E13 RID: 3603 RVA: 0x00047A93 File Offset: 0x00045C93
		public void OnHeroChangedState(Hero hero, Hero.CharacterStates oldState)
		{
			if (hero.IsDead && oldState != Hero.CharacterStates.Dead)
			{
				this._aliveLordsCache.Remove(hero);
				this._deadLordsCache.Add(hero);
			}
		}

		// Token: 0x06000E14 RID: 3604 RVA: 0x00047ABA File Offset: 0x00045CBA
		[LoadInitializationCallback]
		private void OnLoad(MetaData metaData, ObjectLoadData objectLoadData)
		{
			this.InitializeCachedLists();
		}

		// Token: 0x06000E15 RID: 3605 RVA: 0x00047AC4 File Offset: 0x00045CC4
		protected override void AfterLoad()
		{
			for (int i = this._activePolicies.Count - 1; i >= 0; i--)
			{
				if (this._activePolicies[i] == null || !this._activePolicies[i].IsReady)
				{
					this._activePolicies.RemoveAt(i);
				}
			}
			for (int j = this.Clans.Count - 1; j >= 0; j--)
			{
				Clan clan = this.Clans[j];
				if (Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(clan, this))
				{
					foreach (WarPartyComponent warPartyComponent in clan.WarPartyComponents.ToList<WarPartyComponent>())
					{
						if (warPartyComponent.MobileParty.MapEvent != null && (warPartyComponent.MobileParty.Army == null || warPartyComponent.MobileParty.Army.LeaderParty == warPartyComponent.MobileParty))
						{
							warPartyComponent.MobileParty.MapEvent.FinalizeEvent();
						}
					}
				}
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000E16 RID: 3606 RVA: 0x00047BEC File Offset: 0x00045DEC
		public bool IsAllyWith(Kingdom other)
		{
			IAllianceCampaignBehavior campaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
			return campaignBehavior != null && campaignBehavior.IsAllyWithKingdom(this, other);
		}

		// Token: 0x06000E17 RID: 3607 RVA: 0x00047C05 File Offset: 0x00045E05
		public bool HasCalledToWar(Kingdom other)
		{
			IAllianceCampaignBehavior campaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
			return campaignBehavior != null && campaignBehavior.HasCalledToWar(this, other);
		}

		// Token: 0x06000E18 RID: 3608 RVA: 0x00047C1E File Offset: 0x00045E1E
		public bool IsAtWarWith(IFaction other)
		{
			return FactionManager.IsAtWarAgainstFaction(this, other);
		}

		// Token: 0x06000E19 RID: 3609 RVA: 0x00047C27 File Offset: 0x00045E27
		public bool IsAtConstantWarWith(IFaction other)
		{
			return FactionManager.IsAtConstantWarAgainstFaction(this, other);
		}

		// Token: 0x06000E1A RID: 3610 RVA: 0x00047C30 File Offset: 0x00045E30
		public StanceLink GetStanceWith(IFaction other)
		{
			return FactionManager.Instance.GetStanceLinkInternal(this, other);
		}

		// Token: 0x06000E1B RID: 3611 RVA: 0x00047C3E File Offset: 0x00045E3E
		internal void AddArmyInternal(Army army)
		{
			this._armies.Add(army);
		}

		// Token: 0x06000E1C RID: 3612 RVA: 0x00047C4C File Offset: 0x00045E4C
		internal void RemoveArmyInternal(Army army)
		{
			this._armies.Remove(army);
		}

		// Token: 0x06000E1D RID: 3613 RVA: 0x00047C5C File Offset: 0x00045E5C
		public void CreateArmy(Hero armyLeader, Settlement targetSettlement, Army.ArmyTypes selectedArmyType, MBReadOnlyList<MobileParty> partiesToCallToArmy = null)
		{
			if (!armyLeader.IsActive)
			{
				Debug.Print(string.Format("Failed to create army, leader - {0}: {1} is inactive", (armyLeader != null) ? armyLeader.StringId : null, (armyLeader != null) ? armyLeader.Name : null), 0, Debug.DebugColor.White, 17592186044416UL);
				return;
			}
			if (((armyLeader != null) ? armyLeader.PartyBelongedTo.LeaderHero : null) != null)
			{
				Army army = new Army(this, armyLeader.PartyBelongedTo, selectedArmyType);
				army.Gather(targetSettlement, partiesToCallToArmy);
				this.LastArmyCreationDay = (int)CampaignTime.Now.ToDays;
				CampaignEventDispatcher.Instance.OnArmyCreated(army);
			}
			if (armyLeader == Hero.MainHero)
			{
				MapState mapState = Game.Current.GameStateManager.GameStates.Single((GameState S) => S is MapState) as MapState;
				if (mapState == null)
				{
					return;
				}
				mapState.OnArmyCreated(MobileParty.MainParty);
			}
		}

		// Token: 0x06000E1E RID: 3614 RVA: 0x00047D40 File Offset: 0x00045F40
		public void AddDecision(KingdomDecision kingdomDecision, bool ignoreInfluenceCost = false)
		{
			if (!ignoreInfluenceCost)
			{
				Clan proposerClan = kingdomDecision.ProposerClan;
				int influenceCost = kingdomDecision.GetInfluenceCost(proposerClan);
				ChangeClanInfluenceAction.Apply(proposerClan, (float)(-(float)influenceCost));
			}
			bool flag;
			if (!kingdomDecision.DetermineChooser().Leader.IsHumanPlayerCharacter)
			{
				flag = kingdomDecision.DetermineSupporters().Any((Supporter x) => x.IsPlayer);
			}
			else
			{
				flag = true;
			}
			bool isPlayerInvolved = flag;
			CampaignEventDispatcher.Instance.OnKingdomDecisionAdded(kingdomDecision, isPlayerInvolved);
			if (kingdomDecision.Kingdom != Clan.PlayerClan.Kingdom)
			{
				new KingdomElection(kingdomDecision).StartElection();
				return;
			}
			this._unresolvedDecisions.Add(kingdomDecision);
		}

		// Token: 0x06000E1F RID: 3615 RVA: 0x00047DDE File Offset: 0x00045FDE
		public void RemoveDecision(KingdomDecision kingdomDecision)
		{
			this._unresolvedDecisions.Remove(kingdomDecision);
		}

		// Token: 0x06000E20 RID: 3616 RVA: 0x00047DED File Offset: 0x00045FED
		public void OnKingdomDecisionConcluded()
		{
			this.LastKingdomDecisionConclusionDate = CampaignTime.Now;
		}

		// Token: 0x06000E21 RID: 3617 RVA: 0x00047DFA File Offset: 0x00045FFA
		public void AddPolicy(PolicyObject policy)
		{
			if (!this._activePolicies.Contains(policy))
			{
				this._activePolicies.Add(policy);
			}
		}

		// Token: 0x06000E22 RID: 3618 RVA: 0x00047E16 File Offset: 0x00046016
		public void RemovePolicy(PolicyObject policy)
		{
			if (this._activePolicies.Contains(policy))
			{
				this._activePolicies.Remove(policy);
			}
		}

		// Token: 0x06000E23 RID: 3619 RVA: 0x00047E34 File Offset: 0x00046034
		public bool HasPolicy(PolicyObject policy)
		{
			for (int i = 0; i < this._activePolicies.Count; i++)
			{
				if (this._activePolicies[i] == policy)
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x06000E24 RID: 3620 RVA: 0x00047E6C File Offset: 0x0004606C
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this.EncyclopediaText = ((node.Attributes["text"] != null) ? new TextObject(node.Attributes["text"].Value, null) : TextObject.GetEmpty());
			this.EncyclopediaTitle = ((node.Attributes["title"] != null) ? new TextObject(node.Attributes["title"].Value, null) : TextObject.GetEmpty());
			this.EncyclopediaRulerTitle = ((node.Attributes["ruler_title"] != null) ? new TextObject(node.Attributes["ruler_title"].Value, null) : TextObject.GetEmpty());
			Settlement initialHomeSettlement = null;
			if (node.Attributes["initial_home_settlement"] != null)
			{
				initialHomeSettlement = (Settlement)objectManager.ReadObjectReferenceFromXml("initial_home_settlement", typeof(Settlement), node);
			}
			this.InitializeKingdom(new TextObject(node.Attributes["name"].Value, null), (node.Attributes["short_name"] != null) ? new TextObject(node.Attributes["short_name"].Value, null) : new TextObject(node.Attributes["name"].Value, null), (CultureObject)objectManager.ReadObjectReferenceFromXml("culture", typeof(CultureObject), node), null, (node.Attributes["color"] == null) ? 0U : Convert.ToUInt32(node.Attributes["color"].Value, 16), (node.Attributes["color2"] == null) ? 0U : Convert.ToUInt32(node.Attributes["color2"].Value, 16), initialHomeSettlement, this.EncyclopediaText, this.EncyclopediaTitle, this.EncyclopediaRulerTitle);
			Hero hero = objectManager.ReadObjectReferenceFromXml("owner", typeof(Hero), node) as Hero;
			this.RulingClan = ((hero != null) ? hero.Clan : null);
			this.PrimaryBannerColor = ((node.Attributes["primary_banner_color"] == null) ? 0U : Convert.ToUInt32(node.Attributes["primary_banner_color"].Value, 16));
			this.SecondaryBannerColor = ((node.Attributes["secondary_banner_color"] == null) ? 0U : Convert.ToUInt32(node.Attributes["secondary_banner_color"].Value, 16));
			if (node.Attributes["banner_key"] != null)
			{
				this.Banner = new Banner();
				this.Banner.Deserialize(node.Attributes["banner_key"].Value);
			}
			else
			{
				this.Banner = Banner.CreateRandomClanBanner(base.StringId.GetDeterministicHashCode());
			}
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.Name == "relationships")
				{
					using (IEnumerator enumerator2 = xmlNode.ChildNodes.GetEnumerator())
					{
						while (enumerator2.MoveNext())
						{
							object obj2 = enumerator2.Current;
							XmlNode xmlNode2 = (XmlNode)obj2;
							IFaction faction;
							if (xmlNode2.Attributes["clan"] != null)
							{
								faction = (Clan)objectManager.ReadObjectReferenceFromXml("clan", typeof(Clan), xmlNode2);
							}
							else
							{
								faction = (Kingdom)objectManager.ReadObjectReferenceFromXml("kingdom", typeof(Kingdom), xmlNode2);
							}
							if (Convert.ToInt32(xmlNode2.Attributes["value"].InnerText) < 0)
							{
								FactionManager.DeclareWar(this, faction);
							}
							else
							{
								FactionManager.SetNeutral(this, faction);
							}
							if (xmlNode2.Attributes["isAtWar"] != null && Convert.ToBoolean(xmlNode2.Attributes["isAtWar"].Value))
							{
								FactionManager.DeclareWar(this, faction);
							}
						}
						continue;
					}
				}
				if (xmlNode.Name == "policies")
				{
					foreach (object obj3 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode3 = (XmlNode)obj3;
						PolicyObject @object = Game.Current.ObjectManager.GetObject<PolicyObject>(xmlNode3.Attributes["id"].Value);
						if (@object != null)
						{
							this.AddPolicy(@object);
						}
					}
				}
			}
		}

		// Token: 0x06000E25 RID: 3621 RVA: 0x00048364 File Offset: 0x00046564
		internal void AddClanInternal(Clan clan)
		{
			this._clans.Add(clan);
			this.CalculateMidSettlement();
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
		}

		// Token: 0x06000E26 RID: 3622 RVA: 0x0004837F File Offset: 0x0004657F
		internal void RemoveClanInternal(Clan clan)
		{
			this._clans.Remove(clan);
			this.CalculateMidSettlement();
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
		}

		// Token: 0x06000E27 RID: 3623 RVA: 0x0004839C File Offset: 0x0004659C
		public void OnFortificationAdded(Town fortification)
		{
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
			this._fiefsCache.Add(fortification);
			this._settlementsCache.Add(fortification.Settlement);
			foreach (Village village in fortification.Settlement.BoundVillages)
			{
				this.OnBoundVillageAdded(village);
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000E28 RID: 3624 RVA: 0x00048420 File Offset: 0x00046620
		public void OnFortificationRemoved(Town fortification)
		{
			this._distanceToClosestNonAllyFortificationCacheDirty = true;
			this._fiefsCache.Remove(fortification);
			this._settlementsCache.Remove(fortification.Settlement);
			foreach (Village village in fortification.Settlement.BoundVillages)
			{
				this.OnBoundVillageRemoved(village);
			}
			this.CalculateMidSettlement();
		}

		// Token: 0x06000E29 RID: 3625 RVA: 0x000484A4 File Offset: 0x000466A4
		private void OnBoundVillageRemoved(Village village)
		{
			this._villagesCache.Remove(village);
			this._settlementsCache.Remove(village.Settlement);
		}

		// Token: 0x06000E2A RID: 3626 RVA: 0x000484C5 File Offset: 0x000466C5
		internal void OnBoundVillageAdded(Village village)
		{
			this._villagesCache.Add(village);
			this._settlementsCache.Add(village.Settlement);
		}

		// Token: 0x06000E2B RID: 3627 RVA: 0x000484E4 File Offset: 0x000466E4
		public void OnHeroAdded(Hero hero)
		{
			this._heroesCache.Add(hero);
			if (hero.Occupation == Occupation.Lord)
			{
				this.OnLordAdded(hero);
			}
		}

		// Token: 0x06000E2C RID: 3628 RVA: 0x00048502 File Offset: 0x00046702
		public void OnHeroRemoved(Hero hero)
		{
			this._heroesCache.Remove(hero);
			if (hero.Occupation == Occupation.Lord)
			{
				this.OnLordRemoved(hero);
			}
		}

		// Token: 0x06000E2D RID: 3629 RVA: 0x00048521 File Offset: 0x00046721
		private void OnLordAdded(Hero hero)
		{
			if (hero.IsDead)
			{
				this._deadLordsCache.Add(hero);
				return;
			}
			this._aliveLordsCache.Add(hero);
		}

		// Token: 0x06000E2E RID: 3630 RVA: 0x00048544 File Offset: 0x00046744
		private void OnLordRemoved(Hero hero)
		{
			if (hero.IsDead)
			{
				this._deadLordsCache.Remove(hero);
				return;
			}
			this._aliveLordsCache.Remove(hero);
		}

		// Token: 0x06000E2F RID: 3631 RVA: 0x00048569 File Offset: 0x00046769
		public void OnWarPartyAdded(WarPartyComponent warPartyComponent)
		{
			this._warPartyComponentsCache.Add(warPartyComponent);
		}

		// Token: 0x06000E30 RID: 3632 RVA: 0x00048577 File Offset: 0x00046777
		public void OnWarPartyRemoved(WarPartyComponent warPartyComponent)
		{
			this._warPartyComponentsCache.Remove(warPartyComponent);
		}

		// Token: 0x06000E31 RID: 3633 RVA: 0x00048586 File Offset: 0x00046786
		public void CalculateMidSettlement()
		{
			if (Campaign.Current.MapSceneWrapper != null)
			{
				this._midSettlement = FactionHelper.GetMidSettlementOfFaction(this);
			}
		}

		// Token: 0x06000E32 RID: 3634 RVA: 0x000485A0 File Offset: 0x000467A0
		public void ReactivateKingdom()
		{
			this._isEliminated = false;
		}

		// Token: 0x06000E33 RID: 3635 RVA: 0x000485A9 File Offset: 0x000467A9
		internal void DeactivateKingdom()
		{
			this._isEliminated = true;
		}

		// Token: 0x06000E34 RID: 3636 RVA: 0x000485B2 File Offset: 0x000467B2
		string IFaction.get_StringId()
		{
			return base.StringId;
		}

		// Token: 0x06000E35 RID: 3637 RVA: 0x000485BA File Offset: 0x000467BA
		MBGUID IFaction.get_Id()
		{
			return base.Id;
		}

		// Token: 0x040003D1 RID: 977
		[SaveableField(10)]
		private MBList<KingdomDecision> _unresolvedDecisions = new MBList<KingdomDecision>();

		// Token: 0x040003D9 RID: 985
		private MBList<IFaction> _factionsAtWarWith;

		// Token: 0x040003DA RID: 986
		private MBList<Kingdom> _alliedKingdoms;

		// Token: 0x040003DB RID: 987
		[CachedData]
		private MBList<Town> _fiefsCache;

		// Token: 0x040003DC RID: 988
		[CachedData]
		private MBList<Village> _villagesCache;

		// Token: 0x040003DD RID: 989
		[CachedData]
		private MBList<Settlement> _settlementsCache;

		// Token: 0x040003DE RID: 990
		[CachedData]
		private MBList<Hero> _heroesCache;

		// Token: 0x040003DF RID: 991
		[CachedData]
		private MBList<Hero> _aliveLordsCache;

		// Token: 0x040003E0 RID: 992
		[CachedData]
		private MBList<Hero> _deadLordsCache;

		// Token: 0x040003E1 RID: 993
		[CachedData]
		private MBList<WarPartyComponent> _warPartyComponentsCache;

		// Token: 0x040003E3 RID: 995
		[CachedData]
		private MBList<Clan> _clans;

		// Token: 0x040003E4 RID: 996
		[SaveableField(18)]
		private Clan _rulingClan;

		// Token: 0x040003E6 RID: 998
		[SaveableField(20)]
		private MBList<Army> _armies;

		// Token: 0x040003E7 RID: 999
		[CachedData]
		private Settlement _midSettlement;

		// Token: 0x040003E8 RID: 1000
		[CachedData]
		private float _distanceToClosestNonAllyFortificationCache;

		// Token: 0x040003E9 RID: 1001
		[CachedData]
		private bool _distanceToClosestNonAllyFortificationCacheDirty = true;

		// Token: 0x040003EA RID: 1002
		[SaveableField(23)]
		public int PoliticalStagnation;

		// Token: 0x040003EB RID: 1003
		[SaveableField(26)]
		private MBList<PolicyObject> _activePolicies;

		// Token: 0x040003ED RID: 1005
		[SaveableField(29)]
		private bool _isEliminated;

		// Token: 0x040003F0 RID: 1008
		[SaveableField(60)]
		private float _aggressiveness;

		// Token: 0x040003F2 RID: 1010
		[SaveableField(80)]
		private int _tributeWallet;

		// Token: 0x040003F3 RID: 1011
		[SaveableField(81)]
		private int _kingdomBudgetWallet;

		// Token: 0x040003F4 RID: 1012
		[SaveableField(82)]
		private int _callToWarWallet;
	}
}
