using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000302 RID: 770
	public class LordPartyComponent : WarPartyComponent
	{
		// Token: 0x06002CBD RID: 11453 RVA: 0x000BB5F1 File Offset: 0x000B97F1
		internal static void AutoGeneratedStaticCollectObjectsLordPartyComponent(object o, List<object> collectedObjects)
		{
			((LordPartyComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002CBE RID: 11454 RVA: 0x000BB5FF File Offset: 0x000B97FF
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._leader);
			collectedObjects.Add(this.Owner);
		}

		// Token: 0x06002CBF RID: 11455 RVA: 0x000BB620 File Offset: 0x000B9820
		internal static object AutoGeneratedGetMemberValueOwner(object o)
		{
			return ((LordPartyComponent)o).Owner;
		}

		// Token: 0x06002CC0 RID: 11456 RVA: 0x000BB62D File Offset: 0x000B982D
		internal static object AutoGeneratedGetMemberValue_leader(object o)
		{
			return ((LordPartyComponent)o)._leader;
		}

		// Token: 0x06002CC1 RID: 11457 RVA: 0x000BB63A File Offset: 0x000B983A
		internal static object AutoGeneratedGetMemberValue_wagePaymentLimit(object o)
		{
			return ((LordPartyComponent)o)._wagePaymentLimit;
		}

		// Token: 0x17000B09 RID: 2825
		// (get) Token: 0x06002CC2 RID: 11458 RVA: 0x000BB64C File Offset: 0x000B984C
		public override Hero PartyOwner
		{
			get
			{
				return this.Owner;
			}
		}

		// Token: 0x17000B0A RID: 2826
		// (get) Token: 0x06002CC3 RID: 11459 RVA: 0x000BB654 File Offset: 0x000B9854
		public override TextObject Name
		{
			get
			{
				if (this._cachedName == null && this.Owner != null)
				{
					this._cachedName = this.GetPartyName();
				}
				return this._cachedName ?? new TextObject("{=!}unnamedMobileParty", null);
			}
		}

		// Token: 0x17000B0B RID: 2827
		// (get) Token: 0x06002CC4 RID: 11460 RVA: 0x000BB68D File Offset: 0x000B988D
		public override bool CanHaveNavalNavigationCapability
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000B0C RID: 2828
		// (get) Token: 0x06002CC5 RID: 11461 RVA: 0x000BB690 File Offset: 0x000B9890
		public override Settlement HomeSettlement
		{
			get
			{
				return this.Owner.HomeSettlement;
			}
		}

		// Token: 0x17000B0D RID: 2829
		// (get) Token: 0x06002CC6 RID: 11462 RVA: 0x000BB69D File Offset: 0x000B989D
		// (set) Token: 0x06002CC7 RID: 11463 RVA: 0x000BB6A5 File Offset: 0x000B98A5
		[SaveableProperty(20)]
		public Hero Owner { get; private set; }

		// Token: 0x17000B0E RID: 2830
		// (get) Token: 0x06002CC8 RID: 11464 RVA: 0x000BB6AE File Offset: 0x000B98AE
		public override Hero Leader
		{
			get
			{
				return this._leader;
			}
		}

		// Token: 0x17000B0F RID: 2831
		// (get) Token: 0x06002CC9 RID: 11465 RVA: 0x000BB6B6 File Offset: 0x000B98B6
		public override int WagePaymentLimit
		{
			get
			{
				return this._wagePaymentLimit;
			}
		}

		// Token: 0x06002CCA RID: 11466 RVA: 0x000BB6BE File Offset: 0x000B98BE
		public override void SetWagePaymentLimit(int newLimit)
		{
			this._wagePaymentLimit = newLimit;
		}

		// Token: 0x06002CCB RID: 11467 RVA: 0x000BB6C8 File Offset: 0x000B98C8
		protected override void OnMobilePartySetOnCreation()
		{
			base.MobileParty.ActualClan = this.Owner.Clan;
			base.MobileParty.Party.SetVisualAsDirty();
			if (base.MobileParty != MobileParty.MainParty && base.MobileParty.Owner.Clan != Clan.PlayerClan)
			{
				base.MobileParty.Aggressiveness = 0.9f + 0.1f * (float)this.Owner.GetTraitLevel(DefaultTraits.Valor) - 0.05f * (float)this.Owner.GetTraitLevel(DefaultTraits.Mercy);
				this.Owner.PassedTimeAtHomeSettlement = (float)((int)(MBRandom.RandomFloat * 100f));
			}
			if (this._initializationArgs != null)
			{
				this._initializationArgs.InitializeLordPartyProperties(base.MobileParty, this.Owner);
				this._initializationArgs = null;
			}
		}

		// Token: 0x06002CCC RID: 11468 RVA: 0x000BB7A0 File Offset: 0x000B99A0
		public static MobileParty CreateLordParty(string stringId, Hero hero, CampaignVec2 position, float spawnRadius, Settlement spawnSettlement, Hero partyLeader)
		{
			LordPartyComponent.InitializationArgs args = new LordPartyComponent.InitializationArgs(position, spawnRadius, spawnSettlement);
			return MobileParty.CreateParty(stringId + "_party_1", new LordPartyComponent(hero, partyLeader, args));
		}

		// Token: 0x06002CCD RID: 11469 RVA: 0x000BB7D0 File Offset: 0x000B99D0
		public static void ConvertPartyToLordParty(MobileParty mobileParty, Hero owner, Hero partyLeader)
		{
			mobileParty.SetPartyComponent(new LordPartyComponent(owner, partyLeader, null), true);
		}

		// Token: 0x06002CCE RID: 11470 RVA: 0x000BB7E1 File Offset: 0x000B99E1
		protected LordPartyComponent(Hero owner, Hero leader, LordPartyComponent.InitializationArgs args)
		{
			this.Owner = owner;
			this._leader = leader;
			this._initializationArgs = args;
		}

		// Token: 0x06002CCF RID: 11471 RVA: 0x000BB818 File Offset: 0x000B9A18
		internal void ChangePartyOwner(Hero owner)
		{
			this.ClearCachedName();
			this.Owner = owner;
		}

		// Token: 0x06002CD0 RID: 11472 RVA: 0x000BB827 File Offset: 0x000B9A27
		protected override void OnChangePartyLeader(Hero newLeader)
		{
			this._leader = newLeader;
			this.ClearCachedName();
			if (this._leader != null)
			{
				this.ChangePartyOwner(newLeader);
			}
		}

		// Token: 0x06002CD1 RID: 11473 RVA: 0x000BB845 File Offset: 0x000B9A45
		public override void ClearCachedName()
		{
			this._cachedName = null;
		}

		// Token: 0x06002CD2 RID: 11474 RVA: 0x000BB84E File Offset: 0x000B9A4E
		private TextObject GetPartyName()
		{
			TextObject textObject = GameTexts.FindText("str_lord_party_name", null);
			textObject.SetCharacterProperties("TROOP", this.Owner.CharacterObject, false);
			textObject.SetTextVariable("IS_LORDPARTY", 1);
			return textObject;
		}

		// Token: 0x04000CF8 RID: 3320
		private LordPartyComponent.InitializationArgs _initializationArgs;

		// Token: 0x04000CF9 RID: 3321
		[CachedData]
		private TextObject _cachedName;

		// Token: 0x04000CFB RID: 3323
		[SaveableField(30)]
		private Hero _leader;

		// Token: 0x04000CFC RID: 3324
		[SaveableField(40)]
		private int _wagePaymentLimit = Campaign.Current.Models.PartyWageModel.MaxWagePaymentLimit;

		// Token: 0x020006AA RID: 1706
		public class InitializationArgs
		{
			// Token: 0x0600524A RID: 21066 RVA: 0x001857C0 File Offset: 0x001839C0
			public InitializationArgs(CampaignVec2 position, float spawnRadius, Settlement spawnSettlement)
			{
				this.Position = position;
				this.SpawnRadius = spawnRadius;
				this.SpawnSettlement = spawnSettlement;
			}

			// Token: 0x0600524B RID: 21067 RVA: 0x001857E0 File Offset: 0x001839E0
			public void InitializeLordPartyProperties(MobileParty mobileParty, Hero owner)
			{
				mobileParty.AddElementToMemberRoster(owner.CharacterObject, 1, true);
				if (mobileParty == MobileParty.MainParty || owner.Clan == Clan.PlayerClan)
				{
					mobileParty.InitializeMobilePartyAtPosition(this.Position);
				}
				else
				{
					PartyTemplateObject pt = owner.Clan.IsRebelClan ? owner.Clan.Culture.RebelsPartyTemplate : owner.Clan.DefaultPartyTemplate;
					mobileParty.InitializeMobilePartyAroundPosition(pt, this.Position, this.SpawnRadius, 0f);
				}
				mobileParty.ItemRoster.Add(new ItemRosterElement(DefaultItems.Grain, MBRandom.RandomInt(15, 30), null));
				if (this.SpawnSettlement != null)
				{
					MobileParty.NavigationType navigationType = mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default;
					mobileParty.SetMoveGoToSettlement(this.SpawnSettlement, navigationType, mobileParty.IsCurrentlyAtSea);
				}
			}

			// Token: 0x04001A7E RID: 6782
			public readonly CampaignVec2 Position;

			// Token: 0x04001A7F RID: 6783
			public readonly float SpawnRadius;

			// Token: 0x04001A80 RID: 6784
			public readonly Settlement SpawnSettlement;
		}
	}
}
