using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Naval;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace TaleWorlds.CampaignSystem.MapEvents
{
	// Token: 0x02000310 RID: 784
	public class MapEventParty
	{
		// Token: 0x06002EB3 RID: 11955 RVA: 0x000C5562 File Offset: 0x000C3762
		internal static void AutoGeneratedStaticCollectObjectsMapEventParty(object o, List<object> collectedObjects)
		{
			((MapEventParty)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002EB4 RID: 11956 RVA: 0x000C5570 File Offset: 0x000C3770
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._roster);
			collectedObjects.Add(this._woundedInBattle);
			collectedObjects.Add(this._diedInBattle);
			collectedObjects.Add(this._routedInBattle);
			collectedObjects.Add(this.Party);
		}

		// Token: 0x06002EB5 RID: 11957 RVA: 0x000C55AE File Offset: 0x000C37AE
		internal static object AutoGeneratedGetMemberValueParty(object o)
		{
			return ((MapEventParty)o).Party;
		}

		// Token: 0x06002EB6 RID: 11958 RVA: 0x000C55BB File Offset: 0x000C37BB
		internal static object AutoGeneratedGetMemberValuePlunderedGold(object o)
		{
			return ((MapEventParty)o).PlunderedGold;
		}

		// Token: 0x06002EB7 RID: 11959 RVA: 0x000C55CD File Offset: 0x000C37CD
		internal static object AutoGeneratedGetMemberValueGoldLost(object o)
		{
			return ((MapEventParty)o).GoldLost;
		}

		// Token: 0x06002EB8 RID: 11960 RVA: 0x000C55DF File Offset: 0x000C37DF
		internal static object AutoGeneratedGetMemberValue_roster(object o)
		{
			return ((MapEventParty)o)._roster;
		}

		// Token: 0x06002EB9 RID: 11961 RVA: 0x000C55EC File Offset: 0x000C37EC
		internal static object AutoGeneratedGetMemberValue_contributionToBattle(object o)
		{
			return ((MapEventParty)o)._contributionToBattle;
		}

		// Token: 0x06002EBA RID: 11962 RVA: 0x000C55FE File Offset: 0x000C37FE
		internal static object AutoGeneratedGetMemberValue_healthyManCountAtStart(object o)
		{
			return ((MapEventParty)o)._healthyManCountAtStart;
		}

		// Token: 0x06002EBB RID: 11963 RVA: 0x000C5610 File Offset: 0x000C3810
		internal static object AutoGeneratedGetMemberValue_participatingTroopCount(object o)
		{
			return ((MapEventParty)o)._participatingTroopCount;
		}

		// Token: 0x06002EBC RID: 11964 RVA: 0x000C5622 File Offset: 0x000C3822
		internal static object AutoGeneratedGetMemberValue_woundedInBattle(object o)
		{
			return ((MapEventParty)o)._woundedInBattle;
		}

		// Token: 0x06002EBD RID: 11965 RVA: 0x000C562F File Offset: 0x000C382F
		internal static object AutoGeneratedGetMemberValue_diedInBattle(object o)
		{
			return ((MapEventParty)o)._diedInBattle;
		}

		// Token: 0x06002EBE RID: 11966 RVA: 0x000C563C File Offset: 0x000C383C
		internal static object AutoGeneratedGetMemberValue_routedInBattle(object o)
		{
			return ((MapEventParty)o)._routedInBattle;
		}

		// Token: 0x17000B7F RID: 2943
		// (get) Token: 0x06002EBF RID: 11967 RVA: 0x000C5649 File Offset: 0x000C3849
		// (set) Token: 0x06002EC0 RID: 11968 RVA: 0x000C5651 File Offset: 0x000C3851
		[SaveableProperty(1)]
		public PartyBase Party { get; private set; }

		// Token: 0x17000B80 RID: 2944
		// (get) Token: 0x06002EC1 RID: 11969 RVA: 0x000C565C File Offset: 0x000C385C
		public float GainedRenown
		{
			get
			{
				return this.GainedRenownExplained.ResultNumber;
			}
		}

		// Token: 0x17000B81 RID: 2945
		// (get) Token: 0x06002EC2 RID: 11970 RVA: 0x000C5678 File Offset: 0x000C3878
		public float GainedInfluence
		{
			get
			{
				return this.GainedInfluenceExplained.ResultNumber;
			}
		}

		// Token: 0x17000B82 RID: 2946
		// (get) Token: 0x06002EC3 RID: 11971 RVA: 0x000C5694 File Offset: 0x000C3894
		public float GainedMorale
		{
			get
			{
				return this.GainedMoraleExplained.ResultNumber;
			}
		}

		// Token: 0x17000B83 RID: 2947
		// (get) Token: 0x06002EC4 RID: 11972 RVA: 0x000C56AF File Offset: 0x000C38AF
		// (set) Token: 0x06002EC5 RID: 11973 RVA: 0x000C56B7 File Offset: 0x000C38B7
		public ExplainedNumber GainedRenownExplained { get; private set; }

		// Token: 0x17000B84 RID: 2948
		// (get) Token: 0x06002EC6 RID: 11974 RVA: 0x000C56C0 File Offset: 0x000C38C0
		// (set) Token: 0x06002EC7 RID: 11975 RVA: 0x000C56C8 File Offset: 0x000C38C8
		public ExplainedNumber GainedInfluenceExplained { get; private set; }

		// Token: 0x17000B85 RID: 2949
		// (get) Token: 0x06002EC8 RID: 11976 RVA: 0x000C56D1 File Offset: 0x000C38D1
		// (set) Token: 0x06002EC9 RID: 11977 RVA: 0x000C56D9 File Offset: 0x000C38D9
		public ExplainedNumber GainedMoraleExplained { get; private set; }

		// Token: 0x17000B86 RID: 2950
		// (get) Token: 0x06002ECA RID: 11978 RVA: 0x000C56E2 File Offset: 0x000C38E2
		// (set) Token: 0x06002ECB RID: 11979 RVA: 0x000C56EA File Offset: 0x000C38EA
		[SaveableProperty(10)]
		public int PlunderedGold { get; set; }

		// Token: 0x17000B87 RID: 2951
		// (get) Token: 0x06002ECC RID: 11980 RVA: 0x000C56F3 File Offset: 0x000C38F3
		// (set) Token: 0x06002ECD RID: 11981 RVA: 0x000C56FB File Offset: 0x000C38FB
		[SaveableProperty(11)]
		public int GoldLost { get; set; }

		// Token: 0x17000B88 RID: 2952
		// (get) Token: 0x06002ECE RID: 11982 RVA: 0x000C5704 File Offset: 0x000C3904
		public int HealthyManCountAtStart
		{
			get
			{
				return this._healthyManCountAtStart;
			}
		}

		// Token: 0x17000B89 RID: 2953
		// (get) Token: 0x06002ECF RID: 11983 RVA: 0x000C570C File Offset: 0x000C390C
		public TroopRoster DiedInBattle
		{
			get
			{
				return this._diedInBattle;
			}
		}

		// Token: 0x17000B8A RID: 2954
		// (get) Token: 0x06002ED0 RID: 11984 RVA: 0x000C5714 File Offset: 0x000C3914
		public TroopRoster WoundedInBattle
		{
			get
			{
				return this._woundedInBattle;
			}
		}

		// Token: 0x17000B8B RID: 2955
		// (get) Token: 0x06002ED1 RID: 11985 RVA: 0x000C571C File Offset: 0x000C391C
		public TroopRoster RoutedInBattle
		{
			get
			{
				return this._routedInBattle;
			}
		}

		// Token: 0x17000B8C RID: 2956
		// (get) Token: 0x06002ED2 RID: 11986 RVA: 0x000C5724 File Offset: 0x000C3924
		public int ContributionToBattle
		{
			get
			{
				return this._contributionToBattle;
			}
		}

		// Token: 0x17000B8D RID: 2957
		// (get) Token: 0x06002ED3 RID: 11987 RVA: 0x000C572C File Offset: 0x000C392C
		public bool IsNpcParty
		{
			get
			{
				return this.Party != PartyBase.MainParty;
			}
		}

		// Token: 0x17000B8E RID: 2958
		// (get) Token: 0x06002ED4 RID: 11988 RVA: 0x000C573E File Offset: 0x000C393E
		public TroopRoster RosterToReceiveLootMembers
		{
			get
			{
				if (!this.IsNpcParty)
				{
					return PlayerEncounter.Current.RosterToReceiveLootMembers;
				}
				return this.Party.MemberRoster;
			}
		}

		// Token: 0x17000B8F RID: 2959
		// (get) Token: 0x06002ED5 RID: 11989 RVA: 0x000C5760 File Offset: 0x000C3960
		public TroopRoster RosterToReceiveLootPrisoners
		{
			get
			{
				if (!this.IsNpcParty)
				{
					return PlayerEncounter.Current.RosterToReceiveLootPrisoners;
				}
				if (this.Party.IsMobile && (this.Party.MobileParty.IsMilitia || this.Party.MobileParty.IsGarrison))
				{
					return this.Party.MobileParty.HomeSettlement.Party.PrisonRoster;
				}
				return this.Party.PrisonRoster;
			}
		}

		// Token: 0x17000B90 RID: 2960
		// (get) Token: 0x06002ED6 RID: 11990 RVA: 0x000C57D7 File Offset: 0x000C39D7
		public ItemRoster RosterToReceiveLootItems
		{
			get
			{
				if (!this.IsNpcParty)
				{
					return PlayerEncounter.Current.RosterToReceiveLootItems;
				}
				return this.Party.ItemRoster;
			}
		}

		// Token: 0x17000B91 RID: 2961
		// (get) Token: 0x06002ED7 RID: 11991 RVA: 0x000C57F7 File Offset: 0x000C39F7
		public FlattenedTroopRoster Troops
		{
			get
			{
				return this._roster;
			}
		}

		// Token: 0x17000B92 RID: 2962
		// (get) Token: 0x06002ED8 RID: 11992 RVA: 0x000C57FF File Offset: 0x000C39FF
		public int ParticipatingTroopCount
		{
			get
			{
				return this._participatingTroopCount;
			}
		}

		// Token: 0x17000B93 RID: 2963
		// (get) Token: 0x06002ED9 RID: 11993 RVA: 0x000C5807 File Offset: 0x000C3A07
		public bool HasTroopLimit
		{
			get
			{
				return this._participatingTroopCount >= 0 && this._participatingTroopCount < this._healthyManCountAtStart;
			}
		}

		// Token: 0x17000B94 RID: 2964
		// (get) Token: 0x06002EDA RID: 11994 RVA: 0x000C5822 File Offset: 0x000C3A22
		public MBReadOnlyList<Ship> Ships
		{
			get
			{
				return this.Party.Ships;
			}
		}

		// Token: 0x06002EDB RID: 11995 RVA: 0x000C582F File Offset: 0x000C3A2F
		public override string ToString()
		{
			return this.Party.Name.ToString();
		}

		// Token: 0x06002EDC RID: 11996 RVA: 0x000C5844 File Offset: 0x000C3A44
		internal MapEventParty(PartyBase party)
		{
			this.Party = party;
			this.Update();
			this._healthyManCountAtStart = party.NumberOfHealthyMembers;
			this._participatingTroopCount = -1;
		}

		// Token: 0x06002EDD RID: 11997 RVA: 0x000C58AD File Offset: 0x000C3AAD
		internal void SetParticipatingTroopCount(int count)
		{
			this._participatingTroopCount = count;
		}

		// Token: 0x06002EDE RID: 11998 RVA: 0x000C58B8 File Offset: 0x000C3AB8
		internal void TrimRosterToAllocatedTroops(Dictionary<UniqueTroopDescriptor, MapEventParty> allocatedTroops)
		{
			if (this.HasTroopLimit)
			{
				List<UniqueTroopDescriptor> list = new List<UniqueTroopDescriptor>();
				foreach (FlattenedTroopRosterElement flattenedTroopRosterElement in this._roster)
				{
					if (!allocatedTroops.ContainsKey(flattenedTroopRosterElement.Descriptor))
					{
						list.Add(flattenedTroopRosterElement.Descriptor);
					}
				}
				foreach (UniqueTroopDescriptor descriptor in list)
				{
					this._roster.Remove(descriptor);
				}
			}
		}

		// Token: 0x06002EDF RID: 11999 RVA: 0x000C5970 File Offset: 0x000C3B70
		[LoadInitializationCallback]
		private void OnLoad(MetaData metaData, ObjectLoadData objectLoadData)
		{
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0", 0)))
			{
				this._routedInBattle = TroopRoster.CreateDummyTroopRoster();
				object fieldValueBySaveId = objectLoadData.GetFieldValueBySaveId(9);
				if (fieldValueBySaveId != null)
				{
					this._healthyManCountAtStart = (int)fieldValueBySaveId;
				}
			}
			if (MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.14.108208", 0)))
			{
				object propertyValueBySaveId = objectLoadData.GetPropertyValueBySaveId(7);
				object propertyValueBySaveId2 = objectLoadData.GetPropertyValueBySaveId(8);
				object propertyValueBySaveId3 = objectLoadData.GetPropertyValueBySaveId(9);
				if (propertyValueBySaveId != null)
				{
					this.GainedRenownExplained = new ExplainedNumber((float)propertyValueBySaveId, false, null);
				}
				if (propertyValueBySaveId2 != null)
				{
					this.GainedInfluenceExplained = new ExplainedNumber((float)propertyValueBySaveId2, false, null);
				}
				if (propertyValueBySaveId3 != null)
				{
					this.GainedMoraleExplained = new ExplainedNumber((float)propertyValueBySaveId3, false, null);
				}
			}
		}

		// Token: 0x06002EE0 RID: 12000 RVA: 0x000C5A3C File Offset: 0x000C3C3C
		public void Update()
		{
			if (this._roster == null)
			{
				this._roster = new FlattenedTroopRoster(this.Party.MemberRoster.TotalManCount);
			}
			else
			{
				this._roster.Clear();
			}
			foreach (TroopRosterElement troopRosterElement in this.Party.MemberRoster.GetTroopRoster())
			{
				if (troopRosterElement.Character.IsHero)
				{
					if (!this._woundedInBattle.Contains(troopRosterElement.Character) && !this._diedInBattle.Contains(troopRosterElement.Character))
					{
						this._roster.Add(troopRosterElement.Character, troopRosterElement.Character.HeroObject.IsWounded, troopRosterElement.Xp);
					}
				}
				else
				{
					this._roster.Add(troopRosterElement.Character, troopRosterElement.Number, troopRosterElement.WoundedNumber);
				}
			}
		}

		// Token: 0x06002EE1 RID: 12001 RVA: 0x000C5B48 File Offset: 0x000C3D48
		internal void ResetContributionToBattleToStrength()
		{
			this._contributionToBattle = (int)MathF.Sqrt(this.Party.GetCustomStrength(this.Party.Side, this.Party.MapEvent.SimulationContext));
		}

		// Token: 0x06002EE2 RID: 12002 RVA: 0x000C5B7C File Offset: 0x000C3D7C
		public void OnTroopKilled(UniqueTroopDescriptor troopSeed)
		{
			CharacterObject troop = this._roster[troopSeed].Troop;
			if (!troop.IsHero && this.Party.IsActive)
			{
				this.Party.MemberRoster.RemoveTroop(troop, 1, troopSeed, 0);
			}
			this._roster.OnTroopKilled(troopSeed);
			this.DiedInBattle.AddToCounts(this._roster[troopSeed].Troop, 1, false, 0, 0, true, -1);
		}

		// Token: 0x06002EE3 RID: 12003 RVA: 0x000C5BFC File Offset: 0x000C3DFC
		public void OnTroopWounded(UniqueTroopDescriptor troopSeed)
		{
			this.Party.MemberRoster.WoundTroop(this._roster[troopSeed].Troop, 1, troopSeed);
			this._roster.OnTroopWounded(troopSeed);
			this.WoundedInBattle.AddToCounts(this._roster[troopSeed].Troop, 1, false, 1, 0, true, -1);
		}

		// Token: 0x06002EE4 RID: 12004 RVA: 0x000C5C64 File Offset: 0x000C3E64
		public void OnTroopRouted(UniqueTroopDescriptor troopSeed)
		{
			if (!this._roster[troopSeed].Troop.IsHero)
			{
				this.Party.MemberRoster.AddToCounts(this._roster[troopSeed].Troop, -1, false, 0, 0, true, -1);
				this._roster.OnTroopRouted(troopSeed);
				this.RoutedInBattle.AddToCounts(this._roster[troopSeed].Troop, 1, false, 0, 0, true, -1);
				return;
			}
			if (!this._roster[troopSeed].Troop.HeroObject.IsWounded)
			{
				this.Party.MemberRoster.WoundTroop(this._roster[troopSeed].Troop, 1, troopSeed);
			}
		}

		// Token: 0x06002EE5 RID: 12005 RVA: 0x000C5D30 File Offset: 0x000C3F30
		public void OnShipSunk(Ship ship)
		{
			if (this.Party.IsMobile)
			{
				this.Party.MobileParty.RecentEventsMorale += Campaign.Current.Models.BattleRewardModel.GetSunkenShipMoraleEffect(this.Party, ship);
			}
		}

		// Token: 0x06002EE6 RID: 12006 RVA: 0x000C5D7C File Offset: 0x000C3F7C
		public void OnShipDamaged(Ship ship, SiegeEngineType siegeEngine, int damage)
		{
			if (this.Party.IsMobile)
			{
				this.Party.MobileParty.RecentEventsMorale += Campaign.Current.Models.BattleRewardModel.GetShipSiegeEngineHitMoraleEffect(ship, siegeEngine);
			}
			float num;
			ship.OnShipDamaged((float)damage, null, out num);
		}

		// Token: 0x06002EE7 RID: 12007 RVA: 0x000C5DD0 File Offset: 0x000C3FD0
		public void OnShipScoreHit(Ship ship, Ship struckShip, SiegeEngineType siegeEngine, int damage, bool isFinishingStrike)
		{
			float num = (float)damage / struckShip.MaxHitPoints;
			this._contributionToBattle += MathF.Ceiling(num * (float)struckShip.TotalCrewCapacity);
		}

		// Token: 0x06002EE8 RID: 12008 RVA: 0x000C5E04 File Offset: 0x000C4004
		public CharacterObject GetTroop(UniqueTroopDescriptor troopSeed)
		{
			return this._roster[troopSeed].Troop;
		}

		// Token: 0x06002EE9 RID: 12009 RVA: 0x000C5E28 File Offset: 0x000C4028
		public RosterTroopState GetTroopState(UniqueTroopDescriptor troopSeed)
		{
			return this._roster[troopSeed].State;
		}

		// Token: 0x06002EEA RID: 12010 RVA: 0x000C5E4C File Offset: 0x000C404C
		public void OnRoundEnd(MapEventSide partySide, BattleSideEnum roundWinner)
		{
			if (this.Party.IsMobile)
			{
				float num = Campaign.Current.Models.BattleRewardModel.CalculateMoraleChangeOnRoundVictory(this.Party, partySide, roundWinner);
				if (!num.ApproximatelyEqualsTo(0f, 1E-05f))
				{
					this.Party.MobileParty.RecentEventsMorale += num;
				}
			}
		}

		// Token: 0x06002EEB RID: 12011 RVA: 0x000C5EB0 File Offset: 0x000C40B0
		public void OnTroopScoreHit(UniqueTroopDescriptor attackerTroopDesc, CharacterObject attackedTroop, int damage, bool isFatal, bool isTeamKill, WeaponComponentData attackerWeapon, bool isSimulatedHit)
		{
			if (!isTeamKill)
			{
				CharacterObject troop = this._roster[attackerTroopDesc].Troop;
				ExplainedNumber xpFromHit = Campaign.Current.Models.CombatXpModel.GetXpFromHit(troop, null, attackedTroop, this.Party, damage, isFatal, isSimulatedHit ? CombatXpModel.MissionTypeEnum.SimulationBattle : CombatXpModel.MissionTypeEnum.Battle);
				if (!troop.IsHero)
				{
					if (xpFromHit.RoundedResultNumber > 0)
					{
						this._roster.OnTroopGainXp(attackerTroopDesc, xpFromHit.RoundedResultNumber);
					}
				}
				else
				{
					CampaignEventDispatcher.Instance.OnHeroCombatHit(troop, attackedTroop, this.Party, attackerWeapon, isFatal, xpFromHit.RoundedResultNumber);
				}
				this._contributionToBattle += xpFromHit.RoundedResultNumber;
			}
		}

		// Token: 0x06002EEC RID: 12012 RVA: 0x000C5F5A File Offset: 0x000C415A
		public void SetRenownInfluenceAndMoraleOnBattleEnd(ExplainedNumber renown, ExplainedNumber influence, ExplainedNumber morale)
		{
			this.GainedRenownExplained = renown;
			this.GainedInfluenceExplained = influence;
			this.GainedMoraleExplained = morale;
		}

		// Token: 0x06002EED RID: 12013 RVA: 0x000C5F74 File Offset: 0x000C4174
		internal void CommitXpGain()
		{
			if (this.Party.MobileParty != null)
			{
				int num = 0;
				Hero hero = this.Party.LeaderHero ?? this.Party.Owner;
				bool flag = hero != null && hero.IsAlive;
				Dictionary<CharacterObject, int> dictionary = new Dictionary<CharacterObject, int>();
				foreach (FlattenedTroopRosterElement troopRosterElement in this._roster)
				{
					if (!troopRosterElement.IsKilled && troopRosterElement.XpGained > 0)
					{
						CharacterObject troop = troopRosterElement.Troop;
						int num2 = MathF.Round(Campaign.Current.Models.PartyTrainingModel.CalculateXpGainFromBattles(troopRosterElement, this.Party).ResultNumber);
						int num3;
						if (!dictionary.TryGetValue(troop, out num3))
						{
							dictionary.Add(troop, num2);
						}
						else
						{
							dictionary[troop] = num3 + num2;
						}
					}
				}
				this._roster.ResetTroopXP();
				foreach (KeyValuePair<CharacterObject, int> keyValuePair in dictionary)
				{
					CharacterObject key = keyValuePair.Key;
					int value = keyValuePair.Value;
					int num4;
					MobilePartyHelper.CanTroopGainXp(this.Party, key, out num4);
					num4 = Math.Min(num4, value);
					int num5 = value - num4;
					if (num4 > 0)
					{
						int num6 = Campaign.Current.Models.PartyTrainingModel.GenerateSharedXp(key, num4, this.Party.MobileParty);
						if (num6 > 0)
						{
							num += num6;
							if (num5 > 0)
							{
								int num7 = Math.Min(num6, num5);
								num5 -= num7;
								num6 -= num7;
							}
							num4 -= num6;
						}
						if (!key.IsHero)
						{
							this.Party.MemberRoster.AddXpToTroop(key, num4);
						}
					}
					if (flag && num5 > 0)
					{
						SkillLevelingManager.OnBattleEnded(this.Party, key, num5);
					}
				}
				if (num > 0)
				{
					MobilePartyHelper.PartyAddSharedXp(this.Party.MobileParty, (float)num);
				}
			}
		}

		// Token: 0x06002EEE RID: 12014 RVA: 0x000C6188 File Offset: 0x000C4388
		internal void CommitRenownChanges()
		{
			if (this.GainedRenown > 0f)
			{
				Hero leaderHero = this.Party.LeaderHero;
				if (leaderHero != null)
				{
					GainRenownAction.Apply(leaderHero, this.GainedRenown, true);
				}
			}
		}

		// Token: 0x06002EEF RID: 12015 RVA: 0x000C61C0 File Offset: 0x000C43C0
		internal void CommitInfluenceChanges()
		{
			if (!this.GainedInfluence.ApproximatelyEqualsTo(0f, 1E-05f))
			{
				Hero leaderHero = this.Party.LeaderHero;
				if (leaderHero != null)
				{
					GainKingdomInfluenceAction.ApplyForBattle(leaderHero, this.GainedInfluence);
				}
			}
		}

		// Token: 0x06002EF0 RID: 12016 RVA: 0x000C6200 File Offset: 0x000C4400
		internal void CommitMoraleChanges()
		{
			if (!this.GainedMorale.ApproximatelyEqualsTo(0f, 1E-05f) && this.Party.MobileParty != null)
			{
				this.Party.MobileParty.RecentEventsMorale += this.GainedMorale;
			}
		}

		// Token: 0x06002EF1 RID: 12017 RVA: 0x000C6250 File Offset: 0x000C4450
		internal void CommitGoldChanges()
		{
			PartyBase party = this.Party;
			Hero leaderHero = party.LeaderHero;
			if (leaderHero != null)
			{
				if (this.PlunderedGold > 0)
				{
					if (leaderHero == Hero.MainHero)
					{
						MBTextManager.SetTextVariable("GOLD", this.PlunderedGold);
						MBInformationManager.AddQuickInformation(GameTexts.FindText("str_plunder_gain_message", null), 0, null, null, "");
					}
					GiveGoldAction.ApplyBetweenCharacters(null, leaderHero, this.PlunderedGold, true);
				}
				if (this.GoldLost > 0)
				{
					GiveGoldAction.ApplyBetweenCharacters(leaderHero, null, this.GoldLost, true);
				}
			}
			else if (party.IsMobile && party.MobileParty.IsPartyTradeActive)
			{
				party.MobileParty.PartyTradeGold += this.PlunderedGold - this.GoldLost;
			}
			this.PlunderedGold = 0;
			this.GoldLost = 0;
		}

		// Token: 0x04000D8B RID: 3467
		[SaveableField(2)]
		private FlattenedTroopRoster _roster;

		// Token: 0x04000D8C RID: 3468
		[SaveableField(3)]
		private int _contributionToBattle = 1;

		// Token: 0x04000D8D RID: 3469
		[SaveableField(14)]
		private int _healthyManCountAtStart = 1;

		// Token: 0x04000D8E RID: 3470
		[SaveableField(16)]
		private int _participatingTroopCount = -1;

		// Token: 0x04000D8F RID: 3471
		[SaveableField(7)]
		private TroopRoster _woundedInBattle = TroopRoster.CreateDummyTroopRoster();

		// Token: 0x04000D90 RID: 3472
		[SaveableField(8)]
		private TroopRoster _diedInBattle = TroopRoster.CreateDummyTroopRoster();

		// Token: 0x04000D91 RID: 3473
		[SaveableField(15)]
		private TroopRoster _routedInBattle = TroopRoster.CreateDummyTroopRoster();
	}
}
