using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000306 RID: 774
	public class MilitiaPartyComponent : PartyComponent
	{
		// Token: 0x06002D16 RID: 11542 RVA: 0x000BC0BB File Offset: 0x000BA2BB
		internal static void AutoGeneratedStaticCollectObjectsMilitiaPartyComponent(object o, List<object> collectedObjects)
		{
			((MilitiaPartyComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002D17 RID: 11543 RVA: 0x000BC0C9 File Offset: 0x000BA2C9
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Settlement);
		}

		// Token: 0x06002D18 RID: 11544 RVA: 0x000BC0DE File Offset: 0x000BA2DE
		internal static object AutoGeneratedGetMemberValueSettlement(object o)
		{
			return ((MilitiaPartyComponent)o).Settlement;
		}

		// Token: 0x17000B22 RID: 2850
		// (get) Token: 0x06002D19 RID: 11545 RVA: 0x000BC0EB File Offset: 0x000BA2EB
		// (set) Token: 0x06002D1A RID: 11546 RVA: 0x000BC0F3 File Offset: 0x000BA2F3
		[SaveableProperty(1)]
		public Settlement Settlement { get; private set; }

		// Token: 0x17000B23 RID: 2851
		// (get) Token: 0x06002D1B RID: 11547 RVA: 0x000BC0FC File Offset: 0x000BA2FC
		public override Hero PartyOwner
		{
			get
			{
				return this.Settlement.OwnerClan.Leader;
			}
		}

		// Token: 0x06002D1C RID: 11548 RVA: 0x000BC10E File Offset: 0x000BA30E
		public override Banner GetDefaultComponentBanner()
		{
			return this.Settlement.Banner;
		}

		// Token: 0x17000B24 RID: 2852
		// (get) Token: 0x06002D1D RID: 11549 RVA: 0x000BC11B File Offset: 0x000BA31B
		public override bool CanHaveNavalNavigationCapability
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000B25 RID: 2853
		// (get) Token: 0x06002D1E RID: 11550 RVA: 0x000BC120 File Offset: 0x000BA320
		public override TextObject Name
		{
			get
			{
				if (this._cachedName == null)
				{
					this._cachedName = GameTexts.FindText("str_militia_name", null);
					this._cachedName.SetTextVariable("SETTLEMENT_NAME", this.Settlement.Name);
				}
				return this._cachedName;
			}
		}

		// Token: 0x17000B26 RID: 2854
		// (get) Token: 0x06002D1F RID: 11551 RVA: 0x000BC16E File Offset: 0x000BA36E
		public override Settlement HomeSettlement
		{
			get
			{
				return this.Settlement;
			}
		}

		// Token: 0x06002D20 RID: 11552 RVA: 0x000BC178 File Offset: 0x000BA378
		public static MobileParty CreateMilitiaParty(string stringId, Settlement settlement)
		{
			MilitiaPartyComponent.InitializationArgs args = new MilitiaPartyComponent.InitializationArgs();
			MobileParty mobileParty = MobileParty.CreateParty("militias_of_" + stringId + "_aaa1", new MilitiaPartyComponent(settlement, args));
			mobileParty.DesiredAiNavigationType = MobileParty.NavigationType.None;
			EnterSettlementAction.ApplyForParty(mobileParty, settlement);
			return mobileParty;
		}

		// Token: 0x06002D21 RID: 11553 RVA: 0x000BC1B5 File Offset: 0x000BA3B5
		public static void ConvertPartyToMilitiaParty(MobileParty mobileParty, Settlement settlement)
		{
			mobileParty.SetPartyComponent(new MilitiaPartyComponent(settlement, null), true);
		}

		// Token: 0x06002D22 RID: 11554 RVA: 0x000BC1C8 File Offset: 0x000BA3C8
		protected override void OnMobilePartySetOnCreation()
		{
			base.MobileParty.Party.SetVisualAsDirty();
			base.MobileParty.Ai.DisableAi();
			base.MobileParty.Aggressiveness = 0f;
			if (this._initializationArgs != null)
			{
				this._initializationArgs.InitializeMilitiaPartyProperties(base.MobileParty, this.Settlement);
				this._initializationArgs = null;
			}
		}

		// Token: 0x06002D23 RID: 11555 RVA: 0x000BC22B File Offset: 0x000BA42B
		protected MilitiaPartyComponent(Settlement settlement, MilitiaPartyComponent.InitializationArgs args)
		{
			this.Settlement = settlement;
			this._initializationArgs = args;
		}

		// Token: 0x06002D24 RID: 11556 RVA: 0x000BC241 File Offset: 0x000BA441
		protected override void OnInitialize()
		{
			this.Settlement.MilitiaPartyComponent = this;
		}

		// Token: 0x06002D25 RID: 11557 RVA: 0x000BC24F File Offset: 0x000BA44F
		protected override void OnFinalize()
		{
			this.Settlement.MilitiaPartyComponent = null;
		}

		// Token: 0x06002D26 RID: 11558 RVA: 0x000BC25D File Offset: 0x000BA45D
		public override void ClearCachedName()
		{
			this._cachedName = null;
		}

		// Token: 0x04000D0B RID: 3339
		private MilitiaPartyComponent.InitializationArgs _initializationArgs;

		// Token: 0x04000D0D RID: 3341
		[CachedData]
		private TextObject _cachedName;

		// Token: 0x020006AE RID: 1710
		protected class InitializationArgs
		{
			// Token: 0x06005253 RID: 21075 RVA: 0x00185BBC File Offset: 0x00183DBC
			public void InitializeMilitiaPartyProperties(MobileParty mobileParty, Settlement settlement)
			{
				PartyTemplateObject militiaPartyTemplate = settlement.Culture.MilitiaPartyTemplate;
				mobileParty.InitializeMobilePartyAtPosition(militiaPartyTemplate, settlement.GatePosition);
			}
		}
	}
}
