using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Naval;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace TaleWorlds.CampaignSystem.Party
{
	// Token: 0x020002EF RID: 751
	public class MobilePartyAi
	{
		// Token: 0x06002AC3 RID: 10947 RVA: 0x000B0EA1 File Offset: 0x000AF0A1
		internal static void AutoGeneratedStaticCollectObjectsMobilePartyAi(object o, List<object> collectedObjects)
		{
			((MobilePartyAi)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002AC4 RID: 10948 RVA: 0x000B0EB0 File Offset: 0x000AF0B0
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			CampaignVec2.AutoGeneratedStaticCollectObjectsCampaignVec2(this.BehaviorTarget, collectedObjects);
			collectedObjects.Add(this._fleeingData);
			collectedObjects.Add(this._mobileParty);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this._initiativeRestoreTime, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this._nextAiCheckTime, collectedObjects);
			collectedObjects.Add(this._aiBehaviorInteractable);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this._enableAgainAtHour, collectedObjects);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.DoNotAttackMainPartyUntil, collectedObjects);
		}

		// Token: 0x06002AC5 RID: 10949 RVA: 0x000B0F36 File Offset: 0x000AF136
		internal static object AutoGeneratedGetMemberValue_enableAgainAtHour(object o)
		{
			return ((MobilePartyAi)o)._enableAgainAtHour;
		}

		// Token: 0x06002AC6 RID: 10950 RVA: 0x000B0F48 File Offset: 0x000AF148
		internal static object AutoGeneratedGetMemberValueRethinkAtNextHourlyTick(object o)
		{
			return ((MobilePartyAi)o).RethinkAtNextHourlyTick;
		}

		// Token: 0x06002AC7 RID: 10951 RVA: 0x000B0F5A File Offset: 0x000AF15A
		internal static object AutoGeneratedGetMemberValueDoNotMakeNewDecisions(object o)
		{
			return ((MobilePartyAi)o).DoNotMakeNewDecisions;
		}

		// Token: 0x06002AC8 RID: 10952 RVA: 0x000B0F6C File Offset: 0x000AF16C
		internal static object AutoGeneratedGetMemberValueIsAlerted(object o)
		{
			return ((MobilePartyAi)o).IsAlerted;
		}

		// Token: 0x06002AC9 RID: 10953 RVA: 0x000B0F7E File Offset: 0x000AF17E
		internal static object AutoGeneratedGetMemberValueDoNotAttackMainPartyUntil(object o)
		{
			return ((MobilePartyAi)o).DoNotAttackMainPartyUntil;
		}

		// Token: 0x06002ACA RID: 10954 RVA: 0x000B0F90 File Offset: 0x000AF190
		internal static object AutoGeneratedGetMemberValueHourCounter(object o)
		{
			return ((MobilePartyAi)o).HourCounter;
		}

		// Token: 0x06002ACB RID: 10955 RVA: 0x000B0FA2 File Offset: 0x000AF1A2
		internal static object AutoGeneratedGetMemberValueBehaviorTarget(object o)
		{
			return ((MobilePartyAi)o).BehaviorTarget;
		}

		// Token: 0x06002ACC RID: 10956 RVA: 0x000B0FB4 File Offset: 0x000AF1B4
		internal static object AutoGeneratedGetMemberValueDefaultBehaviorNeedsUpdate(object o)
		{
			return ((MobilePartyAi)o).DefaultBehaviorNeedsUpdate;
		}

		// Token: 0x06002ACD RID: 10957 RVA: 0x000B0FC6 File Offset: 0x000AF1C6
		internal static object AutoGeneratedGetMemberValue_fleeingData(object o)
		{
			return ((MobilePartyAi)o)._fleeingData;
		}

		// Token: 0x06002ACE RID: 10958 RVA: 0x000B0FD3 File Offset: 0x000AF1D3
		internal static object AutoGeneratedGetMemberValue_isDisabled(object o)
		{
			return ((MobilePartyAi)o)._isDisabled;
		}

		// Token: 0x06002ACF RID: 10959 RVA: 0x000B0FE5 File Offset: 0x000AF1E5
		internal static object AutoGeneratedGetMemberValue_mobileParty(object o)
		{
			return ((MobilePartyAi)o)._mobileParty;
		}

		// Token: 0x06002AD0 RID: 10960 RVA: 0x000B0FF2 File Offset: 0x000AF1F2
		internal static object AutoGeneratedGetMemberValue_attackInitiative(object o)
		{
			return ((MobilePartyAi)o)._attackInitiative;
		}

		// Token: 0x06002AD1 RID: 10961 RVA: 0x000B1004 File Offset: 0x000AF204
		internal static object AutoGeneratedGetMemberValue_avoidInitiative(object o)
		{
			return ((MobilePartyAi)o)._avoidInitiative;
		}

		// Token: 0x06002AD2 RID: 10962 RVA: 0x000B1016 File Offset: 0x000AF216
		internal static object AutoGeneratedGetMemberValue_initiativeRestoreTime(object o)
		{
			return ((MobilePartyAi)o)._initiativeRestoreTime;
		}

		// Token: 0x06002AD3 RID: 10963 RVA: 0x000B1028 File Offset: 0x000AF228
		internal static object AutoGeneratedGetMemberValue_nextAiCheckTime(object o)
		{
			return ((MobilePartyAi)o)._nextAiCheckTime;
		}

		// Token: 0x06002AD4 RID: 10964 RVA: 0x000B103A File Offset: 0x000AF23A
		internal static object AutoGeneratedGetMemberValue_aiBehaviorInteractable(object o)
		{
			return ((MobilePartyAi)o)._aiBehaviorInteractable;
		}

		// Token: 0x17000A8F RID: 2703
		// (get) Token: 0x06002AD5 RID: 10965 RVA: 0x000B1047 File Offset: 0x000AF247
		// (set) Token: 0x06002AD6 RID: 10966 RVA: 0x000B104F File Offset: 0x000AF24F
		public bool IsDisabled
		{
			get
			{
				return this._isDisabled;
			}
			private set
			{
				this._isDisabled = value;
			}
		}

		// Token: 0x17000A90 RID: 2704
		// (get) Token: 0x06002AD7 RID: 10967 RVA: 0x000B1058 File Offset: 0x000AF258
		// (set) Token: 0x06002AD8 RID: 10968 RVA: 0x000B1060 File Offset: 0x000AF260
		[SaveableProperty(3)]
		private CampaignTime _enableAgainAtHour { get; set; }

		// Token: 0x17000A91 RID: 2705
		// (get) Token: 0x06002AD9 RID: 10969 RVA: 0x000B1069 File Offset: 0x000AF269
		// (set) Token: 0x06002ADA RID: 10970 RVA: 0x000B1071 File Offset: 0x000AF271
		[SaveableProperty(10)]
		public bool RethinkAtNextHourlyTick { get; set; }

		// Token: 0x17000A92 RID: 2706
		// (get) Token: 0x06002ADB RID: 10971 RVA: 0x000B107A File Offset: 0x000AF27A
		// (set) Token: 0x06002ADC RID: 10972 RVA: 0x000B1082 File Offset: 0x000AF282
		[SaveableProperty(11)]
		public bool DoNotMakeNewDecisions { get; private set; }

		// Token: 0x17000A93 RID: 2707
		// (get) Token: 0x06002ADD RID: 10973 RVA: 0x000B108B File Offset: 0x000AF28B
		// (set) Token: 0x06002ADE RID: 10974 RVA: 0x000B1093 File Offset: 0x000AF293
		[SaveableProperty(17)]
		public bool IsAlerted { get; private set; }

		// Token: 0x17000A94 RID: 2708
		// (get) Token: 0x06002ADF RID: 10975 RVA: 0x000B109C File Offset: 0x000AF29C
		// (set) Token: 0x06002AE0 RID: 10976 RVA: 0x000B10A4 File Offset: 0x000AF2A4
		[SaveableProperty(31)]
		public CampaignTime DoNotAttackMainPartyUntil { get; internal set; }

		// Token: 0x17000A95 RID: 2709
		// (get) Token: 0x06002AE1 RID: 10977 RVA: 0x000B10AD File Offset: 0x000AF2AD
		public float AvoidInitiative
		{
			get
			{
				if (!this._initiativeRestoreTime.IsPast)
				{
					return this._avoidInitiative;
				}
				return 1f;
			}
		}

		// Token: 0x17000A96 RID: 2710
		// (get) Token: 0x06002AE2 RID: 10978 RVA: 0x000B10C8 File Offset: 0x000AF2C8
		public float AttackInitiative
		{
			get
			{
				if (!this._initiativeRestoreTime.IsPast)
				{
					return this._attackInitiative;
				}
				return 1f;
			}
		}

		// Token: 0x17000A97 RID: 2711
		// (get) Token: 0x06002AE3 RID: 10979 RVA: 0x000B10E3 File Offset: 0x000AF2E3
		// (set) Token: 0x06002AE4 RID: 10980 RVA: 0x000B10EB File Offset: 0x000AF2EB
		public PartyBase AiBehaviorPartyBase { get; private set; }

		// Token: 0x17000A98 RID: 2712
		// (get) Token: 0x06002AE5 RID: 10981 RVA: 0x000B10F4 File Offset: 0x000AF2F4
		// (set) Token: 0x06002AE6 RID: 10982 RVA: 0x000B10FC File Offset: 0x000AF2FC
		public IInteractablePoint AiBehaviorInteractable
		{
			get
			{
				return this._aiBehaviorInteractable;
			}
			set
			{
				if (this._aiBehaviorInteractable != value)
				{
					this._aiBehaviorInteractable = value;
					this.AiBehaviorPartyBase = null;
					if (this._aiBehaviorInteractable != null)
					{
						PartyBase aiBehaviorPartyBase;
						if ((aiBehaviorPartyBase = (this._aiBehaviorInteractable as PartyBase)) != null)
						{
							this.AiBehaviorPartyBase = aiBehaviorPartyBase;
							return;
						}
					}
					else
					{
						this.AiBehaviorPartyBase = null;
					}
				}
			}
		}

		// Token: 0x06002AE7 RID: 10983 RVA: 0x000B1148 File Offset: 0x000AF348
		internal MobilePartyAi(MobileParty mobileParty)
		{
			this._mobileParty = mobileParty;
			this.RethinkAtNextHourlyTick = false;
			this.HourCounter = MBRandom.RandomInt(100);
			this._fleeingData = new MobilePartyAi.FleeingData();
		}

		// Token: 0x06002AE8 RID: 10984 RVA: 0x000B1198 File Offset: 0x000AF398
		internal void PreAfterLoad()
		{
			this.CacheAiBehaviorPartyBase();
			if (MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0", 0)) && this._mobileParty.ShortTermBehavior == AiBehavior.FleeToGate)
			{
				CampaignVec2 campaignVec = CampaignVec2.Normalized(this._mobileParty.ShortTermTargetParty.Position - this._mobileParty.Position);
				Settlement settlement;
				CampaignVec2 bestTargetPoint;
				AiBehavior newAiBehavior;
				this.GetBehaviorForNearbySettlementToFlee(this._mobileParty.ShortTermTargetParty, campaignVec.ToVec2(), out settlement, out bestTargetPoint, out newAiBehavior);
				this.SetAiBehavior(newAiBehavior, (settlement != null) ? settlement.Party : null, bestTargetPoint);
			}
		}

		// Token: 0x06002AE9 RID: 10985 RVA: 0x000B1230 File Offset: 0x000AF430
		public void CacheAiBehaviorPartyBase()
		{
			PartyBase aiBehaviorPartyBase;
			if (this.AiBehaviorInteractable != null && (aiBehaviorPartyBase = (this.AiBehaviorInteractable as PartyBase)) != null)
			{
				this.AiBehaviorPartyBase = aiBehaviorPartyBase;
			}
		}

		// Token: 0x06002AEA RID: 10986 RVA: 0x000B125C File Offset: 0x000AF45C
		internal void Tick(float dt)
		{
			if (this.DefaultBehaviorNeedsUpdate)
			{
				this._nextAiCheckTime = CampaignTime.Now;
				this.DefaultBehaviorNeedsUpdate = false;
			}
			if (!this._nextAiCheckTime.IsFuture)
			{
				this.TickInternal();
				float num = Campaign.Current.Models.MobilePartyAIModel.AiCheckInterval * (0.6f + 0.1f * MBRandom.RandomFloat);
				num *= ((this._mobileParty.ShortTermTargetParty == MobileParty.MainParty && this._mobileParty.ShortTermBehavior == AiBehavior.EngageParty) ? 0.5f : 1f);
				if (this._mobileParty.IsFleeing())
				{
					num *= ((this._mobileParty.ShortTermTargetParty == MobileParty.MainParty) ? 0.5f : 0.75f);
					num *= (this._mobileParty.IsBandit ? 10f : 1f);
					num *= ((!this._mobileParty.IsBandit && this._fleeingData.CcwFleeDirectionIsBlocked && this._fleeingData.CwFleeDirectionIsBlocked) ? 15f : 1f);
				}
				num *= ((this._mobileParty.SiegeEvent != null) ? 2f : 1f);
				long valueInSeconds = (long)(num * (float)CampaignTime.MinutesInHour * (float)CampaignTime.SecondsInMinute);
				this._nextAiCheckTime = CampaignTime.Now + CampaignTime.Seconds(valueInSeconds);
			}
		}

		// Token: 0x06002AEB RID: 10987 RVA: 0x000B13B4 File Offset: 0x000AF5B4
		[LateLoadInitializationCallback]
		private void OnLateLoad(MetaData metaData, ObjectLoadData objectLoadData)
		{
			if (MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.0", 0))
			{
				object memberValueBySaveId = objectLoadData.GetMemberValueBySaveId(30);
				if (memberValueBySaveId != null)
				{
					MobileParty mobileParty;
					Settlement settlement;
					if ((mobileParty = (memberValueBySaveId as MobileParty)) != null)
					{
						this.AiBehaviorInteractable = mobileParty.Party;
					}
					else if ((settlement = (memberValueBySaveId as Settlement)) != null)
					{
						this.AiBehaviorInteractable = settlement.Party;
					}
				}
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0", 0)))
			{
				object memberValueBySaveId2 = objectLoadData.GetMemberValueBySaveId(20);
				int numberOfRecentFleeingFromAParty = 0;
				if (memberValueBySaveId2 != null)
				{
					numberOfRecentFleeingFromAParty = (int)memberValueBySaveId2;
				}
				object memberValueBySaveId3 = objectLoadData.GetMemberValueBySaveId(21);
				AiBehavior defaultBehavior = AiBehavior.Hold;
				if (memberValueBySaveId3 != null)
				{
					defaultBehavior = (AiBehavior)memberValueBySaveId3;
				}
				object memberValueBySaveId4 = objectLoadData.GetMemberValueBySaveId(22);
				bool aiPathMode = false;
				if (memberValueBySaveId4 != null)
				{
					aiPathMode = (bool)memberValueBySaveId4;
				}
				object memberValueBySaveId5 = objectLoadData.GetMemberValueBySaveId(24);
				MoveModeType partyMoveMode = MoveModeType.Hold;
				if (memberValueBySaveId5 != null)
				{
					partyMoveMode = (MoveModeType)memberValueBySaveId5;
				}
				object memberValueBySaveId6 = objectLoadData.GetMemberValueBySaveId(25);
				Vec2 formationPosition = Vec2.Zero;
				if (memberValueBySaveId6 != null)
				{
					formationPosition = (Vec2)memberValueBySaveId6;
				}
				object memberValueBySaveId7 = objectLoadData.GetMemberValueBySaveId(26);
				MobileParty moveTargetParty = null;
				if (memberValueBySaveId7 != null)
				{
					moveTargetParty = (MobileParty)memberValueBySaveId7;
				}
				object memberValueBySaveId8 = objectLoadData.GetMemberValueBySaveId(27);
				Vec2 nextTargetPosition = Vec2.Zero;
				if (memberValueBySaveId8 != null)
				{
					nextTargetPosition = (Vec2)memberValueBySaveId8;
				}
				object memberValueBySaveId9 = objectLoadData.GetMemberValueBySaveId(28);
				Vec2 moveTargetPoint = Vec2.Zero;
				if (memberValueBySaveId9 != null)
				{
					moveTargetPoint = (Vec2)memberValueBySaveId9;
				}
				object memberValueBySaveId10 = objectLoadData.GetMemberValueBySaveId(29);
				Vec2 aiPathLastPosition = Vec2.Zero;
				if (memberValueBySaveId10 != null)
				{
					aiPathLastPosition = (Vec2)memberValueBySaveId10;
				}
				this._mobileParty.InitializePartyForOldSave(numberOfRecentFleeingFromAParty, defaultBehavior, aiPathMode, partyMoveMode, formationPosition, moveTargetParty, nextTargetPosition, moveTargetPoint, aiPathLastPosition);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0", 0)))
			{
				object memberValueBySaveId11 = objectLoadData.GetMemberValueBySaveId(12);
				Vec2 pos = Vec2.Zero;
				if (memberValueBySaveId11 != null)
				{
					pos = (Vec2)memberValueBySaveId11;
				}
				this.BehaviorTarget = new CampaignVec2(pos, true);
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0", 0)) && this._fleeingData == null)
			{
				this._fleeingData = new MobilePartyAi.FleeingData();
			}
		}

		// Token: 0x06002AEC RID: 10988 RVA: 0x000B15D4 File Offset: 0x000AF7D4
		private void TickInternal()
		{
			if (this._mobileParty.MapEvent != null)
			{
				return;
			}
			if (!this._mobileParty.IsActive)
			{
				return;
			}
			if (this._mobileParty == MobileParty.MainParty && MobileParty.MainParty.DefaultBehavior == AiBehavior.EngageParty && !MobileParty.MainParty.TargetParty.IsVisible)
			{
				MobileParty.MainParty.SetMoveModeHold();
			}
			if (this.IsDisabled)
			{
				if (this.EnableAgainAtHourIsPast())
				{
					this.EnableAi();
				}
				return;
			}
			if (this._mobileParty.Army != null && this._mobileParty.Army.LeaderParty.AttachedParties.Contains(this._mobileParty))
			{
				return;
			}
			AiBehavior newAiBehavior;
			IInteractablePoint interactablePoint;
			CampaignVec2 bestTargetPoint;
			this.GetBehaviors(out newAiBehavior, out interactablePoint, out bestTargetPoint);
			this.SetAiBehavior(newAiBehavior, interactablePoint, bestTargetPoint);
		}

		// Token: 0x06002AED RID: 10989 RVA: 0x000B1690 File Offset: 0x000AF890
		private void GetBestMoveToNearestLandBehavior(out AiBehavior shortTermBehavior, out CampaignVec2 shortTermTargetPoint, out Settlement shortTermTargetSettlement)
		{
			shortTermTargetSettlement = null;
			if (this._mobileParty.HasLandNavigationCapability)
			{
				shortTermBehavior = AiBehavior.GoToPoint;
				int[] invalidTerrainTypesForNavigationType = Campaign.Current.Models.PartyNavigationModel.GetInvalidTerrainTypesForNavigationType(MobileParty.NavigationType.All);
				shortTermTargetPoint = Campaign.Current.MapSceneWrapper.GetNearestFaceCenterForPositionWithPath(this._mobileParty.CurrentNavigationFace, true, Campaign.MapDiagonal / 2f, invalidTerrainTypesForNavigationType);
				return;
			}
			shortTermBehavior = AiBehavior.GoToSettlement;
			shortTermTargetPoint = this._mobileParty.TargetSettlement.PortPosition;
			shortTermTargetSettlement = this._mobileParty.TargetSettlement;
		}

		// Token: 0x06002AEE RID: 10990 RVA: 0x000B171B File Offset: 0x000AF91B
		public void CheckPartyNeedsUpdate()
		{
			if (this.DefaultBehaviorNeedsUpdate)
			{
				this.Tick(0f);
				EncounterManager.HandleEncounterForMobileParty(this._mobileParty, 0f);
			}
		}

		// Token: 0x06002AEF RID: 10991 RVA: 0x000B1740 File Offset: 0x000AF940
		internal void GetBehaviors(out AiBehavior bestAiBehavior, out IInteractablePoint behaviorObject, out CampaignVec2 bestTargetPoint)
		{
			bestAiBehavior = this._mobileParty.DefaultBehavior;
			MobileParty mobileParty = this._mobileParty.TargetParty ?? this._mobileParty.ShortTermTargetParty;
			bestTargetPoint = this._mobileParty.TargetPosition;
			Vec2 avarageEnemyVec = new Vec2(0f, 0f);
			if (Campaign.Current.GameStarted && Campaign.Current.Models.MobilePartyAIModel.ShouldPartyCheckInitiativeBehavior(this._mobileParty))
			{
				AiBehavior aiBehavior;
				MobileParty mobileParty2;
				float num;
				Campaign.Current.Models.MobilePartyAIModel.GetBestInitiativeBehavior(this._mobileParty, out aiBehavior, out mobileParty2, out num, out avarageEnemyVec);
				if (!this.DoNotMakeNewDecisions || (mobileParty2 != null && this._mobileParty.TargetSettlement != null && ((mobileParty2.MapEvent != null && mobileParty2.MapEvent.MapEventSettlement == this._mobileParty.TargetSettlement) || mobileParty2.BesiegedSettlement == this._mobileParty.TargetSettlement)))
				{
					if (num > 1f && (this._mobileParty.DefaultBehavior != AiBehavior.DefendSettlement || mobileParty2 != this._mobileParty.TargetSettlement.LastAttackerParty))
					{
						bestAiBehavior = aiBehavior;
						mobileParty = mobileParty2;
						if (aiBehavior == AiBehavior.EngageParty && mobileParty2.IsCurrentlyAtSea != this._mobileParty.IsCurrentlyAtSea && !this._mobileParty.IsTransitionInProgress)
						{
							this._mobileParty.StartTransitionNextFrameToExitFromPort = true;
						}
					}
					else if (MobileParty.IsFleeBehavior(aiBehavior) && MobileParty.IsFleeBehavior(this._mobileParty.ShortTermBehavior))
					{
						float num2 = this._mobileParty.AiBehaviorTarget.DistanceSquared(this._mobileParty.Position);
						float lastCalculatedSpeed = this._mobileParty._lastCalculatedSpeed;
						if (num2 >= lastCalculatedSpeed * lastCalculatedSpeed * Campaign.Current.Models.MobilePartyAIModel.AiCheckInterval * Campaign.Current.Models.MobilePartyAIModel.AiCheckInterval)
						{
							bestAiBehavior = this._mobileParty.ShortTermBehavior;
							if (this._mobileParty.ShortTermBehavior == AiBehavior.FleeToGate)
							{
								mobileParty = (this._mobileParty.TargetParty ?? mobileParty2);
							}
							else
							{
								mobileParty = (this._mobileParty.ShortTermTargetParty ?? mobileParty2);
							}
						}
					}
					if (MobileParty.IsFleeBehavior(this._mobileParty.ShortTermBehavior) && !MobileParty.IsFleeBehavior(bestAiBehavior))
					{
						this._fleeingData.Clear();
					}
					if (aiBehavior == AiBehavior.DefendSettlement && mobileParty2.DefaultBehavior == AiBehavior.DefendSettlement && mobileParty2.MapEvent != null)
					{
						bestAiBehavior = AiBehavior.EngageParty;
						mobileParty = mobileParty2.ShortTermTargetParty;
					}
				}
			}
			this.IsAlerted = false;
			AiBehavior aiBehavior2 = bestAiBehavior;
			CampaignVec2 campaignVec = bestTargetPoint;
			Settlement targetSettlement = this._mobileParty.TargetSettlement;
			MobileParty mobileParty3 = mobileParty;
			switch (bestAiBehavior)
			{
			case AiBehavior.GoToSettlement:
				if (this._mobileParty.CurrentSettlement == this._mobileParty.TargetSettlement)
				{
					this.GetInSettlementBehavior(ref aiBehavior2, ref mobileParty3);
					if (mobileParty3 != null)
					{
						campaignVec = mobileParty3.Position;
					}
					else
					{
						campaignVec = this._mobileParty.Position;
					}
				}
				break;
			case AiBehavior.BesiegeSettlement:
				if (!this._mobileParty.IsMainParty)
				{
					this.GetBesiegeBehavior(out aiBehavior2, out campaignVec, out targetSettlement);
				}
				break;
			case AiBehavior.EngageParty:
				campaignVec = mobileParty3.Position;
				if (mobileParty3.SiegeEvent != null && this._mobileParty.IsCurrentlyAtSea && this._mobileParty.IsTargetingPort)
				{
					campaignVec = targetSettlement.PortPosition;
					aiBehavior2 = AiBehavior.GoToSettlement;
					this._mobileParty.SetShortTermBehavior(AiBehavior.GoToSettlement, mobileParty3.SiegeEvent.BesiegedSettlement.Party);
				}
				else
				{
					this._mobileParty.SetShortTermBehavior(AiBehavior.EngageParty, mobileParty3.Party);
				}
				break;
			case AiBehavior.GoAroundParty:
				mobileParty3 = this._mobileParty.TargetParty;
				this.GetGoAroundPartyBehavior(this._mobileParty.TargetParty, out aiBehavior2, out campaignVec);
				break;
			case AiBehavior.FleeToPoint:
			case AiBehavior.FleeToGate:
			case AiBehavior.FleeToParty:
				this.IsAlerted = true;
				this.GetFleeBehavior(out aiBehavior2, out campaignVec, ref targetSettlement, mobileParty, avarageEnemyVec);
				break;
			case AiBehavior.PatrolAroundPoint:
			{
				bool forceUpdate = this._mobileParty.ShortTermBehavior == AiBehavior.FleeToPoint || (!this._mobileParty.IsTransitionInProgress && campaignVec.IsOnLand == this._mobileParty.IsCurrentlyAtSea) || this._mobileParty.TargetPosition == this._mobileParty.MoveTargetPoint;
				if (campaignVec.IsOnLand)
				{
					this.GetLandPatrolBehavior(out aiBehavior2, out campaignVec, this._mobileParty.TargetPosition, forceUpdate);
				}
				else
				{
					this.GetNavalPatrolBehavior(out aiBehavior2, out campaignVec, this._mobileParty.TargetPosition, forceUpdate);
				}
				mobileParty3 = null;
				this._mobileParty.SetShortTermBehavior(AiBehavior.GoToPoint, null);
				break;
			}
			case AiBehavior.EscortParty:
				this.GetFollowBehavior(ref aiBehavior2, ref targetSettlement, mobileParty, out campaignVec);
				break;
			case AiBehavior.DefendSettlement:
			{
				Settlement targetSettlement2 = this._mobileParty.TargetSettlement;
				if (targetSettlement2 == null)
				{
					targetSettlement2 = mobileParty.TargetSettlement;
				}
				if (targetSettlement2.LastAttackerParty != null && targetSettlement2.LastAttackerParty.IsActive)
				{
					this.GetDefendSettlementBehavior(targetSettlement2, out aiBehavior2, out campaignVec, out mobileParty3);
				}
				else
				{
					aiBehavior2 = AiBehavior.GoToPoint;
					campaignVec = ((this._mobileParty.IsCurrentlyAtSea && targetSettlement2.HasPort) ? targetSettlement2.PortPosition : targetSettlement2.GatePosition);
				}
				break;
			}
			case AiBehavior.MoveToNearestLandOrPort:
				this.GetBestMoveToNearestLandBehavior(out aiBehavior2, out campaignVec, out targetSettlement);
				break;
			}
			bestAiBehavior = aiBehavior2;
			bestTargetPoint = campaignVec;
			PathFaceRecord face = bestTargetPoint.Face;
			if (mobileParty3 != null)
			{
				mobileParty = mobileParty3;
			}
			if (bestAiBehavior == AiBehavior.GoToSettlement || bestAiBehavior == AiBehavior.RaidSettlement || bestAiBehavior == AiBehavior.AssaultSettlement || bestAiBehavior == AiBehavior.BesiegeSettlement || (bestAiBehavior == AiBehavior.DefendSettlement && mobileParty == null))
			{
				behaviorObject = ((targetSettlement != null) ? targetSettlement.Party : this._mobileParty.TargetSettlement.Party);
				return;
			}
			if (bestAiBehavior == AiBehavior.EngageParty || bestAiBehavior == AiBehavior.FleeToParty || bestAiBehavior == AiBehavior.GoAroundParty || bestAiBehavior == AiBehavior.EscortParty || bestAiBehavior == AiBehavior.JoinParty || bestAiBehavior == AiBehavior.FleeToPoint || (bestAiBehavior == AiBehavior.DefendSettlement && mobileParty != null))
			{
				behaviorObject = ((mobileParty != null) ? mobileParty.Party : null);
				return;
			}
			if (bestAiBehavior == AiBehavior.FleeToGate)
			{
				behaviorObject = (((targetSettlement != null) ? targetSettlement.Party : null) ?? this._mobileParty.ShortTermTargetSettlement.Party);
				return;
			}
			if (bestAiBehavior == AiBehavior.MoveToNearestLandOrPort)
			{
				behaviorObject = this._mobileParty.Ai.AiBehaviorInteractable;
				return;
			}
			if (bestAiBehavior == AiBehavior.Hold || bestAiBehavior == AiBehavior.None)
			{
				behaviorObject = null;
				return;
			}
			if (bestAiBehavior == AiBehavior.GoToPoint)
			{
				IInteractablePoint interactablePoint;
				if (mobileParty3 == null)
				{
					interactablePoint = this.AiBehaviorInteractable;
				}
				else
				{
					IInteractablePoint party = mobileParty3.Party;
					interactablePoint = party;
				}
				behaviorObject = interactablePoint;
				return;
			}
			if (bestAiBehavior == AiBehavior.DoOperation)
			{
				Debug.FailedAssert("DoOperation", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\MobilePartyAi.cs", "GetBehaviors", 643);
				behaviorObject = null;
				return;
			}
			behaviorObject = this.AiBehaviorInteractable;
		}

		// Token: 0x06002AF0 RID: 10992 RVA: 0x000B1D98 File Offset: 0x000AFF98
		private void GetInSettlementBehavior(ref AiBehavior shortTermBehavior, ref MobileParty shortTermTargetParty)
		{
			shortTermTargetParty = null;
			if (this._mobileParty.MapEvent != null)
			{
				MobileParty mobileParty = this._mobileParty.MapEvent.AttackerSide.LeaderParty.MobileParty;
				if (FactionManager.IsAtWarAgainstFaction(mobileParty.MapFaction, this._mobileParty.MapFaction))
				{
					shortTermBehavior = AiBehavior.EngageParty;
					shortTermTargetParty = mobileParty;
				}
			}
		}

		// Token: 0x06002AF1 RID: 10993 RVA: 0x000B1DF0 File Offset: 0x000AFFF0
		private void GetFollowBehavior(ref AiBehavior shortTermBehavior, ref Settlement shortTermTargetSettlement, MobileParty followedParty, out CampaignVec2 shortTermTargetPoint)
		{
			shortTermBehavior = AiBehavior.EscortParty;
			if (followedParty == null || !followedParty.IsActive)
			{
				shortTermBehavior = AiBehavior.Hold;
				shortTermTargetPoint = this._mobileParty.Position;
				return;
			}
			if (followedParty.CurrentSettlement != null)
			{
				shortTermBehavior = AiBehavior.GoToSettlement;
				shortTermTargetSettlement = followedParty.CurrentSettlement;
				shortTermTargetPoint = (this._mobileParty.IsTargetingPort ? followedParty.CurrentSettlement.PortPosition : followedParty.CurrentSettlement.GatePosition);
				return;
			}
			shortTermTargetPoint = followedParty.Position;
			if (followedParty.IsCurrentlyAtSea && !this._mobileParty.HasNavalNavigationCapability)
			{
				CampaignVec2 moveTargetPoint = this._mobileParty.MoveTargetPoint;
				if (DistanceHelper.FindClosestDistanceFromMobilePartyToPoint(this._mobileParty, moveTargetPoint, this._mobileParty.NavigationCapability) > Campaign.MapDiagonal)
				{
					shortTermBehavior = AiBehavior.Hold;
					shortTermTargetPoint = this._mobileParty.Position;
					return;
				}
				shortTermBehavior = AiBehavior.GoToPoint;
				shortTermTargetPoint = this._mobileParty.MoveTargetPoint;
				return;
			}
			else
			{
				shortTermBehavior = AiBehavior.GoToPoint;
				if (this._mobileParty.IsTransitionInProgress && ((this._mobileParty.IsCurrentlyAtSea && !followedParty.IsCurrentlyAtSea && this._mobileParty.HasLandNavigationCapability) || (!this._mobileParty.IsCurrentlyAtSea && followedParty.IsCurrentlyAtSea && this._mobileParty.HasNavalNavigationCapability)))
				{
					shortTermTargetPoint = this._mobileParty.EndPositionForNavigationTransition;
					return;
				}
				shortTermTargetPoint = followedParty.Position;
				return;
			}
		}

		// Token: 0x06002AF2 RID: 10994 RVA: 0x000B1F50 File Offset: 0x000B0150
		private void GetBesiegeBehavior(out AiBehavior shortTermBehavior, out CampaignVec2 shortTermTargetPoint, out Settlement shortTermTargetSettlement)
		{
			if (this._mobileParty.TargetSettlement != null)
			{
				if (this._mobileParty.TargetSettlement.SiegeEvent != null && this._mobileParty.TargetSettlement.SiegeEvent.BesiegerCamp.LeaderParty == this._mobileParty && this._mobileParty.TargetSettlement.SiegeEvent.BesiegerCamp.IsReadyToBesiege)
				{
					shortTermTargetSettlement = this._mobileParty.TargetSettlement;
					shortTermBehavior = AiBehavior.AssaultSettlement;
				}
				else if (this._mobileParty.BesiegedSettlement == this._mobileParty.TargetSettlement)
				{
					shortTermTargetSettlement = null;
					shortTermBehavior = AiBehavior.Hold;
				}
				else
				{
					shortTermTargetSettlement = this._mobileParty.TargetSettlement;
					shortTermBehavior = AiBehavior.GoToSettlement;
				}
			}
			else
			{
				shortTermTargetSettlement = null;
				shortTermBehavior = AiBehavior.GoToPoint;
			}
			shortTermTargetPoint = this._mobileParty.TargetSettlement.GatePosition;
		}

		// Token: 0x06002AF3 RID: 10995 RVA: 0x000B2020 File Offset: 0x000B0220
		private void GetFleeBehavior(out AiBehavior fleeBehaviorInternal, out CampaignVec2 fleeTargetPoint, ref Settlement fleeTargetSettlement, MobileParty partyToFleeFrom, Vec2 avarageEnemyVec)
		{
			fleeBehaviorInternal = this._mobileParty.ShortTermBehavior;
			fleeTargetPoint = this._mobileParty.AiBehaviorTarget;
			if (this._mobileParty.CurrentSettlement != null && (partyToFleeFrom == null || partyToFleeFrom.CurrentSettlement != this._mobileParty.CurrentSettlement))
			{
				fleeBehaviorInternal = AiBehavior.GoToSettlement;
				fleeTargetSettlement = this._mobileParty.CurrentSettlement;
				fleeTargetPoint = (this._mobileParty.IsCurrentlyAtSea ? fleeTargetSettlement.PortPosition : fleeTargetSettlement.GatePosition);
			}
			else if (partyToFleeFrom != null && this._mobileParty.DefaultBehavior == AiBehavior.GoToSettlement && ((partyToFleeFrom.MapEvent != null && partyToFleeFrom.MapEvent.MapEventSettlement == this._mobileParty.TargetSettlement) || partyToFleeFrom.BesiegedSettlement == this._mobileParty.TargetSettlement))
			{
				fleeBehaviorInternal = AiBehavior.FleeToPoint;
				fleeTargetPoint = this._mobileParty.Position;
			}
			else
			{
				fleeBehaviorInternal = AiBehavior.FleeToPoint;
				fleeTargetPoint = this._mobileParty.Position;
				if (partyToFleeFrom != null && this._mobileParty.DefaultBehavior == AiBehavior.PatrolAroundPoint && partyToFleeFrom.Position.DistanceSquared(this._mobileParty.TargetPosition.ToVec2()) < 4f)
				{
					if (partyToFleeFrom.IsMoving || partyToFleeFrom.IsGarrison)
					{
						if (!this._mobileParty.TargetPosition.IsOnLand)
						{
							this.GetNavalPatrolBehavior(out fleeBehaviorInternal, out fleeTargetPoint, this._mobileParty.TargetPosition, true);
						}
						else
						{
							this.GetLandPatrolBehavior(out fleeBehaviorInternal, out fleeTargetPoint, this._mobileParty.TargetPosition, true);
						}
					}
					else
					{
						fleeBehaviorInternal = AiBehavior.Hold;
						fleeTargetPoint = this._mobileParty.Position;
					}
				}
				else
				{
					this.CalculateFleePosition(out fleeTargetPoint, partyToFleeFrom, avarageEnemyVec);
				}
			}
			Vec2 fleeDirection = fleeTargetPoint.ToVec2() - this._mobileParty.Position.ToVec2();
			fleeDirection.Normalize();
			bool flag = this._mobileParty.IsLordParty || this._mobileParty.IsCaravan || this._mobileParty.IsVillager;
			if (partyToFleeFrom != null && flag)
			{
				MobileParty nearbyPartyToFlee = this.GetNearbyPartyToFlee(partyToFleeFrom, fleeDirection);
				if (nearbyPartyToFlee != null)
				{
					fleeBehaviorInternal = AiBehavior.FleeToParty;
					fleeTargetPoint = nearbyPartyToFlee.Position;
				}
			}
			if (flag && this._mobileParty.MapFaction.IsKingdomFaction && partyToFleeFrom != null && partyToFleeFrom.MapEvent == null && partyToFleeFrom.SiegeEvent == null)
			{
				CampaignVec2 campaignVec;
				this.GetBehaviorForNearbySettlementToFlee(partyToFleeFrom, fleeDirection, out fleeTargetSettlement, out campaignVec, out fleeBehaviorInternal);
				if (fleeTargetSettlement != null)
				{
					fleeTargetPoint = campaignVec;
					this._fleeingData.CcwFleeDirectionIsBlocked = true;
					this._fleeingData.CwFleeDirectionIsBlocked = true;
				}
			}
		}

		// Token: 0x06002AF4 RID: 10996 RVA: 0x000B22A8 File Offset: 0x000B04A8
		public void CalculateFleePosition(out CampaignVec2 fleeTargetPoint, MobileParty partyToFleeFrom, Vec2 averageEnemyVec)
		{
			if (this._fleeingData.CcwFleeDirectionIsBlocked && this._fleeingData.CwFleeDirectionIsBlocked)
			{
				this._fleeingData.Clear();
			}
			float num = (partyToFleeFrom != null && partyToFleeFrom.Army != null) ? Campaign.Current.Models.EncounterModel.MaximumAllowedDistanceForEncounteringMobilePartyInArmy : Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringMobileParty;
			num *= 2f;
			Vec2 vec = (partyToFleeFrom != null) ? partyToFleeFrom.Position.ToVec2() : (this._mobileParty.Position.ToVec2() + averageEnemyVec);
			Vec2 vec2 = vec - this._mobileParty.Position.ToVec2();
			float num2 = vec2.Length;
			Vec2 vec3 = -vec2;
			vec3.Normalize();
			vec2 += 3f * averageEnemyVec;
			vec2.Normalize();
			float targetDistance = this._mobileParty.LastCalculatedBaseSpeed * 5f;
			this.GetAccessibleTargetPointInDirection(out fleeTargetPoint, vec3, targetDistance, this._mobileParty.Position, 100, true, false, 0f);
			bool flag = fleeTargetPoint.NearlyEquals(this._mobileParty.Position, num * 0.15f);
			if (!this._mobileParty.IsBandit && (partyToFleeFrom == null || this._mobileParty._lastCalculatedSpeed > partyToFleeFrom._lastCalculatedSpeed || partyToFleeFrom.MapEvent != null || partyToFleeFrom.SiegeEvent != null))
			{
				bool flag2 = partyToFleeFrom == null;
				bool flag3 = partyToFleeFrom != null && !partyToFleeFrom.IsMoving;
				if (flag2)
				{
					float num3 = this._mobileParty.Ships.SumQ((Ship x) => x.HitPoints / x.MaxHitPoints) / (float)this._mobileParty.Ships.Count;
					num2 *= num3;
				}
				if (!flag3 && flag)
				{
					float num4 = 0.01f;
					float epsilon = num * 0.75f;
					float num5 = 0.9424779f;
					float num6 = num5 * 0.05f;
					while (num4 <= num5 && fleeTargetPoint.NearlyEquals(this._mobileParty.Position, epsilon))
					{
						num4 += num6;
						Vec2 direction = vec3;
						CampaignVec2 campaignVec = new CampaignVec2(vec3.LeftVec(), !this._mobileParty.IsCurrentlyAtSea);
						direction.RotateCCW(campaignVec.Face.IsValid() ? num4 : (-num4));
						bool flag4 = num4 > num5 * 0.66f;
						this.GetAccessibleTargetPointInDirection(out fleeTargetPoint, direction, num2, this._mobileParty.Position, 100, true, flag4, flag4 ? 0.5f : 0f);
					}
					if (fleeTargetPoint.NearlyEquals(this._mobileParty.Position, epsilon))
					{
						fleeTargetPoint = this._mobileParty.MoveTargetPoint;
					}
				}
				else if (!this._fleeingData.AlreadyReachedTheDestinationWhileFleeing)
				{
					if (this._mobileParty.RecalculateLongTermPath())
					{
						float num7 = this._mobileParty.NextLongTermPathPoint.Distance(this._mobileParty.Position);
						float num8 = this._mobileParty.NextLongTermPathPoint.Distance(vec);
						float num9 = ((this._mobileParty.Position + vec) * 0.5f).Distance(this._mobileParty.NextLongTermPathPoint);
						if (num7 < num8 && num9 > num7)
						{
							bool flag5 = this._mobileParty.Position.Distance(this._mobileParty.NextLongTermPathPoint) < num;
							if (flag5)
							{
								this._mobileParty.RecalculateLongTermPath();
								flag5 = (this._mobileParty.Path.Size == 1 && this._mobileParty.Path.PathPoints[0].NearlyEquals(this._mobileParty.Position.ToVec2(), num));
								if (flag5)
								{
									this._fleeingData.AlreadyReachedTheDestinationWhileFleeing = true;
								}
							}
							if (!flag5)
							{
								fleeTargetPoint = this._mobileParty.NextLongTermPathPoint;
							}
						}
						else if (!flag3 || partyToFleeFrom.Position.DistanceSquared(this._mobileParty.NextLongTermPathPoint) >= 1f)
						{
							Vec2 vec4 = this._mobileParty.NextLongTermPathPoint.ToVec2() - vec;
							Vec2 v = this._mobileParty.Position.ToVec2();
							Vec2 vec5 = vec2.Normalized();
							CampaignVec2 campaignVec2 = new CampaignVec2(v + vec5.RightVec(), !this._mobileParty.IsCurrentlyAtSea);
							Vec2 v2 = this._mobileParty.Position.ToVec2();
							vec5 = vec2.Normalized();
							CampaignVec2 campaignVec3 = new CampaignVec2(v2 + vec5.LeftVec(), !this._mobileParty.IsCurrentlyAtSea);
							vec5 = vec4.Normalized();
							Vec2 vec6 = vec2.Normalized();
							float num10 = Vec2.Determinant(vec5, vec6);
							this._fleeingData.CcwFleeDirectionIsBlocked = (this._fleeingData.CcwFleeDirectionIsBlocked || !campaignVec2.Face.IsValid());
							this._fleeingData.CwFleeDirectionIsBlocked = (this._fleeingData.CwFleeDirectionIsBlocked || !campaignVec3.Face.IsValid());
							if (!this._fleeingData.CcwFleeDirectionIsBlocked)
							{
								bool flag6 = Campaign.Current.Models.PartyNavigationModel.IsTerrainTypeValidForNavigationType(Campaign.Current.MapSceneWrapper.GetFaceTerrainType(campaignVec2.Face), this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default);
								this._fleeingData.CcwFleeDirectionIsBlocked = !flag6;
							}
							if (!this._fleeingData.CwFleeDirectionIsBlocked)
							{
								bool flag7 = Campaign.Current.Models.PartyNavigationModel.IsTerrainTypeValidForNavigationType(Campaign.Current.MapSceneWrapper.GetFaceTerrainType(campaignVec3.Face), this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default);
								this._fleeingData.CwFleeDirectionIsBlocked = !flag7;
							}
							bool flag8 = this._fleeingData.ShouldFleeClockWise || this._fleeingData.CcwFleeDirectionIsBlocked || (!this._fleeingData.CwFleeDirectionIsBlocked && num10 <= 0f);
							float num11 = flag2 ? (this._mobileParty._lastCalculatedSpeed * 0.75f) : partyToFleeFrom._lastCalculatedSpeed;
							if (flag3)
							{
								num11 *= 0.15f;
								num = 0.5f;
								num2 *= 0.2f;
							}
							float num12 = num2 * num11 / this._mobileParty._lastCalculatedSpeed + num * 1.25f;
							float num13 = 2f * (float)Math.Asin((double)(num12 * 0.5f / num2));
							if (!float.IsNaN(num13))
							{
								Vec2 vec7 = vec2.Normalized();
								vec7.RotateCCW(flag8 ? num13 : (-num13));
								vec3 = vec7;
								vec3.Normalize();
								Vec2 vec8 = this._mobileParty.NextLongTermPathPoint.ToVec2() - this._mobileParty.Position.ToVec2();
								Vec2 v3 = this._mobileParty.Position.ToVec2() + vec3 * num2;
								if (MathF.Abs(vec8.AngleBetween(v3 - this._mobileParty.Position.ToVec2())) < (flag3 ? 0.8f : 0.2f))
								{
									fleeTargetPoint = this._mobileParty.NextLongTermPathPoint;
								}
								else
								{
									this.GetAccessibleTargetPointInDirection(out fleeTargetPoint, vec3, MathF.Clamp(num2 * 3f, num, num * 5f), this._mobileParty.Position, 100, true, false, 0f);
									if (fleeTargetPoint.NearlyEquals(this._mobileParty.Position, num))
									{
										if (flag8)
										{
											this._fleeingData.CwFleeDirectionIsBlocked = true;
										}
										else
										{
											this._fleeingData.CcwFleeDirectionIsBlocked = true;
										}
										flag8 = !this._fleeingData.ShouldFleeClockWise;
									}
								}
								this._fleeingData.ShouldFleeClockWise = flag8;
							}
							else if (flag8)
							{
								this._fleeingData.CwFleeDirectionIsBlocked = true;
							}
							else
							{
								this._fleeingData.CcwFleeDirectionIsBlocked = true;
							}
						}
					}
				}
				else
				{
					this._fleeingData.CcwFleeDirectionIsBlocked = true;
					this._fleeingData.CwFleeDirectionIsBlocked = true;
				}
			}
			if (flag || (this._fleeingData.CcwFleeDirectionIsBlocked && this._fleeingData.CwFleeDirectionIsBlocked))
			{
				this.GetAccessibleTargetPointInDirection(out fleeTargetPoint, vec3, 10f, this._mobileParty.Position, 100, true, true, 0.2f);
				this._fleeingData.CcwFleeDirectionIsBlocked = true;
				this._fleeingData.CwFleeDirectionIsBlocked = true;
			}
		}

		// Token: 0x06002AF5 RID: 10997 RVA: 0x000B2B38 File Offset: 0x000B0D38
		private void GetDefendSettlementBehavior(Settlement targetSettlement, out AiBehavior shortTermBehavior, out CampaignVec2 shortTermTargetPoint, out MobileParty goAroundPartyTargetParty)
		{
			goAroundPartyTargetParty = targetSettlement.LastAttackerParty;
			if (targetSettlement.SiegeEvent != null)
			{
				if (this._mobileParty.CurrentSettlement == targetSettlement)
				{
					shortTermBehavior = AiBehavior.GoToSettlement;
					shortTermTargetPoint = this._mobileParty.Position;
					return;
				}
				shortTermBehavior = AiBehavior.GoToPoint;
				shortTermTargetPoint = targetSettlement.LastAttackerParty.Position;
				if (targetSettlement.HasPort && !targetSettlement.SiegeEvent.IsBlockadeActive && this._mobileParty.HasNavalNavigationCapability)
				{
					if (!this._mobileParty.IsTargetingPort)
					{
						this._mobileParty.Ai.RethinkAtNextHourlyTick = true;
					}
					shortTermBehavior = AiBehavior.GoToSettlement;
					shortTermTargetPoint = targetSettlement.PortPosition;
					return;
				}
				bool flag;
				bool flag2;
				bool flag3;
				MobileParty mobileParty;
				MobileParty mobileParty2;
				if (targetSettlement.HasPort && targetSettlement.SiegeEvent.IsBlockadeActive && targetSettlement.SiegeEvent.BesiegerCamp.LeaderParty.MapEvent != null && (targetSettlement.SiegeEvent.BesiegerCamp.LeaderParty.MapEvent.IsBlockade || targetSettlement.SiegeEvent.BesiegerCamp.LeaderParty.MapEvent.IsBlockadeSallyOut))
				{
					if (this._mobileParty.HasNavalNavigationCapability)
					{
						shortTermBehavior = AiBehavior.GoToSettlement;
						shortTermTargetPoint = targetSettlement.PortPosition;
						return;
					}
					shortTermBehavior = AiBehavior.Hold;
					shortTermTargetPoint = this._mobileParty.Position;
					return;
				}
				else if (this.GetNearbyPartyDataWhileDefendingSettlement(targetSettlement, out flag, out flag2, out flag3, out mobileParty, out mobileParty2))
				{
					bool flag4 = this._mobileParty.ShortTermTargetParty != null && this._mobileParty.ShortTermTargetParty.IsActive && !this._mobileParty.ShortTermTargetParty.MapFaction.IsAtWarWith(this._mobileParty.MapFaction) && this._mobileParty.ShortTermTargetParty.MapEvent == null;
					if (!flag3 && flag4 && !flag)
					{
						shortTermBehavior = AiBehavior.GoToPoint;
						goAroundPartyTargetParty = this._mobileParty.ShortTermTargetParty;
						this.GetDefendingPosition(this._mobileParty.ShortTermTargetParty.Position, MobileParty.NavigationType.All, 1.5f, out shortTermTargetPoint);
						return;
					}
					if (flag3)
					{
						if (flag2)
						{
							shortTermBehavior = AiBehavior.EngageParty;
							goAroundPartyTargetParty = targetSettlement.SiegeEvent.BesiegerCamp.LeaderParty;
							return;
						}
						shortTermBehavior = AiBehavior.GoToSettlement;
						shortTermTargetPoint = targetSettlement.PortPosition;
						return;
					}
					else
					{
						if (flag)
						{
							shortTermBehavior = AiBehavior.GoToPoint;
							MobileParty mobileParty3 = flag2 ? mobileParty : mobileParty2;
							goAroundPartyTargetParty = mobileParty3;
							this.GetDefendingPosition(mobileParty3.Position, MobileParty.NavigationType.All, 0.5f, out shortTermTargetPoint);
							return;
						}
						float settlementDefendingWaitingPositionRadius = Campaign.Current.Models.MobilePartyAIModel.SettlementDefendingWaitingPositionRadius;
						if (this._mobileParty.IsCurrentlyAtSea && targetSettlement.HasPort && targetSettlement.Party.MapEventSide == null)
						{
							if (!this.GetDefendingPosition(targetSettlement.PortPosition, MobileParty.NavigationType.Naval, settlementDefendingWaitingPositionRadius, out shortTermTargetPoint))
							{
								this.GetDefendingPosition(targetSettlement.PortPosition, MobileParty.NavigationType.Naval, settlementDefendingWaitingPositionRadius * 5f, out shortTermTargetPoint);
								return;
							}
						}
						else if (!this.GetDefendingPosition(goAroundPartyTargetParty.Position, this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.All : MobileParty.NavigationType.Default, settlementDefendingWaitingPositionRadius, out shortTermTargetPoint))
						{
							this.GetDefendingPosition(goAroundPartyTargetParty.Position, MobileParty.NavigationType.All, settlementDefendingWaitingPositionRadius, out shortTermTargetPoint);
							return;
						}
					}
				}
			}
			else
			{
				bool flag5;
				bool flag6;
				bool flag7;
				MobileParty mobileParty4;
				MobileParty mobileParty5;
				this.GetNearbyPartyDataWhileDefendingSettlement(targetSettlement, out flag5, out flag6, out flag7, out mobileParty4, out mobileParty5);
				if (flag7)
				{
					if (!flag6)
					{
						shortTermBehavior = AiBehavior.GoToSettlement;
						shortTermTargetPoint = targetSettlement.PortPosition;
						return;
					}
					shortTermBehavior = AiBehavior.EngageParty;
					goAroundPartyTargetParty = targetSettlement.LastAttackerParty;
					shortTermTargetPoint = targetSettlement.LastAttackerParty.Position;
					if (targetSettlement.LastAttackerParty.IsCurrentlyAtSea && !this._mobileParty.HasNavalNavigationCapability)
					{
						shortTermTargetPoint = targetSettlement.GatePosition;
						return;
					}
				}
				else
				{
					if (this._mobileParty.IsCurrentlyAtSea == goAroundPartyTargetParty.IsCurrentlyAtSea)
					{
						this.GetGoAroundPartyBehavior(goAroundPartyTargetParty, out shortTermBehavior, out shortTermTargetPoint);
						return;
					}
					shortTermBehavior = AiBehavior.GoToSettlement;
					shortTermTargetPoint = ((this._mobileParty.IsCurrentlyAtSea && targetSettlement.HasPort) ? targetSettlement.PortPosition : targetSettlement.GatePosition);
				}
			}
		}

		// Token: 0x06002AF6 RID: 10998 RVA: 0x000B2EE0 File Offset: 0x000B10E0
		public bool GetNearbyPartyDataWhileDefendingSettlement(Settlement targetSettlement, out bool shouldConsiderJoiningNearbyAllyParties, out bool shouldJoinLandSide, out bool shouldEngage, out MobileParty mostPowerfulLandAlly, out MobileParty mostPowerfulNavalAlly)
		{
			shouldEngage = false;
			shouldConsiderJoiningNearbyAllyParties = false;
			shouldJoinLandSide = false;
			mostPowerfulLandAlly = null;
			mostPowerfulNavalAlly = null;
			CampaignVec2 v = (targetSettlement.SiegeEvent != null) ? targetSettlement.SiegeEvent.BesiegerCamp.LeaderParty.Position : targetSettlement.GatePosition;
			bool flag = (targetSettlement.Party.MapEventSide == null || targetSettlement.Party.MapEvent.IsNavalMapEvent == this._mobileParty.IsCurrentlyAtSea) && this._mobileParty.Position.Distance(v) < Campaign.Current.Models.MobilePartyAIModel.SettlementDefendingNearbyPartyCheckRadius;
			if (flag)
			{
				float num = 0f;
				float num2 = 0f;
				if (targetSettlement.IsFortification)
				{
					if (targetSettlement.SiegeEvent != null)
					{
						using (IEnumerator<PartyBase> enumerator = targetSettlement.SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege).GetEnumerator())
						{
							while (enumerator.MoveNext())
							{
								PartyBase partyBase = enumerator.Current;
								num += partyBase.GetCustomStrength(BattleSideEnum.Defender, MapEvent.PowerCalculationContext.PlainBattle);
								num2 += partyBase.GetCustomStrength(BattleSideEnum.Defender, MapEvent.PowerCalculationContext.SeaBattle);
							}
							goto IL_1B5;
						}
					}
					num = ((targetSettlement.LastAttackerParty.Army != null && targetSettlement.LastAttackerParty.Army.LeaderParty == targetSettlement.LastAttackerParty) ? targetSettlement.LastAttackerParty.Army.EstimatedStrength : targetSettlement.LastAttackerParty.Party.EstimatedStrength);
				}
				else if (targetSettlement.Party.MapEventSide != null)
				{
					MobileParty mobileParty = targetSettlement.Party.MapEventSide.OtherSide.LeaderParty.MobileParty;
					num = ((mobileParty.Army != null && mobileParty.Army.LeaderParty == mobileParty) ? mobileParty.Army.EstimatedStrength : mobileParty.Party.EstimatedStrength);
				}
				IL_1B5:
				LocatableSearchData<MobileParty> locatableSearchData = MobileParty.StartFindingLocatablesAroundPosition(v.ToVec2(), Campaign.Current.Models.MobilePartyAIModel.SettlementDefendingNearbyPartyCheckRadius);
				MobileParty mobileParty2 = MobileParty.FindNextLocatable(ref locatableSearchData);
				float num3 = 0f;
				float num4 = 0f;
				float num5 = 0f;
				float num6 = 0f;
				while (mobileParty2 != null)
				{
					if (mobileParty2.AttachedTo == null && ((mobileParty2.DefaultBehavior == AiBehavior.DefendSettlement && mobileParty2.TargetSettlement == targetSettlement) || (mobileParty2.ShortTermBehavior == AiBehavior.EngageParty && mobileParty2.ShortTermTargetParty == targetSettlement.LastAttackerParty)))
					{
						Army army = mobileParty2.Army;
						float num7 = (army != null) ? army.GetCustomStrength(BattleSideEnum.Attacker, MapEvent.PowerCalculationContext.PlainBattle) : mobileParty2.Party.GetCustomStrength(BattleSideEnum.Attacker, MapEvent.PowerCalculationContext.PlainBattle);
						Army army2 = mobileParty2.Army;
						float num8 = (army2 != null) ? army2.GetCustomStrength(BattleSideEnum.Attacker, MapEvent.PowerCalculationContext.SeaBattle) : mobileParty2.Party.GetCustomStrength(BattleSideEnum.Attacker, MapEvent.PowerCalculationContext.SeaBattle);
						if (!mobileParty2.IsCurrentlyAtSea)
						{
							num3 += num7;
							if (mostPowerfulLandAlly == null || num5 < num7)
							{
								mostPowerfulLandAlly = mobileParty2;
								num5 = num7;
							}
						}
						else if (targetSettlement.HasPort)
						{
							num4 += num8;
							if (mostPowerfulNavalAlly == null || num6 < num8)
							{
								mostPowerfulNavalAlly = mobileParty2;
								num6 = num8;
							}
						}
					}
					mobileParty2 = MobileParty.FindNextLocatable(ref locatableSearchData);
				}
				shouldConsiderJoiningNearbyAllyParties = (num3 > num || num4 > num2);
				if (shouldConsiderJoiningNearbyAllyParties)
				{
					if (num < num3)
					{
						shouldJoinLandSide = true;
					}
					else if (num2 < num4)
					{
						shouldJoinLandSide = false;
					}
					else
					{
						float num9 = num - num3;
						float num10 = num2 - num4;
						shouldJoinLandSide = (num9 < num10);
					}
					if (shouldJoinLandSide && mostPowerfulLandAlly == this._mobileParty)
					{
						if (num3 > num * 1.1f)
						{
							shouldEngage = true;
						}
						shouldConsiderJoiningNearbyAllyParties = false;
					}
					if (!shouldJoinLandSide && mostPowerfulNavalAlly == this._mobileParty)
					{
						if (num4 > num2 * 1.1f)
						{
							shouldEngage = true;
						}
						shouldConsiderJoiningNearbyAllyParties = false;
					}
					if (((mostPowerfulLandAlly != null & shouldJoinLandSide) && mostPowerfulLandAlly != this._mobileParty && (mostPowerfulLandAlly.MapEvent != null || mostPowerfulLandAlly.ShortTermBehavior == AiBehavior.EngageParty)) || (mostPowerfulNavalAlly != null && !shouldJoinLandSide && mostPowerfulNavalAlly != this._mobileParty && (mostPowerfulNavalAlly.MapEvent != null || mostPowerfulNavalAlly.ShortTermBehavior == AiBehavior.EngageParty)))
					{
						shouldEngage = true;
					}
					if (!this._mobileParty.HasNavalNavigationCapability && !shouldJoinLandSide)
					{
						shouldConsiderJoiningNearbyAllyParties = false;
					}
				}
			}
			return flag;
		}

		// Token: 0x06002AF7 RID: 10999 RVA: 0x000B32D8 File Offset: 0x000B14D8
		private void GetGoAroundPartyBehavior(MobileParty targetParty, out AiBehavior goAroundPartyBehavior, out CampaignVec2 goAroundPartyTargetPoint)
		{
			CampaignVec2 position = targetParty.Position;
			goAroundPartyTargetPoint = position;
			float defendRadius = Campaign.Current.Models.EncounterModel.GetEncounterJoiningRadius * 1.15f;
			MobileParty.NavigationType navigationType = position.IsOnLand ? MobileParty.NavigationType.Default : MobileParty.NavigationType.Naval;
			CampaignVec2 campaignVec;
			if (this.GetDefendingPosition(targetParty.Position, navigationType, defendRadius, out campaignVec))
			{
				if (MBRandom.RandomFloat < 0.2f * this._mobileParty.AiBehaviorTarget.DistanceSquared(campaignVec) || targetParty._lastCalculatedSpeed > this._mobileParty._lastCalculatedSpeed)
				{
					goAroundPartyTargetPoint = campaignVec;
				}
				else
				{
					goAroundPartyTargetPoint = this._mobileParty.AiBehaviorTarget;
				}
				goAroundPartyBehavior = AiBehavior.GoToPoint;
				return;
			}
			goAroundPartyBehavior = AiBehavior.EngageParty;
			goAroundPartyTargetPoint = targetParty.Position;
		}

		// Token: 0x06002AF8 RID: 11000 RVA: 0x000B3390 File Offset: 0x000B1590
		private bool GetDefendingPosition(CampaignVec2 targetPosition, MobileParty.NavigationType navigationType, float defendRadius, out CampaignVec2 possibleTargetPoint)
		{
			PathFaceRecord currentNavigationFace = this._mobileParty.CurrentNavigationFace;
			Vec2 vec = this._mobileParty.Position.ToVec2() - targetPosition.ToVec2();
			float length = vec.Length;
			vec.Normalize();
			bool flag = false;
			possibleTargetPoint = targetPosition;
			int num = 5;
			while (num >= 0 && !flag)
			{
				int num2 = this._mobileParty.RandomInt(-4, 5);
				int num3 = 1;
				while (num3 <= 2 && !flag)
				{
					for (int i = num2; i < num2 + 9; i++)
					{
						Vec2 v = vec;
						v.RotateCCW((float)i / 9f * 1.5707964f * (float)num3 * 0.5f * (MathF.Min(MathF.Max(0f, length - defendRadius * defendRadius * 0.5f), 3f * defendRadius) / (3f * defendRadius)));
						CampaignVec2 campaignVec = targetPosition + v * defendRadius * defendRadius * 0.5f * ((float)num / 5f);
						if (campaignVec.IsValid() && (navigationType == MobileParty.NavigationType.All || Campaign.Current.MapSceneWrapper.AreFacesOnSameIsland(currentNavigationFace, campaignVec.Face, navigationType)) && NavigationHelper.IsPositionValidForNavigationType(campaignVec, navigationType))
						{
							flag = true;
							possibleTargetPoint = campaignVec;
							break;
						}
					}
					num3++;
				}
				num--;
			}
			return flag;
		}

		// Token: 0x06002AF9 RID: 11001 RVA: 0x000B3500 File Offset: 0x000B1700
		private void GetNavalPatrolBehavior(out AiBehavior patrolBehavior, out CampaignVec2 patrolTargetPoint, CampaignVec2 patrollingCenterPoint, bool forceUpdate)
		{
			patrolBehavior = AiBehavior.GoToPoint;
			patrolTargetPoint = (forceUpdate ? patrollingCenterPoint : this._mobileParty.MoveTargetPoint);
			bool flag = forceUpdate || MBRandom.RandomFloat < 0.1f * Campaign.Current.Models.MobilePartyAIModel.AiCheckInterval;
			if (!flag && this._mobileParty.IsBandit)
			{
				CampaignVec2 position = this._mobileParty.Position + this._mobileParty.Bearing;
				if (!position.IsValid())
				{
					position = this._mobileParty.Position;
				}
				flag = Campaign.Current.Models.BanditDensityModel.IsPositionInsideNavalSafeZone(position);
			}
			if (flag)
			{
				float patrolRadius = Campaign.Current.Models.MobilePartyAIModel.GetPatrolRadius(this._mobileParty, patrolTargetPoint);
				if (this._mobileParty.IsLordParty)
				{
					if (!this._mobileParty.IsCurrentlyAtSea)
					{
						patrolBehavior = AiBehavior.GoToPoint;
						patrolTargetPoint = this._mobileParty.TargetSettlement.PortPosition;
						return;
					}
					int num = 0;
					CampaignVec2 campaignVec = CampaignVec2.Zero;
					TerrainType faceTerrainType;
					do
					{
						campaignVec = NavigationHelper.FindPointAroundPosition(patrollingCenterPoint, this._mobileParty.DesiredAiNavigationType, patrolRadius, patrolRadius * 0.5f, true, false);
						faceTerrainType = Campaign.Current.MapSceneWrapper.GetFaceTerrainType(campaignVec.Face);
						num++;
					}
					while (num < 100 && faceTerrainType != TerrainType.CoastalSea && faceTerrainType != TerrainType.NonNavigableRiver && faceTerrainType != TerrainType.River && faceTerrainType != TerrainType.UnderBridge);
					patrolBehavior = AiBehavior.GoToPoint;
					patrolTargetPoint = campaignVec;
					return;
				}
				else
				{
					CampaignVec2 campaignVec2 = NavigationHelper.FindPointAroundPosition(patrollingCenterPoint, MobileParty.NavigationType.Naval, patrolRadius, 0f, true, true);
					int num2 = 0;
					do
					{
						campaignVec2 = NavigationHelper.FindPointAroundPosition(patrollingCenterPoint, MobileParty.NavigationType.Naval, patrolRadius, 0f, true, false);
						num2++;
					}
					while (num2 < 100 && Campaign.Current.Models.BanditDensityModel.IsPositionInsideNavalSafeZone(campaignVec2));
					patrolBehavior = AiBehavior.GoToPoint;
					patrolTargetPoint = campaignVec2;
				}
			}
		}

		// Token: 0x06002AFA RID: 11002 RVA: 0x000B36CC File Offset: 0x000B18CC
		private void GetLandPatrolBehavior(out AiBehavior patrolBehavior, out CampaignVec2 patrolTargetPoint, CampaignVec2 patrollingCenterPoint, bool forceUpdate)
		{
			float num = this._mobileParty.AiBehaviorTarget.DistanceSquared(this._mobileParty.Position);
			patrolBehavior = AiBehavior.GoToPoint;
			patrolTargetPoint = this._mobileParty.AiBehaviorTarget;
			if (num < 1f || forceUpdate || !patrolTargetPoint.IsNonZero())
			{
				if (MBRandom.RandomFloat < 0.5f * Campaign.Current.Models.MobilePartyAIModel.AiCheckInterval || forceUpdate)
				{
					Vec2 v = patrollingCenterPoint.ToVec2() - this._mobileParty.Position.ToVec2();
					float num2 = v.Normalize();
					float patrolRadius = Campaign.Current.Models.MobilePartyAIModel.GetPatrolRadius(this._mobileParty, patrolTargetPoint);
					float num3 = MathF.Max(num2 * 0.25f, patrolRadius);
					if (this._mobileParty.IsCurrentlyAtSea == patrollingCenterPoint.IsOnLand || num2 > num3 * (3.2f / (this._mobileParty.IsCurrentlyUsedByAQuest ? 1.5f : 1f)))
					{
						patrolBehavior = AiBehavior.GoToPoint;
						CampaignVec2 campaignVec;
						if (this._mobileParty.TargetSettlement != null)
						{
							campaignVec = (this._mobileParty.IsTargetingPort ? this._mobileParty.TargetSettlement.PortPosition : this._mobileParty.TargetSettlement.GatePosition);
						}
						else
						{
							campaignVec = patrollingCenterPoint;
						}
						patrolTargetPoint = campaignVec;
						return;
					}
					float num4 = (this._mobileParty.TargetSettlement != null && this._mobileParty.TargetSettlement.NearbyLandThreatIntensity > 1f) ? (MathF.Sqrt(this._mobileParty.TargetSettlement.NearbyLandThreatIntensity) - 1f) : 0f;
					float num5 = MathF.Max(0f, MathF.Min(0.9f, num2 / (num3 / (((this._mobileParty.TargetSettlement != null && this._mobileParty.TargetSettlement.MapFaction == this._mobileParty.MapFaction) ? num4 : 0f) + 1f)) - 0.4f));
					Vec2 direction = (1f - num5) * this._mobileParty.Bearing + num5 * v;
					direction.RotateCCW((-0.3f + MBRandom.RandomFloat) * 0.15f);
					direction.Normalize();
					float num6 = 0.5f + 0.5f * MBRandom.RandomFloat;
					float rotationChangeLimitAddition = (num2 > patrolRadius * 4f) ? 0.2f : ((num2 > patrolRadius * 2f) ? 0.4f : ((num2 > patrolRadius) ? 0.6f : 1f));
					this.GetAccessibleTargetPointInDirection(out patrolTargetPoint, direction, num3 * num6, patrollingCenterPoint, 20, true, true, rotationChangeLimitAddition);
					return;
				}
				else
				{
					patrolTargetPoint = patrollingCenterPoint;
				}
			}
		}

		// Token: 0x06002AFB RID: 11003 RVA: 0x000B397C File Offset: 0x000B1B7C
		private void SetAiBehavior(AiBehavior newAiBehavior, IInteractablePoint interactablePoint, CampaignVec2 bestTargetPoint)
		{
			this._mobileParty.SetShortTermBehavior(newAiBehavior, interactablePoint);
			this.BehaviorTarget = bestTargetPoint;
			this.UpdateBehavior();
		}

		// Token: 0x06002AFC RID: 11004 RVA: 0x000B3998 File Offset: 0x000B1B98
		private void UpdateBehavior()
		{
			if (this._mobileParty.ShortTermBehavior == AiBehavior.GoToPoint || this._mobileParty.ShortTermBehavior == AiBehavior.FleeToPoint || this._mobileParty.ShortTermBehavior == AiBehavior.FleeToGate || this._mobileParty.ShortTermBehavior == AiBehavior.FleeToParty || this._mobileParty.ShortTermBehavior == AiBehavior.MoveToNearestLandOrPort || ((this._mobileParty.ShortTermBehavior == AiBehavior.GoToSettlement || this._mobileParty.ShortTermBehavior == AiBehavior.RaidSettlement || this._mobileParty.ShortTermBehavior == AiBehavior.AssaultSettlement || this._mobileParty.ShortTermBehavior == AiBehavior.BesiegeSettlement) && this.AiBehaviorPartyBase != null && this.AiBehaviorPartyBase.IsValid))
			{
				this._mobileParty.SetNavigationModePoint(this.BehaviorTarget);
			}
			else
			{
				AiBehavior shortTermBehavior = this._mobileParty.ShortTermBehavior;
				if (shortTermBehavior <= AiBehavior.EngageParty)
				{
					if (shortTermBehavior == AiBehavior.Hold)
					{
						this._mobileParty.SetNavigationModeHold();
						goto IL_113;
					}
					if (shortTermBehavior == AiBehavior.EngageParty)
					{
						this._mobileParty.SetNavigationModeParty(this.AiBehaviorPartyBase.MobileParty);
						goto IL_113;
					}
				}
				else if (shortTermBehavior - AiBehavior.FleeToPoint <= 2 || shortTermBehavior == AiBehavior.DefendSettlement)
				{
					goto IL_113;
				}
				Debug.FailedAssert("false", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\MobilePartyAi.cs", "UpdateBehavior", 1694);
			}
			IL_113:
			if (!this._mobileParty.IsMainParty && this._mobileParty.BesiegedSettlement != null && this._mobileParty.DefaultBehavior != AiBehavior.BesiegeSettlement && this._mobileParty.DefaultBehavior != AiBehavior.EscortParty && this._mobileParty.DefaultBehavior != AiBehavior.AssaultSettlement)
			{
				this._mobileParty.BesiegerCamp = null;
			}
		}

		// Token: 0x06002AFD RID: 11005 RVA: 0x000B3B0C File Offset: 0x000B1D0C
		private MobileParty GetNearbyPartyToFlee(MobileParty partyToFleeFrom, Vec2 fleeDirection)
		{
			ValueTuple<MobileParty, float> valueTuple = new ValueTuple<MobileParty, float>(null, 0f);
			float fleeToNearbyPartyRadius = Campaign.Current.Models.MobilePartyAIModel.FleeToNearbyPartyRadius;
			MobileParty.NavigationType navigationType = this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default;
			float estimatedStrength = this._mobileParty.Party.EstimatedStrength;
			float estimatedStrength2 = partyToFleeFrom.Party.EstimatedStrength;
			LocatableSearchData<MobileParty> locatableSearchData = MobileParty.StartFindingLocatablesAroundPosition(this._mobileParty.Position.ToVec2(), fleeToNearbyPartyRadius);
			for (MobileParty mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData); mobileParty != null; mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData))
			{
				if (!mobileParty.IsMilitia && !mobileParty.IsGarrison && !mobileParty.IsCaravan && mobileParty != this._mobileParty && (mobileParty.MapFaction == this._mobileParty.MapFaction || (mobileParty.IsBandit && this._mobileParty.IsBandit)) && DistanceHelper.FindClosestDistanceFromMobilePartyToMobileParty(this._mobileParty, mobileParty, navigationType) < Campaign.MapDiagonal)
				{
					if (mobileParty.AttachedTo != null || mobileParty.CurrentSettlement != null || mobileParty.MapEvent != null)
					{
						mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData);
						continue;
					}
					if (!NavigationHelper.IsPositionValidForNavigationType(mobileParty.Position, navigationType))
					{
						mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData);
						continue;
					}
					float num = (mobileParty.Army != null && mobileParty.Army.DoesLeaderPartyAndAttachedPartiesContain(this._mobileParty)) ? mobileParty.Army.EstimatedStrength : mobileParty.Party.EstimatedStrength;
					if (num > estimatedStrength && (this._mobileParty.IsBandit || num + estimatedStrength > estimatedStrength2 * 0.5f))
					{
						float num2 = DistanceHelper.FindClosestDistanceFromMobilePartyToMobileParty(this._mobileParty, mobileParty, navigationType);
						if (num2 > Campaign.MapDiagonal)
						{
							mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData);
							continue;
						}
						CampaignVec2 campaignVec = mobileParty.Position - this._mobileParty.Position;
						if (num2 < 1f && mobileParty._lastCalculatedSpeed < this._mobileParty._lastCalculatedSpeed)
						{
							mobileParty = MobileParty.FindNextLocatable(ref locatableSearchData);
							continue;
						}
						float length = (partyToFleeFrom.Position.ToVec2() - mobileParty.Position.ToVec2()).Length;
						campaignVec.Normalize();
						if (campaignVec.DistanceSquared(fleeDirection) < 0.3f + 0.1f * (fleeToNearbyPartyRadius - Math.Min(fleeToNearbyPartyRadius, num2)) && num2 < length * 0.86f)
						{
							float num3 = num2 * 0.66f + num * 0.34f;
							if (valueTuple.Item2 < num3)
							{
								valueTuple.Item1 = mobileParty;
								valueTuple.Item2 = num3;
							}
						}
					}
				}
			}
			return valueTuple.Item1;
		}

		// Token: 0x06002AFE RID: 11006 RVA: 0x000B3DC8 File Offset: 0x000B1FC8
		private void GetBehaviorForNearbySettlementToFlee(MobileParty partyToFleeFrom, Vec2 fleeDirection, out Settlement fleeSettlement, out CampaignVec2 targetPoint, out AiBehavior aiBehavior)
		{
			float num = Campaign.Current.Models.EncounterModel.NeededMaximumDistanceForEncounteringTown * 2f;
			fleeSettlement = null;
			targetPoint = this._mobileParty.Position;
			aiBehavior = AiBehavior.FleeToPoint;
			MobileParty.NavigationType navigationType = this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default;
			LocatableSearchData<Settlement> locatableSearchData = Campaign.Current.SettlementLocator.StartFindingLocatablesAroundPosition(this._mobileParty.Position.ToVec2(), Campaign.Current.Models.MobilePartyAIModel.FleeToNearbySettlementRadius);
			for (Settlement settlement = Campaign.Current.SettlementLocator.FindNextLocatable(ref locatableSearchData); settlement != null; settlement = Campaign.Current.SettlementLocator.FindNextLocatable(ref locatableSearchData))
			{
				if ((settlement.IsFortification || (settlement.IsVillage && this._mobileParty.IsVillager && this._mobileParty.HomeSettlement == settlement)) && !settlement.MapFaction.IsAtWarWith(this._mobileParty.MapFaction) && (!settlement.IsUnderSiege || (settlement.HasPort && !settlement.SiegeEvent.IsBlockadeActive && this._mobileParty.IsCurrentlyAtSea)) && (navigationType != MobileParty.NavigationType.Naval || settlement.HasPort) && DistanceHelper.FindClosestDistanceFromMobilePartyToSettlement(this._mobileParty, settlement, navigationType) < Campaign.MapDiagonal)
				{
					CampaignVec2 v = (this._mobileParty.IsCurrentlyAtSea && settlement.HasPort) ? settlement.PortPosition : settlement.GatePosition;
					Vec2 vec = v.ToVec2() - this._mobileParty.Position.ToVec2();
					float length = vec.Length;
					vec.Normalize();
					float f = vec.AngleBetween(fleeDirection.Normalized());
					bool flag = partyToFleeFrom.Position.DistanceSquared(v) / partyToFleeFrom._lastCalculatedSpeed > this._mobileParty.Position.DistanceSquared(v) / this._mobileParty._lastCalculatedSpeed;
					if (MathF.Abs(f) < 0.1f || length < num || (length < Campaign.Current.Models.EncounterModel.GetEncounterJoiningRadius * 2f && flag))
					{
						if (length > num)
						{
							aiBehavior = AiBehavior.FleeToGate;
							fleeSettlement = settlement;
						}
						else
						{
							aiBehavior = AiBehavior.GoToSettlement;
							fleeSettlement = settlement;
						}
					}
				}
			}
			if (fleeSettlement != null)
			{
				targetPoint = (this._mobileParty.IsCurrentlyAtSea ? fleeSettlement.PortPosition : fleeSettlement.GatePosition);
			}
		}

		// Token: 0x06002AFF RID: 11007 RVA: 0x000B4044 File Offset: 0x000B2244
		private bool GetAccessibleTargetPointInDirection(out CampaignVec2 targetPoint, Vec2 direction, float targetDistance, CampaignVec2 alternativePosition, int neededTriesForAlternative, bool doNotEmbarkDisembark, bool randomizeDirection, float rotationChangeLimitAddition = 0f)
		{
			targetPoint = this._mobileParty.Position;
			float num = 2f * rotationChangeLimitAddition;
			float num2 = 1f;
			bool flag = false;
			int num3 = 0;
			while (!flag)
			{
				Vec2 v = direction;
				if (randomizeDirection)
				{
					v.RotateCCW((-0.5f + MBRandom.RandomFloat) * num);
					num += rotationChangeLimitAddition;
				}
				targetPoint = this._mobileParty.Position + v * targetDistance * num2;
				num3++;
				num2 *= 0.97f;
				PathFaceRecord face = targetPoint.Face;
				MobileParty.NavigationType navigationType = this._mobileParty.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default;
				MobileParty.NavigationType navigationType2 = doNotEmbarkDisembark ? navigationType : this._mobileParty.NavigationCapability;
				if (face.IsValid() && NavigationHelper.IsPositionValidForNavigationType(face, navigationType2) && targetPoint.Distance(this._mobileParty.Position) < targetDistance && (targetPoint.X > Campaign.Current.MinSettlementX - 50f || targetPoint.X > this._mobileParty.Position.X) && (targetPoint.Y > Campaign.Current.MinSettlementY - 50f || targetPoint.Y > this._mobileParty.Position.Y) && (targetPoint.X < Campaign.Current.MaxSettlementX + 50f || targetPoint.X < this._mobileParty.Position.X) && (targetPoint.Y < Campaign.Current.MaxSettlementY + 50f || targetPoint.Y < this._mobileParty.Position.Y) && Campaign.Current.MapSceneWrapper.AreFacesOnSameIsland(face, this._mobileParty.CurrentNavigationFace, navigationType))
				{
					flag = (num3 >= neededTriesForAlternative || MobilePartyAi.CheckIfThereIsAnyHugeObstacleBetweenPartyAndTarget(this._mobileParty, targetPoint.ToVec2()));
				}
				if (num3 >= neededTriesForAlternative)
				{
					flag = true;
					targetPoint = alternativePosition;
				}
			}
			return flag;
		}

		// Token: 0x06002B00 RID: 11008 RVA: 0x000B4251 File Offset: 0x000B2451
		public void DisableForHours(int hours)
		{
			this._isDisabled = true;
			this._enableAgainAtHour = CampaignTime.Now + CampaignTime.Hours((float)hours);
		}

		// Token: 0x06002B01 RID: 11009 RVA: 0x000B4271 File Offset: 0x000B2471
		public void DisableAi()
		{
			this._isDisabled = true;
			this._enableAgainAtHour = CampaignTime.Never;
		}

		// Token: 0x06002B02 RID: 11010 RVA: 0x000B4285 File Offset: 0x000B2485
		public void EnableAi()
		{
			this._isDisabled = false;
			this._enableAgainAtHour = CampaignTime.Now;
		}

		// Token: 0x06002B03 RID: 11011 RVA: 0x000B429C File Offset: 0x000B249C
		public bool EnableAgainAtHourIsPast()
		{
			return this._enableAgainAtHour.IsPast;
		}

		// Token: 0x06002B04 RID: 11012 RVA: 0x000B42B8 File Offset: 0x000B24B8
		public void SetDoNotAttackMainParty(int hours)
		{
			if (this.DoNotAttackMainPartyUntil.RemainingHoursFromNow < (float)hours)
			{
				this.DoNotAttackMainPartyUntil = CampaignTime.HoursFromNow((float)hours);
			}
		}

		// Token: 0x06002B05 RID: 11013 RVA: 0x000B42E4 File Offset: 0x000B24E4
		internal void ForceDefaultBehaviorUpdate()
		{
			this.DefaultBehaviorNeedsUpdate = true;
		}

		// Token: 0x06002B06 RID: 11014 RVA: 0x000B42ED File Offset: 0x000B24ED
		public void SetInitiative(float attackInitiative, float avoidInitiative, float hoursUntilReset)
		{
			if (this._mobileParty != MobileParty.MainParty)
			{
				this._attackInitiative = attackInitiative;
				this._avoidInitiative = avoidInitiative;
				this._initiativeRestoreTime = CampaignTime.HoursFromNow(hoursUntilReset);
			}
		}

		// Token: 0x06002B07 RID: 11015 RVA: 0x000B4316 File Offset: 0x000B2516
		public void SetDoNotMakeNewDecisions(bool doNotMakeNewDecisions)
		{
			this.DoNotMakeNewDecisions = doNotMakeNewDecisions;
		}

		// Token: 0x06002B08 RID: 11016 RVA: 0x000B431F File Offset: 0x000B251F
		internal void InitializeForOldSaves(float attackInitiative, float avoidInitiative, CampaignTime initiativeRestoreTime, int numberOfRecentFleeingFromAParty, AiBehavior aiBehavior, Vec2 oldAiBehaviorTarget, bool oldAiPathMode, bool oldAiPathNeeded, MoveModeType oldPartyMoveMode, MobileParty oldMoveTargetParty, Vec2 oldNextTargetPosition, Vec2 oldMoveTargetPoint, Vec2 oldAiPathLastPosition, Vec2 oldFormationPosition, IInteractablePoint oldAiBehaviorMapEntity, CampaignTime oldDoNotAttackMainPartyUntil)
		{
			this._attackInitiative = attackInitiative;
			this._avoidInitiative = avoidInitiative;
			this._initiativeRestoreTime = initiativeRestoreTime;
			this.BehaviorTarget = new CampaignVec2(oldAiBehaviorTarget, true);
			this.AiBehaviorInteractable = oldAiBehaviorMapEntity;
			this.DoNotAttackMainPartyUntil = oldDoNotAttackMainPartyUntil;
		}

		// Token: 0x06002B09 RID: 11017 RVA: 0x000B4354 File Offset: 0x000B2554
		internal static bool CheckIfThereIsAnyHugeObstacleBetweenPartyAndTarget(MobileParty party, Vec2 newTargetPosition)
		{
			MobileParty.NavigationType navigationType = party.IsCurrentlyAtSea ? MobileParty.NavigationType.Naval : MobileParty.NavigationType.Default;
			IMapScene mapSceneWrapper = Campaign.Current.MapSceneWrapper;
			Vec2 vec = party.Position.ToVec2();
			PathFaceRecord face = new CampaignVec2(new Vec2((newTargetPosition.x + vec.x * 3f) * 0.25f, (newTargetPosition.y + vec.y * 3f) * 0.25f), !party.IsCurrentlyAtSea).Face;
			PathFaceRecord face2 = new CampaignVec2(new Vec2((newTargetPosition.x + vec.x) * 0.5f, (newTargetPosition.y + vec.y) * 0.5f), !party.IsCurrentlyAtSea).Face;
			PathFaceRecord face3 = new CampaignVec2(new Vec2((newTargetPosition.x * 3f + vec.x) * 0.25f, (newTargetPosition.y * 3f + vec.y) * 0.25f), !party.IsCurrentlyAtSea).Face;
			return face.IsValid() && mapSceneWrapper.AreFacesOnSameIsland(face, party.CurrentNavigationFace, navigationType) && face2.IsValid() && mapSceneWrapper.AreFacesOnSameIsland(face2, party.CurrentNavigationFace, navigationType) && face3.IsValid() && mapSceneWrapper.AreFacesOnSameIsland(face3, party.CurrentNavigationFace, navigationType);
		}

		// Token: 0x04000C34 RID: 3124
		public static readonly List<ValueTuple<float, Vec2>> DangerousPartiesAndTheirVecs = new List<ValueTuple<float, Vec2>>();

		// Token: 0x04000C35 RID: 3125
		[SaveableField(33)]
		private MobilePartyAi.FleeingData _fleeingData;

		// Token: 0x04000C36 RID: 3126
		[SaveableField(2)]
		private bool _isDisabled;

		// Token: 0x04000C38 RID: 3128
		[SaveableField(5)]
		private readonly MobileParty _mobileParty;

		// Token: 0x04000C39 RID: 3129
		[SaveableField(6)]
		public int HourCounter;

		// Token: 0x04000C3C RID: 3132
		[SaveableField(32)]
		internal CampaignVec2 BehaviorTarget;

		// Token: 0x04000C3D RID: 3133
		[SaveableField(13)]
		private float _attackInitiative = 1f;

		// Token: 0x04000C3E RID: 3134
		[SaveableField(14)]
		private float _avoidInitiative = 1f;

		// Token: 0x04000C3F RID: 3135
		[SaveableField(15)]
		private CampaignTime _initiativeRestoreTime;

		// Token: 0x04000C41 RID: 3137
		[SaveableField(18)]
		private CampaignTime _nextAiCheckTime;

		// Token: 0x04000C42 RID: 3138
		[SaveableField(19)]
		internal bool DefaultBehaviorNeedsUpdate;

		// Token: 0x04000C43 RID: 3139
		[SaveableField(30)]
		private IInteractablePoint _aiBehaviorInteractable;

		// Token: 0x02000684 RID: 1668
		public class FleeingData
		{
			// Token: 0x06005168 RID: 20840 RVA: 0x00183461 File Offset: 0x00181661
			internal static void AutoGeneratedStaticCollectObjectsFleeingData(object o, List<object> collectedObjects)
			{
				((MobilePartyAi.FleeingData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005169 RID: 20841 RVA: 0x0018346F File Offset: 0x0018166F
			protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
			}

			// Token: 0x0600516A RID: 20842 RVA: 0x00183471 File Offset: 0x00181671
			internal static object AutoGeneratedGetMemberValueAlreadyReachedTheDestinationWhileFleeing(object o)
			{
				return ((MobilePartyAi.FleeingData)o).AlreadyReachedTheDestinationWhileFleeing;
			}

			// Token: 0x0600516B RID: 20843 RVA: 0x00183483 File Offset: 0x00181683
			internal static object AutoGeneratedGetMemberValueShouldFleeClockWise(object o)
			{
				return ((MobilePartyAi.FleeingData)o).ShouldFleeClockWise;
			}

			// Token: 0x0600516C RID: 20844 RVA: 0x00183495 File Offset: 0x00181695
			internal static object AutoGeneratedGetMemberValueCwFleeDirectionIsBlocked(object o)
			{
				return ((MobilePartyAi.FleeingData)o).CwFleeDirectionIsBlocked;
			}

			// Token: 0x0600516D RID: 20845 RVA: 0x001834A7 File Offset: 0x001816A7
			internal static object AutoGeneratedGetMemberValueCcwFleeDirectionIsBlocked(object o)
			{
				return ((MobilePartyAi.FleeingData)o).CcwFleeDirectionIsBlocked;
			}

			// Token: 0x0600516E RID: 20846 RVA: 0x001834B9 File Offset: 0x001816B9
			public void Clear()
			{
				this.AlreadyReachedTheDestinationWhileFleeing = false;
				this.ShouldFleeClockWise = false;
				this.CwFleeDirectionIsBlocked = false;
				this.CcwFleeDirectionIsBlocked = false;
			}

			// Token: 0x04001A14 RID: 6676
			[SaveableField(1)]
			public bool AlreadyReachedTheDestinationWhileFleeing;

			// Token: 0x04001A15 RID: 6677
			[SaveableField(2)]
			public bool ShouldFleeClockWise;

			// Token: 0x04001A16 RID: 6678
			[SaveableField(3)]
			public bool CwFleeDirectionIsBlocked;

			// Token: 0x04001A17 RID: 6679
			[SaveableField(4)]
			public bool CcwFleeDirectionIsBlocked;
		}
	}
}
