using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000300 RID: 768
	public abstract class PartyComponent
	{
		// Token: 0x06002C5A RID: 11354 RVA: 0x000BA3FC File Offset: 0x000B85FC
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x17000AF6 RID: 2806
		// (get) Token: 0x06002C5B RID: 11355 RVA: 0x000BA3FE File Offset: 0x000B85FE
		// (set) Token: 0x06002C5C RID: 11356 RVA: 0x000BA406 File Offset: 0x000B8606
		public MobileParty MobileParty { get; private set; }

		// Token: 0x17000AF7 RID: 2807
		// (get) Token: 0x06002C5D RID: 11357 RVA: 0x000BA40F File Offset: 0x000B860F
		public PartyBase Party
		{
			get
			{
				return this.MobileParty.Party;
			}
		}

		// Token: 0x17000AF8 RID: 2808
		// (get) Token: 0x06002C5E RID: 11358
		public abstract Hero PartyOwner { get; }

		// Token: 0x17000AF9 RID: 2809
		// (get) Token: 0x06002C5F RID: 11359
		public abstract TextObject Name { get; }

		// Token: 0x17000AFA RID: 2810
		// (get) Token: 0x06002C60 RID: 11360
		public abstract Settlement HomeSettlement { get; }

		// Token: 0x17000AFB RID: 2811
		// (get) Token: 0x06002C61 RID: 11361 RVA: 0x000BA41C File Offset: 0x000B861C
		public virtual bool AvoidHostileActions
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000AFC RID: 2812
		// (get) Token: 0x06002C62 RID: 11362 RVA: 0x000BA41F File Offset: 0x000B861F
		public virtual int WagePaymentLimit
		{
			get
			{
				return Campaign.Current.Models.PartyWageModel.MaxWagePaymentLimit;
			}
		}

		// Token: 0x06002C63 RID: 11363 RVA: 0x000BA435 File Offset: 0x000B8635
		public virtual void SetWagePaymentLimit(int newLimit)
		{
			Debug.FailedAssert("Invalid set wage payment limit function usage!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "SetWagePaymentLimit", 30);
		}

		// Token: 0x17000AFD RID: 2813
		// (get) Token: 0x06002C64 RID: 11364 RVA: 0x000BA44D File Offset: 0x000B864D
		public virtual Hero Leader
		{
			get
			{
				return null;
			}
		}

		// Token: 0x17000AFE RID: 2814
		// (get) Token: 0x06002C65 RID: 11365 RVA: 0x000BA450 File Offset: 0x000B8650
		public Banner Banner
		{
			get
			{
				return this.MobileParty.Banner;
			}
		}

		// Token: 0x06002C66 RID: 11366
		public abstract Banner GetDefaultComponentBanner();

		// Token: 0x17000AFF RID: 2815
		// (get) Token: 0x06002C67 RID: 11367 RVA: 0x000BA45D File Offset: 0x000B865D
		public virtual bool CanHaveNavalNavigationCapability
		{
			get
			{
				Clan actualClan = this.MobileParty.ActualClan;
				return actualClan != null && actualClan.HasNavalNavigationCapability;
			}
		}

		// Token: 0x17000B00 RID: 2816
		// (get) Token: 0x06002C68 RID: 11368 RVA: 0x000BA475 File Offset: 0x000B8675
		public virtual bool CanHaveLandNavigationCapability
		{
			get
			{
				return true;
			}
		}

		// Token: 0x06002C69 RID: 11369 RVA: 0x000BA478 File Offset: 0x000B8678
		internal void Create(MobileParty party)
		{
			this.MobileParty = party;
			this.OnMobilePartySetOnCreation();
		}

		// Token: 0x06002C6A RID: 11370 RVA: 0x000BA487 File Offset: 0x000B8687
		internal void Initialize(MobileParty party)
		{
			this.MobileParty = party;
			this.OnInitialize();
		}

		// Token: 0x06002C6B RID: 11371 RVA: 0x000BA496 File Offset: 0x000B8696
		internal void Finish()
		{
			this.OnFinalize();
		}

		// Token: 0x06002C6C RID: 11372 RVA: 0x000BA49E File Offset: 0x000B869E
		protected virtual void OnMobilePartySetOnCreation()
		{
		}

		// Token: 0x06002C6D RID: 11373 RVA: 0x000BA4A0 File Offset: 0x000B86A0
		protected virtual void OnInitialize()
		{
		}

		// Token: 0x06002C6E RID: 11374 RVA: 0x000BA4A2 File Offset: 0x000B86A2
		protected virtual void OnFinalize()
		{
		}

		// Token: 0x06002C6F RID: 11375 RVA: 0x000BA4A4 File Offset: 0x000B86A4
		public virtual void ClearCachedName()
		{
		}

		// Token: 0x06002C70 RID: 11376 RVA: 0x000BA4A8 File Offset: 0x000B86A8
		public void ChangePartyLeader(Hero newLeader)
		{
			if (newLeader != null && !this.MobileParty.MemberRoster.Contains(newLeader.CharacterObject))
			{
				Debug.FailedAssert(string.Concat(new object[]
				{
					(newLeader != null) ? newLeader.Name : null,
					" is not a member of ",
					this.Name,
					"!\nParty leader did not change."
				}), "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "ChangePartyLeader", 67);
				return;
			}
			Hero leader = this.Leader;
			this.OnChangePartyLeader(newLeader);
			if (newLeader == null && this.MobileParty.MapEvent == null)
			{
				this.MobileParty.SetMoveModeHold();
			}
			if (leader != this.Leader)
			{
				CampaignEventDispatcher.Instance.OnPartyLeaderChanged(this.MobileParty, leader);
			}
		}

		// Token: 0x06002C71 RID: 11377 RVA: 0x000BA558 File Offset: 0x000B8758
		protected virtual void OnChangePartyLeader(Hero newLeader)
		{
		}

		// Token: 0x06002C72 RID: 11378 RVA: 0x000BA55A File Offset: 0x000B875A
		public virtual void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
		{
			mountStringId = "";
			harnessStringId = "";
		}

		// Token: 0x020006A4 RID: 1700
		// (Invoke) Token: 0x060051E4 RID: 20964
		public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);
	}
}
