using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Naval;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Settlements.Buildings;
using TaleWorlds.CampaignSystem.Settlements.Workshops;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Settlements
{
	// Token: 0x020003B5 RID: 949
	public class Town : Fief
	{
		// Token: 0x0600377B RID: 14203 RVA: 0x000E37D1 File Offset: 0x000E19D1
		internal static void AutoGeneratedStaticCollectObjectsTown(object o, List<object> collectedObjects)
		{
			((Town)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600377C RID: 14204 RVA: 0x000E37E0 File Offset: 0x000E19E0
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Buildings);
			collectedObjects.Add(this.BuildingsInProgress);
			collectedObjects.Add(this._ownerClan);
			collectedObjects.Add(this._marketData);
			collectedObjects.Add(this._governor);
			collectedObjects.Add(this._soldItems);
			collectedObjects.Add(this.Workshops);
			collectedObjects.Add(this.LastCapturedBy);
		}

		// Token: 0x0600377D RID: 14205 RVA: 0x000E3854 File Offset: 0x000E1A54
		internal static object AutoGeneratedGetMemberValueWorkshops(object o)
		{
			return ((Town)o).Workshops;
		}

		// Token: 0x0600377E RID: 14206 RVA: 0x000E3861 File Offset: 0x000E1A61
		internal static object AutoGeneratedGetMemberValueLastCapturedBy(object o)
		{
			return ((Town)o).LastCapturedBy;
		}

		// Token: 0x0600377F RID: 14207 RVA: 0x000E386E File Offset: 0x000E1A6E
		internal static object AutoGeneratedGetMemberValueGarrisonAutoRecruitmentIsEnabled(object o)
		{
			return ((Town)o).GarrisonAutoRecruitmentIsEnabled;
		}

		// Token: 0x06003780 RID: 14208 RVA: 0x000E3880 File Offset: 0x000E1A80
		internal static object AutoGeneratedGetMemberValueBuildings(object o)
		{
			return ((Town)o).Buildings;
		}

		// Token: 0x06003781 RID: 14209 RVA: 0x000E388D File Offset: 0x000E1A8D
		internal static object AutoGeneratedGetMemberValueBuildingsInProgress(object o)
		{
			return ((Town)o).BuildingsInProgress;
		}

		// Token: 0x06003782 RID: 14210 RVA: 0x000E389A File Offset: 0x000E1A9A
		internal static object AutoGeneratedGetMemberValueBoostBuildingProcess(object o)
		{
			return ((Town)o).BoostBuildingProcess;
		}

		// Token: 0x06003783 RID: 14211 RVA: 0x000E38AC File Offset: 0x000E1AAC
		internal static object AutoGeneratedGetMemberValueInRebelliousState(object o)
		{
			return ((Town)o).InRebelliousState;
		}

		// Token: 0x06003784 RID: 14212 RVA: 0x000E38BE File Offset: 0x000E1ABE
		internal static object AutoGeneratedGetMemberValue_prosperity(object o)
		{
			return ((Town)o)._prosperity;
		}

		// Token: 0x06003785 RID: 14213 RVA: 0x000E38D0 File Offset: 0x000E1AD0
		internal static object AutoGeneratedGetMemberValue_ownerClan(object o)
		{
			return ((Town)o)._ownerClan;
		}

		// Token: 0x06003786 RID: 14214 RVA: 0x000E38DD File Offset: 0x000E1ADD
		internal static object AutoGeneratedGetMemberValue_security(object o)
		{
			return ((Town)o)._security;
		}

		// Token: 0x06003787 RID: 14215 RVA: 0x000E38EF File Offset: 0x000E1AEF
		internal static object AutoGeneratedGetMemberValue_loyalty(object o)
		{
			return ((Town)o)._loyalty;
		}

		// Token: 0x06003788 RID: 14216 RVA: 0x000E3901 File Offset: 0x000E1B01
		internal static object AutoGeneratedGetMemberValue_marketData(object o)
		{
			return ((Town)o)._marketData;
		}

		// Token: 0x06003789 RID: 14217 RVA: 0x000E390E File Offset: 0x000E1B0E
		internal static object AutoGeneratedGetMemberValue_tradeTax(object o)
		{
			return ((Town)o)._tradeTax;
		}

		// Token: 0x0600378A RID: 14218 RVA: 0x000E3920 File Offset: 0x000E1B20
		internal static object AutoGeneratedGetMemberValue_governor(object o)
		{
			return ((Town)o)._governor;
		}

		// Token: 0x0600378B RID: 14219 RVA: 0x000E392D File Offset: 0x000E1B2D
		internal static object AutoGeneratedGetMemberValue_soldItems(object o)
		{
			return ((Town)o)._soldItems;
		}

		// Token: 0x17000D39 RID: 3385
		// (get) Token: 0x0600378C RID: 14220 RVA: 0x000E393A File Offset: 0x000E1B3A
		// (set) Token: 0x0600378D RID: 14221 RVA: 0x000E3942 File Offset: 0x000E1B42
		public float Prosperity
		{
			get
			{
				return this._prosperity;
			}
			set
			{
				this._prosperity = value;
				if (this._prosperity < 0f)
				{
					this._prosperity = 0f;
				}
			}
		}

		// Token: 0x0600378E RID: 14222 RVA: 0x000E3963 File Offset: 0x000E1B63
		public IEnumerable<PartyBase> GetDefenderParties(MapEvent.BattleTypes battleType)
		{
			yield return base.Settlement.Party;
			foreach (MobileParty mobileParty in base.Settlement.Parties)
			{
				if (mobileParty.MapFaction.IsAtWarWith(base.Settlement.SiegeEvent.BesiegerCamp.MapFaction) && mobileParty.IsActive && !mobileParty.IsVillager && !mobileParty.IsCaravan && (!mobileParty.IsMilitia || (!this.InRebelliousState && battleType != MapEvent.BattleTypes.SallyOut)))
				{
					yield return mobileParty.Party;
				}
			}
			List<MobileParty>.Enumerator enumerator = default(List<MobileParty>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x0600378F RID: 14223 RVA: 0x000E397C File Offset: 0x000E1B7C
		public PartyBase GetNextDefenderParty(ref int partyIndex, MapEvent.BattleTypes battleType)
		{
			partyIndex++;
			if (partyIndex == 0)
			{
				return base.Settlement.Party;
			}
			for (int i = partyIndex - 1; i < base.Settlement.Parties.Count; i++)
			{
				MobileParty mobileParty = base.Settlement.Parties[i];
				if (mobileParty.MapFaction.IsAtWarWith(base.Settlement.SiegeEvent.BesiegerCamp.MapFaction) && mobileParty.IsActive && !mobileParty.IsVillager && !mobileParty.IsCaravan && (!mobileParty.IsMilitia || (!this.InRebelliousState && battleType != MapEvent.BattleTypes.SallyOut)))
				{
					partyIndex = i + 1;
					return mobileParty.Party;
				}
			}
			return null;
		}

		// Token: 0x17000D3A RID: 3386
		// (get) Token: 0x06003790 RID: 14224 RVA: 0x000E3A2D File Offset: 0x000E1C2D
		public CultureObject Culture
		{
			get
			{
				return base.Owner.Settlement.Culture;
			}
		}

		// Token: 0x17000D3B RID: 3387
		// (get) Token: 0x06003791 RID: 14225 RVA: 0x000E3A40 File Offset: 0x000E1C40
		public float ProsperityChange
		{
			get
			{
				return Campaign.Current.Models.SettlementProsperityModel.CalculateProsperityChange(this, false).ResultNumber;
			}
		}

		// Token: 0x17000D3C RID: 3388
		// (get) Token: 0x06003792 RID: 14226 RVA: 0x000E3A6B File Offset: 0x000E1C6B
		public ExplainedNumber ProsperityChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementProsperityModel.CalculateProsperityChange(this, true);
			}
		}

		// Token: 0x17000D3D RID: 3389
		// (get) Token: 0x06003793 RID: 14227 RVA: 0x000E3A84 File Offset: 0x000E1C84
		public float FoodChange
		{
			get
			{
				return Campaign.Current.Models.SettlementFoodModel.CalculateTownFoodStocksChange(this, true, false).ResultNumber;
			}
		}

		// Token: 0x17000D3E RID: 3390
		// (get) Token: 0x06003794 RID: 14228 RVA: 0x000E3AB0 File Offset: 0x000E1CB0
		public float FoodChangeWithoutMarketStocks
		{
			get
			{
				return Campaign.Current.Models.SettlementFoodModel.CalculateTownFoodStocksChange(this, false, false).ResultNumber;
			}
		}

		// Token: 0x17000D3F RID: 3391
		// (get) Token: 0x06003795 RID: 14229 RVA: 0x000E3ADC File Offset: 0x000E1CDC
		public ExplainedNumber FoodChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementFoodModel.CalculateTownFoodStocksChange(this, true, true);
			}
		}

		// Token: 0x17000D40 RID: 3392
		// (get) Token: 0x06003796 RID: 14230 RVA: 0x000E3AF8 File Offset: 0x000E1CF8
		public float LoyaltyChange
		{
			get
			{
				return Campaign.Current.Models.SettlementLoyaltyModel.CalculateLoyaltyChange(this, false).ResultNumber;
			}
		}

		// Token: 0x17000D41 RID: 3393
		// (get) Token: 0x06003797 RID: 14231 RVA: 0x000E3B23 File Offset: 0x000E1D23
		public ExplainedNumber LoyaltyChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementLoyaltyModel.CalculateLoyaltyChange(this, true);
			}
		}

		// Token: 0x17000D42 RID: 3394
		// (get) Token: 0x06003798 RID: 14232 RVA: 0x000E3B3C File Offset: 0x000E1D3C
		public float SecurityChange
		{
			get
			{
				return Campaign.Current.Models.SettlementSecurityModel.CalculateSecurityChange(this, false).ResultNumber;
			}
		}

		// Token: 0x17000D43 RID: 3395
		// (get) Token: 0x06003799 RID: 14233 RVA: 0x000E3B67 File Offset: 0x000E1D67
		public ExplainedNumber SecurityChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementSecurityModel.CalculateSecurityChange(this, true);
			}
		}

		// Token: 0x17000D44 RID: 3396
		// (get) Token: 0x0600379A RID: 14234 RVA: 0x000E3B80 File Offset: 0x000E1D80
		public float MilitiaChange
		{
			get
			{
				return Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaChange(base.Owner.Settlement, false).ResultNumber;
			}
		}

		// Token: 0x17000D45 RID: 3397
		// (get) Token: 0x0600379B RID: 14235 RVA: 0x000E3BB5 File Offset: 0x000E1DB5
		public ExplainedNumber MilitiaChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaChange(base.Owner.Settlement, true);
			}
		}

		// Token: 0x17000D46 RID: 3398
		// (get) Token: 0x0600379C RID: 14236 RVA: 0x000E3BD8 File Offset: 0x000E1DD8
		public float Construction
		{
			get
			{
				return Campaign.Current.Models.BuildingConstructionModel.CalculateDailyConstructionPower(this, false).ResultNumber;
			}
		}

		// Token: 0x17000D47 RID: 3399
		// (get) Token: 0x0600379D RID: 14237 RVA: 0x000E3C03 File Offset: 0x000E1E03
		public ExplainedNumber ConstructionExplanation
		{
			get
			{
				return Campaign.Current.Models.BuildingConstructionModel.CalculateDailyConstructionPower(this, true);
			}
		}

		// Token: 0x17000D48 RID: 3400
		// (get) Token: 0x0600379E RID: 14238 RVA: 0x000E3C1B File Offset: 0x000E1E1B
		// (set) Token: 0x0600379F RID: 14239 RVA: 0x000E3C23 File Offset: 0x000E1E23
		public Clan OwnerClan
		{
			get
			{
				return this._ownerClan;
			}
			set
			{
				if (this._ownerClan != value)
				{
					this.ChangeClanInternal(value);
				}
			}
		}

		// Token: 0x17000D49 RID: 3401
		// (get) Token: 0x060037A0 RID: 14240 RVA: 0x000E3C35 File Offset: 0x000E1E35
		// (set) Token: 0x060037A1 RID: 14241 RVA: 0x000E3C3D File Offset: 0x000E1E3D
		public float Security
		{
			get
			{
				return this._security;
			}
			set
			{
				this._security = value;
				if (this._security < 0f)
				{
					this._security = 0f;
					return;
				}
				if (this._security > 100f)
				{
					this._security = 100f;
				}
			}
		}

		// Token: 0x17000D4A RID: 3402
		// (get) Token: 0x060037A2 RID: 14242 RVA: 0x000E3C77 File Offset: 0x000E1E77
		// (set) Token: 0x060037A3 RID: 14243 RVA: 0x000E3C7F File Offset: 0x000E1E7F
		public float Loyalty
		{
			get
			{
				return this._loyalty;
			}
			set
			{
				this._loyalty = value;
				if (this._loyalty < 0f)
				{
					this._loyalty = 0f;
					return;
				}
				if (this._loyalty > 100f)
				{
					this._loyalty = 100f;
				}
			}
		}

		// Token: 0x17000D4B RID: 3403
		// (get) Token: 0x060037A4 RID: 14244 RVA: 0x000E3CB9 File Offset: 0x000E1EB9
		public MBReadOnlyList<Village> TradeBoundVillages
		{
			get
			{
				return this._tradeBoundVillagesCache;
			}
		}

		// Token: 0x060037A5 RID: 14245 RVA: 0x000E3CC1 File Offset: 0x000E1EC1
		internal void SetTradeBoundVillageInternal(Village village)
		{
			this._tradeBoundVillagesCache.Add(village);
		}

		// Token: 0x060037A6 RID: 14246 RVA: 0x000E3CCF File Offset: 0x000E1ECF
		internal void RemoveTradeBoundVillageInternal(Village village)
		{
			this._tradeBoundVillagesCache.Remove(village);
		}

		// Token: 0x060037A7 RID: 14247 RVA: 0x000E3CE0 File Offset: 0x000E1EE0
		public int FoodStocksUpperLimit()
		{
			ExplainedNumber explainedNumber = new ExplainedNumber((float)Campaign.Current.Models.SettlementFoodModel.FoodStocksUpperLimit, false, null);
			if (this.IsCastle)
			{
				explainedNumber.Add((float)Campaign.Current.Models.SettlementFoodModel.CastleFoodStockUpperLimitBonus, null, null);
			}
			this.AddEffectOfBuildings(BuildingEffectEnum.FoodStock, ref explainedNumber);
			return (int)explainedNumber.ResultNumber;
		}

		// Token: 0x17000D4C RID: 3404
		// (get) Token: 0x060037A8 RID: 14248 RVA: 0x000E3D43 File Offset: 0x000E1F43
		// (set) Token: 0x060037A9 RID: 14249 RVA: 0x000E3D4B File Offset: 0x000E1F4B
		[SaveableProperty(1005)]
		public Workshop[] Workshops { get; protected set; }

		// Token: 0x17000D4D RID: 3405
		// (get) Token: 0x060037AA RID: 14250 RVA: 0x000E3D54 File Offset: 0x000E1F54
		public Building CurrentBuilding
		{
			get
			{
				if (!this.BuildingsInProgress.IsEmpty<Building>())
				{
					return this.BuildingsInProgress.Peek();
				}
				return this.CurrentDefaultBuilding;
			}
		}

		// Token: 0x17000D4E RID: 3406
		// (get) Token: 0x060037AB RID: 14251 RVA: 0x000E3D75 File Offset: 0x000E1F75
		public Building CurrentDefaultBuilding
		{
			get
			{
				if (!this.BuildingsInProgress.IsEmpty<Building>())
				{
					return null;
				}
				return this.Buildings.FirstOrDefaultQ((Building k) => k.IsCurrentlyDefault);
			}
		}

		// Token: 0x17000D4F RID: 3407
		// (get) Token: 0x060037AC RID: 14252 RVA: 0x000E3DB0 File Offset: 0x000E1FB0
		public TownMarketData MarketData
		{
			get
			{
				return this._marketData;
			}
		}

		// Token: 0x17000D50 RID: 3408
		// (get) Token: 0x060037AD RID: 14253 RVA: 0x000E3DB8 File Offset: 0x000E1FB8
		// (set) Token: 0x060037AE RID: 14254 RVA: 0x000E3DC0 File Offset: 0x000E1FC0
		public int TradeTaxAccumulated
		{
			get
			{
				return this._tradeTax;
			}
			set
			{
				this._tradeTax = value;
			}
		}

		// Token: 0x17000D51 RID: 3409
		// (get) Token: 0x060037AF RID: 14255 RVA: 0x000E3DC9 File Offset: 0x000E1FC9
		// (set) Token: 0x060037B0 RID: 14256 RVA: 0x000E3DD1 File Offset: 0x000E1FD1
		public Hero Governor
		{
			get
			{
				return this._governor;
			}
			set
			{
				if (this._governor != value)
				{
					if (this._governor != null)
					{
						this._governor.GovernorOf = null;
					}
					this._governor = value;
					if (this._governor != null)
					{
						this._governor.GovernorOf = this;
					}
				}
			}
		}

		// Token: 0x17000D52 RID: 3410
		// (get) Token: 0x060037B1 RID: 14257 RVA: 0x000E3E0B File Offset: 0x000E200B
		public MBReadOnlyList<Ship> AvailableShips
		{
			get
			{
				return base.Settlement.Party.Ships;
			}
		}

		// Token: 0x060037B2 RID: 14258 RVA: 0x000E3E20 File Offset: 0x000E2020
		public Town()
		{
			this.Buildings = new MBList<Building>();
			this.BuildingsInProgress = new Queue<Building>();
			this.Workshops = new Workshop[0];
			this._marketData = new TownMarketData(this);
			this._tradeBoundVillagesCache = new MBList<Village>();
		}

		// Token: 0x17000D53 RID: 3411
		// (get) Token: 0x060037B3 RID: 14259 RVA: 0x000E3E7F File Offset: 0x000E207F
		public static IEnumerable<Town> AllFiefs
		{
			get
			{
				foreach (Town town in Campaign.Current.AllTowns)
				{
					yield return town;
				}
				List<Town>.Enumerator enumerator = default(List<Town>.Enumerator);
				foreach (Town town2 in Campaign.Current.AllCastles)
				{
					yield return town2;
				}
				enumerator = default(List<Town>.Enumerator);
				yield break;
				yield break;
			}
		}

		// Token: 0x17000D54 RID: 3412
		// (get) Token: 0x060037B4 RID: 14260 RVA: 0x000E3E88 File Offset: 0x000E2088
		public static MBReadOnlyList<Town> AllTowns
		{
			get
			{
				return Campaign.Current.AllTowns;
			}
		}

		// Token: 0x17000D55 RID: 3413
		// (get) Token: 0x060037B5 RID: 14261 RVA: 0x000E3E94 File Offset: 0x000E2094
		public static MBReadOnlyList<Town> AllCastles
		{
			get
			{
				return Campaign.Current.AllCastles;
			}
		}

		// Token: 0x17000D56 RID: 3414
		// (get) Token: 0x060037B6 RID: 14262 RVA: 0x000E3EA0 File Offset: 0x000E20A0
		public override bool IsTown
		{
			get
			{
				return !this._isCastle;
			}
		}

		// Token: 0x17000D57 RID: 3415
		// (get) Token: 0x060037B7 RID: 14263 RVA: 0x000E3EAB File Offset: 0x000E20AB
		public override bool IsCastle
		{
			get
			{
				return this._isCastle;
			}
		}

		// Token: 0x060037B8 RID: 14264 RVA: 0x000E3EB4 File Offset: 0x000E20B4
		public override void OnInit()
		{
			this.Loyalty = (float)base.Owner.RandomIntWithSeed(1337U, 30, 70);
			this.Security = (float)base.Owner.RandomIntWithSeed(1001U, 40, 60);
			this.TradeTaxAccumulated = (this.IsTown ? (1000 + MBRandom.RandomInt(1000)) : 0);
			base.ChangeGold(20000);
		}

		// Token: 0x060037B9 RID: 14265 RVA: 0x000E3F24 File Offset: 0x000E2124
		public override void OnSessionStart()
		{
			List<MatrixFrame> list;
			List<MatrixFrame> list2;
			Campaign.Current.MapSceneWrapper.GetSiegeCampFrames(base.Settlement, out list, out list2);
			this.BesiegerCampPositions1 = list.ToArray();
			this.BesiegerCampPositions2 = list2.ToArray();
		}

		// Token: 0x060037BA RID: 14266 RVA: 0x000E3F64 File Offset: 0x000E2164
		public void InitializeWorkshops(int count)
		{
			if (count > 0)
			{
				this.Workshops = new Workshop[count];
				for (int i = 0; i < count; i++)
				{
					this.Workshops[i] = new Workshop(base.Owner.Settlement, "workshop_" + i);
				}
			}
		}

		// Token: 0x060037BB RID: 14267 RVA: 0x000E3FB5 File Offset: 0x000E21B5
		[LoadInitializationCallback]
		private void OnLoad()
		{
			this._tradeBoundVillagesCache = new MBList<Village>();
		}

		// Token: 0x060037BC RID: 14268 RVA: 0x000E3FC2 File Offset: 0x000E21C2
		protected override void PreAfterLoad()
		{
			Clan ownerClan = this._ownerClan;
			if (ownerClan == null)
			{
				return;
			}
			ownerClan.OnFortificationAdded(this);
		}

		// Token: 0x060037BD RID: 14269 RVA: 0x000E3FD8 File Offset: 0x000E21D8
		protected override void AfterLoad()
		{
			Workshop[] workshops = this.Workshops;
			for (int i = 0; i < workshops.Length; i++)
			{
				workshops[i].AfterLoad();
			}
			bool flag = false;
			for (int j = this.Buildings.Count - 1; j >= 0; j--)
			{
				Building building = this.Buildings[j];
				if (building.BuildingType == null || !building.BuildingType.IsReady)
				{
					this.Buildings.RemoveAt(j);
					flag = true;
				}
			}
			if (!flag)
			{
				foreach (Building building2 in this.BuildingsInProgress)
				{
					if (building2.BuildingType == null || !building2.BuildingType.IsReady)
					{
						flag = true;
						break;
					}
				}
			}
			if (flag)
			{
				this.BuildingsInProgress.Clear();
			}
			if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.0", 0) && (!this.OwnerClan.MapFaction.IsKingdomFaction || (this.OwnerClan.MapFaction as Kingdom).Clans.Count == 1))
			{
				base.IsOwnerUnassigned = false;
			}
			if (this.Governor != null && this.Governor.GovernorOf == null)
			{
				this.Governor = null;
			}
		}

		// Token: 0x17000D58 RID: 3416
		// (get) Token: 0x060037BE RID: 14270 RVA: 0x000E412C File Offset: 0x000E232C
		public IReadOnlyCollection<Town.SellLog> SoldItems
		{
			get
			{
				return this._soldItems;
			}
		}

		// Token: 0x17000D59 RID: 3417
		// (get) Token: 0x060037BF RID: 14271 RVA: 0x000E4134 File Offset: 0x000E2334
		public override IFaction MapFaction
		{
			get
			{
				Clan ownerClan = this.OwnerClan;
				if (ownerClan == null)
				{
					return null;
				}
				return ownerClan.MapFaction;
			}
		}

		// Token: 0x17000D5A RID: 3418
		// (get) Token: 0x060037C0 RID: 14272 RVA: 0x000E4147 File Offset: 0x000E2347
		public bool IsUnderSiege
		{
			get
			{
				return base.Settlement.IsUnderSiege;
			}
		}

		// Token: 0x17000D5B RID: 3419
		// (get) Token: 0x060037C1 RID: 14273 RVA: 0x000E4154 File Offset: 0x000E2354
		[CachedData]
		public MBReadOnlyList<Village> Villages
		{
			get
			{
				return base.Settlement.BoundVillages;
			}
		}

		// Token: 0x17000D5C RID: 3420
		// (get) Token: 0x060037C2 RID: 14274 RVA: 0x000E4161 File Offset: 0x000E2361
		// (set) Token: 0x060037C3 RID: 14275 RVA: 0x000E4169 File Offset: 0x000E2369
		[SaveableProperty(1030)]
		public Clan LastCapturedBy { get; set; }

		// Token: 0x060037C4 RID: 14276 RVA: 0x000E4172 File Offset: 0x000E2372
		private void ChangeClanInternal(Clan value)
		{
			if (this._ownerClan != null)
			{
				this.RemoveOwnerClan();
			}
			this._ownerClan = value;
			if (this._ownerClan != null)
			{
				this.SetNewOwnerClan();
			}
		}

		// Token: 0x060037C5 RID: 14277 RVA: 0x000E4198 File Offset: 0x000E2398
		public void AddEffectOfBuildings(BuildingEffectEnum buildingEffect, ref ExplainedNumber result)
		{
			foreach (Building building in this.Buildings)
			{
				building.AddEffectOfBuilding(buildingEffect, ref result);
			}
		}

		// Token: 0x060037C6 RID: 14278 RVA: 0x000E41EC File Offset: 0x000E23EC
		private void SetNewOwnerClan()
		{
			this._ownerClan.OnFortificationAdded(this);
			foreach (Village village in base.Settlement.BoundVillages)
			{
				village.Settlement.Party.SetVisualAsDirty();
				VillagerPartyComponent villagerPartyComponent = village.VillagerPartyComponent;
				if (villagerPartyComponent != null)
				{
					villagerPartyComponent.MobileParty.Party.SetVisualAsDirty();
				}
			}
		}

		// Token: 0x060037C7 RID: 14279 RVA: 0x000E4274 File Offset: 0x000E2474
		private void RemoveOwnerClan()
		{
			this._ownerClan.OnFortificationRemoved(this);
		}

		// Token: 0x17000D5D RID: 3421
		// (get) Token: 0x060037C8 RID: 14280 RVA: 0x000E4282 File Offset: 0x000E2482
		public bool HasTournament
		{
			get
			{
				return this.IsTown && Campaign.Current.TournamentManager.GetTournamentGame(this) != null;
			}
		}

		// Token: 0x060037C9 RID: 14281 RVA: 0x000E42A4 File Offset: 0x000E24A4
		internal void DailyTick()
		{
			this.Loyalty += this.LoyaltyChange;
			this.Security += this.SecurityChange;
			if (base.FoodStocks > 0f)
			{
				base.Owner.OnConsumedFood();
			}
			base.FoodStocks += this.FoodChange;
			if (base.FoodStocks < 0f)
			{
				base.FoodStocks = 0f;
				base.Owner.RemainingFoodPercentage = -100;
			}
			else
			{
				base.Owner.RemainingFoodPercentage = 0;
			}
			if (base.FoodStocks > (float)this.FoodStocksUpperLimit())
			{
				base.FoodStocks = (float)this.FoodStocksUpperLimit();
			}
			if (this.Governor != null)
			{
				if (this.Governor.GetPerkValue(DefaultPerks.Roguery.WhiteLies) && MBRandom.RandomFloat <= DefaultPerks.Roguery.WhiteLies.SecondaryBonus)
				{
					Hero randomElement = base.Settlement.Notables.GetRandomElement<Hero>();
					if (randomElement != null)
					{
						ChangeRelationAction.ApplyRelationChangeBetweenHeroes(this.Governor, randomElement, 1, true);
					}
				}
				if (this.Governor.GetPerkValue(DefaultPerks.Roguery.Scarface) && MBRandom.RandomFloat <= DefaultPerks.Roguery.Scarface.SecondaryBonus)
				{
					Hero randomElementWithPredicate = base.Settlement.Notables.GetRandomElementWithPredicate((Hero x) => x.IsGangLeader);
					if (randomElementWithPredicate != null)
					{
						ChangeRelationAction.ApplyRelationChangeBetweenHeroes(this.Governor, randomElementWithPredicate, 1, true);
					}
				}
			}
			this.Prosperity += this.ProsperityChange;
			base.Owner.Settlement.Militia += this.MilitiaChange;
			this.RepairWallsOfSettlementDaily();
		}

		// Token: 0x060037CA RID: 14282 RVA: 0x000E443C File Offset: 0x000E263C
		private void RepairWallsOfSettlementDaily()
		{
			float num = Campaign.Current.Models.SettlementGarrisonModel.GetMaximumDailyRepairAmount(base.Settlement) / base.Settlement.MaxHitPointsOfOneWallSection;
			for (int i = 0; i < base.Settlement.SettlementWallSectionHitPointsRatioList.Count; i++)
			{
				float num2 = base.Settlement.SettlementWallSectionHitPointsRatioList[i];
				float num3 = MathF.Min(1f - num2, num);
				base.Settlement.SetWallSectionHitPointsRatioAtIndex(i, num2 + num3);
				num -= num3;
				if (num3 <= 0f)
				{
					break;
				}
			}
		}

		// Token: 0x060037CB RID: 14283 RVA: 0x000E44C8 File Offset: 0x000E26C8
		public int GetWallLevel()
		{
			int result = 0;
			foreach (Building building in this.Buildings)
			{
				if (building.BuildingType == DefaultBuildingTypes.SettlementFortifications && this.IsTown)
				{
					result = building.CurrentLevel;
					break;
				}
				if (building.BuildingType == DefaultBuildingTypes.CastleFortifications && this.IsCastle)
				{
					result = building.CurrentLevel;
					break;
				}
			}
			return result;
		}

		// Token: 0x060037CC RID: 14284 RVA: 0x000E4554 File Offset: 0x000E2754
		public override string ToString()
		{
			return base.Name.ToString();
		}

		// Token: 0x060037CD RID: 14285 RVA: 0x000E4564 File Offset: 0x000E2764
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			this._isCastle = (node.Attributes["is_castle"] != null && bool.Parse(node.Attributes["is_castle"].Value));
			base.BackgroundCropPosition = float.Parse(node.Attributes["background_crop_position"].Value);
			base.BackgroundMeshName = node.Attributes["background_mesh"].Value;
			base.WaitMeshName = node.Attributes["wait_mesh"].Value;
			if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
			{
				this._prosperity = float.Parse(node.Attributes["prosperity"].Value);
			}
			this.BesiegerCampPositions1 = new MatrixFrame[]
			{
				MatrixFrame.Identity
			};
			this.BesiegerCampPositions2 = new MatrixFrame[]
			{
				MatrixFrame.Identity
			};
			if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
			{
				this.Buildings.Clear();
				foreach (object obj in node.ChildNodes)
				{
					XmlNode xmlNode = (XmlNode)obj;
					if (xmlNode.Name.Equals("Buildings"))
					{
						foreach (object obj2 in xmlNode.ChildNodes)
						{
							XmlNode xmlNode2 = (XmlNode)obj2;
							if (xmlNode2.Name.Equals("Building"))
							{
								string value = xmlNode2.Attributes["id"].Value;
								XmlAttribute xmlAttribute = xmlNode2.Attributes["level"];
								BuildingType @object = MBObjectManager.Instance.GetObject<BuildingType>(value);
								int currentLevel = @object.StartLevel;
								if (xmlAttribute != null)
								{
									currentLevel = int.Parse(xmlAttribute.Value);
								}
								this.Buildings.Add(new Building(@object, this, 0f, currentLevel));
							}
						}
					}
				}
			}
		}

		// Token: 0x060037CE RID: 14286 RVA: 0x000E47A8 File Offset: 0x000E29A8
		public void SetSoldItems(IEnumerable<Town.SellLog> logList)
		{
			this._soldItems = logList.ToArray<Town.SellLog>();
		}

		// Token: 0x060037CF RID: 14287 RVA: 0x000E47B6 File Offset: 0x000E29B6
		public override int GetItemPrice(ItemObject item, MobileParty tradingParty = null, bool isSelling = false)
		{
			return this.MarketData.GetPrice(item, tradingParty, isSelling, null);
		}

		// Token: 0x060037D0 RID: 14288 RVA: 0x000E47C7 File Offset: 0x000E29C7
		public override int GetItemPrice(EquipmentElement itemRosterElement, MobileParty tradingParty = null, bool isSelling = false)
		{
			return this.MarketData.GetPrice(itemRosterElement, tradingParty, isSelling, null);
		}

		// Token: 0x060037D1 RID: 14289 RVA: 0x000E47D8 File Offset: 0x000E29D8
		public override SettlementComponent.ProsperityLevel GetProsperityLevel()
		{
			if (this._prosperity >= 5000f)
			{
				return SettlementComponent.ProsperityLevel.High;
			}
			if (this._prosperity >= 2000f)
			{
				return SettlementComponent.ProsperityLevel.Mid;
			}
			return SettlementComponent.ProsperityLevel.Low;
		}

		// Token: 0x060037D2 RID: 14290 RVA: 0x000E47F9 File Offset: 0x000E29F9
		protected override void OnInventoryUpdated(ItemRosterElement item, int count)
		{
			this.MarketData.OnTownInventoryUpdated(item, count);
		}

		// Token: 0x060037D3 RID: 14291 RVA: 0x000E4808 File Offset: 0x000E2A08
		public float GetItemCategoryPriceIndex(ItemCategory itemCategory)
		{
			return this.MarketData.GetPriceFactor(itemCategory);
		}

		// Token: 0x060037D4 RID: 14292 RVA: 0x000E4816 File Offset: 0x000E2A16
		public MBReadOnlyList<Settlement> GetNeighborFortifications(MobileParty.NavigationType navigationType)
		{
			return Campaign.Current.Models.MapDistanceModel.GetNeighborsOfFortification(this, navigationType);
		}

		// Token: 0x0400110E RID: 4366
		private const int InitialTownGold = 20000;

		// Token: 0x0400110F RID: 4367
		private const int HighProsperityThreshold = 5000;

		// Token: 0x04001110 RID: 4368
		private const int MidProsperityThreshold = 2000;

		// Token: 0x04001111 RID: 4369
		[SaveableField(1017)]
		private float _prosperity;

		// Token: 0x04001112 RID: 4370
		[CachedData]
		public MatrixFrame[] BesiegerCampPositions1;

		// Token: 0x04001113 RID: 4371
		[CachedData]
		public MatrixFrame[] BesiegerCampPositions2;

		// Token: 0x04001114 RID: 4372
		private bool _isCastle;

		// Token: 0x04001115 RID: 4373
		[SaveableField(1016)]
		public bool GarrisonAutoRecruitmentIsEnabled = true;

		// Token: 0x04001116 RID: 4374
		[SaveableField(1040)]
		private Clan _ownerClan;

		// Token: 0x04001117 RID: 4375
		[SaveableField(1015)]
		private float _security;

		// Token: 0x04001118 RID: 4376
		[SaveableField(1014)]
		private float _loyalty;

		// Token: 0x04001119 RID: 4377
		[CachedData]
		private MBList<Village> _tradeBoundVillagesCache;

		// Token: 0x0400111B RID: 4379
		[SaveableField(1006)]
		public MBList<Building> Buildings;

		// Token: 0x0400111C RID: 4380
		[SaveableField(1007)]
		public Queue<Building> BuildingsInProgress;

		// Token: 0x0400111D RID: 4381
		[SaveableField(1008)]
		public int BoostBuildingProcess;

		// Token: 0x0400111E RID: 4382
		[SaveableField(1009)]
		private readonly TownMarketData _marketData;

		// Token: 0x0400111F RID: 4383
		[SaveableField(1010)]
		private int _tradeTax;

		// Token: 0x04001120 RID: 4384
		[SaveableField(1011)]
		public bool InRebelliousState;

		// Token: 0x04001121 RID: 4385
		[SaveableField(1012)]
		private Hero _governor;

		// Token: 0x04001122 RID: 4386
		[SaveableField(1013)]
		private Town.SellLog[] _soldItems = new Town.SellLog[0];

		// Token: 0x02000773 RID: 1907
		public struct SellLog
		{
			// Token: 0x06006133 RID: 24883 RVA: 0x001B810C File Offset: 0x001B630C
			public static void AutoGeneratedStaticCollectObjectsSellLog(object o, List<object> collectedObjects)
			{
				((Town.SellLog)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06006134 RID: 24884 RVA: 0x001B8128 File Offset: 0x001B6328
			private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				collectedObjects.Add(this.Category);
			}

			// Token: 0x06006135 RID: 24885 RVA: 0x001B8138 File Offset: 0x001B6338
			internal static object AutoGeneratedGetMemberValueCategory(object o)
			{
				return ((Town.SellLog)o).Category;
			}

			// Token: 0x06006136 RID: 24886 RVA: 0x001B8154 File Offset: 0x001B6354
			internal static object AutoGeneratedGetMemberValueNumber(object o)
			{
				return ((Town.SellLog)o).Number;
			}

			// Token: 0x170014FD RID: 5373
			// (get) Token: 0x06006137 RID: 24887 RVA: 0x001B8174 File Offset: 0x001B6374
			// (set) Token: 0x06006138 RID: 24888 RVA: 0x001B817C File Offset: 0x001B637C
			[SaveableProperty(200)]
			public ItemCategory Category { get; private set; }

			// Token: 0x170014FE RID: 5374
			// (get) Token: 0x06006139 RID: 24889 RVA: 0x001B8185 File Offset: 0x001B6385
			// (set) Token: 0x0600613A RID: 24890 RVA: 0x001B818D File Offset: 0x001B638D
			[SaveableProperty(201)]
			public int Number { get; private set; }

			// Token: 0x0600613B RID: 24891 RVA: 0x001B8196 File Offset: 0x001B6396
			public SellLog(ItemCategory category, int count)
			{
				this.Category = category;
				this.Number = count;
			}
		}
	}
}
