using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election
{
	// Token: 0x020002CA RID: 714
	public class TradeAgreementDecision : KingdomDecision
	{
		// Token: 0x0600267D RID: 9853 RVA: 0x000A0EA6 File Offset: 0x0009F0A6
		internal static void AutoGeneratedStaticCollectObjectsTradeAgreementDecision(object o, List<object> collectedObjects)
		{
			((TradeAgreementDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600267E RID: 9854 RVA: 0x000A0EB4 File Offset: 0x0009F0B4
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.TargetKingdom);
		}

		// Token: 0x0600267F RID: 9855 RVA: 0x000A0EC9 File Offset: 0x0009F0C9
		internal static object AutoGeneratedGetMemberValueTargetKingdom(object o)
		{
			return ((TradeAgreementDecision)o).TargetKingdom;
		}

		// Token: 0x06002680 RID: 9856 RVA: 0x000A0ED6 File Offset: 0x0009F0D6
		public TradeAgreementDecision(Clan proposerClan, Kingdom targetKingdom) : base(proposerClan)
		{
			this.TargetKingdom = targetKingdom;
			this._tradeAgreementsCampaignBehavior = Campaign.Current.GetCampaignBehavior<ITradeAgreementsCampaignBehavior>();
		}

		// Token: 0x06002681 RID: 9857 RVA: 0x000A0EF6 File Offset: 0x0009F0F6
		public override bool OnShowDecision()
		{
			if (this.TargetKingdom == Clan.PlayerClan.Kingdom && !Hero.MainHero.Clan.IsUnderMercenaryService)
			{
				this._tradeAgreementsCampaignBehavior.OnTradeAgreementOfferedToPlayer(base.Kingdom);
				return false;
			}
			return true;
		}

		// Token: 0x06002682 RID: 9858 RVA: 0x000A0F30 File Offset: 0x0009F130
		public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
		{
			if (((TradeAgreementDecision.TradeAgreementDecisionOutcome)chosenOutcome).ShouldTradeAgreementStart)
			{
				ITradeAgreementsCampaignBehavior campaignBehavior = Campaign.Current.GetCampaignBehavior<ITradeAgreementsCampaignBehavior>();
				if (campaignBehavior == null)
				{
					return;
				}
				campaignBehavior.MakeTradeAgreement(base.Kingdom, this.TargetKingdom, Campaign.Current.Models.TradeAgreementModel.GetTradeAgreementDurationInYears(base.Kingdom, this.TargetKingdom));
			}
		}

		// Token: 0x06002683 RID: 9859 RVA: 0x000A0F8A File Offset: 0x0009F18A
		public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
		{
		}

		// Token: 0x06002684 RID: 9860 RVA: 0x000A0F8C File Offset: 0x0009F18C
		public static Clan GetProposerClanForPlayerKingdom(Kingdom target)
		{
			if (Clan.PlayerClan.Kingdom == null)
			{
				return null;
			}
			TextObject textObject;
			Clan clan = (Clan.PlayerClan.Kingdom.RulingClan != Clan.PlayerClan && Campaign.Current.Models.TradeAgreementModel.GetScoreOfStartingTradeAgreement(Clan.PlayerClan.Kingdom, target, Clan.PlayerClan.Kingdom.RulingClan, out textObject, false) > 50f) ? Clan.PlayerClan.Kingdom.RulingClan : null;
			if (clan == null)
			{
				List<Clan> list = Clan.PlayerClan.Kingdom.Clans.Where(delegate(Clan x)
				{
					TextObject textObject2;
					return !x.IsUnderMercenaryService && x != Clan.PlayerClan && Campaign.Current.Models.TradeAgreementModel.GetScoreOfStartingTradeAgreement(Clan.PlayerClan.Kingdom, target, x, out textObject2, false) > 50f;
				}).ToList<Clan>();
				if (list.Count > 0)
				{
					clan = list.MaxBy(delegate(Clan x)
					{
						TextObject textObject2;
						return Campaign.Current.Models.TradeAgreementModel.GetScoreOfStartingTradeAgreement(Clan.PlayerClan.Kingdom, target, x, out textObject2, false);
					});
				}
				else
				{
					clan = Clan.PlayerClan;
				}
			}
			return clan;
		}

		// Token: 0x06002685 RID: 9861 RVA: 0x000A1068 File Offset: 0x0009F268
		public override Clan DetermineChooser()
		{
			return base.Kingdom.RulingClan;
		}

		// Token: 0x06002686 RID: 9862 RVA: 0x000A1078 File Offset: 0x0009F278
		protected override bool ShouldBeCancelledInternal()
		{
			TextObject textObject;
			return !Campaign.Current.Models.TradeAgreementModel.CanMakeTradeAgreement(base.Kingdom, this.TargetKingdom, false, out textObject, false);
		}

		// Token: 0x06002687 RID: 9863 RVA: 0x000A10AC File Offset: 0x0009F2AC
		public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
		{
			yield return new TradeAgreementDecision.TradeAgreementDecisionOutcome(true, base.Kingdom, this.TargetKingdom);
			yield return new TradeAgreementDecision.TradeAgreementDecisionOutcome(false, base.Kingdom, this.TargetKingdom);
			yield break;
		}

		// Token: 0x06002688 RID: 9864 RVA: 0x000A10BC File Offset: 0x0009F2BC
		public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			foreach (DecisionOutcome decisionOutcome in possibleOutcomes)
			{
				if (((TradeAgreementDecision.TradeAgreementDecisionOutcome)decisionOutcome).ShouldTradeAgreementStart)
				{
					decisionOutcome.SetSponsor(base.ProposerClan);
				}
				else
				{
					base.AssignDefaultSponsor(decisionOutcome);
				}
			}
		}

		// Token: 0x06002689 RID: 9865 RVA: 0x000A1128 File Offset: 0x0009F328
		public float CalculateSupport(Clan clan, out TextObject hint)
		{
			return this.DetermineSupport(clan, new TradeAgreementDecision.TradeAgreementDecisionOutcome(true, base.Kingdom, this.TargetKingdom), true, out hint);
		}

		// Token: 0x0600268A RID: 9866 RVA: 0x000A1148 File Offset: 0x0009F348
		private float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome, bool includeExplanations, out TextObject hint)
		{
			float scoreOfStartingTradeAgreement = Campaign.Current.Models.TradeAgreementModel.GetScoreOfStartingTradeAgreement(base.Kingdom, this.TargetKingdom, clan, out hint, includeExplanations);
			if (((TradeAgreementDecision.TradeAgreementDecisionOutcome)possibleOutcome).ShouldTradeAgreementStart)
			{
				return scoreOfStartingTradeAgreement;
			}
			return 100f - scoreOfStartingTradeAgreement;
		}

		// Token: 0x0600268B RID: 9867 RVA: 0x000A1190 File Offset: 0x0009F390
		public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
		{
			TextObject textObject;
			return this.DetermineSupport(clan, possibleOutcome, false, out textObject);
		}

		// Token: 0x0600268C RID: 9868 RVA: 0x000A11A8 File Offset: 0x0009F3A8
		public override TextObject GetChooseDescription()
		{
			TextObject textObject = new TextObject("{=O9XpB5Ah}As the ruler, you must decide if a trade agreement will be made with the {KINGDOM}", null);
			textObject.SetTextVariable("KINGDOM", this.TargetKingdom.Name);
			return textObject;
		}

		// Token: 0x0600268D RID: 9869 RVA: 0x000A11CC File Offset: 0x0009F3CC
		public override TextObject GetChooseTitle()
		{
			TextObject textObject = new TextObject("{=zXuo0Wbj}Signing a trade agreement with the {KINGDOM}", null);
			textObject.SetTextVariable("KINGDOM", this.TargetKingdom.InformalName);
			return textObject;
		}

		// Token: 0x0600268E RID: 9870 RVA: 0x000A11F0 File Offset: 0x0009F3F0
		public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, KingdomDecision.SupportStatus supportStatus, bool isShortVersion = false)
		{
			TextObject textObject;
			if (((TradeAgreementDecision.TradeAgreementDecisionOutcome)chosenOutcome).ShouldTradeAgreementStart)
			{
				if (base.IsSingleClanDecision())
				{
					textObject = new TextObject("{=Gj5d9y2g}{RULER.NAME} of the {KINGDOM} has decided to sign a trade agreement with the {OTHER_KINGDOM}.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Majority)
				{
					textObject = new TextObject("{=5DdbkWLu}{RULER.NAME} of the {KINGDOM} has decided to sign a trade agreement with the {OTHER_KINGDOM} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else if (supportStatus == KingdomDecision.SupportStatus.Minority)
				{
					textObject = new TextObject("{=1o8vgwTf}{RULER.NAME} of the {KINGDOM} has decided to sign a trade agreement with the {OTHER_KINGDOM} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council.", null);
				}
				else
				{
					textObject = new TextObject("{=PP7KD7OC}{RULER.NAME} of the {KINGDOM} has decided to sign a trade agreement with the {OTHER_KINGDOM}, with his {?RULER.GENDER}her{?}his{\\?} council evenly divided on the matter.", null);
				}
			}
			else if (base.IsSingleClanDecision())
			{
				textObject = new TextObject("{=UQq4ekeu}{RULER.NAME} of the {KINGDOM} has chosen not to sign a trade agreement with the {OTHER_KINGDOM}.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Majority)
			{
				textObject = new TextObject("{=dCDBqYsh}{RULER.NAME} of the {KINGDOM} has chosen not to sign a trade agreement with the {OTHER_KINGDOM} with the support of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else if (supportStatus == KingdomDecision.SupportStatus.Minority)
			{
				textObject = new TextObject("{=rJIuQ0hc}{RULER.NAME} of the {KINGDOM} has chosen not to sign a trade agreement with the {OTHER_KINGDOM} over the objections of {?RULER.GENDER}her{?}his{\\?} council.", null);
			}
			else
			{
				textObject = new TextObject("{=xAuejv91}{RULER.NAME} of the {KINGDOM} has decided against making peace with the {OTHER_KINGDOM}, with his {?RULER.GENDER}her{?}his{\\?} council evenly divided on the matter.", null);
			}
			StringHelpers.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, textObject, false);
			textObject.SetTextVariable("KINGDOM", base.Kingdom.Name);
			textObject.SetTextVariable("OTHER_KINGDOM", this.TargetKingdom.Name);
			return textObject;
		}

		// Token: 0x0600268F RID: 9871 RVA: 0x000A12E4 File Offset: 0x0009F4E4
		public override TextObject GetGeneralTitle()
		{
			TextObject textObject = new TextObject("{=CWMNTvSb}Trade Agreement with {KINGDOM}", null);
			textObject.SetTextVariable("KINGDOM", this.TargetKingdom.Name);
			return textObject;
		}

		// Token: 0x06002690 RID: 9872 RVA: 0x000A1308 File Offset: 0x0009F508
		public override int GetProposalInfluenceCost()
		{
			return Campaign.Current.Models.TradeAgreementModel.GetInfluenceCostOfProposingTradeAgreement(base.ProposerClan);
		}

		// Token: 0x06002691 RID: 9873 RVA: 0x000A1324 File Offset: 0x0009F524
		public override bool CanMakeDecision(out TextObject reason, bool includeReason = false)
		{
			return Campaign.Current.Models.TradeAgreementModel.CanMakeTradeAgreement(base.Kingdom, this.TargetKingdom, true, out reason, includeReason);
		}

		// Token: 0x06002692 RID: 9874 RVA: 0x000A1349 File Offset: 0x0009F549
		public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
		{
			return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((TradeAgreementDecision.TradeAgreementDecisionOutcome)t).ShouldTradeAgreementStart);
		}

		// Token: 0x06002693 RID: 9875 RVA: 0x000A1370 File Offset: 0x0009F570
		public override TextObject GetSecondaryEffects()
		{
			return TextObject.GetEmpty();
		}

		// Token: 0x06002694 RID: 9876 RVA: 0x000A1378 File Offset: 0x0009F578
		public override TextObject GetSupportDescription()
		{
			TextObject textObject = new TextObject("{=Vg5RmOqL}{FACTION_LEADER} will decide if the {KINGDOM} will sign a trade agreement with the {OTHER_KINGDOM}. You can pick your stance regarding this decision.", null);
			textObject.SetTextVariable("FACTION_LEADER", this.DetermineChooser().Leader.Name);
			textObject.SetTextVariable("OTHER_KINGDOM", this.TargetKingdom.Name);
			textObject.SetTextVariable("KINGDOM", base.Kingdom.Name);
			return textObject;
		}

		// Token: 0x06002695 RID: 9877 RVA: 0x000A13DA File Offset: 0x0009F5DA
		public override TextObject GetSupportTitle()
		{
			TextObject textObject = new TextObject("{=LlTtwQpZ}Vote for signing a trade agreement with {KINGDOM}", null);
			textObject.SetTextVariable("KINGDOM", this.TargetKingdom.Name);
			return textObject;
		}

		// Token: 0x06002696 RID: 9878 RVA: 0x000A13FE File Offset: 0x0009F5FE
		public override bool IsAllowed()
		{
			return !base.Kingdom.IsAtWarWith(this.TargetKingdom);
		}

		// Token: 0x04000B67 RID: 2919
		[SaveableField(0)]
		public readonly Kingdom TargetKingdom;

		// Token: 0x04000B68 RID: 2920
		private ITradeAgreementsCampaignBehavior _tradeAgreementsCampaignBehavior;

		// Token: 0x0200066D RID: 1645
		public class TradeAgreementDecisionOutcome : DecisionOutcome
		{
			// Token: 0x060051F7 RID: 20983 RVA: 0x0018AF0B File Offset: 0x0018910B
			internal static void AutoGeneratedStaticCollectObjectsTradeAgreementDecisionOutcome(object o, List<object> collectedObjects)
			{
				((TradeAgreementDecision.TradeAgreementDecisionOutcome)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x060051F8 RID: 20984 RVA: 0x0018AF19 File Offset: 0x00189119
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this.Kingdom1);
				collectedObjects.Add(this.Kingdom2);
			}

			// Token: 0x060051F9 RID: 20985 RVA: 0x0018AF3A File Offset: 0x0018913A
			internal static object AutoGeneratedGetMemberValueShouldTradeAgreementStart(object o)
			{
				return ((TradeAgreementDecision.TradeAgreementDecisionOutcome)o).ShouldTradeAgreementStart;
			}

			// Token: 0x060051FA RID: 20986 RVA: 0x0018AF4C File Offset: 0x0018914C
			internal static object AutoGeneratedGetMemberValueKingdom1(object o)
			{
				return ((TradeAgreementDecision.TradeAgreementDecisionOutcome)o).Kingdom1;
			}

			// Token: 0x060051FB RID: 20987 RVA: 0x0018AF59 File Offset: 0x00189159
			internal static object AutoGeneratedGetMemberValueKingdom2(object o)
			{
				return ((TradeAgreementDecision.TradeAgreementDecisionOutcome)o).Kingdom2;
			}

			// Token: 0x060051FC RID: 20988 RVA: 0x0018AF66 File Offset: 0x00189166
			public TradeAgreementDecisionOutcome(bool shouldStart, Kingdom kingdom1, Kingdom kingdom2)
			{
				this.Kingdom1 = kingdom1;
				this.Kingdom2 = kingdom2;
				this.ShouldTradeAgreementStart = shouldStart;
			}

			// Token: 0x060051FD RID: 20989 RVA: 0x0018AF84 File Offset: 0x00189184
			public override TextObject GetDecisionDescription()
			{
				TextObject textObject = TextObject.GetEmpty();
				if (this.ShouldTradeAgreementStart)
				{
					textObject = new TextObject("{=saHvdWSf}We support a trade agreement with {KINGDOM}", null);
				}
				else
				{
					textObject = new TextObject("{=bSGB0vWb}We oppose a trade agreement with {KINGDOM}", null);
				}
				textObject.SetTextVariable("KINGDOM", this.Kingdom2.Name);
				return textObject;
			}

			// Token: 0x060051FE RID: 20990 RVA: 0x0018AFD1 File Offset: 0x001891D1
			public override ImageIdentifier GetDecisionImageIdentifier()
			{
				return null;
			}

			// Token: 0x060051FF RID: 20991 RVA: 0x0018AFD4 File Offset: 0x001891D4
			public override string GetDecisionLink()
			{
				return null;
			}

			// Token: 0x06005200 RID: 20992 RVA: 0x0018AFD7 File Offset: 0x001891D7
			public override TextObject GetDecisionTitle()
			{
				TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}", null);
				textObject.SetTextVariable("SUPPORT", this.ShouldTradeAgreementStart ? 1 : 0);
				return textObject;
			}

			// Token: 0x04001A19 RID: 6681
			[SaveableField(100)]
			public readonly bool ShouldTradeAgreementStart;

			// Token: 0x04001A1A RID: 6682
			[SaveableField(110)]
			public readonly Kingdom Kingdom1;

			// Token: 0x04001A1B RID: 6683
			[SaveableField(120)]
			public readonly Kingdom Kingdom2;
		}
	}
}
