using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x0200048C RID: 1164
	public class TransferPrisonerBarterable : Barterable
	{
		// Token: 0x17000E97 RID: 3735
		// (get) Token: 0x060049B2 RID: 18866 RVA: 0x00175A91 File Offset: 0x00173C91
		public override string StringID
		{
			get
			{
				return "transfer_prisoner_barterable";
			}
		}

		// Token: 0x060049B3 RID: 18867 RVA: 0x00175A98 File Offset: 0x00173C98
		public TransferPrisonerBarterable(Hero prisonerCharacter, Hero owner, PartyBase ownerParty, Hero opponentHero, PartyBase otherParty) : base(owner, ownerParty)
		{
			this._prisonerCharacter = prisonerCharacter;
			this._opponentHero = opponentHero;
			this._otherParty = otherParty;
		}

		// Token: 0x17000E98 RID: 3736
		// (get) Token: 0x060049B4 RID: 18868 RVA: 0x00175ABC File Offset: 0x00173CBC
		public override TextObject Name
		{
			get
			{
				TextObject textObject = new TextObject("{=g5bzJjd5}Transfer {PRISONER.NAME}", null);
				StringHelpers.SetCharacterProperties("PRISONER", this._prisonerCharacter.CharacterObject, textObject, false);
				return textObject;
			}
		}

		// Token: 0x060049B5 RID: 18869 RVA: 0x00175AF0 File Offset: 0x00173CF0
		public override int GetUnitValueForFaction(IFaction faction)
		{
			int num = Campaign.Current.Models.RansomValueCalculationModel.PrisonerRansomValue(this._prisonerCharacter.CharacterObject, null);
			Hero originalOwner = base.OriginalOwner;
			if (faction != ((originalOwner != null) ? originalOwner.Clan : null))
			{
				Hero originalOwner2 = base.OriginalOwner;
				if (faction != ((originalOwner2 != null) ? originalOwner2.MapFaction : null) && faction != base.OriginalParty.MapFaction)
				{
					return num;
				}
			}
			return -num;
		}

		// Token: 0x060049B6 RID: 18870 RVA: 0x00175B5A File Offset: 0x00173D5A
		public override ImageIdentifier GetVisualIdentifier()
		{
			return new CharacterImageIdentifier(CharacterCode.CreateFrom(this._prisonerCharacter.CharacterObject));
		}

		// Token: 0x060049B7 RID: 18871 RVA: 0x00175B71 File Offset: 0x00173D71
		public override string GetEncyclopediaLink()
		{
			return this._prisonerCharacter.EncyclopediaLink;
		}

		// Token: 0x060049B8 RID: 18872 RVA: 0x00175B80 File Offset: 0x00173D80
		public override void Apply()
		{
			if (this._otherParty != null && this._otherParty.MapFaction.IsAtWarWith(this._prisonerCharacter.MapFaction))
			{
				TransferPrisonerAction.Apply(this._prisonerCharacter.CharacterObject, base.OriginalParty, this._otherParty);
				return;
			}
			Debug.FailedAssert("Failed to transfer prisoner through barter", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\BarterSystem\\Barterables\\TransferPrisonerBarterable.cs", "Apply", 71);
		}

		// Token: 0x060049B9 RID: 18873 RVA: 0x00175BE5 File Offset: 0x00173DE5
		internal static void AutoGeneratedStaticCollectObjectsTransferPrisonerBarterable(object o, List<object> collectedObjects)
		{
			((TransferPrisonerBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060049BA RID: 18874 RVA: 0x00175BF3 File Offset: 0x00173DF3
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._prisonerCharacter);
			collectedObjects.Add(this._opponentHero);
			collectedObjects.Add(this._otherParty);
		}

		// Token: 0x060049BB RID: 18875 RVA: 0x00175C20 File Offset: 0x00173E20
		internal static object AutoGeneratedGetMemberValue_prisonerCharacter(object o)
		{
			return ((TransferPrisonerBarterable)o)._prisonerCharacter;
		}

		// Token: 0x060049BC RID: 18876 RVA: 0x00175C2D File Offset: 0x00173E2D
		internal static object AutoGeneratedGetMemberValue_opponentHero(object o)
		{
			return ((TransferPrisonerBarterable)o)._opponentHero;
		}

		// Token: 0x060049BD RID: 18877 RVA: 0x00175C3A File Offset: 0x00173E3A
		internal static object AutoGeneratedGetMemberValue_otherParty(object o)
		{
			return ((TransferPrisonerBarterable)o)._otherParty;
		}

		// Token: 0x04001454 RID: 5204
		[SaveableField(10)]
		private readonly Hero _prisonerCharacter;

		// Token: 0x04001455 RID: 5205
		[SaveableField(20)]
		private readonly Hero _opponentHero;

		// Token: 0x04001456 RID: 5206
		[SaveableField(30)]
		private readonly PartyBase _otherParty;
	}
}
