using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Settlements
{
	// Token: 0x020003B6 RID: 950
	public class Village : SettlementComponent
	{
		// Token: 0x060037D2 RID: 14290 RVA: 0x000E4862 File Offset: 0x000E2A62
		internal static void AutoGeneratedStaticCollectObjectsVillage(object o, List<object> collectedObjects)
		{
			((Village)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060037D3 RID: 14291 RVA: 0x000E4870 File Offset: 0x000E2A70
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._bound);
			collectedObjects.Add(this._marketData);
		}

		// Token: 0x060037D4 RID: 14292 RVA: 0x000E4891 File Offset: 0x000E2A91
		internal static object AutoGeneratedGetMemberValueLastDemandSatisfiedTime(object o)
		{
			return ((Village)o).LastDemandSatisfiedTime;
		}

		// Token: 0x060037D5 RID: 14293 RVA: 0x000E48A3 File Offset: 0x000E2AA3
		internal static object AutoGeneratedGetMemberValueHearth(object o)
		{
			return ((Village)o).Hearth;
		}

		// Token: 0x060037D6 RID: 14294 RVA: 0x000E48B5 File Offset: 0x000E2AB5
		internal static object AutoGeneratedGetMemberValueTradeTaxAccumulated(object o)
		{
			return ((Village)o).TradeTaxAccumulated;
		}

		// Token: 0x060037D7 RID: 14295 RVA: 0x000E48C7 File Offset: 0x000E2AC7
		internal static object AutoGeneratedGetMemberValue_villageState(object o)
		{
			return ((Village)o)._villageState;
		}

		// Token: 0x060037D8 RID: 14296 RVA: 0x000E48D9 File Offset: 0x000E2AD9
		internal static object AutoGeneratedGetMemberValue_bound(object o)
		{
			return ((Village)o)._bound;
		}

		// Token: 0x060037D9 RID: 14297 RVA: 0x000E48E6 File Offset: 0x000E2AE6
		internal static object AutoGeneratedGetMemberValue_marketData(object o)
		{
			return ((Village)o)._marketData;
		}

		// Token: 0x17000D5C RID: 3420
		// (get) Token: 0x060037DA RID: 14298 RVA: 0x000E48F3 File Offset: 0x000E2AF3
		public static MBReadOnlyList<Village> All
		{
			get
			{
				return Campaign.Current.AllVillages;
			}
		}

		// Token: 0x060037DB RID: 14299 RVA: 0x000E48FF File Offset: 0x000E2AFF
		public IEnumerable<PartyBase> GetDefenderParties(MapEvent.BattleTypes battleType)
		{
			yield return base.Settlement.Party;
			foreach (MobileParty mobileParty in base.Settlement.Parties)
			{
				if (mobileParty.MapFaction == base.Settlement.MapFaction && ((!mobileParty.IsMilitia && !mobileParty.IsVillager) || battleType == MapEvent.BattleTypes.Raid || battleType == MapEvent.BattleTypes.IsForcingSupplies || battleType == MapEvent.BattleTypes.IsForcingVolunteers) && !mobileParty.IsCaravan)
				{
					yield return mobileParty.Party;
				}
			}
			List<MobileParty>.Enumerator enumerator = default(List<MobileParty>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x060037DC RID: 14300 RVA: 0x000E4918 File Offset: 0x000E2B18
		public PartyBase GetNextDefenderParty(ref int partyIndex, MapEvent.BattleTypes battleType)
		{
			partyIndex++;
			if (partyIndex == 0)
			{
				return base.Settlement.Party;
			}
			for (int i = partyIndex - 1; i < base.Settlement.Parties.Count; i++)
			{
				MobileParty mobileParty = base.Settlement.Parties[i];
				if (mobileParty.MapFaction == base.Settlement.MapFaction && !mobileParty.IsCaravan)
				{
					partyIndex = i + 1;
					return mobileParty.Party;
				}
			}
			return null;
		}

		// Token: 0x17000D5D RID: 3421
		// (get) Token: 0x060037DD RID: 14301 RVA: 0x000E4993 File Offset: 0x000E2B93
		// (set) Token: 0x060037DE RID: 14302 RVA: 0x000E499C File Offset: 0x000E2B9C
		public Village.VillageStates VillageState
		{
			get
			{
				return this._villageState;
			}
			set
			{
				if (this._villageState != value)
				{
					this._villageState = value;
					switch (this._villageState)
					{
					case Village.VillageStates.Normal:
						CampaignEventDispatcher.Instance.OnVillageBecomeNormal(this);
						return;
					case Village.VillageStates.BeingRaided:
						CampaignEventDispatcher.Instance.OnVillageBeingRaided(this);
						return;
					case Village.VillageStates.ForcedForVolunteers:
					case Village.VillageStates.ForcedForSupplies:
						break;
					case Village.VillageStates.Looted:
						CampaignEventDispatcher.Instance.OnVillageLooted(this);
						break;
					default:
						return;
					}
				}
			}
		}

		// Token: 0x17000D5E RID: 3422
		// (get) Token: 0x060037DF RID: 14303 RVA: 0x000E49FE File Offset: 0x000E2BFE
		public bool IsDeserted
		{
			get
			{
				return this._villageState == Village.VillageStates.Looted;
			}
		}

		// Token: 0x17000D5F RID: 3423
		// (get) Token: 0x060037E0 RID: 14304 RVA: 0x000E4A09 File Offset: 0x000E2C09
		// (set) Token: 0x060037E1 RID: 14305 RVA: 0x000E4A11 File Offset: 0x000E2C11
		[SaveableProperty(105)]
		public float LastDemandSatisfiedTime { get; private set; }

		// Token: 0x17000D60 RID: 3424
		// (get) Token: 0x060037E2 RID: 14306 RVA: 0x000E4A1A File Offset: 0x000E2C1A
		// (set) Token: 0x060037E3 RID: 14307 RVA: 0x000E4A22 File Offset: 0x000E2C22
		public Settlement Bound
		{
			get
			{
				return this._bound;
			}
			private set
			{
				if (this._bound != value)
				{
					Settlement bound = this._bound;
					if (bound != null)
					{
						bound.RemoveBoundVillageInternal(this);
					}
					this._bound = value;
					Settlement bound2 = this._bound;
					if (bound2 == null)
					{
						return;
					}
					bound2.AddBoundVillageInternal(this);
				}
			}
		}

		// Token: 0x17000D61 RID: 3425
		// (get) Token: 0x060037E4 RID: 14308 RVA: 0x000E4A57 File Offset: 0x000E2C57
		// (set) Token: 0x060037E5 RID: 14309 RVA: 0x000E4A74 File Offset: 0x000E2C74
		public Settlement TradeBound
		{
			get
			{
				if (!this._bound.IsTown)
				{
					return this._tradeBound;
				}
				return this._bound;
			}
			set
			{
				if (this._tradeBound != value && !this._bound.IsTown)
				{
					Settlement tradeBound = this._tradeBound;
					if (tradeBound != null)
					{
						tradeBound.Town.RemoveTradeBoundVillageInternal(this);
					}
					this._tradeBound = value;
					Settlement tradeBound2 = this._tradeBound;
					if (tradeBound2 == null)
					{
						return;
					}
					tradeBound2.Town.SetTradeBoundVillageInternal(this);
				}
			}
		}

		// Token: 0x17000D62 RID: 3426
		// (get) Token: 0x060037E6 RID: 14310 RVA: 0x000E4ACB File Offset: 0x000E2CCB
		public override IFaction MapFaction
		{
			get
			{
				return this.Bound.MapFaction;
			}
		}

		// Token: 0x17000D63 RID: 3427
		// (get) Token: 0x060037E7 RID: 14311 RVA: 0x000E4AD8 File Offset: 0x000E2CD8
		public VillageMarketData MarketData
		{
			get
			{
				return this._marketData;
			}
		}

		// Token: 0x17000D64 RID: 3428
		// (get) Token: 0x060037E8 RID: 14312 RVA: 0x000E4AE0 File Offset: 0x000E2CE0
		// (set) Token: 0x060037E9 RID: 14313 RVA: 0x000E4AE8 File Offset: 0x000E2CE8
		[SaveableProperty(108)]
		public float Hearth { get; set; }

		// Token: 0x17000D65 RID: 3429
		// (get) Token: 0x060037EA RID: 14314 RVA: 0x000E4AF1 File Offset: 0x000E2CF1
		// (set) Token: 0x060037EB RID: 14315 RVA: 0x000E4AF9 File Offset: 0x000E2CF9
		[SaveableProperty(110)]
		public int TradeTaxAccumulated { get; set; }

		// Token: 0x060037EC RID: 14316 RVA: 0x000E4B02 File Offset: 0x000E2D02
		public Village()
		{
			this.LastDemandSatisfiedTime = -1f;
			this._marketData = new VillageMarketData(this);
		}

		// Token: 0x060037ED RID: 14317 RVA: 0x000E4B24 File Offset: 0x000E2D24
		public void DailyTick()
		{
			int hearthLevel = this.GetHearthLevel();
			this.Hearth += this.HearthChange;
			if (hearthLevel != this.GetHearthLevel())
			{
				base.Settlement.Party.SetLevelMaskIsDirty();
			}
			if (this.Hearth < 10f)
			{
				this.Hearth = 10f;
			}
			base.Owner.Settlement.Militia += this.MilitiaChange;
			if (base.Gold > 1000)
			{
				base.ChangeGold(1000 - base.Gold);
			}
		}

		// Token: 0x060037EE RID: 14318 RVA: 0x000E4BB6 File Offset: 0x000E2DB6
		public override void OnInit()
		{
			ChangeVillageStateAction.ApplyBySettingToNormal(base.Settlement);
			base.ChangeGold(1000);
		}

		// Token: 0x060037EF RID: 14319 RVA: 0x000E4BD0 File Offset: 0x000E2DD0
		public int GetWarehouseCapacity()
		{
			float num = Campaign.Current.Models.VillageProductionCalculatorModel.CalculateDailyFoodProductionAmount(this);
			foreach (ValueTuple<ItemObject, float> valueTuple in this.VillageType.Productions)
			{
				float resultNumber = Campaign.Current.Models.VillageProductionCalculatorModel.CalculateDailyProductionAmount(this, valueTuple.Item1).ResultNumber;
				num += resultNumber;
			}
			return MathF.Ceiling(MathF.Max(1f, num) * 5f);
		}

		// Token: 0x060037F0 RID: 14320 RVA: 0x000E4C78 File Offset: 0x000E2E78
		public override int GetItemPrice(ItemObject item, MobileParty tradingParty = null, bool isSelling = false)
		{
			if (this.TradeBound == null)
			{
				return 1;
			}
			return this.TradeBound.Town.MarketData.GetPrice(item, tradingParty, isSelling, null);
		}

		// Token: 0x060037F1 RID: 14321 RVA: 0x000E4C9D File Offset: 0x000E2E9D
		public override int GetItemPrice(EquipmentElement itemRosterElement, MobileParty tradingParty = null, bool isSelling = false)
		{
			if (this.TradeBound == null)
			{
				return 1;
			}
			return this.TradeBound.Town.MarketData.GetPrice(itemRosterElement, tradingParty, isSelling, null);
		}

		// Token: 0x060037F2 RID: 14322 RVA: 0x000E4CC2 File Offset: 0x000E2EC2
		public override string ToString()
		{
			return base.Name.ToString();
		}

		// Token: 0x060037F3 RID: 14323 RVA: 0x000E4CD0 File Offset: 0x000E2ED0
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			base.Deserialize(objectManager, node);
			base.BackgroundCropPosition = float.Parse(node.Attributes["background_crop_position"].Value);
			base.BackgroundMeshName = node.Attributes["background_mesh"].Value;
			base.CastleBackgroundMeshName = node.Attributes["castle_background_mesh"].Value;
			base.WaitMeshName = node.Attributes["wait_mesh"].Value;
			if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
			{
				this.Hearth = (float)int.Parse(node.Attributes["hearth"].Value);
			}
			this.VillageType = (VillageType)objectManager.ReadObjectReferenceFromXml("village_type", typeof(VillageType), node);
			if (Campaign.Current.CampaignGameLoadingType != Campaign.GameLoadingType.SavedCampaign)
			{
				if (this.Bound != null && this.Bound.IsTown)
				{
					this.Bound.Town.RemoveTradeBoundVillageInternal(this);
				}
				this.Bound = (Settlement)objectManager.ReadObjectReferenceFromXml("bound", typeof(Settlement), node);
				if (this.Bound.IsTown)
				{
					this.Bound.Town.SetTradeBoundVillageInternal(this);
				}
			}
		}

		// Token: 0x060037F4 RID: 14324 RVA: 0x000E4E18 File Offset: 0x000E3018
		public bool IsProducing(ItemObject item)
		{
			using (List<ValueTuple<ItemObject, float>>.Enumerator enumerator = this.VillageType.Productions.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current.Item1 == item)
					{
						return true;
					}
				}
			}
			return false;
		}

		// Token: 0x17000D66 RID: 3430
		// (get) Token: 0x060037F5 RID: 14325 RVA: 0x000E4E78 File Offset: 0x000E3078
		public float HearthChange
		{
			get
			{
				return Campaign.Current.Models.SettlementProsperityModel.CalculateHearthChange(this, false).ResultNumber;
			}
		}

		// Token: 0x17000D67 RID: 3431
		// (get) Token: 0x060037F6 RID: 14326 RVA: 0x000E4EA3 File Offset: 0x000E30A3
		public float Militia
		{
			get
			{
				return base.Owner.Settlement.Militia;
			}
		}

		// Token: 0x17000D68 RID: 3432
		// (get) Token: 0x060037F7 RID: 14327 RVA: 0x000E4EB8 File Offset: 0x000E30B8
		public float MilitiaChange
		{
			get
			{
				return Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaChange(base.Owner.Settlement, false).ResultNumber;
			}
		}

		// Token: 0x17000D69 RID: 3433
		// (get) Token: 0x060037F8 RID: 14328 RVA: 0x000E4EED File Offset: 0x000E30ED
		public ExplainedNumber MilitiaChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaChange(base.Owner.Settlement, true);
			}
		}

		// Token: 0x17000D6A RID: 3434
		// (get) Token: 0x060037F9 RID: 14329 RVA: 0x000E4F0F File Offset: 0x000E310F
		public ExplainedNumber HearthChangeExplanation
		{
			get
			{
				return Campaign.Current.Models.SettlementProsperityModel.CalculateHearthChange(this, true);
			}
		}

		// Token: 0x060037FA RID: 14330 RVA: 0x000E4F27 File Offset: 0x000E3127
		public int GetHearthLevel()
		{
			if (this.Hearth >= 600f)
			{
				return 2;
			}
			if (this.Hearth >= 200f)
			{
				return 1;
			}
			return 0;
		}

		// Token: 0x060037FB RID: 14331 RVA: 0x000E4F48 File Offset: 0x000E3148
		public override SettlementComponent.ProsperityLevel GetProsperityLevel()
		{
			if (this.GetHearthLevel() >= 2)
			{
				return SettlementComponent.ProsperityLevel.High;
			}
			if (this.GetHearthLevel() >= 1)
			{
				return SettlementComponent.ProsperityLevel.Mid;
			}
			return SettlementComponent.ProsperityLevel.Low;
		}

		// Token: 0x04001123 RID: 4387
		public const int MidHearthThreshold = 600;

		// Token: 0x04001124 RID: 4388
		public const int LowHearthThreshold = 200;

		// Token: 0x04001125 RID: 4389
		private const int InitialVillageGold = 1000;

		// Token: 0x04001126 RID: 4390
		public const int NumberOfDaysToFillVillageStocks = 5;

		// Token: 0x04001127 RID: 4391
		[CachedData]
		public VillagerPartyComponent VillagerPartyComponent;

		// Token: 0x04001128 RID: 4392
		[SaveableField(104)]
		private Village.VillageStates _villageState;

		// Token: 0x0400112A RID: 4394
		[SaveableField(106)]
		private Settlement _bound;

		// Token: 0x0400112B RID: 4395
		public VillageType VillageType;

		// Token: 0x0400112C RID: 4396
		private Settlement _tradeBound;

		// Token: 0x0400112D RID: 4397
		[SaveableField(107)]
		private VillageMarketData _marketData;

		// Token: 0x02000777 RID: 1911
		public enum VillageStates
		{
			// Token: 0x04001E1C RID: 7708
			Normal,
			// Token: 0x04001E1D RID: 7709
			BeingRaided,
			// Token: 0x04001E1E RID: 7710
			ForcedForVolunteers,
			// Token: 0x04001E1F RID: 7711
			ForcedForSupplies,
			// Token: 0x04001E20 RID: 7712
			Looted
		}
	}
}
