using System;
using System.Linq;
using HarmonyLib;
using ModifiedPolitics.HeroOffices.Behaviors;
using ModifiedPolitics.HeroOffices.Domain;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.CampaignSystem.Actions;

namespace ModifiedPolitics.HeroOffices.Patches
{
    /// <summary>
    /// Reduces only negative relationship changes generated by kingdom political voting.
    /// </summary>
    [HarmonyPatch(typeof(KingdomElection), "GetRelationChangeWithSponsor")]
    internal static class CourtStewardRelationPatch
    {
        [HarmonyPostfix]
        private static void ReducePoliticalRelationLoss(
            KingdomDecision ___decision,
            ref int __result)
        {
            if (__result >= 0 || ___decision?.Kingdom == null)
                return;

            bool hasCourtSteward = HeroOfficeBehavior.Current?
                .GetAssignments(___decision.Kingdom, OfficeType.CourtSteward)
                .Any() == true;
            if (!hasCourtSteward)
                return;

            // Round the remaining loss away from zero so the office never erases it entirely.
            __result = -(int)Math.Ceiling(Math.Abs(__result) * 0.75f);
        }
    }

    /// <summary>
    /// Expulsion applies its vote penalty directly and therefore needs the same scoped reduction.
    /// </summary>
    [HarmonyPatch]
    internal static class CourtStewardExpulsionRelationPatch
    {
        [System.ThreadStatic]
        private static bool _isReducingExpulsion;

        [HarmonyPrefix]
        [HarmonyPatch(typeof(ExpelClanFromKingdomDecision), "ApplyChosenOutcome")]
        private static void BeginExpulsion(ExpelClanFromKingdomDecision __instance)
        {
            _isReducingExpulsion = __instance?.Kingdom != null
                && HeroOfficeBehavior.Current?
                    .GetAssignments(__instance.Kingdom, OfficeType.CourtSteward)
                    .Any() == true;
        }

        [HarmonyFinalizer]
        [HarmonyPatch(typeof(ExpelClanFromKingdomDecision), "ApplyChosenOutcome")]
        private static void EndExpulsion()
        {
            _isReducingExpulsion = false;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(ChangeRelationAction), "ApplyRelationChangeBetweenHeroes")]
        private static void ReduceDirectExpulsionLoss(ref int relationChange)
        {
            if (_isReducingExpulsion && relationChange < 0)
                relationChange = -(int)Math.Ceiling(Math.Abs(relationChange) * 0.75f);
        }
    }
}
