using System;
using System.Linq;
using HarmonyLib;
using ModifiedPolitics.HeroOffices.Behaviors;
using ModifiedPolitics.HeroOffices.Domain;
using TaleWorlds.CampaignSystem.Election;

namespace ModifiedPolitics.HeroOffices.Patches
{
    /// <summary>
    /// Reduces negative relationship changes generated by kingdom political voting.
    /// </summary>
    [HarmonyPatch(typeof(KingdomElection), "GetRelationChangeWithSponsor")]
    internal static class CourtStewardRelationPatch
    {
        [HarmonyPostfix]
        private static void ReducePoliticalRelationLoss(
            KingdomDecision ____decision,
            ref int __result)
        {
            if (__result >= 0 || ____decision?.Kingdom == null)
                return;

            bool hasCourtSteward = HeroOfficeBehavior.Current?
                .GetAssignments(____decision.Kingdom, OfficeType.CourtSteward)
                .Any() == true;
            if (!hasCourtSteward)
                return;

            // Keep 75% of the loss and round away from zero as specified by the design.
            __result = -(int)Math.Ceiling(Math.Abs(__result) * 0.75f);
        }
    }
}
