using System;
using System.Linq;
using HarmonyLib;
using ModifiedPolitics.HeroOffices.Behaviors;
using ModifiedPolitics.HeroOffices.Domain;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.CampaignSystem.GameComponents;

namespace ModifiedPolitics.HeroOffices.Patches
{
    /// <summary>
    /// Reduces negative relationship changes generated by kingdom political voting.
    /// </summary>
    [HarmonyPatch(typeof(KingdomElection), "GetRelationChangeWithSponsor")]
    internal static class CourtStewardRelationPatch
    {
        [HarmonyPostfix]
        private static void ReducePoliticalRelationLoss(
            KingdomDecision ____decision,
            ref int __result)
        {
            if (__result >= 0 || ____decision?.Kingdom == null)
                return;

            bool hasCourtSteward = HeroOfficeBehavior.Current?
                .GetAssignments(____decision.Kingdom, OfficeType.CourtSteward)
                .Any() == true;
            if (!hasCourtSteward)
                return;

            // Keep 75% of the loss and round away from zero as specified by the design.
            __result = -(int)Math.Ceiling(Math.Abs(__result) * 0.75f);
        }
    }

    /// <summary>
    /// Reduces the relation cost returned specifically while an expulsion outcome is applied.
    /// </summary>
    [HarmonyPatch]
    internal static class CourtStewardExpulsionRelationPatch
    {
        [ThreadStatic]
        private static bool _isApplyingProtectedExpulsion;

        [HarmonyPrefix]
        [HarmonyPatch(typeof(ExpelClanFromKingdomDecision), "ApplyChosenOutcome")]
        private static void BeginExpulsion(
            ExpelClanFromKingdomDecision __instance,
            DecisionOutcome chosenOutcome)
        {
            _isApplyingProtectedExpulsion =
                chosenOutcome is ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome outcome
                && outcome.ShouldBeExpelled
                && __instance?.Kingdom != null
                && HeroOfficeBehavior.Current?
                    .GetAssignments(__instance.Kingdom, OfficeType.CourtSteward)
                    .Any() == true;
        }

        [HarmonyFinalizer]
        [HarmonyPatch(typeof(ExpelClanFromKingdomDecision), "ApplyChosenOutcome")]
        private static Exception EndExpulsion(Exception __exception)
        {
            _isApplyingProtectedExpulsion = false;
            return __exception;
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(DefaultDiplomacyModel), "GetRelationCostOfExpellingClanFromKingdom")]
        private static void ReduceExpulsionRelationLoss(ref int __result)
        {
            if (_isApplyingProtectedExpulsion && __result < 0)
                __result = -(int)Math.Ceiling(Math.Abs(__result) * 0.75f);
        }
    }
}
