<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\..\harmony\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.ObjectSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Core">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.CampaignSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.MountAndBlade">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Library">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Localization">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>