<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Bannerlord.BuildResources" Version="1.1.0.129">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Bannerlord.MCM" Version="5.11.3" />
	  <PackageReference Include="Bannerlord.UIExtenderEx" Version="2.13.0" />
	  <PackageReference Include="BUTR.Harmony.Analyzer" Version="1.0.1.50">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Harmony.Extensions" Version="3.2.0.77">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="IsExternalInit" Version="1.0.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Lib.Harmony" Version="2.4.2" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\..\harmony\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.ObjectSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Core">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.CampaignSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.MountAndBlade">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Library">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Localization">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.ScreenSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Engine">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Engine.GauntletUI">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Engine.GauntletUI.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.InputSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.Core.ViewModelCollection">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.ViewModelCollection.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.SaveSystem">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.SaveSystem.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.GauntletUI.Data">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll</HintPath>
		</Reference>
		<Reference Include="TaleWorlds.LinQuick">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.LinQuick.dll</HintPath>
		</Reference>


		<Reference Include="SandBox.View">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll</HintPath>
		</Reference>
		<Reference Include="SandBox.GauntletUI">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.dll</HintPath>
		</Reference>
		
		
		<Reference Include="TaleWorlds.MountAndBlade.View">
			<HintPath>D:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.View.dll</HintPath>
		</Reference>		
	</ItemGroup>
</Project>